Ajout d'un second TDB pour les DDETS
betagouv/itou pull request #1072
Opened 2022-01-20 13:55 UTC by dejafait

### Quoi ?

Les DDETS avaient déjà une vue `stats_ddets`, on la renomme en `stats_ddets_overview` et on en ajoute une nouvelle `stats_ddets_diagnosis_control` pour le contrôle a posteriori.

### Pourquoi ?

Demande de Soumia.

### Captures d'écran 

FIXME

2022-01-20 13:58 UTC, dejafait commented
![](https://github.trello.services/images/mini-trello-icon.png) [En tant que DDETS je veux voir des stats sur le contrôle a posteriori via le C1](https://trello.com/c/hfoNelJE/2710-en-tant-que-ddets-je-veux-voir-des-stats-sur-le-contr%C3%B4le-a-posteriori-via-le-c1)

2022-01-24 10:00 UTC, celine-m-s requested changes
Petite modification orthographique. Merci !

2022-01-24 10:00 UTC, celine-m-s commented on config/settings/base.py
> +}
:+1: 
C'est bien plus lisible.

2022-01-24 10:00 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +                            <a href="{% url 'stats:stats_ddets_diagnosis_control' %}">Voir mes données 2021 du contrôle à postériori (Version beta)</a>
```suggestion
                            <a href="{% url 'stats:stats_ddets_diagnosis_control' %}">Voir mes données 2021 du contrôle a posteriori (Version beta)</a>
```

A posteriori, comme a priori, sont des [locutions latines](https://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3799). Elles ne prennent donc [pas d'accent](https://www.larousse.fr/dictionnaires/francais/a_posteriori/4595). L'orthographe révisée de 1990 l'autorise mais crée une incohérence dans la langue (en plus d'un non-sens). Je propose de les enlever, on pourra toujours les remettre partout plus tard.

2022-01-24 10:00 UTC, celine-m-s commented on itou/templates/layout/_footer.html
> +              <a href="{% url 'stats:stats_public' %}">Statistiques, lexiques et indicateurs</a>
Super changement aussi.

2022-01-24 10:06 UTC, dejafait commented on itou/templates/dashboard/dashboard.html
> +                            <a href="{% url 'stats:stats_ddets_diagnosis_control' %}">Voir mes données 2021 du contrôle à postériori (Version beta)</a>
Eh bien tu vas rire j'ai eu exactement la même lecture ! A ma grande surprise selon https://fr.wikipedia.org/wiki/A_priori_et_a_posteriori les accents sont possibles depuis 1990. Etant matheux puriste j'aime beaucoup les locutions latines (a fortiori hahaha) et j'étais tenté de corriger l'orthographe de Eric mais je n'ai pas osé. On est deux donc go !

TIL `nec plus ultra` est une locution latine o_O je pensais que c'était une veille expression des années 1990 lol.

2022-01-24 10:09 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +                            <a href="{% url 'stats:stats_ddets_diagnosis_control' %}">Voir mes données 2021 du contrôle à postériori (Version beta)</a>
Ha ha ha !

2022-01-24 14:44 UTC, merged