Migration 'toutes données - gestion des fiches de poste en doublon
betagouv/itou pull request #1101
Opened 2022-02-03 14:36 UTC by vincentporte

### Quoi ?

Migration des données d'une SIAE à une autre. Cas de la migration 'toutes données'

### Pourquoi ?

Le modèle de données contient une contrainte d'unicité sur les fiches de poste. Il ne peut y avoir qu'une seule fiche de poste pour une SIAE et un code ROME.
Une fiche de poste peut exister avec le même code ROME dans les 2 SIAE.

Lors de la migration : 
- les fiches de poste sont détachées de la SIAE d'origine et de la fiche de poste, pour être rattachées à la SIAE de destination 
- les candidatures sont détachées de la SIAE d'origine et de la fiche de poste, pour être rattachées à la SIAE de destination et la nouvelle fiche de poste.

MISE A JOUR :
- Les fiches de poste en doublon ne sont pas migrées
- Les fiches de poste qui ne sont pas en doublon sont migrées
- Toutes les candidatures sont rattachées à la fiche de poste de la SIAE de destination

### Comment ?

La selection des SiaeJobDescription exclut les fiches de postes qui ont une correspondance dans la SIAE de destination (couple unique SIAE / Code ROME)

2022-02-03 14:53 UTC, dejafait requested changes
Sauf erreur de ma part il manque une opération dans le edge case.

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        logger.info(f"| Brand '{to_siae.brand}' will be update with '{from_siae.display_name}'")
```suggestion
        logger.info(f"| Brand '{to_siae.brand}' will be updated with '{from_siae.display_name}'")
```

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        logger.info(f"| Description \n{to_siae.description}\nwill be update with\n{from_siae.description}")
```suggestion
        logger.info(f"| Description \n{to_siae.description}\nwill be updated with\n{from_siae.description}")
```

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        logger.info(f"| Phone '{to_siae.phone}' will be update with '{from_siae.phone}'")
```suggestion
        logger.info(f"| Phone '{to_siae.phone}' will be updated with '{from_siae.phone}'")
```

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        logger.info(f"| Coords '{to_siae.coords}' will be update with '{from_siae.coords}'")
```suggestion
        logger.info(f"| Coords '{to_siae.coords}' will be updated with '{from_siae.coords}'")
```

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        logger.info(f"| Geocoding Score '{to_siae.geocoding_score}' will be update with '{from_siae.geocoding_score}'")
```suggestion
        logger.info(f"| Geocoding Score '{to_siae.geocoding_score}' will be updated with '{from_siae.geocoding_score}'")
```

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        )
Ok, bien joué avec le Exists/OuterRef.

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        # Job Description present in siae destination
```
# Move job descriptions from A to B unless B already has another job description with the same ROME code.
# When that edge case happens .... FIXME ?
````

2022-02-03 14:53 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +        # Job Description present in siae destination
Si j'ai bien suivi il manque encore une opération dans le edge case. On est en train de déplacer la candidature C de la SIAE A et fiche F1 vers la SIAE B et fiche F2 (avec le même code ROME que F1).

Tu rattaches bien C à B. Mais à quel moment détaches-tu C de F1 (qui reste à jamais sur A) ou bien encore rattaches-tu C à F2 ?

Là tel quel, C finit attachée à la fois à B (directement) et à A (via F1). Bonjour les ennuis ;-)

C'est aussi possible que j'ai loupé un truc hein, pas taper !

2022-02-03 14:58 UTC, vincentporte commented on itou/siaes/management/commands/move_siae_data.py
> +        )
merci

2022-02-03 14:59 UTC, vincentporte commented on itou/siaes/management/commands/move_siae_data.py
> +        # Job Description present in siae destination
je verifie...

2022-02-07 17:20 UTC, vincentporte commented on itou/siaes/management/commands/move_siae_data.py
> +        # Job Description present in siae destination
updated. les job_description en doublons ne sont plus migrées. les job_applications liées à ces job_description sont détachées et sont migrées en tant que candidatures libres

2022-02-10 08:46 UTC, vperron reviewed
Ce n'est pas fondamental ni bloquant mais:
- je serais vraiment heureux que les commentaires soient repris pour coller plus au code et soit consistants. Des fois on a "Appellation" et des fois "Job description" ce qui me déroute; pareil des fois on parle de Siae A et B mais je pense que c'est plus clair si l'on parle partout de from_siae et to_siae.
- je suis étonné que cette commande ne soit pas testée. Comment sait-on qu'elle fonctionne, notamment dans des edge cases aussi précis que ceux que tu corriges ?

2022-02-10 10:27 UTC, vincentporte commented
> Ce n'est pas fondamental ni bloquant mais:
> 
>     * je serais vraiment heureux que les commentaires soient repris pour coller plus au code et soit consistants. Des fois on a "Appellation" et des fois "Job description"

* "Appellation" et "Job Description" sont des tables du modèle de données
* from_siae et to_siae fait sens, à la place de SIAE A et B

2022-03-03 14:51 UTC, dejafait commented
> "Appellation" et "Job Description" sont des tables du modèle de données

Ah oui ce sont deux modèles biens distincts. 

> from_siae et to_siae fait sens, à la place de SIAE A et B

👍

2022-03-03 14:57 UTC, dejafait approved these changes
LGTM

2022-03-03 14:57 UTC, dejafait commented on itou/siaes/management/commands/move_siae_data.py
> +                job_application.selected_jobs.clear()
Ok c'est là que les candidatures sur une fiche de poste non transférable sont converties en candidatures libres pour pouvoir être transférées.

2022-03-03 17:08 UTC, merged