Factorisation de la brique d'authentification
betagouv/itou pull request #1111
Opened 2022-02-10 12:59 UTC by celine-m-s

### Quoi ?

Découpage de la vue d'authentification en plusieurs pour préparer le SSO.

### Pourquoi ?

Les types d'utilisateurs n'ont pas tous le même besoin. Les boutons `PEConnect` et `FranceConnect` sont affichés pour les candidats uniquement. Bientôt, le bouton `Inclusion Connect` le sera pour les prescripteurs.

2022-02-24 09:15 UTC, vperron reviewed
Très joli, j'ai quelques commentaires de précaution, à toi de voir comment et si tu les traites ! Bien joué !

2022-02-24 09:15 UTC, vperron commented on itou/www/login/views.py
> +        We've split them into multiple classes but we should handle old urls.
du coup, on peut mettre un TODO concernant la suppression de ce code ? Quand pourra-t-on cesser de gérer les anciennes URLs ?

2022-02-24 09:15 UTC, vperron commented on itou/www/login/views.py
> +    def redirect_to_login_type(self):
je proposerais deux choses:
- préfixer avec un `_` pour bien montrer que l'on est pas dans une fonction héritant de `allauth.LoginView`
- retourner None explicitement si on ne redirige pas (pylint, typage toussa)

2022-02-24 09:15 UTC, vperron commented on itou/www/login/views.py
> +        return super(ItouLoginView, self).get(*args, **kwargs)
`return self.redirect_to_login() or super(ItouLoginView, self).get(*args, **kwargs)` ?

2022-02-24 09:15 UTC, vperron commented on itou/www/welcoming_tour/tests.py
> -        self.assertContains(response, "Revoir le message")
ah c'est top ça de le mettre dans tous les tests :+1:

2022-02-24 09:15 UTC, vperron commented on itou/www/invitations_views/views.py
> +                url=login_url,
pas 100% certain mais je ne suis pas totalement sûr que cette modification soit couverte par un test.

2022-02-24 15:05 UTC, SebastienReuiller requested changes
Je n'ai rien vu de particulier sur le code 👌. Par contre, j'ai trouvé un comportement gênant. 
Si on veut postuler sur une offre d'emploi sans être connecté, on est redirigé vers la vue générique et celle-ci n'a plus le bouton d'inscription, en plus de ne plus avoir les boutons France Connect et PE. Est-ce qu'on est en droit de penser que le bouton "Postuler" est utilisé par des candidats ? ou est-ce que les prescripteurs passent aussi par là ? Dans ce dernier cas, difficile de présenter la bonne mire...

2022-03-01 17:07 UTC, celine-m-s commented on itou/templates/account/login_generic.html
> +{% block title %}Connexion{{ block.super }}{% endblock %}
L'espace est dans le gabarit de base (base.html).

https://github.com/betagouv/itou/blob/master/itou/templates/layout/base.html#L8

2022-03-01 17:09 UTC, celine-m-s commented on itou/www/approvals_views/tests/test_pe_approval.py
> +        # TODO: redirect to prescriber's connection page with a flash message instead.
Bonne idée, je viens de le rajouter.

2022-03-01 17:14 UTC, celine-m-s commented on itou/www/login/views.py
> +        We've split them into multiple classes but we should handle old urls.
Ticket créé !

2022-03-02 09:07 UTC, celine-m-s commented on itou/www/login/views.py
> +        return super(ItouLoginView, self).get(*args, **kwargs)
Bonne idée !

2022-03-02 09:19 UTC, celine-m-s commented on itou/www/login/views.py
> +    def redirect_to_login_type(self):
Bonne idée. C'est modifié.

2022-03-02 15:29 UTC, celine-m-s commented on itou/templates/layout/_nav_btn_items.html
> +            <a class="dropdown-item" href="{% url 'login:labor_inspector' %}{% if redirect_field_value %}?{{ redirect_field_name }}={{ redirect_field_value }}{% endif %}">
`redirect_field_name` et `redirect_field_value` sont des paramètres gérés par Allauth et auxquels j'avoue que je n'ai pas trop envie de toucher.
En revanche, c'est vrai qu'il y a trop de répétitions. J'ai donc ajouté un _template tag_ [dans ce commit](https://github.com/betagouv/itou/pull/1111/commits/82e0c68bd808aaecaf79a591848bafead8273f3f). Je pense qu'on pourrait aller encore plus loin mais je n'ai pas trop le temps de continuer à factoriser.

2022-03-02 16:35 UTC, celine-m-s commented
> Je n'ai rien vu de particulier sur le code ok_hand. Par contre, j'ai trouvé un comportement gênant.
> Si on veut postuler sur une offre d'emploi sans être connecté, on est redirigé vers la vue générique et celle-ci n'a plus le bouton d'inscription, en plus de ne plus avoir les boutons France Connect et PE. Est-ce qu'on est en droit de penser que le bouton "Postuler" est utilisé par des candidats ? ou est-ce que les prescripteurs passent aussi par là ? Dans ce dernier cas, difficile de présenter la bonne mire...

Bien vu !!
J'avoue que je n'ai pas de bonne solution rapide à mettre en oeuvre. L'idéal serait d'avoir une page de connexion générique comme celle de l'inscription dans laquelle l'utilisateur choisit lui-même son profil.
Je crée une carte pour les UX.

2022-03-03 11:02 UTC, vperron approved these changes
Remarques très mineures (trois fois la meme, plus un commentaire eventuel à aouter)

Par contre je pense que vraiment il y a moyen de réorganiser les commits, 25 c'est bien trop et un seul serait dommage.

Je verrais bien un scénario où:
- tu squashes tout en un seul
- tu fais un `git reset @^` pour avoir tous les changements ouverts sur le filesystem
- tu fais un `git add -p` pour découper en commits plus atomiques.

Je verrais bien ici:
- un commit de renommage du `SIGNIN_ACCOUNT_TYPE `
- un commit pour le refactor du `_redirect_to_job_seeker_login_on_error`
- un commit pour la transformation en `SimpleTestCase`
- un commit pour les templatetags `redirection_fields`
- un dernier commit pour la véritable feature de séparation des routes.

A part ça, LGTM

2022-03-07 16:42 UTC, vperron commented
Pas de problème, j'ai déjà validé la PR !

2022-03-08 10:11 UTC, SebastienReuiller approved these changes
OK pour moi.
Comme tu as créé la carte UX et qu'au pire quand on veut se connecter pour postuler, si on n'a pas de compte, il y a le bouton "Se connecter / s'inscrire" en haut à droite en attendant.

2022-03-08 14:24 UTC, celine-m-s commented on itou/france_connect/views.py
> +        return _redirect_to_job_seeker_login_on_error(error_msg, request)
Traité

2022-03-08 14:24 UTC, celine-m-s commented on itou/france_connect/views.py
> +        return _redirect_to_job_seeker_login_on_error(error_msg, request)
Traité

2022-03-08 14:24 UTC, celine-m-s commented on itou/france_connect/views.py
> +        return _redirect_to_job_seeker_login_on_error(error_msg, request)
Traité

2022-03-08 14:25 UTC, celine-m-s commented on itou/utils/perms/middleware.py
> +        login_routes = [reverse(f"login:{url.name}") for url in login_urls.urlpatterns] + [reverse("account_login")]
Hum, je ne suis pas vraiment sure qu'il sautera. Je préfère laisser comme ça pour le moment.

2022-03-08 15:02 UTC, merged