Fusion des agréments PE
betagouv/itou pull request #1112
Opened 2022-02-10 16:07 UTC by Keirua

Regroupe les PoleEmploiApproval, en une unique entrée qui couvre la durée de tous les agréments associés à un même numéro:

 - on considère les 12 premiers caractères du numéro d’agrément pour trouver les agréments en "doublons"
 - date de début = la date la plus ancienne de tous les agréments
 - date de fin = la date la plus récente
 - pour le reste, on recopie les valeurs de l’agrément PE
 - On crée un nouvel agrément qu’on sauvegarde dans une table dédiée (`merged_approvals_poleemploiapproval`), et on met un flag `merged=true` pour les PoleEmploiApproval considérés.

J’ai essayé d’accéler le processus de migration de plein de manières:
 - ajout d’un index sur `merged`. Un booléen ne pouvant avoir que 2 valeurs, ce n’est pas un bon index, mais ça se tentait ;)
 - ajout d’une colonne `number12`, représentation entière du numéro d’agrément pour chercher par entier et non via l’opérateur like
 - Un `IntegerField` ne suffisant pas pour stocker 12 chiffres, j’ai opté pour un `BigInteger`
 - Tous nos numéros d’agréments ne contiennent pas que des numéros dans les 12 premiers caractères, j’ai essayé un `UUID`. Cette fois ci c’était bon mais même vitesse qu’au début.
 - C’est finalement le SQL brut + une table dédiée d’écriture qui est le plus rapide. On pourrait aller plus vite (écriture en batch plutôt qu’une écriture par agrément) mais c’est suffisant (1H pour MAJ toute la table).

2022-02-14 15:54 UTC, Keirua commented
Ajout de l’enrichissement du fichier excel demandé. Ce script à usage unique ne restera pas, je le laisse temporairement pour relecture dans cette PR car lié à la précédente.

2022-02-15 09:38 UTC, Keirua commented
Ajout d’un script de debug. Nous avons 62% des NIRs des candidats considérés.

2022-02-17 08:28 UTC, Keirua commented
On a vu avec Éric qu’on est bons concernant l’enrchissement des infos transmises. Il reste:
 - À merger cette PR, après avoir supprimé `improve_asp_db.py` qui a servi en local
 - À faire tourner `merge_pe_approvals`
 - Lorsqu’on est bons (retour PE OK? à voir avec Éric), on fait tourner `trash_old_pe_approvals` pour utiliser la nouvelle table, et on supprime toutes ces *management commands* qui n’ont vocation à tourner qu’une fois.

2022-02-24 09:35 UTC, Keirua commented
Suppression du `drop table` comme discuté. On va garder l’ancienne table quelques temps.

2022-02-24 10:03 UTC, celine-m-s requested changes
Beau premier jet ! Bravo !
Mes commentaires concernent surtout la bascule. Comme écrit dans un de mes commentaires, je pense que ce serait mieux de :
- créer un modèle PoleEmploiMergedApproval avec la migration associée (dans une PR dédiée, pas ici),
- utiliser ce modèle dans cette PR,
- puis de modifier le code pour utiliser PoleEmploiMergedApproval et non plus PoleEmploiApproval et ainsi réaliser la bascule.

Qu'en penses-tu ? On peut en discuter si tu veux.

2022-02-24 10:03 UTC, celine-m-s commented on itou/approvals/models.py
> +        return self.filter(Q(nir__isnull=False) | Q(ntt_nia__isnull=False))
Cette méthode n'étant appelée nulle part, je pense que tu peux l'enlever.

2022-03-01 16:42 UTC, Keirua commented on itou/approvals/management/commands/improve_asp_db.py
> +    return all_nirs_and_ntt_nia
je veux juste récupérer tout ce qui ressemble à un nir chez nous pour voir si la donnée fournie par l’ASP est quelque part chez nous, n’importe où

2022-03-01 16:43 UTC, Keirua commented on itou/approvals/management/commands/improve_asp_db.py
> +    print("nombre de nirs distincts dans la feuille Excel:")
ils ne sont en effet pas forcément distincts mais c’est pas très important, c’est juste pour savoir quelle quantité d’info nous n’arrivons pas à associer à un candidat chez nous

2022-03-01 16:49 UTC, Keirua commented on itou/approvals/management/commands/improve_asp_db.py
> +                approval = u.approvals_wrapper.latest_approval
C’est bien ça

2022-03-07 08:29 UTC, Keirua commented
J’ai nettoyé une bonne partie de cette PR pour suivre les retours:
 - suppression de `trash_old_approvals`
 - suppression de la commande pour hydrater l’excel ASP (fichier déjà transmis)
 - création et exploitation d’un modèle dédié MergedPoleEmploiApproval
 Il y a beaucoup de commits, j’ai laissé l’historique mais ca se relit bien en prenant juste le diff final, l’essentiel est dans la `management command`.

2022-03-07 15:15 UTC, celine-m-s requested changes
C'est presque tout bon pour moi ! Je veux juste être sure que `self.merge_table` est bien défini quelque part.

2022-03-07 15:15 UTC, celine-m-s commented on itou/approvals/management/commands/merge_pe_approvals.py
> +            f"TRUNCATE {self.merge_table};",  # noqa
Je ne comprends pas bien où est défini `self.merge_table`.

2022-03-07 15:24 UTC, celine-m-s approved these changes
Et c'est parti !! :rocket:

2022-03-07 15:35 UTC, merged