[Admin] demander l'organisation prescriptrice seulement si le prescripteur est lié à une organisation
betagouv/itou pull request #1119
Opened 2022-02-14 11:09 UTC by vincentporte

reprise de la PR 1109

## Quoi ?

L'ajout de l’organisation du prescripteur est obligatoire dans l'admin, lors de l'enregistrement d'une candidature, même par si le prescripteur est sans orga.

## Pourquoi ?

Permettre l'enregistrement de candidature pour les prescripteurs sans organisation, y compris le support

## Comment ?

Modification du formulaire de l'admin Candidatures (job_applications) pour ne plus afficher le message bloquant  `Organisation du prescripteur émettrice manquante` si le prescripteur n’est pas lié à une orga.

2022-02-16 15:27 UTC, vperron requested changes
J'ai des remarques concernant le python et django, sur la logique des tests je verrai en seconde lecture; ça semble OK de loin mais je préfèrerai voir cela en seconde lecture.

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +    def test_JobApplicationAdminForm(self):
en Python, le nom des méthodes (toutes, sans exception) sera du `snake_case`

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        """
si le titre de ton test est explicite (il devrait contenir un verbe ou adjectif, comme `test_jobapplicationadminform_validation` ou `test_job_seeker_can_create_foobar`) tu n'as pas besoin de ce commentaire. 

Toujours essayer de choisir un nommage approprié plutot que se rattraper avec des commentaires.

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertIn("created_at", form.fields)
c'est très précis mais pourquoi pas :) mieux : tu pourrais vérifier l'égalité de `form.fields` avec une liste, tu aurais l'ordre et ça casserait si on essaie d'en ajouter à la volée, ce qui est rassurant.

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertIn("Ce champ est obligatoire.", form.errors["to_siae"])
pareil, tu peux regarder si ton dictionnaire entier est valide.

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        data["to_siae"] = None
`data = model_to_dict(JobApplicationSentByJobSeekerFactory(job_seeker=None, to_siae=None))`

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        """
meme remarque sur les noms et commentaires

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertTrue(form.is_valid())
pareil, utiliser des factories au lieu des copy()

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        """
hmmm ? keskecé ?

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        """
joli nommage du test, on voit bien que le commentaire est redondant

2022-02-16 15:27 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertIn("Emetteur prescripteur manquant.", form.errors["__all__"])
pourquoi jamais `assertEqual` ?

2022-02-17 07:45 UTC, vincentporte commented on itou/job_applications/tests.py
> +        )
:100:

2022-02-17 07:47 UTC, vincentporte commented on itou/job_applications/tests.py
> +    def test_JobApplicationAdminForm(self):
:100:

2022-02-17 09:56 UTC, vincentporte commented on itou/job_applications/tests.py
> +        self.assertTrue(form.is_valid())
:100:

2022-02-17 09:57 UTC, vincentporte commented on itou/job_applications/tests.py
> +        data["to_siae"] = None
:100:

2022-02-17 13:03 UTC, vincentporte commented
Merci @vperron pour tes remarques. Quand tu auras le temps,  ton avis sur la structure des tests est bienvenue :)
Il reste la question des `assertEqual` vs `assertIn`, l'un est-il plus rapide que l'autre ?

2022-02-17 13:36 UTC, vperron commented
Je vais jeter un oeil. Pour la différence entre  `assertEqual` et `assertIn` la réponse n'est pas une question de rapidité ou de performance (d'ailleurs, c'est TRES rarement vraiment la question quand on code) ; c'est simplement que:
- `assertIn` vérifie la présence d'un ou plusieurs éléments au sein d'un autre
- `assertEqual` vérifie une égalité stricte (meme nombre d'éléments, tous identiques, dans le meme ordre
`assertIn` est donc plus faible et quand tu peux faire `assertEqual` c'est mieux.

Exemple:
```python
MY_LIST = [1, 2, 3]

self.assertIn(MY_LIST, [1, 2])  # vrai
self.assertEqual(MY_LIST, [1, 2, 3])  # vrai aussi

# je change, quelques semaines plus tard, ma définition
MY_LIST = [1, 2, 4]

self.assertIn(MY_LIST, [1, 2])  # ça reste vrai
self.assertEqual(MY_LIST, [1, 2, 3])  # ça casse, il faut adapter le test: il est donc plus sévère et va détecter le changement
```

2022-02-17 13:55 UTC, vperron reviewed
Très complet, merci pour les tests costauds. J'ai encore quelque remarques de culture concernant `assertIn` et les factories !

2022-02-17 13:55 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertEqual(list(form.fields.keys()), form_fields_list)
c'est violent mais au moins on aura un test qui casse si quelqu'un ajoute, retire ou réordonne un des champs de ce formulaire dans l'admin :+1:

2022-02-17 13:55 UTC, vperron commented on itou/job_applications/tests.py
> +        )
je pense que tu devrais plutot ecrire un dictionnaire Python et le transformer en json plutot que d'avoir une chaine de caractères, parce que là tu t'embetes un petit peu avec toutes ces concaténations et quotes :)

2022-02-17 13:55 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertTrue(form.is_valid())
je t'embete encore un tout petit peu :) plutot que de relancer une factory *à chaque fois* tu pourrais avoir:
```python
job_application = JobApplicationSentByJobSeekerFactory()

# cas 1
job_application.sender = None
JobApplicationAdminForm(model_to_dict(job_application))
[...]

# cas 2
job_application.sender_kind = SENDER_KIND_PRESCRIBER
JobApplicationAdminForm(model_to_dict(job_application))
[...]

# ...
```
ça fera moins de construction d'objets dans tous les sens en DB et moins de boilerplate à la relecture.

2022-02-17 13:55 UTC, vperron commented on itou/job_applications/tests.py
> +        self.assertIn("SIAE émettrice manquante.", form.errors["__all__"])
là tu vois je poursserais pour le `assertEqual` parce que si `form.errors['__all__']` contient *toutes* les erreurs possibles, ton test va passer quelle que soit la condition que tu es en train de tester.
Mais tu as peut etre une bonne raison de faire un `assertIn` : le assertEqual serait trop pénible ? J'avoue je ne sais pas, a toi de me dire :)

2022-02-17 13:55 UTC, vperron commented on itou/job_applications/tests.py
> +        data = model_to_dict(JobApplicationSentBySiaeFactory())
pareil ici : les factories c'est bien mais une par test ça suffit en général, arrange toi pour réutiliser tes objets. Chaque factory sera N ecritures en DB et ça ralentit les tests de manière inutile.

par contre, en recréer une par test c'est important pour ne pas avoir des objets partagés entre tests !

2022-02-17 14:04 UTC, vincentporte commented on itou/job_applications/tests.py
> +        )
:100: ce code me plaisait moyen

2022-02-17 14:04 UTC, vincentporte commented on itou/job_applications/tests.py
> +        self.assertTrue(form.is_valid())
:100:

2022-02-22 10:59 UTC, celine-m-s approved these changes

2022-02-22 11:25 UTC, merged