Correction des erreurs a11y sur les tableaux
betagouv/itou pull request #1123
Opened 2022-02-15 10:20 UTC by hellodeloo

### Quoi ?

Correction des erreurs a11y sur les tableaux

### Pourquoi ?

Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit

### Comment ?

En respectant les règles RGAA 5.1/5.2 et en ajoutant un titre aux <table> via la balsie <caption>
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-5-1

2022-02-16 12:47 UTC, celine-m-s requested changes

2022-02-16 12:47 UTC, celine-m-s commented on itou/templates/apply/list_of_available_exports.html
> +                <caption>Liste de candidatures reçues</caption>
```suggestion
                <caption>Liste des candidatures reçues par mois</caption>
```
On affiche des fichiers qui listent les candidatures mois par mois.

2022-02-16 12:47 UTC, celine-m-s commented on itou/templates/siaes/includes/_configure_jobs_list.html
> +    <caption>Liste de métiers(s) exercé(s) dans votre structure</caption>
```suggestion
    <caption>Liste des métiers exercés dans votre structure</caption>
```

Même s'il n'y a qu'un métier, une liste est censée en afficher plusieurs. Bon, à toi de juger. :)

2022-02-17 09:42 UTC, hellodeloo commented on itou/templates/siaes/includes/_configure_jobs_list.html
> +    <caption>Liste de métiers(s) exercé(s) dans votre structure</caption>
hi hi oui :)
c'est bien que tu repasses la dessus, les captions de tables et bientot les label d'input seront plus précis s'ils sont revus par les devs qui connaissent exactement de quoi il retourne. Moi je mets ce qui me semble bon mais sans plus de profondeur.

2022-02-17 15:31 UTC, merged