Correction des erreurs a11y sur les scripts
betagouv/itou pull request #1125
Opened 2022-02-15 16:45 UTC by hellodeloo

### Quoi ?

Correction des erreurs a11y sur les scripts, les roles boutons d'ouverture des dropdowns, des modals.
Replacement ou suppression des role="alert"

### Pourquoi ?

Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit

### Comment ?

En respectant ces règles 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
https://www.w3.org/TR/wai-aria/#combobox
https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_status_role

2022-02-16 12:40 UTC, celine-m-s requested changes
Un changement d'indentation mais le reste est bon pour moi. Juste quelques questions par curiosité.

2022-02-16 12:40 UTC, celine-m-s commented on itou/templates/apply/includes/job_applications_filters.html
> +            <a href="{% url 'apply:list_for_prescriber_exports' %}" class="btn btn-ico btn-outline-primary">
```suggestion
                <a href="{% url 'apply:list_for_prescriber_exports' %}" class="btn btn-ico btn-outline-primary">
```

Notre convention est d'indenter les blocs HTML dans les blocs Python.

2022-02-16 12:40 UTC, celine-m-s commented on itou/templates/apply/list_for_siae.html
> +        <div class="alert alert-emploi mt-3">
Pas de `role="status"` ici car l'information n'est pas assez importante ?

2022-02-16 12:40 UTC, celine-m-s commented on itou/templates/dashboard/edit_job_seeker_info.html
> +<div class="alert alert-warning">
Pourquoi on n'a pas de rôle status ici ?

2022-02-17 09:50 UTC, hellodeloo commented on itou/templates/apply/includes/job_applications_filters.html
> +            <a href="{% url 'apply:list_for_prescriber_exports' %}" class="btn btn-ico btn-outline-primary">
Bon a savoir

2022-02-17 09:54 UTC, hellodeloo commented on itou/templates/apply/list_for_siae.html
> +        <div class="alert alert-emploi mt-3">
Ben c'est une info qui n'est pas affichée apres une action mais toujours présente (enfin si `siae.is_subject_to_eligibility_rule = true`).  Donc je dirais que ce n'est pas nécessaire

2022-02-17 10:00 UTC, hellodeloo commented on itou/templates/dashboard/edit_job_seeker_info.html
> +<div class="alert alert-warning">
Il me semble que l'info est toujours visible par défaut non ?  Par contre si ce template n'est chargé que via une action alors là oui il faudrait un role=status

Via une url basique -> pas de rôle (car l'info n'est pas conditionnée à une interaction). Via une action sur un formulaire ou bouton -> role=status

À toi de me dire, parceque moi je ne sais pas sous quelle condition est chargé ce template.

2022-02-17 15:28 UTC, merged