wip: fix a11y forms
betagouv/itou pull request #1165
Opened 2022-03-08 10:26 UTC by hellodeloo

### Quoi ?

Correction des erreurs a11y sur les formulaires

### Pourquoi ?

Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit.

### Comment ?

2022-03-09 10:51 UTC, celine-m-s requested changes

2022-03-09 10:51 UTC, celine-m-s commented on itou/templates/apply/includes/job_applications_filters.html
> +                    </ul>
Hum, cette modif est aussi présente dans la PR #1168, non ?

2022-03-09 10:51 UTC, celine-m-s commented on itou/templates/layout/_footer.html
> +                        <li><a href="{% url 'accessibility' %}" rel="noopener">Accessibilité : partiellement conforme</a></li>
![party](https://user-images.githubusercontent.com/6150920/157426986-e0845f5b-462a-4d20-98fd-bd04b92e0c66.gif)

2022-03-09 10:51 UTC, celine-m-s commented on itou/templates/static/accessibility.html
> +    <p>Cette déclaration a été établie le 22/06/2021. Elle a été mise à jour le 08/03/20221.</p>
On est déjà en 20 221 ? J'ai loupé l'info. :trollface:

2022-03-10 09:07 UTC, hellodeloo commented on itou/templates/apply/includes/job_applications_filters.html
> +                    </ul>
Effectivement. Je vais rebase master du coup

2022-03-10 09:07 UTC, hellodeloo commented on itou/templates/static/accessibility.html
> +    <p>Cette déclaration a été établie le 22/06/2021. Elle a été mise à jour le 08/03/20221.</p>
Arf

2022-03-10 10:30 UTC, celine-m-s approved these changes
YOUHOU !! :tada:

2022-03-10 10:38 UTC, merged