Contrôle à Posteriori : phase selection des Siaes
betagouv/itou pull request #1186
Opened 2022-03-17 11:11 UTC by vincentporte

### Quoi ?

Ajout des fonctionnalités de sélection des Siaes dans le processus de contrôle à postériori des pièces justificatives des auto-prescriptions.

### Pourquoi ?

Les DDETS doivent pouvoir lancer des campagnes de contrôles des prescriptions de Pass IAE réalisées par les Siaes, appelées "auto-prescriptions".

### Comment ?

- ajout d'une application Django `siae_evaluations`
- ajout du modèle de données associé
- ajout des méthodes associées au modèle de données
- ajout des vues
- ajout des templates pour les pages dédiées aux institutions
- ajout des urls
- ajout des liens de navigation depuis le dashboard des institutions
- ajout des tests

2022-03-22 14:11 UTC, vperron commented on itou/siae_evaluations/admin.py
> +#    readonly_fields = ("document_url", "uploaded_at", "uploaded_by")
je pense que l'on va pouvoir retirer ce commentaire ^^ tu me connais :)

2022-03-22 14:14 UTC, vperron commented on itou/siae_evaluations/factories.py
> +    """Generate an EvaluationCampaign() object for unit tests."""
inutile je pense

2022-03-22 14:14 UTC, vperron commented on itou/siae_evaluations/factories.py
> +    criteria = factory.SubFactory(AdministrativeCriteriaFactory)
ce sont trois factories de trop je pense. Conserve les de ton coté pour plus tard mais pas dans master ?

2022-03-22 14:23 UTC, vperron commented on itou/siae_evaluations/models.py
> +from itou.siae_evaluations.enums import (
hint: le namespacing pour eviter les imports à rallonge et savoir mieux d'où vient un enum
```python
from itou.siae_evaluations import enums as evaluation_enums

[...]


print(evaluation_enums.DocumentState)
```

2022-03-22 14:24 UTC, vperron commented on itou/siae_evaluations/models.py
> +        # *** still wondering how to filter on a method :-| ***
comment donc ?

2022-03-22 14:30 UTC, vperron commented on itou/siae_evaluations/models.py
> +        return self.filter(selected_at=None)
a la relecture je me dis que `selected` est en fait pas tarrible car j'ai mis pas mal de temps à comprendre qu'il ne s'agissait pas de campagnes "sélectionnées" par l'utilisateur (comme dans une liste avec cases à  cocher par exemple)

L'élection ou un autre mot plus caractéristique seraient peut etre plus clairs.

2022-03-22 14:33 UTC, vperron commented on itou/siae_evaluations/models.py
> +        return self.for_institution(institution).not_selected().first()
attention à la répétition des noms de la classe dans tes méthodes, pas besoin de préciser `evaluation_campaign`, c'est deja ton Manager. Exemple plus parlant:
```python

class Person:

    def person_has_limbs(self):
         return True

# donnera en utilisation

Person().person_has_limbs()  # person_ est inutile
Person().has_limbs()  # plus court et naturel
```

2022-03-22 14:34 UTC, vperron commented on itou/siae_evaluations/models.py
> +    There is only one campaign in one departement for one evaluated period
est-on certain de cela ? peut etre retirer cette mention si le code ne l'oblige pas

2022-03-22 14:34 UTC, vperron commented on itou/siae_evaluations/models.py
> +    name = models.CharField(verbose_name="Nom de la campagne d'évaluation", max_length=25, blank=False, null=False)
25 est un peu court, pas besoin de se limiter autant, non ?

2022-03-22 14:36 UTC, vperron commented on itou/siae_evaluations/models.py
> +    )
j'hésite. On ajoute une dépendance sur le modèle User (qui est de loin la plus volumineuse des tables du système) pour cette petite application probablement jetable. 

Une foreignkey c'est des lenteurs, des index supplémentaires, un lock quand on met à jour cette colonne, etc. Je me demande si ce n'est pas overkill pour un besoin non établi à ce jour.

2022-03-22 14:38 UTC, vperron commented on itou/siae_evaluations/models.py
> +    )
je ne suis pas certain de deux choses:
- quelles sont les dates en question, ce sont celles paramétrées à la création de l'objet Campagne ? Pour signifier le début et la fin ? Ces dates sont-elles nécessaires ? Comment les utilise-t-on ?
- si elles sont entrées dès le départ à la création de la campagne, pourquoi ne pas les rendre obligatoirees ? (blank=False, null=False)

2022-03-22 14:40 UTC, vperron commented on itou/siae_evaluations/models.py
> +            )
plutot que d'utiliser `clean` pourquoi ne pas...
```python
IntegerField(
        default=1,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1)
        ]
     )
```

2022-03-22 14:40 UTC, vperron commented on itou/siae_evaluations/models.py
> +        #        )
a tretirer ou garder dans tes snippets non commités je pense. On doit vraiment eviter de commiter du commentiare sur master.

2022-03-22 14:41 UTC, vperron commented on itou/siae_evaluations/models.py
> +        return "new"
je ne suis pas certain de l'intérêt de ceci à ce stade, surtout sans utiliser des enumérations pour les états. On l'utilise ?
mais l'idée est là oui :)

2022-03-22 14:42 UTC, vperron commented on itou/siae_evaluations/models.py
> +        on_delete=models.PROTECT,
bien vu :)

2022-03-23 07:35 UTC, vincentporte commented on itou/templates/dashboard/dashboard.html
> -                            </li>
Le mockup précédent.…
Le meme lien existe encore pour les membres d'institutions type DGEFP. Rien n'est précisé pour l'instant. J'ai laissé en l'état.

2022-03-23 07:38 UTC, vincentporte commented on itou/templates/dashboard/dashboard.html
> +                    <p class="h4 card-header">Contrôle à postériori <span class="badge badge-info">Nouveau</span></p>
ok

2022-03-23 08:21 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        return self.filter(selected_at=None)
percent_set_at

2022-03-23 08:31 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    There is only one campaign in one departement for one evaluated period
right

2022-03-23 08:38 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    )
`created_at`, `percent_set_at`, `evaluations_asked_at`, `ended_at` sont les étapes de déroulement du contrôle. Ces dates sont utilisées pour déclencher l'envoi des emails, gérer l'accès aux pages, l'affichage des liens.
Elles sont utilisées pour définir l'état de la campagne. Je trouve plus souple de laisser à None que de tester en permanence avec la date du jour.

`evaluated_period_start_at` et `evaluated_period_end_at` sont les dates entre lesquelles les candidatures seront selectionnées. Elles sont obligatoires dès le paramétrage de la campagne

2022-03-23 08:38 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    )
overkill! FK enlevée

2022-03-23 08:41 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        return "new"
removed

2022-03-23 08:55 UTC, vincentporte commented on itou/templates/dashboard/dashboard.html
> +                {% endcomment %}
make quality est creatif :- |

2022-03-23 09:04 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            )
updated

2022-03-23 10:34 UTC, vperron commented on itou/templates/dashboard/dashboard.html
> +                {% endcomment %}
en effet, il est meme bien bizarre !

2022-03-23 10:49 UTC, vincentporte commented on itou/templates/dashboard/dashboard.html
> +        {% if can_view_stats_ddets and has_active_siae_evaluations_campaign %}
to be fixed : ` {% if can_view_stats_ddets and has_active_campaign %}`

2022-03-23 14:54 UTC, vincentporte commented
@hellodeloo je t'ai ajouté dans la revue pour review le template samples_selection.html

2022-03-23 15:14 UTC, vincentporte commented on .gitignore
> +/redisdata
removed

2022-03-23 15:15 UTC, vincentporte commented on itou/templates/dashboard/dashboard.html
> -                            </li>
le lien a finalement été réutilisé pour la visualisation des données.

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +            raise ValidationError(f"Sélectionnez une institution de type {Institution.Kind.DDETS}")
cette fonction n'a pas besoin d'être dans `EvaluationCampaign` car tu n'accèdes pas à `self`. Mets-la en top-level et teste la unitairement, en lui passant juste des IDs, pas au travers d'une validation complexe via une vue et un save() comme tu le fais plus bas.

`get_object_or_404` n'a de sens que dans une vue, ici on est dans des modèles; je pense que tu devrais plutôt récupérer ton objet `Institution` et `raise ValidationError("L'institution sélectionnée n'existe pas !")`

Aussi: evitons de nommer la fonction par rapport à  ce qu'il y a dedans car son contenu peut justement changer.
On nomme suivant l'emploi, pas suivant le contenu :) Du coup `validate_institution` irait très bien.

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +    percent_set_at = models.DateTimeField(verbose_name=("Date de paramétrage de la selection"), blank=True, null=True)
nit: sélection

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +    ended_at = models.DateTimeField(verbose_name=("Date de clotûre de la campagne"), blank=True, null=True)
nit: clôture

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +        verbose_name=("Institution type DDETS"),
Institution responsable du contrôle ?

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +        related_name="evaluation_campaign",
nop, le related d'une ForeignKey est forcément une liste. `evaluation_campaigns` ?

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/models.py
> +        verbose_name="Pourcentage de selection",
nit: sélection

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/tests/tests_admin.py
> +    def test_check_is_DDETS(self):
fais un test unitaire tout petit de la fonction à la place de ce gros machin, ça sera plus concis :)

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/tests/tests_management_command.py
> +# from io import StringIO
a retirer

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/tests/tests_management_command.py
> +# from itou.siae_evaluations.management.commands import generate_new_campaigns
a retirer

2022-03-25 08:18 UTC, vperron commented on itou/siae_evaluations/tests/tests_management_command.py
> +class EvaluationCampaignManagementCommand(TestCase):
je pense que l'on peut retirer la management command et laisser juste l'admin si c'est pour juste créer un objet

2022-03-25 08:18 UTC, vperron commented on itou/templates/stats/stats.html
> +        Le tableau ci-dessous comprend 100% des auto-prescriptions faites en 2021, vous en avez accès pour prendre connaissance de ces caractéristiques.
"vous en avez accès pour prendre connaissance de ces caractéristiques" ?? est-ce bien français ?

2022-03-25 08:18 UTC, vperron commented on itou/templates/siae_evaluations/samples_selection.html
> +                        <p class="font-weight-bold">Vous n'avez pas de selection en attente.</p>
nit: sélection

2022-03-25 08:18 UTC, vperron commented on itou/templates/siae_evaluations/samples_selection.html
> +                        <button type="submit" class="btn btn-primary  float-right" onclick="return confirm('Le ratio sélectionné ne sera plus modifiable pour cette campagne de contrôles. Confirmez-vo
campagne de contrôle, sans S

2022-03-25 08:18 UTC, vperron commented on itou/templates/siae_evaluations/samples_selection.html
> +                    <p class="font-weight-bold">Ratio selectionné : <span id="showChosenPercentValue"></span> %</p>
nit : sélectionné

2022-03-25 08:18 UTC, vperron commented on itou/templates/siae_evaluations/samples_selection.html
> +                        <p>Si une ETTI de votre territoire à fait 270 auto-prescriptions, vous n'en aurez à en contrôler que 20 et non 54 (20% de 270)</p>
nit: à fait ?? => a fait.

Tu ne copies/colles pas depuis Figma ? Ou ce sont les maquettes qui ont des typos ?

2022-03-25 08:18 UTC, vperron commented on itou/templates/siae_evaluations/samples_selection.html
> +                        <p>Si une ETTI de votre territoire à fait 270 auto-prescriptions, vous n'en aurez à en contrôler que 20 et non 54 (20% de 270)</p>
"vous n'en aurez à en contrôler" bizarre aussi

2022-03-25 08:18 UTC, vperron commented on itou/www/siae_evaluations_views/tests.py
> +        membershipfactory = InstitutionMembershipFactory()
c'est une membership le retour de cette fonction.

2022-03-25 08:18 UTC, vperron commented on itou/www/siae_evaluations_views/views.py
> +        selection.save()
`update_fields=['chosen_percent', 'percent_set_at']`

2022-03-25 08:18 UTC, vperron commented on itou/www/siae_evaluations_views/views.py
> +            f"Le pourcentage de selection pour le contrôle a posteriori "
nit: sélection

2022-03-25 10:27 UTC, vincentporte commented on itou/siae_evaluations/enums.py
> +    # Percents range set by DGEFP (national labor inspection)
…

2022-03-25 10:27 UTC, vincentporte commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +    """
…

2022-03-25 10:34 UTC, vincentporte commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Thank you for traveling with us!")
pour la V0 du mock jetable, je n'ai pas pluggé dans l'admin ^^

2022-03-25 10:38 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        related_name="evaluation_campaign",
bien vu

2022-03-25 10:39 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        verbose_name=("Institution type DDETS"),
l'idée est d'insister avec insistance qu'il faut choisir une DDETS
=> DDETS responsable du contrôle

2022-03-25 10:49 UTC, vincentporte commented on itou/templates/stats/stats.html
> +        Le tableau ci-dessous comprend 100% des auto-prescriptions faites en 2021, vous en avez accès pour prendre connaissance de ces caractéristiques.
ne dénigrons pas les régionalismes :D

2022-03-25 11:34 UTC, vincentporte commented on itou/siae_evaluations/tests/tests_admin.py
> +    def test_check_is_DDETS(self):
ok, bien vu. 
idem pour tester la methode clean

2022-03-25 12:28 UTC, vperron commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Thank you for traveling with us!")
c'est faux, tu as bien un admin.py ? dans cette PR !

2022-03-25 12:30 UTC, vperron commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Thank you for traveling with us!")
tu t'embetes beaucoup plus avec une management command en realité, c'est du code en plus, des tests en plus et ce n'est pas plus pratique à utiliser.

2022-03-28 07:34 UTC, vincentporte commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Thank you for traveling with us!")
pour la V0 du mock jetable, je n'ai pas pluggé >la commande de génération <dans l'admin. cette commande demande 2 dates en paramètres. Peux tu m'apprendre à crée une action de l'admin qui prend des paramètres en entrée pour remplacer la management command ?

2022-03-28 07:35 UTC, vperron commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Thank you for traveling with us!")
ah tiens ? je suis étonné que ce soit un problème, mais bien sûr on peut en parler ! j'ai peut etre loupé quelque chose :/

2022-03-28 07:37 UTC, vincentporte commented on itou/www/siae_evaluations_views/views.py
> +        selection.save()
updated.

2022-03-28 11:57 UTC, vperron commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +            evaluation_campaign.institution = institution
tu peux de manière plus concise écrire les kwargs dans le constructeur.
de plus tu es en train d'overrider des arguments par défaut (comme now et 30)
donc:
```python

for inst in Institution.objects.filter(...):
    # created_at est par défaut à now, chosen_percent à 30
    ec = EvaluationCampaign(name=name, evaluated_period_start_at=start_at, end_at=end_at, institution=inst)
    ec.save()

```

2022-03-28 15:02 UTC, vincentporte commented on itou/siae_evaluations/management/commands/generate_new_campaigns.py
> +        self.stdout.write("Hey Buddies")
outdated

2022-03-29 10:57 UTC, vperron requested changes
je ne finis pas la review mais je ne suis pas d'accord, on avait dit qu'on se limitait au modèle EvaluationCampaign et ta PR etait à 99% prête. 
Là on ajoute de nouveau les 4 autres modèles hyper rapidement ce qui est une mauvaise idée parce que ils vont probablement changer (pas plus tard que ce matin Jo et Zo ont proposé une évolution qui va venir modifier les EvaluatedSiae et autres modèles !)
Il faut je pense rapidement:
- stocker tout ce travail quelque par concernant le calcul et sélection d'une SIAE
- revenir vite à une PR qui stocke uniquement le pourcentage et la merge, elle était bien !
- faire une nouvelle PR qui réalise le populate() mais avec 4 semaines pour la faire et pas 2 jours.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/migrations/0001_initial.py
> +    ]
supprime et recrée ton fichier de migration, là sinon tu vas créer des modèles en DB alors qu'ils ne sont plus dans ton models.py.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/factories.py
> +    created_at = timezone.now()
je crois que tu as déjà un default now dans le modèle sur ce champ.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/enums.py
> +    Evaluable = [Siae.KIND_EI, Siae.KIND_ACI, Siae.KIND_ETTI]
si on a un seul membre dans l'énumération, est-ce une constante  ou une énumération ? pour moi ça dépend de si on pense en ajouter un jour. auquel cas aucun souci, et ignore ce commentaire.

par contre peut etre rappeller pourquoi on a mis uniquement ces dernières peut être utile pour savoir si on peut le modifier un jour.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +def select_eligible_job_applications(campaign):
si tu lui passes un objet campaign, autant le mettre dans le modèle `EvaluationCampaign` et agir sur self non ?

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +            eligibility_diagnosis__author_kind="siae_staff",
non : pour ces deux lignes il faut utiliser l'enum (en espérant qu'il existe !) et pas hardcoder la valeur. Nous ne sommes pas dans les tests ici.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +        return []
il vaut mieux de loin retourner un queryset. 
```python
return queryset.none()
```

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +    if qs.count() < 2:
expliquer les magic values et leur choix, toujours.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +    qty = qs.count() * 0.2
attention tu fais deux fois un count() à la suite donc deux requetes en DB pour pas grand chose.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +        qty = int(round(qty))
tout ce code semble pouvoir se réécrire en
```python
# select 20% max, within bounds
limit = int(round(qs.count() * 0.2))
if limit < 2:
    limit = 0
elif limit > 20:
    limit = 20
# do not use random.sample + list, ça va faire une requete monstre sur toute la table, convertir en python puis
# truncate ! utiliser le order_by(random)
return qs.order_by("?")[:limit]
```

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +    return random.sample(list(qs), qty)
cf commentaire plus haut, cela est vraiment pas top en termes de requete et perf

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +    random_siaes = random.sample(siaes, round(len(siaes) * campaign.chosen_percent / 100))
il est un peu plus compliqué d'utiliser order_by("?") ici puisque tu pars de ta liste `eligible_job_applications` pour recupérer tes SIAE et faire un distinct(), mais.... je pense qu'on peut faire mieux.
Après, peut etre pas la peine de partir dans une subquery de dingo pour ce code jetable, mais si on laisse tel quel parce que ça marche et c'est suffisant, peut etre juste laisser un commentiare pour dire qu'on a fait vite ici mais que ça suffit :)

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +    _ = insert_eligibility_diagnoses(evaluated_job_applications)
toutes les fonctions intermédiaires que tu as appelées sont plut ou moins des one-liners et ne sont appelées qu'une fois, je te conseillerais de ne pas les séparer et de tout mettre directement dans `populate_campaign` ça dfera moins d'indirections.

2022-03-29 10:57 UTC, vperron commented on itou/siae_evaluations/models.py
> +        raise ValidationError("Le ratio n'a pas encore été validé par l'institution en charge du contrôle.")
pourquoi ne pas mettre `populate()` sur l'objet `EvaluationCampaign` ?

2022-03-29 16:26 UTC, celine-m-s commented on config/settings/base.py
> +    "itou.www.siae_evaluations_views",
C'est Marc qui avait architecturé le projet comme cela pour séparer les apps back purement back (modèles) de celles qui sont exposées (vues).

2022-03-29 17:40 UTC, vincentporte commented on itou/siae_evaluations/enums.py
> +    Evaluable = [Siae.KIND_EI, Siae.KIND_ACI, Siae.KIND_ETTI]
il faudra ajouter les AI pour les contrôles de 2022. ok pour le commentaire

2022-03-29 17:46 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        qty = int(round(qty))
ok

2022-03-29 17:48 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    _ = insert_eligibility_diagnoses(evaluated_job_applications)
j'ai choisi de les séparer et d'isoler les bulk_create() pour simplifier les tests.

2022-03-29 17:50 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +        raise ValidationError("Le ratio n'a pas encore été validé par l'institution en charge du contrôle.")
à discuter de vive-voix, j'interprète de 2 manières ta question

2022-03-29 17:50 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    random_siaes = random.sample(siaes, round(len(siaes) * campaign.chosen_percent / 100))
ok pour le commentaire

2022-03-29 17:50 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    return random.sample(list(qs), qty)
k

2022-03-29 17:51 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +def select_eligible_job_applications(campaign):
k

2022-03-29 17:53 UTC, vincentporte commented on itou/siae_evaluations/migrations/0001_initial.py
> +    ]
> je ne finis pas la review mais je ne suis pas d'accord, on avait dit qu'on se limitait au modèle EvaluationCampaign et ta PR etait à 99% prête. Là on ajoute de nouveau les 4 autres modèles hyper rapidement ce qui est une mauvaise idée parce que ils vont probablement changer (pas plus tard que ce matin Jo et Zo ont proposé une évolution qui va venir modifier les EvaluatedSiae et autres modèles !) Il faut je pense rapidement:
> 
>     * stocker tout ce travail quelque par concernant le calcul et sélection d'une SIAE
> 
>     * revenir vite à une PR qui stocke uniquement le pourcentage et la merge, elle était bien !
> 
>     * faire une nouvelle PR qui réalise le populate() mais avec 4 semaines pour la faire et pas 2 jours.

ça me va bien d'ajouter les SIAE et les autoprescriptions, quand le pourcentage est validé, dès l'ouverture de la campagne. ça évitera des reprises de données ensuite. l'ensemble est prêt et testé.

2022-03-29 17:54 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    qty = qs.count() * 0.2
k

2022-03-29 17:55 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            eligibility_diagnosis__author_kind="siae_staff",
à discuter de vive voix

2022-03-30 11:23 UTC, vperron commented on itou/siae_evaluations/models.py
> +            eligibility_diagnosis__author_kind="siae_staff",
utiliser `from itou.utils.perms.user import KIND_SIAE_STAFF`, pas une chaine de caractères en dur dans le code.
Pareil pour `"accepted"` qui etait un de tes enums (mais que l'on a plus dans cette PR ci) : ne pas hardcoder.

2022-03-30 12:27 UTC, vperron approved these changes
quelques remarques vachement mineures et de culture gé mais c'est approved :+1:

2022-03-30 12:27 UTC, vperron commented on itou/siae_evaluations/models.py
> +    evaluation_campaign = EvaluationCampaign.objects.bulk_create(campaigns)
nit: un peu confusant, `bulk_create` va te retourner une liste de `created_campaigns`.
supernit: tu crees une liste avec `campaigns mais tu pourrais faire un itérateur ^^ on en parlera un jour si tu vois pas la différence

```python
# liste en mémoire
campaigns = [xxx for xxx in stuff]
EvaluationCampaign.objects.bulk_create(campaigns)

# itérateur, ne consomme pas de ram jusqu'au tout dernier moment (evaluation du queryset)
EvaluationCampaign.objects.bulk_create(xxx for stuff in stuff)  # pas de [] 
```

2022-03-30 12:27 UTC, vperron commented on itou/siae_evaluations/models.py
> +    return get_email_message(to, context, subject, body, bcc=bcc)
je ne sais pas si tu as besoin de toutes ces variables intermédiaires, tu pourrais aussi bien appeler directement `get_email_message` dans `create_campaign en passant les arguments directement sans créer `to`, `bcc`, etc.

2022-03-30 12:27 UTC, vperron commented on itou/siae_evaluations/models.py
> +    return get_email_message(to, context, subject, body, bcc=bcc)
mais bon c'est tres mineur comme commentaire

2022-03-30 12:27 UTC, vperron commented on itou/www/siae_evaluations_views/tests.py
> +        cls.url = reverse("siae_evaluations_views:samples_selection")
comme dit ailleurs, il est souvent préférable d'utiliser `setUp` pour eviter que tes tests ne se genent les uns les autres. mineur mais je le dis pour l'avenir.

2022-03-30 12:54 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +    bcc = emails
bien vu : https://github.com/betagouv/itou/blob/bb769c6b721dcd57b6e3238c7fe90546a8d1deb3/itou/utils/emails.py#L69
Mailjet met une limite à 50. Itou ne sanitize que le champ TO ^^
=> to rework

2022-03-30 16:19 UTC, merged