Quelques ajustements frontend
betagouv/itou pull request #1216
Opened 2022-04-04 15:22 UTC by hellodeloo

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

2022-04-06 15:28 UTC, celine-m-s requested changes
Quelques remarques sur le `d-none` et sur des couleurs dans le CSS.
J'aurais préféré que tu fasses une PR pour chaque carte Notion. Cela peut paraître un peu pénible mais, dans notre cas, j'en aurais validé une des deux (le bouton dans l'alerte).

2022-04-06 15:28 UTC, celine-m-s commented on itou/static/css/itou.css
> +        background: linear-gradient(to left, #fbfbfb 50%, #f2f8fd 50%);
Je ne comprends pas pourquoi on a besoin de ces background-colors ?
On ne peut pas le faire avec le thème ?

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/account/login_generic.html
> -    <div class="mt-5 d-none d-sm-block">
Pourquoi supprimer ce d-none ? La colonne de gauche ne doit pas apparaître sur mobile (elle est décorative) et l'indiquer ici rend l'information plus explicite que dans le CSS.

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/account/login_job_seeker.html
> -    <div class="mt-5 d-none d-sm-block">
Même remarque ici.

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> +    <section class="s-section-twocolumns">
Pourquoi remplacer `main` par `section` ? Nous sommes bien ici dans le contenu principal de la page et non dans une section. Non ?

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> -    <main class="{% block content_container_css_classes %}{% endblock %} container-fluid">
Pourquoi supprimer le block de classes CSS ?

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> +    <section class="s-section-twocolumns">
Attention, le bloc permettant d'ajouter des classes CSS à partir de gabarits enfants a sauté. À vérifier s'il est utilisé.

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> +                <div class="d-none d-md-block col-12 col-lg-6 order-md-1 bg-emploi-lightest pr-lg-5 py-5 py-lg-7">
J'ai fait exprès de ne pas ajouter le `d-none` ici pour laisser le choix dans le gabarit enfant.

2022-04-06 15:28 UTC, celine-m-s commented on itou/templates/signup/job_seeker_nir.html
> +            <a href="https://www.ameli.fr/assure/droits-demarches/principes/numero-securite-sociale" title="Article concernant le numéro de sécurité sociale (ouverture dans un nouvel onglet)" rel="no
:+1:

2022-04-06 15:31 UTC, celine-m-s commented
PS : le CSS étant en conflit avec celui sur la branche Master, il n'est pas possible de créer de recette jetable. Pourrais-tu faire un rebase ? Merci !

2022-04-07 13:31 UTC, celine-m-s commented on itou/static/css/itou.css
> +        background: linear-gradient(to left, #fbfbfb 50%, #f2f8fd 50%);
Heu oui mais ces fonds ne sont pas nécessaires, si ? On n'en avait pas avant.

2022-04-25 13:22 UTC, hellodeloo commented
@celine-m-s Rebase Ok 
J'ai aussi sorti le fix de l'alert pour e mettre dans une PR séparée

2022-04-25 14:04 UTC, hellodeloo reviewed
Done

2022-04-25 14:08 UTC, hellodeloo reviewed
Done

2022-04-25 14:08 UTC, hellodeloo commented on itou/templates/account/login_generic.html
> -    <div class="mt-5 d-none d-sm-block">
Yes, mauvaise idée. Il y a effectivement le template job_seeker_nir.html qui affiche toujours cette colonne. J'avais cru qu'ils la masquaient tous. My mistake

2022-04-25 14:09 UTC, hellodeloo reviewed
Done

2022-04-29 10:18 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> +    <section class="s-section-twocolumns">
Ah, d’accord !

2022-04-29 10:19 UTC, celine-m-s commented on itou/templates/layout/content_two_columns.html
> -    <main class="{% block content_container_css_classes %}{% endblock %} container-fluid">
Ah oui, c’est vrai. Tu peux l’enlever si tu veux faire du ménage ou le laisser si tu penses t’en servir un jour.

2022-04-29 10:22 UTC, celine-m-s commented on itou/static/css/itou.css
> +        background: linear-gradient(to left, #fbfbfb 50%, #f2f8fd 50%);
Ok ! 👌

2022-05-02 09:07 UTC, merged