feat(api): ajout d'une vue pour représenter les siaes au format data.inclusion
betagouv/itou pull request #1314
Opened 2022-05-24 14:57 UTC by vmttn

### Quoi ?

Ajout d'un endpoint `/api/structures/` (nommage à préciser) pour lister les données de type structures (SIAEs dans le cas présent), au format data.inclusion.

* [schéma data.inclusion](https://github.com/betagouv/data-inclusion-schema)
* [doc du schéma data.inclusion](https://app.gitbook.com/o/-LumF4j8whrJ3iKwLJ6f/s/8F5IpX18jjDR1Iawzsnj/schemas-de-donnees-de-loffre/schema-des-structures-dinsertion)

### Pourquoi ?

Le but est d'exposer les données dans un format en cours de standardisation pour permettre le moissonnage par data.inclusion le partage et la réutilisation des données.

### Comment ?

* dito
* endpoint avec accès restreint (données de contact exposées)
* changement self-contained dans `itou/api/data_inclusion_api/`

### Autres

- [x] tests du endpoint
- [x] reste à traiter la relation de type antenne entre 2 siaes
- [x] récupération du code_insee via ban par page

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/tests.py
> +                },
joli, ce test est assez clean ! cela dit plutot que `ANY` tu aurais été plus robuste en utilisant `self.antenne`.

Ce serait bien d'avoir aussi un test qui voie ce que ça donne quand le descriptif fait plus de 280 caractères ou quand la SIAE n'est pas en `USER_CREATED`.

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +    def __init__(self, base_url: str = settings.API_BAN_BASE_URL):
ce setting n'est défini nulle part, non ?

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +                )
OMG cette API n'a pas de gestion JSON ? :)

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +            except httpx.RequestError as e:
bien :) mais dommage de retourner None au lieu par exemple d'une liste vide ou dictionnaire vide,  ton appelant va casser.

Attention d'ailleurs car ce client d'API n'est pas du tout testé, ni son appelant `annotate_with_insee_code`.

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +            writer = csv.DictWriter(wrapper, fieldnames=["id", "post_code"])
on donne littéralement un `id` interne itou à une API externe et elle se débrouille avec ? wahou par quelle magie ? on est plus connus que je ne pensais :)

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +        siae.insee_code = insee_code_by_id.get(siae.id, "") if insee_code_by_id else ""
nit: ça me semble un tout petit peu alambiqué mais pourquoi pas :)

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/viewsets.py
> +    queryset = Siae.objects.all().order_by("id")
par date d'ajout peut etre ? meme les inactives ?

2022-05-30 14:11 UTC, vperron commented on itou/api/data_inclusion_api/viewsets.py
> +        # on the BAN api.
c'est quand meme un petit peu cavalier je pense de faire un appel à une seconde API pendant l'appel à une première, ça cascade les éventuelles erreurs et ça rend le tout plutot fragile. On ne sait pas combien le client va requeter de données d'ailleurs.

Idealement on devrait plutot avoir soit:
- un cron de notre coté quir écupère les codes INSEE si on ne les a pas déjà et les enregistre progressivement en base
- c'est au client de se débrouiller pour appeler les 2 APIs et faire son matching si il a besoin des deux infos.
Moi en l'état cette méthode me rend plutot mal à l'aise, à dispo pour en discuter ! Je n'ai pas tous les tenants et aboutissants.

2022-05-30 15:08 UTC, ikarius commented on itou/api/data_inclusion_api/serializers.py
> +        if obj.source == Siae.SOURCE_USER_CREATED:
La recherche sur des "antennes" au sens C1 du terme implique que la source soit à cette valeur.
Si c'est bien ce que tu as voulu exprimer Valentin ...

2022-05-30 15:35 UTC, ikarius commented on itou/api/data_inclusion_api/serializers.py
> +            if structure_parente is not None:
- un petit `select_related` sur la convention pour le queryset qui sera utilisé sur le viewset me semblerait bien en ce cas
- ou `Siae.objects.get(source=Siae.SOURCE_ASP, convention__asp_id=obj.asp_id )` pour les structures parentes
-  et je plussoie la remarque de Victor

2022-05-30 15:37 UTC, ikarius commented on itou/api/data_inclusion_api/serializers.py
> +                return structure_parente.id
L'`asp_id` est un bon choix alternatif effectivement si tu veux utiliser ce qui touche aux antennes, conventions, etc,,,

2022-05-30 15:37 UTC, ikarius commented on itou/api/data_inclusion_api/utils.py
> +    def __init__(self, base_url: str = settings.API_BAN_BASE_URL):
je le cherche depuis tout à l'heure effectivement :)

2022-05-30 15:44 UTC, ikarius commented on itou/api/data_inclusion_api/viewsets.py
> +    queryset = Siae.objects.all().order_by("id")
Ca fait beaucoup de SIAE ça :)
Correct, dans les SIAE inactives, il y en a certainement qui n'existent plus IRL.
Si besoin, `SiaeQuerySet.active_lookup` directement sur le manager / queryset de l'objet `Siae`

2022-05-30 15:56 UTC, ikarius commented on itou/api/data_inclusion_api/utils.py
> +        siae.insee_code = insee_code_by_id.get(siae.id, "") if insee_code_by_id else ""
L'utlisation de cette API c'est uniquement pour le code INSEE ?

Parce qu'on a les codes INSEE à dispo (à plusieurs endroits même) : le plus pertinent eT à jour dans l'objet `cities.City`.
Ca devrait pas être trop dur de croiser avec les infos de la table SIAE...

Par ailleurs, une recherche de code INSEE par code postal, c'est pas fiable (possibilité de doublons ou +).

2022-05-30 15:58 UTC, ikarius commented on itou/api/data_inclusion_api/viewsets.py
> +        # on the BAN api.
Voir précédente remarque sur les codes INSEE.

2022-05-30 16:15 UTC, ikarius requested changes
Quelques remarques et un point bloquant à discuter concernant les codes INSEE.
Belle utilisation de DRF, BTW

2022-05-30 20:17 UTC, celine-m-s commented on itou/api/data_inclusion_api/serializers.py
> +            "id",
Heu, ptètre pas non. Je n'en vois pas l'utilité.

2022-05-31 20:34 UTC, celine-m-s commented on itou/api/data_inclusion_api/serializers.py
> +            structure_parente = Siae.objects.exclude(source=Siae.SOURCE_USER_CREATED).get(
Pour info, notre convention, sur Itou, est de coder en anglais mais de faire les PR en français.
Tout ce qui concerne le code (nom de variables, de classes, commentaires, champs en base de données, ...) est en anglais.
Tout ce qui peut être lu par le métier ou par des partenaires externes (nom et description de PR, commentaires des PR, JSON renvoyé par les endpoints d'API) est en français.
Je comprends que la variable « structure_parente » porte ce nom-là car elle est exposée par l'API mais je le dis au passage.

2022-05-31 20:44 UTC, celine-m-s reviewed
Je ne suis pas favorable à ce que les ID soient exposés en clair. Si c'est une information importante, je suggère de les chiffrer (comme Fred l'a fait [pour les Users](https://github.com/betagouv/itou/blob/master/itou/users/models.py#L595)).

Par ailleurs, j'ai peut-être mal regardé mais je ne vois pas la gestion de l'authentification. Je ne souhaite pas que cette API soit accessible publiquement (mais on peut en discuter si vous voulez).

2022-06-07 10:05 UTC, vmttn commented on itou/api/data_inclusion_api/viewsets.py
> +        # on the BAN api.
ah si on peut en discuter de vives voix ça serait bien plus pratique !

2022-06-07 10:07 UTC, vmttn commented on itou/api/data_inclusion_api/serializers.py
> +            "id",
Côté data.inclusion on a besoin des identifiants des structures dans les différentes bases, afin de pouvoir remonter le fil et de créer des tables de correspondances. Vous récupérer bien un identifiant provenant de l'ASP : ça serait le même principe.
Quels seraient vos préoccupations ? Est-ce qu'il y a une alternative à utiliser votre identifiant interne ?

2022-06-07 10:07 UTC, vmttn commented on itou/api/data_inclusion_api/serializers.py
> +        if obj.source == Siae.SOURCE_USER_CREATED:
C'est bien ce que j'ai voulu exprimer.

En tout cas c'est les infos que j'avais sur les antennes. Il y a peut-être plus de cas ?

2022-06-07 10:07 UTC, vmttn commented on itou/api/data_inclusion_api/serializers.py
> +            structure_parente = Siae.objects.exclude(source=Siae.SOURCE_USER_CREATED).get(
ok je modifie le nom de la PR.
Les champs définis dans le serializer sont basés sur la spéc du schéma (qui est en français). Il faut que ça matche et je ne me suis donc pas posé de questions.

2022-06-07 10:07 UTC, vmttn commented on itou/api/data_inclusion_api/serializers.py
> +                return structure_parente.id
Pour `id` vs `pk`, nit effectivement je ferais ce que vous préférerez. Tu parles d'indirection dans le prochain commentaire et je pense que `.pk` en est un bon exemple.

Il me semble que le SIRET puisse être dupliqué pour une valeur de `kind` donnée. En faisant l'hypothèse que j'exclus les données qui n'ont pas de convention (quelles implications?) pour utiliser `asp_id`, l'`asp_id` a le même problème que le siret. L'intérêt pour moi d'utiliser l'id dans le cas présent est la contrainte d'unicité explicite. Cela permet de faire une référence explicite à une autre donnée dans le dataset, sans avoir à expliciter une logique "si 2 structures ont le même id, alors...").

2022-06-07 10:08 UTC, vmttn commented on itou/api/data_inclusion_api/tests.py
> +        cls.antenne = SiaeFactory(source=Siae.SOURCE_USER_CREATED, convention=cls.siae.convention)
Comme vous préférez !
* Les instances sont partagées entre les tests mais il n'y aura pas autre chose que de la lecture.
* J'étais soucieux du temps d'exécutions de vos tests, même s'il n'y a pas grand chose à gagner ici.
* je suis d'accord avec toi concernant l'indirection, d'autant plus que la méthode est introduite par django.

2022-06-07 10:08 UTC, vmttn commented on itou/api/data_inclusion_api/tests.py
> +                },
* pour `self.antenne`, je considére que du moment que `"structure_parente": self.siae.id` est bon, ça reviendrait à tester les mêmes choses que dans le premier cas. C'est bien sûr un tradeoff à la discrétion des mainteneurs, je vais faire le changement
* ok pour le test du descriptif à 280+ caractères
* `self.siae` est en `SOURCE_ASP`

2022-06-07 10:09 UTC, vmttn commented on itou/api/data_inclusion_api/utils.py
> +    def __init__(self, base_url: str = settings.API_BAN_BASE_URL):
https://github.com/betagouv/itou/blob/1d23ba66c0bc203c3db7c110c1464b556073604b/config/settings/base.py#L350

2022-06-07 10:09 UTC, vmttn commented on itou/api/data_inclusion_api/utils.py
> +                )
pour le géocodage en batch, pas à ma connaissance

2022-06-07 10:09 UTC, vmttn commented on itou/api/data_inclusion_api/utils.py
> +            except httpx.RequestError as e:
* tout à fait d'accord sur le dict vide :+1:
* pour les tests spécifiques à `BaseAdresseNationaleBackend`, ma préférence c'est de tester en appelant l'api BAN, sans mock. Pour `annotate_with_insee_code`, permettre d'injecter un faux `ban_backend`, sans mock.
* J'ai vu pas mal de mocks dans la codebase. Je peux me conformer à ce que vous avez l'habitude de faire.

2022-06-07 10:10 UTC, vmttn commented on itou/api/data_inclusion_api/utils.py
> +            except httpx.RequestError as e:
Si on peut discuter de l'intéret de passer par l'api BAN avant ça pourrait être pas mal

2022-06-07 10:10 UTC, vmttn commented on itou/api/data_inclusion_api/viewsets.py
> +    queryset = Siae.objects.all().order_by("id")
ok merci !

2022-06-07 14:07 UTC, vperron commented on itou/api/data_inclusion_api/serializers.py
> +            "id",
Je vois. Mais a priori, nous sommes totalement "esclaves" de l'ASP en ce qui concerne les SIAE: ce sont eux les maîtres de la donnée à ce sujet, et si nous avons bien un identifiant interne c'est par pure simplicité lors des manipulations de données.
Le souci avec les API c'est que dès que tu mets quelque chose dedans, ça sera utilisé et ça va nous forcer à garantir une stabilité quelconque sur nos identifiants, or ils sont censés etre opaques. 
Une API devrait n'exposer que le strict minimum et je serais rassuré que nous faisions ceci ici, quitte à le réintroduire plus tard si le besoin se fait sentir.

2022-06-07 14:17 UTC, vperron commented on itou/api/data_inclusion_api/serializers.py
> +            "id",
Mais attention (je me dis que il peut y avoir confusion !)

- le modèle et la table `Siae` chez nous contient à la fois des `Siae` (au sens ASP, qui ont donc un `asp_id`
- ... ET des associations, des structures diverses et exotiques, etc.

SI ta vue n'affiche que les SIAE au sens "Entreprise d'insertion" alors oui, tu vas filtrer dans cette table les structures qui viennent de l'ASP et elles auront un `asp_id`; auquel cas pas très utile de sortir l'ID interne Itou.

Si ta vue cherche à répertorier TOUTES les structures Itou, loars il est fort probable en effet que vous ayiez besoin de notre ID interne car nombreuses seront les structures non "SIAE au sens métier", donc sans `asp_id`.

2022-06-07 14:18 UTC, vperron commented on itou/api/data_inclusion_api/serializers.py
> +        if obj.source == Siae.SOURCE_USER_CREATED:
non je voulais bien m'assurer que c'etait bien cela que tu vherchais ! top.

2022-06-07 14:21 UTC, vperron commented on itou/api/data_inclusion_api/serializers.py
> +                return structure_parente.id
OK !

2022-06-07 14:22 UTC, vperron commented on itou/api/data_inclusion_api/tests.py
> +        cls.antenne = SiaeFactory(source=Siae.SOURCE_USER_CREATED, convention=cls.siae.convention)
D'une manière générale je préfère toujours privilégier en effet la probable stabilité long terme du test que sa rapidité d'exécution, je vois très bien un nouveau sur le code arriver et modifier une instance partagée sans faire attention, et patatras.

2022-06-07 14:26 UTC, vperron commented on itou/api/data_inclusion_api/tests.py
> +                },
parfait, merci ! pas grave du tout pour le ANY, comme je disais ça rend juste le test un poil + robuste avec `self.antenne` mais c'est très mineur; ma surprise venait du fait que nous n'utilisons quasi jamais ANY dans la base de code, et du coup quand je le vois arriver je me dis "tiens, il cherche spécifiquement à montrer qu'on se fiche de telle valeur". Mon habitude joue un peu ici ^^

2022-06-07 14:32 UTC, vperron commented on itou/api/data_inclusion_api/utils.py
> +        siae.insee_code = insee_code_by_id.get(siae.id, "") if insee_code_by_id else ""
yes

2022-06-07 14:32 UTC, vperron commented on itou/api/data_inclusion_api/serializers.py
> +            structure_parente = Siae.objects.exclude(source=Siae.SOURCE_USER_CREATED).get(
:+1:

2022-06-16 08:30 UTC, vperron approved these changes

2022-06-16 08:37 UTC, vperron approved these changes
LGTM, avec squash des commits de valentin si possible. Je peux la merger moi meme pour ce faire.

2022-06-16 08:45 UTC, celine-m-s approved these changes
LGTM

2022-06-16 08:50 UTC, vperron commented
Yes, j'ai vu, comme bcp de mes PR huhu

2022-06-28 07:58 UTC, merged