Amélioration de la performance du cron Metabase quotidien.
betagouv/itou pull request #1339
Opened 2022-06-06 13:15 UTC by dejafait

### Quoi ?

Amélioration de la performance du cron Metabase quotidien :
- refactoring significatif autour de `is_from_ai_stock`.
- `populate_job_seekers` tombe de 120 minutes à 30 minutes en local dev.
- amélioration de la documentation autour du timeout infranchissable de 6 heures des github actions.

### Pourquoi ?

- depuis 2-3 semaines ce cron échoue chaque nuit car dépasse le timeout de 6 heures. En dépannant je le lancais chaque samedi depuis mon local dev (qui, ironiquement, ne prend que 4 heures, comme quoi le réseau n'est pas à blamer).

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

2022-06-08 14:34 UTC, vperron commented on itou/metabase/management/commands/_utils.py
> +AI_STOCK_JOB_SEEKER_PKS = set(_get_ai_stock_approvals().values_list("user_id", flat=True))
je ne suis jamais très fan de ce genre de propriétés calculées au "chargement du module Python" donc de l'app.

En gros ça veut dire que on faut deux requetes sur la table Approval au moment où on lance l'app Django, plutot qu'au moment o ùla tâche accède à ces clés. Je préfère de loin une petite fonction qui fait ça.

Et sinon pourquoi faire `set` quand tu peux essayer d'utiliser `distinct()` ? La DB sera plus efficace je pense.

2022-06-08 15:37 UTC, celine-m-s requested changes
Je rejoins l'avis de Victor : je ne suis pas bien convaincue par l'exécution de la fonction au chargement du module. Je comprends que le résultat est toujours le même mais ça prend de l'espace mémoire dans des environnements qui, sauf erreur de ma part, n'en ont pas besoin (la prod par exemple). Étant donné que le script tourne sur une instance dédiée, relancer le calcul chaque nuit me semble plus optimal. Qu'en penses-tu ?
Sinon : bravo ! Belle amélioration !!

2022-06-17 13:19 UTC, dejafait commented on itou/metabase/management/commands/_job_seekers.py
> +        "fn": lambda o: o.pk in AI_STOCK_JOB_SEEKER_PKS,
Mmm je viens de tester `o.id` vs `o.pk` sur un échantillon et je n'ai pas constaté d'amélioration. Donc je garde `o.pk` par harmonie avec le reste de la base de code.

2022-06-17 13:25 UTC, dejafait commented on itou/metabase/management/commands/_utils.py
> +AI_STOCK_JOB_SEEKER_PKS = set(_get_ai_stock_approvals().values_list("user_id", flat=True))
Ok pour le `distinct()` au lieu du `set`.

2022-06-17 14:18 UTC, dejafait commented on itou/metabase/management/commands/_utils.py
> +AI_STOCK_JOB_SEEKER_PKS = set(_get_ai_stock_approvals().values_list("user_id", flat=True))
Ok je vais déplacer ce chargement dans une fonction et sa sortie devra être cachée avec un décorateur `@lru_cache` pour pas que le calcul ne soit fait un million de fois.

2022-06-17 14:22 UTC, dejafait commented
Nouvelle revue svp 🙏 @vperron @celine-m-s 
- `distinct()` au lieu de `set()`
- utilisation d'une fonction à la sortie cachée pour être le plus possible en "lazy load"
- amélioration mineure de la perf du dry run en passant

2022-06-17 15:34 UTC, dejafait commented
Les deux scripts metabase (fluxIAE et itou) manquent cruellement de tests, c'est ma faute, pas taper. Je vais voir en équipe C2 si je peux me prioriser un peu de temps pour ça.

2022-06-17 15:39 UTC, merged