feat(api): ajout des données organisations à la vue d'api data.inclusion
betagouv/itou pull request #1413
Opened 2022-07-13 14:02 UTC by vmttn

### Quoi ?

Ajout des données organisations (`PrescriberOrganization`) au endpoint représentant les données au format data.inclusion.

### Pourquoi ?

dans la continuité des travaux entamés avec #1314

### Comment ?

* Un seul endpoint pour les données provenant des 2 tables `Siae` et `PrescriberOrganization`.
* Récupération de l'une ou de l'utre table via le query param `?type=siae` ou `?type=orga`

2022-07-19 15:42 UTC, celine-m-s requested changes

2022-07-19 15:42 UTC, celine-m-s commented on itou/api/data_inclusion_api/views.py
> +    SIAE = "siae"
Nous regroupons les enums dans un fichier `enums.py` dans chaque app. Est-ce que tu pourrais en créer un STP ?

2022-07-19 15:42 UTC, celine-m-s commented on itou/api/data_inclusion_api/views.py
> +            StructureTypeStr.SIAE: Siae.objects.active().order_by("created_at").select_related("convention"),
```suggestion
            StructureTypeStr.SIAE: Siae.objects.active().order_by("created_at", "pk").select_related("convention"),
```

2022-07-19 15:42 UTC, celine-m-s commented on itou/api/data_inclusion_api/views.py
> +            StructureTypeStr.ORGA: PrescriberOrganization.objects.all(),
Tiens, pourquoi ne pas appliquer le même tri que pour les SIAE ?

2022-07-19 15:42 UTC, celine-m-s commented on itou/api/data_inclusion_api/views.py
> +            StructureTypeStr.SIAE: Siae.objects.active().order_by("created_at").select_related("convention"),
cf https://github.com/betagouv/itou/pull/1423

2022-07-21 09:36 UTC, vmttn commented on itou/api/data_inclusion_api/views.py
> +            StructureTypeStr.ORGA: PrescriberOrganization.objects.all(),
J'attendais un retour sur le petit soucis de tri ;)

2022-07-25 13:57 UTC, celine-m-s approved these changes

2022-07-25 14:14 UTC, merged