Controle a posteriori : Correction de bugs remontés par les DDETS et SIAE
betagouv/itou pull request #1460
Opened 2022-08-17 09:39 UTC by vperron

### Quoi ?

Cf chaque commit.

### Pourquoi ?

Changements remontés par les utilisateurs.

### Comment ?

Cf chaque commit.

### Captures d'écran (optionnel)

#### Bandeau d'affichage des pièces:
1. Version que je n'aime pas trop
![Screenshot from 2022-08-16 13-04-08](https://user-images.githubusercontent.com/88618/185086674-1b1792bd-7df3-4026-afcd-817ba681cda9.png)
2. Version implémentée
![Screenshot from 2022-08-17 10-41-22](https://user-images.githubusercontent.com/88618/185086676-3c8f1efb-6969-46b7-951f-1015d16afb25.png)

#### Présence de la mention "Phase contradictoire"
1. Déjà présente sur les fiches SIAE
![Screenshot from 2022-08-17 10-42-04](https://user-images.githubusercontent.com/88618/185086679-064f4742-b46e-4040-8ced-2aa56892a042.png)
2. Ajoutée sur la page de candidature
![Screenshot from 2022-08-17 10-42-11](https://user-images.githubusercontent.com/88618/185086683-d8a3d23b-45db-4e09-833f-10a78811a039.png)

2022-08-17 12:05 UTC, vincentporte commented on itou/templates/siae_evaluations/includes/siae_infos.html
> +                {# NOTE(vperron): Why do we check reviewed_at here, instead of state == ADVERSARIAL_STATE ? #}
Deux raisons :
- state est calculée alors que reviewed_at est une valeur nulle ou non,
- surtout : le state de la SIAE en phase contradictoire (reviewed_at non nulle) n'est plus à ADVERSARIAL_STATE lors de la mise à jour et de la soumission des documents

2022-08-17 12:06 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            and self.evaluated_job_application.evaluated_siae.reviewed_at
ok :D

2022-08-17 12:10 UTC, vincentporte commented on itou/www/siae_evaluations_views/views.py
> +    )
optim interessante, qui disparaitra quand on accedera à la vue avec l'ID du EvaluatedSiae. 
En attendant, ça fait plus propre. GG.

2022-08-17 12:13 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            eval_job_app.state == evaluation_enums.EvaluatedJobApplicationsState.SUBMITTED
wow, c'est tellement plus propre que je me demande si un corner-case n'a pas sauté ici.
L'autre version, c'est que le codage en marche forcé fini par créer du code bizarre.

2022-08-17 12:21 UTC, vincentporte requested changes
Efficace, comme toujours. Bravo
Je mets "request changes" en attendant de discuter sur la carte notion

2022-08-17 12:21 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            .exclude(
je pensais à un exclude directement sur le `state` de `EvaluatedSiae`

```
EvaluatedSiae.objects.filter(evaluation_campaign=self, reviewed_at__isnull=True).exclude(state=EvaluatedSiaeState.SUBMITTED)```

pros : code plus "intuitif"
cons : le state de EvaluatedSiae est calculé à l'inverse du review_state de EvaluatedAdministrativeCriteria

2022-08-18 06:21 UTC, vperron commented on itou/siae_evaluations/models.py
> +            .exclude(
on ne peut pas faire ça ? le `state` de `EvaluatedSiae` est bien une propriété calculée non ? Auquel cas il n'est pas possible de demander à l'ORM de créer une requete SQL du type `column = 'value'` quand le colonne n'existe pas en DB.

2022-08-18 06:22 UTC, vperron commented on itou/siae_evaluations/models.py
> +            eval_job_app.state == evaluation_enums.EvaluatedJobApplicationsState.SUBMITTED
ben... a force de voir comment cassaient les tests et comment les réparer et regarder les différents use cases droit dans les yeux, il semblerait que en fait... non, ça suffit avec ça. 
Attention toutefois: l'endroit où est réalisé ce `if` dans la méthode `state` est extrêmement important. 
Ca casse si je le mets plus haut ou plus bas dans la méthode, et à juste titre.

2022-08-18 06:53 UTC, vincentporte commented on itou/siae_evaluations/models.py
> +            .exclude(
Bien vu, une des limites des états calculés qui a pimenté le projet. Sans regret pour autant :+1:

2022-08-18 06:54 UTC, vincentporte approved these changes
:100:  merci Victor

2022-08-18 09:24 UTC, merged