itou.users: Use the real accept date for `.last_accepted_job_application()`
betagouv/itou pull request #1536
Opened 2022-09-15 10:07 UTC by rsebille

### Quoi ?

Calcul de la date d'acceptation d'une candidature :
- Pour une candidature classique : on se réfère au log des transitions
- Pour une candidature créée lors d’un import d’agrément : on se réfère à la date de création de la candidature.

### Pourquoi ?

Permettre au dernier employeur qui a embauché un candidat d’avoir la main pour prolonger ou suspendre

### Comment ?

En ne se basant plus sur la date de contrat mais sur la date d’acceptation de la candidature.

2022-09-20 08:38 UTC, ikarius commented on itou/job_applications/models.py
> +            .values("timestamp")[0:1],
Pinaillage: pourquoi [0:1] au lieu de [:1] ?

2022-09-20 08:45 UTC, ikarius commented on itou/job_applications/models.py
> +            output_field=DateTimeField(),
Pinaillage: c'est pour être explicite, ou on en a vraiment besoin ?

2022-09-20 08:47 UTC, ikarius commented on itou/job_applications/models.py
> +
Nice le découplage en agréments et PASS IAE

2022-09-20 08:59 UTC, ikarius commented on itou/job_applications/models.py
> +                default=None,
Tous les cas sont couverts,  non ?

2022-09-20 09:20 UTC, ikarius commented on itou/job_applications/tests/tests.py
> +        job_application = JobApplicationSentBySiaeFactory(created_from_pe_approval=False)
Plutôt que la `default_value`, c'est que la candidature n'a pas été acceptée, non ?

2022-09-20 09:27 UTC, ikarius commented on itou/users/tests/test_models.py
> +            created_at=now,
Il manquerais pas un `job_seeker=user` là ?

2022-09-20 09:28 UTC, ikarius commented on itou/users/tests/test_models.py
> +        self.assertNotEqual(job_application_2, user.last_accepted_job_application)
... 
histoire de tester sur le même utilisateur et pas deux demandeurs différents

2022-09-20 09:36 UTC, ikarius requested changes
Vraiment très propre 👏🏻 
J'ai un toutefois doute sur deux test à cause des demandeurs des candidatures de tests (et quelques pinaillages :))

2022-09-22 13:47 UTC, rsebille commented on itou/job_applications/models.py
> +            .values("timestamp")[0:1],
Ça dépend de comment je me suis levé le matin :grin:, même si en général j'aime bien mettre la valeur des deux cotés pour éviter la soupe de caractères spéciaux ^^.

2022-09-22 13:47 UTC, rsebille commented on itou/job_applications/models.py
> +                default=None,
Oui, et de toute manière : 
> If a `default` argument isn’t provided, None is used.

2022-09-22 13:47 UTC, rsebille commented on itou/job_applications/models.py
> +            output_field=DateTimeField(),
Je testerais sans, mais de mémoire fallait le mettre sinon l'ORM était pas d'accord à cause de problème de type mais c'est pas pour le même bout de code.

2022-09-22 13:47 UTC, rsebille commented on itou/job_applications/tests/tests.py
> +        job_application = JobApplicationSentBySiaeFactory(created_from_pe_approval=False)
Dans les faits, oui.
Vu que le but du test c'est de tester le cas où ce n'est aucun de ceux supportés je reste générique sur le nommage plutôt que de limiter ça à "non acceptée".

2022-09-22 13:47 UTC, rsebille commented on itou/users/tests/test_models.py
> +            created_at=now,
Bah si...

2022-09-22 13:47 UTC, rsebille commented on itou/users/tests/test_models.py
> -            job_seeker=user,
_The original sin_ ;).

2022-09-22 14:04 UTC, ikarius commented on itou/job_applications/models.py
> +            .values("timestamp")[0:1],
Ça se tient :)

2022-09-22 14:06 UTC, ikarius commented on itou/job_applications/models.py
> +            output_field=DateTimeField(),
Apparemment, ça marche sans, mais être explicite ne me dérange pas !

2022-09-27 08:02 UTC, merged