Correction de l'ui des card job_description
betagouv/itou pull request #1613
Opened 2022-10-14 14:42 UTC by hellodeloo

### Quoi ?

Correction de l'ui des card job_description.
En passant, petit fix sur une erreur de DOM dans le breadcrumb et ajout d'un ALLOWED_HOSTS dans le dev.py (apparemment nécessaire dans mon installation locale sous docker)

### Pourquoi ?

Pour répondre a cette demande https://www.notion.so/Fiche-de-poste-C1-658699a57e5848caa1f2f75a5ac1f02a

2022-10-18 15:11 UTC, celine-m-s commented on itou/templates/siaes/job_description_card.html
> +                            <h2 class="h2">Consulter le(s) recrutement(s) en cours dans cette structure</h2>
Suggestion d'amélioration (à tester).

```
                            <h2 class="h2">Consulter le{{ others_active_jobs|pluralize }} recrutement{{ others_active_jobs|pluralize }} en cours dans cette structure</h2>
```

2022-10-21 07:32 UTC, hellodeloo commented on itou/templates/siaes/job_description_card.html
> +                            <h2 class="h2">Consulter le(s) recrutement(s) en cours dans cette structure</h2>
Yes, je le note et je ferais ça apres le merge de la version 5.0.2 du thème afin de pouvoir prendre en compte le retour d'Antoine https://www.notion.so/Fiche-de-poste-C1-658699a57e5848caa1f2f75a5ac1f02a

2022-10-24 12:56 UTC, hellodeloo commented on itou/templates/siaes/job_description_card.html
> +                            <h2 class="h2">Consulter le(s) recrutement(s) en cours dans cette structure</h2>
@celine-m-s Ça semble fonctionner en local, mais je ne peux pas terser en recette jetable, car le `TestPaginator` n'apprécie pas mes modifs et je ne pige pas pourquoi ?

2022-10-27 13:03 UTC, celine-m-s commented
Le test échoue en local chez moi aussi. Je creuse.

2022-10-27 13:15 UTC, celine-m-s requested changes
Je ne comprends pas bien pourquoi on modifie le nombre de résultats par page.

2022-10-27 13:15 UTC, celine-m-s commented on itou/utils/pagination.py
> +def pager(queryset, page, items_per_page=10, pages_num=9):
Mais c'est normal que le test casse, tu as modifié le nombre de résultats par page ! Pourquoi ne veux-tu que 9 résultats et non 10 ?

2022-10-28 07:00 UTC, hellodeloo commented on itou/utils/pagination.py
> +def pager(queryset, page, items_per_page=10, pages_num=9):
Arf c'est ça. Parcqu'a vec 10 resultat la pagination passe sur 2 lignes ;)

2022-11-07 10:41 UTC, hellodeloo commented on itou/utils/pagination.py
> +def pager(queryset, page, items_per_page=10, pages_num=9):
@celine-m-s Ok, je suis repassé à 10, tant pis pour l'intégration cassée. Une autre fois, un autre ticket

2022-11-07 10:55 UTC, celine-m-s approved these changes

2022-11-07 10:59 UTC, merged