Ajout d'une application Django 'geo'
betagouv/itou pull request #1637
Opened 2022-10-21 17:01 UTC by ikarius

### Quoi ?

- ajout d'une nouvelle application `geo`,
- ajout d'une management command de MaJ et d'import / export / update des données de géolocalisation des demandeurs d'emploi,
- MaJ de l'admin Django

### Pourquoi ?

A court-terme, ajouter le modèle des QPV pour savoir si un demandeur d'emploi réside dans une des ces zones.
A moyen-long-terme, avoir nos propres modèles GIS si tant est qu'ils soient simples à maintenir. 

Pour info, le modèle de QPV n'a pas bougé depuis 2015.
On évite ainsi des appels à des API externes.

### Comment ?
- ajout d'un modèle `geo.QPV` contenant la codification et les contours des 1514 QPVs définis actuellement (source officielle: https://sig.ville.gouv.fr/atlas/QP/).
- ajout d'informations sur l'appartenance à un QPV dans l'admin `User`

La MaJ des données sur l'environnement de production se fera en deux étapes:
- sur un poste de dev, avec une base de prod récente, on procède à la géolocalisation des demandeurs d'emploi
- on génère un fichier d'export de ces données
- que l'on importe sur la production en dehors des horaires de travail (soirée ou nuit)

### Divers
La MaJ et l'invalidation des données de géolocalisation "au fil de l'eau" pour les demandeurs d'emploi n'est pas encore définie.
On peut imaginer l'invalidation après une saisie dans le formulaires des informations de l'utilisateur.
A confirmer et légèrement hors-scope de cette PR : PR à suivre donc...

### Captures d'écran

#### Admin :  adresse en QPV pour un demandeur d'emploi

![image](https://user-images.githubusercontent.com/147232/197983916-898b9967-7de0-4a4d-a1ca-26ad98a36c25.png)

#### Admin : Affichage du détails du QPV

![image](https://user-images.githubusercontent.com/147232/197984276-09c3808c-6a11-40cc-b928-e723282bae03.png)

#### Bonus

09.11.2022 En attendant, ajout du modèle, factories, test et données pour la gestion des ZRR (a minima sans demande métier précise encore ...)

2022-11-10 08:52 UTC, tonial approved these changes
Ça me semble top.
Il y a juste l'histoire du commentaire pour éviter un soucis de perfs futur

2022-11-10 08:52 UTC, tonial commented on itou/users/admin.py
> +    def address_in_qpv(self, obj):
Tant qu'on ne le met pas dans la liste, c'est bon ^^
Peut être ajouter un commentaire en disant de ne surtout pas l'ajouter dans la liste ?

2022-11-10 09:02 UTC, ikarius commented on itou/users/admin.py
> +    def address_in_qpv(self, obj):
Oui, recalculer sur la liste / display sur tous les utilisateurs ça pourrait être ... pénible.
Le commentaire est une excellente idée, je prends ! Merci !

2022-11-15 09:34 UTC, vperron requested changes
Je n'ai pas  tout lu mais pour moi ce n'est pas encore au point, en particulier sur les tests et la structure de la management command. Il n'y en a pas et il y a un certain nombre de problèmes que je trouve bloquants.

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                self.stdout.write(f"! Unknown command '{action}', exiting.")
on n'a pas la possibilité de mettre un choix sur l'action dans les arguments et laisser argparse gérer ça ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/models.py
> +    LAST_UPDATED = "2021"
pourtant on est fin 2022. On peut mettre une explication de ce qu'il faut mettre ici pour que les prochains codeurs savent quoi écrire ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/models.py
> +        return self.filter(status=enums.ZRRStatus.PARTIALLY_IN_ZRR)
hmm, ces méthodes sont un petit peu triviales je trouve. Est-ce vraiment utile de faire ce queryset spécialisé ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/models.py
> +    communes_info = models.CharField(verbose_name="Nom des communes du QPV", max_length=254)
subitement un champ en français, les autres étant en anglais ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                updated += nb_updated
je ne vois aucun `if wet_run` ici. Cette commande va écrire en DB tout le temps.

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            for idx in tqdm(range(0, count, batch_size)):
je propose une motion pour cesser d'utiliser tqdm pour toujours. Les scripts ne sont pas utilisés pour etre suivis par nos yeux, mais pour etre lancés sur des machines avec des logs exploitables a posteriori.
Ca allonge le code sans bonne raison a mon avis.

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return self._from_csv(r.content)
pas super fan de ça. Je te propose de prendre `api_lookup`, `_to_csv` et `_from_csv` et de mettre ça dans un `api-adresse.py` exterieur qui pourra:
- etre testé indépendamment, notamment avec des mocks d'API
- ne pas dépendre de la commande elle-meme
- etre réutilisable ailleurs

Les URLs devraient etre des secrets venant des settings d'ailleurs, et on a deja l'URL de base de l'API adresse quelque part (notamment pour les sondes)

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +        )
les chunk size et score de base : je ne suis pas certain qu'on ait besoin d'en faire des arguments, ils ne changeront probablement quasiment jamais et un patch c'est un commit + un deploiement immédiat chez nous. Autant simplifier non ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +DEFAULT_FILENAME = "job_seeker_geocoding_data.csv"
on a des shared folders, des dossiers import/ et export/ configurables. On ne veut pas les utiliser pour que le script y écrive ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            "postcode": "post_code",
marrant. C'est un mapping ? Je ne connais pas cette API.

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return []
je me dis que du coup _to_csv n'est pas super utile car on re-checke la condition de sortie de cette dernière juste ici.

On ne peut pas juste éviter d'appeler _api_lookup si wet_run est faux ou si on a pas d'adresses à lui fournir ? Ca serait  plus clean. D'une manière générale d'ailleurs api_lookup n'a pas a savoir que on est dans le contexte d'une commande Django ou à se faire passer un argument comme wet_run je pense.

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return []
je n'aime pas ce genre d'ignore explicite d'erreur. Si ça crashe on veut le savoir dans sentry, non ? Quitte à remonter un warning dans Sentry et continuer les opérations ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                            except Exception:
Est-on vraiment certains que l'on veut un except Exception ?

2022-11-15 09:34 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +        return updated, errors
je ne suis jamais fan de ce genre de "on remonte un tas d'erreurs sans vraiment savoir lesquelles". Habituons nous à emettre un log d'erreur précis par erreur, ça sera beaucoup plus facile à inspecter par la suite.

2022-11-15 09:56 UTC, ikarius commented on itou/geo/models.py
> +    LAST_UPDATED = "2021"
C'est la source de données qui date de 2021. Oui un commentaire pour clarifier

2022-11-15 10:06 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return []
Cette management command va tourner une seule fois, est-ce qu'on veut les erreurs dans sentry (parce que sur 600k vérifications, il ya beaucoup d'erreurs de géoloc)

2022-11-15 10:33 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                            except Exception:
Mmm. On peut être plus précis. Je pense que ça ne peut jeter qu'une `ValueError` non ?

2022-11-15 11:30 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                self.stdout.write(f"! Unknown command '{action}', exiting.")
Euh, j'ai pas compris

2022-11-15 13:13 UTC, vperron commented on itou/geo/models.py
> +    LAST_UPDATED = "2021"
A quoi sert ce LAST_UPDATED ? Je ne vois pas son usage dans le code. Si il n'est pas utilisé, on peut le laisser en commentaire ?

2022-11-15 13:15 UTC, vperron commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                self.stdout.write(f"! Unknown command '{action}', exiting.")
https://docs.python.org/3/library/argparse.html#choices

Je pense que tu n'as pas besoin de traiter manuellement le cas où `action` vaudrait autre chose que tes 3 choix. Par ailleurs le mettre dans `choices` va permettre à ta commande d'afficher automatiquement la documentation associée (les 3 choix possibles)

2022-11-15 15:13 UTC, ikarius commented on itou/geo/models.py
> +        return self.filter(status=enums.ZRRStatus.PARTIALLY_IN_ZRR)
C'est plus par convention. Et le queryset risque de se muscler par la suite. Les ZRR ne sont pas encore exploités

2022-11-15 15:17 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +        )
Je m'en suis servi lors de mes différentes expérimentations, mais effectivement, les valeurs par défauts n'ont plus besoin de changer, on peu virer ces paramètres de la commande.

2022-11-15 15:48 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return self._from_csv(r.content)
Je prends le point sur la constante. Par contre sur le fait d'extérioriser, pas sur de la nécessité si on déplace le tout vers les scripts "one-shot"

2022-11-15 15:57 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +                self.stdout.write(f"! Unknown command '{action}', exiting.")
TIL `argparse/choices`. Merci !

2022-11-15 16:44 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            "postcode": "post_code",
Oui, c'est cette API : https://adresse.data.gouv.fr/api-doc/adresse#csv-search
Super utile pour envoyer des lots à géolocaliser

2022-11-15 16:50 UTC, ikarius commented on itou/geo/management/commands/geolocate_jobseeker_addresses.py
> +            return []
Oui, en regardant de plus loin, autant le zapper direct. Merci !

2022-11-15 17:26 UTC, ikarius commented on itou/geo/models.py
> +    communes_info = models.CharField(verbose_name="Nom des communes du QPV", max_length=254)
`commune` est peu courant mais possible en anglais. Et déjà utilisé dans l'app `asp` (pas une référence mais bon). 
Si trop choquant, je renomme

2022-11-21 15:03 UTC, merged