Suppression de l’encodage de l’id de la SIAE durant l’inscription
betagouv/itou pull request #1700
Opened 2022-11-14 12:07 UTC by francoisfreitag

### Quoi ?

Suppression de l’encodage de l’id de la SIAE durant l’inscription

### Pourquoi ?

L’encodage n’a pas raison d’être et rend la validation de la clé primaire de la SIAE plus difficile. Autant se simplifier la vie.

### Comment ?

Après une période de transition, la vue n’acceptera plus qu’un entier pour l’argument `siae_id`.

### Autre

- https://sentry.io/organizations/itou/issues/3646581964/
- https://itou-inclusion.slack.com/archives/C0412CTV63D/p1668424659933449

2022-11-15 08:39 UTC, tonial commented
Le principe de ce code est d'empêcher quelqu'un de "facilement" rejoindre une SIAE.
Je ne pense pas que ce soit vraiment nécessaire, mais ça reste une mesure de sécurité.

Je suis donc plutôt en phase pour dire que c'est pas très utile à garder :)

2022-11-17 09:20 UTC, dejafait requested changes
Je pense qu'il y a un bug à corriger dans le fallback. Sinon nickel LGTM et kudos pour avoir pris la peine de faire une transition douce avec fallback. 👍

2022-11-17 09:20 UTC, dejafait commented on itou/www/signup/views.py
> +                int(siae_id)
Oulà il y a un bug là je pense. `siae_id` est une `str` et ne devient jamais au final un `int`. Je pense qu'ici tu veux plutôt `siae_id = int(siae_id)` non ?

2022-11-17 09:20 UTC, dejafait commented on itou/templates/signup/siae_signup.html
> -{% endblock %}
Effectivement `siae_signup` introuvable dans le code donc pas utilisé. Bien vu !

2022-11-17 09:20 UTC, dejafait commented on itou/www/signup/views.py
> +        self.siae = None if siae_id is None else Siae.objects.active().filter(pk=siae_id).get()
Ici `filter(pk=siae_id)` va casser si `siae_id` est un `str` non ?

2022-11-17 10:06 UTC, francoisfreitag commented on itou/www/signup/views.py
> +                int(siae_id)
Ce n’est pas un bug en l’état. Le _cast_ identifie si la valeur décodée est bien interprétable comme un `int`. Le champ Django (`id`, un `AutoField`) prépare la valeur pour la base de données et _cast_ la `str` en `int`, au moment de la requête SQL c’est bien un `int` qui est envoyé.
Cela dit, c’est un bug en puissance si quelqu’un réutilise la valeur `siae_id` en s’attendant (raisonnablement) à ce que ce soit un `int`. :+1:

2022-11-18 09:37 UTC, dejafait commented on itou/www/signup/views.py
> +                int(siae_id)
Ah ok TIL merci !

2022-11-18 09:38 UTC, dejafait approved these changes
LGTM

2022-11-21 16:25 UTC, merged