Squash d'une partie des migrations
betagouv/itou pull request #1916
Opened 2023-01-02 08:54 UTC by tonial

Il reste les plus grosses apps (à venir soit dans cette PR soit dans une suivante)

2023-01-02 10:39 UTC, celine-m-s approved these changes

2023-01-02 10:41 UTC, celine-m-s requested changes
Tous les tests sont en erreur à cause d'un index impossible à créer. Rapidement, j'ai l'impression qu'un truc nécessaire à Postgis est passé à la trappe.

2023-01-02 12:23 UTC, tonial commented
En effet, il fallait que la migration asp pointe sur users.0001_initial ou sont installées les extensions psql

2023-01-02 19:34 UTC, vperron commented
Pour les SIAES, vu que j'ai en préparation la PR des offres PEC qui ajoutent pas mal de migrations je pense que ce serait pas mal d'attendre que je les merge :)

2023-01-02 19:41 UTC, tonial commented
Pour info : GitGuardian a détecté des faux positifs en confondant des noms de migrations avec des secrets.

2023-01-02 20:13 UTC, tonial commented
Je suis tombé sur un truc étrange sur l'app approvals, voir l'avant dernier commit "approvals: Remove unnecessary index"
cc @celine-m-s sans doute vu que ça date de presque un an.

2023-01-02 22:50 UTC, vperron commented
En effet il y a eu un switch de modèles à un moment: un dev (Clément) a hot-swappé une table PoleEmploiApprovals et MergedPoleEmploiApprovals après avoir fait le remplissage de cette dernière a partir d'un certain nombre de fichiers fournis par Pole Emploi.

CF cette PR où je documente un peu le process : https://github.com/betagouv/itou/pull/1236/commits

Cette carte Notion où Clément décrit son opération de swap en production:
https://www.notion.so/Consolider-le-fichier-des-agr-ments-PE-f0cbc8ebc81240ed80295dc807feb7dc?d=0ce51b7108984c4da7578fea62054ea2

En clair, les `merged_pe_approvals` sont les agréments PE "originaux" que l'on n'utilise pas car non "mergés" (post-processés, disons) mais que l'on garde dans un coin si on en a besoin un jour (encore un an ou deux si je me rappelle bien, ils ont une certaine durée de vie) ; c'est misleading mais c'est le cas.

La table `approvals_poleemploiapprovals` contient bien les Agréments utilisés en prod "pour de vrai". Mon idée est que tu peux dropper ce qui concerne les "merged".

Cf le ticket Notion, voilà ce que Clément avait fait pour inverser les tables:
```
ALTER TABLE approvals_poleemploiapproval RENAME TO approvals_poleemploiapproval_tmp;
ALTER TABLE merged_approvals_poleemploiapproval RENAME TO approvals_poleemploiapproval;
ALTER TABLE approvals_poleemploiapproval_tmp RENAME TO merged_approvals_poleemploiapproval;
REINDEX INDEX merged_approvals_poleemploiapproval_pkey;
REINDEX INDEX merged_approvals_poleemploiapproval_end_at_700e9623;
REINDEX INDEX merged_approvals_poleemploiapproval_number_ec12fef8_like;
REINDEX INDEX merged_approvals_poleemploiapproval_number_key;
REINDEX INDEX merged_approvals_poleemploiapproval_start_at_0767f0da;
REINDEX INDEX merged_pe_id_and_birthdate_idx;
REINDEX INDEX approvals_poleemploiapproval_pkey;
REINDEX INDEX approvals_poleemploiapproval_end_at_dede51c0;
REINDEX INDEX approvals_poleemploiapproval_number_70b4edca_like;
REINDEX INDEX approvals_poleemploiapproval_number_key;
REINDEX INDEX approvals_poleemploiapproval_number_like_idx;
REINDEX INDEX approvals_poleemploiapproval_start_at_bfaf978e;
REINDEX INDEX pe_id_and_birthdate_idx;
alter table approvals_poleemploiapproval add merged boolean;
```

2023-01-03 07:40 UTC, tonial commented
Ok, Du coup les indexs et sequences ont tous des noms inversés, ce qui risque de poser des soucis pas cool du tout le jour où l'on supprimera une des tables.

Je propose donc de passer les commandes suivantes afin de corriger le tintouin :
```
DROP INDEX approvals_poleemploiapproval_number_like_idx;

ALTER INDEX pe_id_and_birthdate_idx RENAME TO merged_pe_id_and_birthdate_idx_tmp;
ALTER INDEX merged_pe_id_and_birthdate_idx RENAME TO pe_id_and_birthdate_idx;
ALTER INDEX merged_pe_id_and_birthdate_idx_tmp RENAME TO merged_pe_id_and_birthdate_idx;

ALTER INDEX approvals_poleemploiapproval_pkey RENAME TO merged_approvals_poleemploiapproval_pkey_tmp;
ALTER INDEX merged_approvals_poleemploiapproval_pkey RENAME TO approvals_poleemploiapproval_pkey;
ALTER INDEX merged_approvals_poleemploiapproval_pkey_tmp RENAME TO merged_approvals_poleemploiapproval_pkey;

ALTER INDEX approvals_poleemploiapproval_number_key RENAME TO merged_approvals_poleemploiapproval_number_key_tmp;
ALTER INDEX merged_approvals_poleemploiapproval_number_key RENAME TO approvals_poleemploiapproval_number_key;
ALTER INDEX merged_approvals_poleemploiapproval_number_key_tmp RENAME TO merged_approvals_poleemploiapproval_number_key;

ALTER INDEX approvals_poleemploiapproval_start_at_bfaf978e RENAME TO merged_approvals_poleemploiapproval_start_at_0767f0da_tmp;
ALTER INDEX merged_approvals_poleemploiapproval_start_at_0767f0da RENAME TO approvals_poleemploiapproval_start_at_bfaf978e;
ALTER INDEX merged_approvals_poleemploiapproval_start_at_0767f0da_tmp RENAME TO merged_approvals_poleemploiapproval_start_at_0767f0da;

ALTER INDEX approvals_poleemploiapproval_end_at_dede51c0 RENAME TO merged_approvals_poleemploiapproval_end_at_700e9623_tmp;
ALTER INDEX merged_approvals_poleemploiapproval_end_at_700e9623 RENAME TO approvals_poleemploiapproval_end_at_dede51c0;
ALTER INDEX merged_approvals_poleemploiapproval_end_at_700e9623_tmp RENAME TO merged_approvals_poleemploiapproval_end_at_700e9623;

ALTER INDEX approvals_poleemploiapproval_number_70b4edca_like RENAME TO merged_approvals_poleemploiapproval_number_ec12fef8_like_tmp;
ALTER INDEX merged_approvals_poleemploiapproval_number_ec12fef8_like RENAME TO approvals_poleemploiapproval_number_70b4edca_like;
ALTER INDEX merged_approvals_poleemploiapproval_number_ec12fef8_like_tmp RENAME TO merged_approvals_poleemploiapproval_number_ec12fef8_like;

ALTER SEQUENCE approvals_poleemploiapproval_id_seq RENAME TO merged_approvals_poleemploiapproval_id_seq_tmp;
ALTER SEQUENCE merged_approvals_poleemploiapproval_id_seq RENAME TO approvals_poleemploiapproval_id_seq;
ALTER SEQUENCE merged_approvals_poleemploiapproval_id_seq_tmp RENAME TO merged_approvals_poleemploiapproval_id_seq;
```

Soit je le mets dans un RUN SQL d'une nouvelle migration, soit je le passe à côté et je l'indique dans la carte notion.
Un avis ?

2023-01-03 10:35 UTC, xavfernandez commented on itou/approvals/migrations/0002_clean_pe_aprrovals_indices_name.py
> +            eldable=True,
elidable :eyes:

2023-01-03 10:48 UTC, tonial commented on itou/approvals/migrations/0002_clean_pe_aprrovals_indices_name.py
> +            eldable=True,
oups

2023-01-03 11:20 UTC, celine-m-s approved these changes

2023-01-03 13:04 UTC, merged