stats: Ajout d'un tableau de bord DIHAL
betagouv/itou pull request #1936
Opened 2023-01-04 20:24 UTC by vperron

**Carte Notion : https://www.notion.so/TB-DIHAL-d-ployer-le-TB-81ff15c839a141ef9cf4b30243c2454f**

### Pourquoi ?

Il s'agit dune demande de la DIHAL.

### Comment (optionnel)
Comme le reste. La gestion des permissions d'accès aux Stats me semble chargée, mais je ne vois pas de moyen simple, rapide et explicite de faire mieux, il y a pour l'instant un peu trop d'exceptions partout. Ce n'est pas très joli mais à part ça on n'a pas beaucoup de problèmes qui en découlent.

Deux choses cependant:
- il y a zéro tests sur les accès, il faudrait essayer d'en ajouter (comme ici) à chaque modification.
- a minima les `can_view_stats` sur User et l'injection de chaque droit dans le contexte devrait être plus "automatique": un systeme par tags (`custom_permissions = [("read", "stats", {"cd89", "cd56", "dgefp"}), ...]`) permettrait cela mais rendrait plus complexe son exploitation (template tags custom, etc)

2023-01-05 14:22 UTC, dejafait requested changes
Je suis très content que tu aies l'occasion de plonger une première fois dans ces cablages d'accès des stats acteur par acteur et offrir une seconde opinion. En plus de mes remarques dans le code, quelques autres ici en dehors du code :
- J'ai jeté un oeil à la review app, le TB C1 est OK mais j'ai une 500 quand je tente d'ouvrir le TB DIHAL. En même temps c'est complètement logique car les recettes jetables (tout comme démo et staging) n'ont jamais été cablés avec Metabase (on a qu'un Metabase de prod, pas de démo car pas de solution simple pour maintenir une démo Metabase) donc ce n'est pas choquant. Ca aurait même été flippant si ça avait marché (car j'aurai potentiellement vu des données confidentielles Metabase de prod haha). Bref historiquement je n'utilise pour info pas vraiment les review apps pour le C2, je me contente de quelques screenshots de mon local dev pour faire confirmer les wordings etc. Au plaisir d'en reparler.
- Pour ta remarque "il y a zéro tests sur les accès" peux-tu stp jeter un oeil aux tests sur les `can_view_stats*` dans `users/tests/test_models.py` et me dire ce que tu en penses ?

2023-01-05 14:22 UTC, dejafait commented on itou/www/dashboard/tests.py
> +        self.assertContains(response, "Voir les données IAE France entière")
Ok pourquoi pas. Pour info perso j'ai l'habitude de tester unitairement toutes les méthodes `user.can_view_stats*` dans `users/tests/test_models.py`. Peux-tu y jeter un oeil stp et me dire ce que tu en penses ?

2023-01-05 14:22 UTC, dejafait commented on itou/www/stats/views.py
> +        "page_title": "Données des régions",
FIXME Wording à confirmer. cf https://itou-inclusion.slack.com/archives/CT7986ULC/p1672926405219189?thread_ts=1672826254.909129&cid=CT7986ULC

2023-01-05 14:22 UTC, dejafait commented on itou/www/stats/views.py
> +    params = get_params_for_whole_country()
❌ 🔪 
Ici tu peux complètement oublier les `params` car contrairement au TB de la DGEFP (qui a des filtres verrouillés compliqués pour les sous-vues région/département des DREETS/DDETS) ici le TB DIHAL est trivial et n'a pas ces filtres verrouillés.

2023-01-05 18:06 UTC, vperron commented on itou/institutions/migrations/0001_initial.py
> +                            ("DIHAL", "Délégation interministérielle à l'hébergement et à l'accès au logement"),
Justement c'est tout l'objectif.
Les `choices` d'un champ n'ont aucun sens en SQL, ce ne sont donc pas de vraies "migrations". Juste Django cherche à toujours connaître ce qui est attendu par le modèle et ce que lui il a noté en interne.
En éditant la migration initiale (et la seule, on vient de squasher) justement, j'évite que Django ne veuille générer une nouvelle migration (un `AlterField`) pour en réalité aucune bonne raison, les choices ne seront pas enregistrés dans la base de données.

2023-01-05 18:34 UTC, vperron commented on itou/templates/dashboard/includes/stats.html
> +                        <a href="{% url 'stats:stats_dihal_iae' %}">Voir les données IAE France entière</a>
Vu, merci !

2023-01-05 18:35 UTC, vperron commented on itou/utils/apis/metabase.py
> +    "stats_dihal_iae": {
Vu, merci !

2023-01-05 18:41 UTC, vperron commented on itou/www/stats/views.py
> +    params = get_params_for_whole_country()
Done !

2023-01-05 18:41 UTC, vperron commented
Pris en compte toutes tes remarques et essayé de répondre précisément aux questions ouvertes !

Tu as raison, il ne serait pas raisonnable de donner accès à des TB privés sur les review apps. J'ai donc supprimé la RA en question. Je vais revérifier en local maintenant :)

2023-01-05 19:11 UTC, vperron commented on itou/institutions/migrations/0001_initial.py
> +                            ("DIHAL", "Délégation interministérielle à l'hébergement et à l'accès au logement"),
C'est ce qui fait d'ailleurs que le `check_migrations` de la CI ne casse pas.

2023-01-05 19:11 UTC, merged

2023-01-06 09:23 UTC, dejafait commented on itou/institutions/migrations/0001_initial.py
> +                            ("DIHAL", "Délégation interministérielle à l'hébergement et à l'accès au logement"),
TIL, merci !