autocomplete: Improve city searches (order, accuracy, zip codes)
betagouv/itou pull request #2051
Opened 2023-01-27 12:41 UTC by vperron

The search suffered from many issues.

It could return entries that had nothing to see with the query. The order was seemingly random. The number of results was frustrating when looking for a city that exists in many different departments.

Also there were issues related to the case and accent matching.

We could not lookup by post code either.

Address all of that.

**Carte Notion : https://www.notion.so/Am-liorer-la-recherche-de-communes-cf94f8db05c34730aa9ec71e0baa692c**

### Pourquoi ?
CF le ticket, la recherche est hasardeuse au mieux.

### Comment (optionnel)
Cesser d'utiliser des trigrammes, avoir un tri plus malin.

2023-01-27 13:32 UTC, tonial approved these changes
Super !
Le tri par département n'est pas testé, mais je pense pas que ce soit super utile à faire :D

2023-01-27 13:41 UTC, vperron commented
Ui, il faudrait que j'inclue des exemple pipeau pour ça.... Je vais le faire.

2023-01-31 10:08 UTC, tonial requested changes

2023-01-31 10:08 UTC, tonial commented on itou/www/autocomplete/views.py
> +                key=lambda c: (unidecode(c.name.lower()).index(term), len(c.name), c.name, c.department),
attention, si il faut aussi faire unidecode(term.lower())

2023-01-31 10:11 UTC, tonial commented
Et il faudrait faire la même chose sur communes_autocomplete : j'ai un ticket client à ce sujet car il n'arrive pas à trouver Saint-Pierre (974).

2023-01-31 10:19 UTC, tonial commented on itou/www/autocomplete/views.py
> +                key=lambda c: (unidecode(c.name.lower()).index(term), len(c.name), c.name, c.department),
Ah, non c'est fait juste au dessus., c'est bon

2023-01-31 10:19 UTC, tonial approved these changes

2023-01-31 11:32 UTC, vperron commented
Atttnion : je dis ça pour les communes mais sur mon ticket Notion il y a deux tickets retour pour des améliorations de la recherche par rapport à ce qui est fait ici.

2023-02-03 15:09 UTC, merged