Ajout d'une page pour créer / accéder à son token d'API
betagouv/itou pull request #2089
Opened 2023-02-03 14:47 UTC by tonial

Carte Notion : https://www.notion.so/plateforme-inclusion/Acc-s-l-API-avec-un-compte-Inclusion-Connect-7f56844b0f624e06b746fa4030f3937c

### Pourquoi ?

Une fois passé à inclusion connect, il est impossible d'agir sur son mot de passe pour le changer et donc accéder à l'api de génération de token

### Comment (optionnel)

Il faudrait éventuellement permettre d'en générer un nouveau ?

### Captures d'écran (optionnel)

![image](https://user-images.githubusercontent.com/7632730/216632122-844c4d31-be7a-4557-bae6-8c28bdae1df2.png)
![image](https://user-images.githubusercontent.com/7632730/216632158-7d7c3238-532e-47a3-b26c-40e8f44df2b2.png)

2023-03-28 13:27 UTC, francoisfreitag requested changes
Je ne vois rien pour révoquer un token, ni le régénérer ? C’est demandé dans la carte action et me semble également être une bonne pratique de sécurité.

2023-03-28 13:27 UTC, francoisfreitag commented on itou/templates/dashboard/api_token.html
> +{% block title %}Mes notifications{{ block.super }}{% endblock %}
Mes notifications ?
Il manque l’espace avant le tiret.
```suggestion
{% block title %}Mon token d’API {{ block.super }}{% endblock %}
```

2023-03-28 13:27 UTC, francoisfreitag commented on itou/templates/dashboard/api_token.html
> +                                    <button type="submit" class="btn btn-primary">Créer un token d'API</button>
C’est le comportement par défaut.
```suggestion
                                    <button class="btn btn-primary">Créer un token d'API</button>
```

2023-03-28 13:27 UTC, francoisfreitag commented on itou/templates/dashboard/api_token.html
> +                        <div class="form-group mb-0 col-12 col-lg order-2">
C’est normal d’avoir le bouton avant en mode mobile ? J’ai l’impression qu’on pourrait tout aussi bien laisser le flux des éléments par défaut (et donc avoir le bouton copier sous le texte)

2023-03-28 13:27 UTC, francoisfreitag commented on itou/templates/dashboard/api_token.html
> +                            <span>Votre token d'API est :</span>
```suggestion
                            Votre token d'API est :
```

2023-03-28 13:27 UTC, francoisfreitag commented on itou/www/dashboard/tests.py
> +    assertNotContains(response, url)
On pourrait appairer les assertions avec les assertions positives, pour éviter qu’une mise à jour du texte rende cette assertion caduque.

2023-03-28 13:27 UTC, francoisfreitag commented on itou/www/dashboard/views.py
> +
Pourquoi spécifier en particulier le cas du prescripteur, si on attend le même comportement que pour tous les utilisateurs qui ne sont pas employés par une SIAE ?

2023-03-28 13:27 UTC, francoisfreitag commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
On attend un seul token par utilisateur.
```suggestion
        token = Token.objects.filter(user=request.user).get()
```

2023-03-28 13:29 UTC, francoisfreitag commented on itou/www/dashboard/views.py
> +        token = Token.objects.create(user=request.user)
Si je `POST` plusieurs fois, j’aurai une belle collection de `Token` ?

2023-03-28 13:32 UTC, tonial commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
C'est un access token de DRF, il permet de récupérer la liste des salariés avec leur PASS IAE.

2023-03-28 13:33 UTC, tonial commented on itou/templates/dashboard/api_token.html
> +{% block title %}Mes notifications{{ block.super }}{% endblock %}
C/C d'un autre template pour le POC en oubliant de modifier cette ligne, 
merci

2023-03-28 13:38 UTC, tonial commented on itou/www/dashboard/views.py
> +
Ah, c'est très juste, je voulais vérifier si un prescripteur avait parfois besoin d'accéder à cette API

2023-03-28 13:46 UTC, tonial commented on itou/www/dashboard/views.py
> +        token = Token.objects.create(user=request.user)
je mets un get_or_create, bien vu

2023-03-28 13:51 UTC, francoisfreitag commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
Humpf. Peut-être une bonne occasion pour introduire :

```python
from django.shortcuts import _get_queryset


  def get_or_none(cls, *args, **kwargs):
      qs = _get_queryset(cls)
      try:
          obj = qs.get(*args, **kwargs)
      except qs.model.DoesNotExist:
          obj = None
      return obj

2023-03-28 13:53 UTC, francoisfreitag commented on itou/www/dashboard/tests.py
> +    assertNotContains(response, url)
Je parlais de mettre `"Token d’API"` dans une variable, qui serait utilisé dans le test positif (`assertContains`) et négatif. De cette manière, si le texte change, l’assertion positive sera mise à jour (via la variable), et l’assertion négative aussi. L’idée est de lier ces deux assertions dans le code.

2023-03-28 13:57 UTC, tonial commented on itou/www/dashboard/tests.py
> +    assertNotContains(response, url)
Je comprends, du coup tu le mettrais dans un `TOKEN_MENU_STR = "Toekn d'API"` ?

2023-03-28 14:03 UTC, tonial commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
L'idée c'est de crasher s'il y en a 2, c'est ça ?

2023-03-28 16:09 UTC, francoisfreitag commented on itou/www/dashboard/tests.py
> +    assertNotContains(response, url)
Yep, ça irait très bien.

2023-03-28 16:10 UTC, francoisfreitag commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
Tout à fait.

2023-03-29 08:42 UTC, ikarius commented on itou/www/dashboard/views.py
> +        current_siae_pk = request.session.get(global_constants.ITOU_SESSION_CURRENT_SIAE_KEY)
`get_current_siae_or_404(request)` ? (dans `itou.utils.perms.siae`)

2023-03-29 08:44 UTC, ikarius commented on itou/www/dashboard/views.py
> +        membership = request.user.siaemembership_set.get(siae=siae)
`siae.has_admin(request.user)`  ?

2023-03-29 08:46 UTC, ikarius approved these changes
LGTM
Peut-être quelques simplications à l'aide d'helpers existants (voir commentaires un peu laconiques).
Ma remarque sur les clés globales.ciblées nécessite plus de réflexion, mais je pense qu'on y viendra.

2023-03-29 08:49 UTC, ikarius commented on itou/www/dashboard/views.py
> +        token = Token.objects.filter(user=request.user).first()
C'est un bon début, et ça fait avancer le sujet. Même si à terme, je pense qu'une clé par API sera nécessaire.
Si je ne me trompe pas, ce token DRF est global pour tous les accès / API.
On voudra peut-être faire en sorte que les tokens n'aient que des accès a des API ciblées.

2023-03-30 09:32 UTC, tonial commented on itou/www/dashboard/views.py
> +        membership = request.user.siaemembership_set.get(siae=siae)
On a pleins de helpers pratiques !

2023-03-30 10:30 UTC, tonial commented
Nouvelle proposition : 
![image](https://user-images.githubusercontent.com/7632730/228809004-b63fad03-d919-4eba-8440-8259e87583f7.png)

2023-03-30 15:52 UTC, ikarius commented on itou/api/token_auth/views.py
> +class ObtainAuthTokent(drf_authtoken_views.ObtainAuthToken):
token**t** ?

2023-03-30 16:23 UTC, francoisfreitag commented
> je ne me rappelle plus de la proposition de @francoisfreitag de ce matin

Je disais que PyPI utilise `__token__`. Mais peu importe comment on marque que c’est un identifiant réserver, il ne faut juste pas que ça conflicte avec un nom d’utilisateur réel probable.

2023-03-31 07:21 UTC, tonial commented
Normalement c'est bon : l'identifiant c'est un email donc ça peut être `__token__`

2023-03-31 08:38 UTC, merged