[Metabase] Ajout de deux nouveaux TB (Auto-prescription et CAP) aux DDETS / DREETS / DGEFP
betagouv/itou pull request #2141
Opened 2023-02-14 17:04 UTC by dejafait

**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-er-le-TB-Focus-Autoprescription-et-contr-le-a-posteriori-dans-le-TB-priv-DDETS-DREETS-et-DGEFP-1770e22dc62b4d50946b26443c53780c**

### Pourquoi ?

FIXME

### Comment

FIXME

2023-02-21 09:54 UTC, vperron requested changes
Un certain nombre de petites remarques, qui au final font que la compréhension du code et sa robustesse peuvent etre un petit peu améliorés !

Le mode de gestion des tableaux de bord de stats commence à me sembler bizarre avec son inversion de contrôle; rien à corriger et tout est bien centralisé mais on y décèle quelques bizarreries, comme le fait d'avoir exactement le meme code au titre près entre deux TB, mais que au final la requete se fait inspecter en bout de chaine pour injecter lebon numéro de TB quelque part: on inverse le principe de gestion des urls de Django.

Avec la factorisation, ça se voit plus car tout devient un one-liner ^^

Par ailleurs, cela donne des cas où l'on injecte des flags extérieurs (je pense à `show_diagnosis_control_message` pour contrôler in fine ce qui sera dans la template partagée) . 

Encore une fois rien à changer sur ce comportement général là, mais ça me fait une petite gymnastique mentale quand je retombe dessus !

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +    This dashboard shows the diagnosis control ("Contrôle a posteriori") raw data.
Intéressant parce que tout ce qui est controle a posteriori utilise le terme "siae evaluation" c'est meme le nom de l'app. On pourrait peut etre se passer de ce commentaire en renommant ici en `stats_ddets_siae_evaluations` ? Ca serait plus facilement greppable pour tout ce qui touche au controle a posteriori.

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
>      """
pareil ici, j'irais plus loin et supprimerais entierement la docstring.

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +        page_title=f"Données facilitation de l'embauche de mon département : {DEPARTMENTS[department]}",
nitpick pas nécessaire: je me demande si on pourrait pas refiler le boulot d'ajouter le suffixe ` de mon département : {DEPARTMENTS[department]}` directement à `render_stats_ddets`, ça éviterait de calculer deux fois le département (dedans et dehors) et ça donnerait une gestion unifiée du titre.
On y passerait donc juste un `title_prefix="Données facilitation de l'embauche"` par exemple.

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +        page_title=f"Données de ma région : {region}",
pareil ici que le nitpick plus haut avec `title_prefix="Données"`.

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +    if add_params:
pas fan de cette API, de ce `if`...
Je te recommanderais plutot de passer un `extra_params=None` à ton `render_stats_dgefp` et de laissant l'appellant lui passer.
```python
return render_stats_dgefp(
    request=request,
    page_title="Données des régions",
    extra_params=get_params_for_whole_country()
)
```

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +def render_stats_dgefp(request, page_title, add_params=True, extra_context={}):
attention, ne jamais passer un mutable comme argument par défaut d'un callable. Ca lui donne un state.
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +    This dashboard shows diagnosis control ("Contrôle a posteriori") raw data.
meme remarque concernant le choix de nommage qui est a contre courant de l'app du controle a posteriori à mon sens.

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +    """
hm, pas certain que ce commentaire soit nécessaire là on a retiré le meme genre de choses un peu partout ailleurs, non ?

2023-02-21 09:54 UTC, vperron commented on itou/www/stats/views.py
> +    """
gné, ce genre de commentaire sans beaucoup de valeur ajoutée me fait toujours un peu bizarre.

https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/

2023-02-23 16:22 UTC, dejafait commented on itou/www/stats/views.py
> +    This dashboard shows the diagnosis control ("Contrôle a posteriori") raw data.
Très bonne remarque ! C'est très curieux que j'ai créé ce terme `diagnosis_control` qui n'est aujourd'hui pas utilisé ailleurs dans le C1 que dans la logique C2... mais d'où ai-je pu sortir ce terme ? J'ai trouvé ! Dans cette très vieille conversation avec Céline : https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1642673974058300

Cela date d'*avant* l'implémentation du CAP dans le C1, donc *avant* que le terme `siae_evaluations` existe lol. 🤣 

Je renomme comme tu le proposes. Attention effet pervers : cela va changer les URL donc le traffic dans Matomo sera un peu perturbé. Je vais prévenir les analistos. @vperron

2023-02-23 16:23 UTC, dejafait commented on itou/www/stats/views.py
> +    This dashboard shows the diagnosis control ("Contrôle a posteriori") raw data.
Je vais garder le singulier pour être iso avec les autres routes stats. Donc `stats_ddets_siae_evaluation`.

2023-02-23 16:29 UTC, dejafait commented on itou/www/stats/views.py
> +    This dashboard shows the diagnosis control ("Contrôle a posteriori") raw data.
J'ai prévenu le C2 ici ([lien](https://itou-inclusion.slack.com/archives/CT7986ULC/p1677169739654669))

2023-02-23 16:58 UTC, dejafait commented on itou/www/stats/views.py
> +def render_stats_dgefp(request, page_title, add_params=True, extra_context={}):
TIL merci ! Je vais utiliser la solution préconisée. Mais FTR si j'ai bien compris comme je ne modifie pas `extra_context` dans la fonction, aucun bug n'aurait pu se produire.

2023-02-24 11:03 UTC, merged