Création de la table pour le suivi du contrôle à posteriori
betagouv/itou pull request #2170
Opened 2023-02-21 15:33 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Cr-er-les-indicateurs-contr-le-du-contr-le-posteriori-e7b99880b3b649cd9bf7d2542f5b26ef?pvs=4

### Pourquoi ?

Pour suivre les structures controlées par département et par campagne.

2023-02-21 16:57 UTC, dejafait approved these changes
LGTM

2023-02-21 16:57 UTC, dejafait commented on itou/metabase/sql/035_suivi_cap.sql
> +-- nb de structures référencées par dept
Pinaillage : commentaire redondant donc inutile. 🔪

2023-02-21 16:57 UTC, dejafait commented on itou/metabase/sql/035_suivi_cap.sql
> +        département,
Tiens tu as pas du mettre de guillements malgré l'accent ? (cf discussion Beautify sur Table Plus)

2023-02-21 16:57 UTC, dejafait commented on itou/metabase/sql/035_suivi_cap.sql
> +            end) as float) / max(nb_tot_dep.nb_struct) * 100 as pct_contrôlées,
Exactement deux fois la même expression :

```
sum(
            case when cap_struct."date_contrôle" is not null then
                1
            else
                0
            end)
```

il n'y a pas moyen de factoriser ?

2023-02-22 10:34 UTC, YannickPassa requested changes
Petites modifs mineures

2023-02-22 10:34 UTC, YannickPassa commented on itou/metabase/sql/035_suivi_cap.sql
> +    max(cap_camp. "pourcentage_sélection") as "pct_sélection",
Je te conseille de laisse tes valeurs de % en X/100 pour avoir un nombre décimal.
Sinon quand tu déclareras que ta colonne est sous forme "percent" dans metabase tu te retrouveras avec des valeurs absurdes du type 3000%

Aussi je trouve que "pct" n'est pas très clair comme indication pour un titre de colonne.

2023-02-22 10:34 UTC, YannickPassa commented on itou/metabase/sql/035_suivi_cap.sql
> +    sum(cap_struct_cnt. "nb_contrôlées") / max(nb_tot_dep.nb_struct) * 100 as "pct_contrôlées"
même remarque qu'au dessus

2023-02-22 11:03 UTC, YannickPassa requested changes
Il faut changer ton numéro de table en 037 !
+ mini commentaire

2023-02-22 11:04 UTC, YannickPassa commented on itou/metabase/sql/035_suivi_cap.sql
> +    max(cap_camp. "pourcentage_sélection")/100 as "part_structures_à_contrôler",
chez moi ça donne 0 cette ligne, pas 0,XX

2023-02-22 13:25 UTC, merged