fix: comparaison des emails inclusion connect en casse insensible
betagouv/itou pull request #2210
Opened 2023-03-01 15:15 UTC by vjousse

**Carte Notion : **

https://www.notion.so/plateforme-inclusion/BUG-une-diff-rence-de-casse-au-niveau-de-l-e-mail-impacte-les-invitations-2d2ed331e8b04529a738a7ba40f47797?pvs=4

### Pourquoi ?

Une différence de casse au niveau de l’e-mail impacte les invitations

2023-03-02 08:33 UTC, tonial requested changes

2023-03-02 08:33 UTC, tonial commented on itou/www/invitations_views/tests/tests_siae_accept.py
> +        invitation = SentSiaeStaffInvitationFactory(email=OIDC_USERINFO["email"])
Le problème rencontré est l'inverse : on a du upper dans l'invitation, et du lower dans le retour.
Ta correction fonctionne parfaitement, mais tant qu'à faire, je préfère qu'on soit sur de verrouiller le bon comportement au cas où le code soit revu à un moment.
-> `OIDC_USERINFO["email"].upper()` ici

2023-03-02 08:33 UTC, tonial commented on itou/www/invitations_views/tests/tests_siae_accept.py
> +            user_email=invitation.email.upper(),
ici tu peux retirer ce champ (la valeur par défaut marche) ou alors mettre invitation.email.lower() pour insister sur le fait que ce n'est pas la même valeur.

2023-03-06 09:47 UTC, tonial approved these changes
Nickel !

2023-03-06 10:28 UTC, rsebille approved these changes

2023-03-06 10:28 UTC, rsebille commented on itou/www/invitations_views/tests/tests_siae_accept.py
> +        user = User.objects.get(email=invitation.email)
J'ai l'impression qu'ici on ne veux tester que l'utilisateur et pas le nombre d'utilisateurs donc peut-être remplacer le premier `User.objects.count()` par `User.objects.filter(...).first() is None` (ou `.count() == 0` :grinning:) et faire disparaître le second au profit du `User.objects.get(...)`.

2023-03-06 15:40 UTC, merged