fix: ajout du next_url pour la redirection Inclusion Connect
betagouv/itou pull request #2235
Opened 2023-03-08 11:17 UTC by vjousse

### Carte Notion

https://www.notion.so/plateforme-inclusion/BUG-en-lien-avec-inclusion-connect-les-invitations-dans-une-autre-orga-ne-fonctionnent-plus-f80a49b85e8244c1b633a2b30b90b751?pvs=4

### Pourquoi ?

BUG en lien avec inclusion connect les invitations dans une autre orga ne fonctionnent plus

2023-03-09 08:29 UTC, tonial requested changes
Ça me semble être exactement ce qu'il faut.

Est-ce que tu peux regarder les tests existants pour les améliorer et garantir qu'on transmet bien le paramètre ?

2023-03-09 12:00 UTC, tonial commented on itou/www/invitations_views/tests/tests_prescriber_organization.py
> +        self.assertContains(response, reverse("login:activate_prescriber_account") + "?")
Le `'"'` sert à vérifier qu'on a exactement la bonne url avec les bons paramètres, donc il faut le laisser et corriger plutot l'url testée (qui contient à présent le next_url).

Je me rends compte qu'il manque un test sur la partie SIAE, il faudrait l'ajouter dans tests_siae_accept.py :
```
    @respx.mock
    def test_accept_existing_user_not_logged_in_using_IC(self):
        invitation = SentSiaeStaffInvitationFactory(email=OIDC_USERINFO["email"])
        user = SiaeStaffFactory(email=OIDC_USERINFO["email"], has_completed_welcoming_tour=True)
        response = self.client.get(invitation.acceptance_link, follow=True)
        assert reverse("login:siae_staff") in response.wsgi_request.get_full_path()
        assert not invitation.accepted
        ### -> changer l'url testée ici
        self.assertContains(response, reverse("login:activate_siae_staff_account") + '"')

        next_url = reverse("invitations_views:join_siae", args=(invitation.pk,))
        previous_url = f"{reverse('login:siae_staff')}?{urlencode({'next': next_url})}"
        response = mock_oauth_dance(
            self,
            UserKind.SIAE_STAFF,
            assert_redirects=False,
            user_email=user.email,
            channel="invitation",
            previous_url=previous_url,
            next_url=next_url,
        )
        # Follow the redirection.
        response = self.client.get(response.url, follow=True)

        assert response.context["user"].is_authenticated
        self.assert_accepted_invitation(response, invitation, user)
```

2023-03-10 15:37 UTC, tonial commented on itou/www/invitations_views/tests/tests_prescriber_organization.py
> +            reverse("login:activate_prescriber_account")
Tu devrais plutôt faire un `urlencode({"next": next_url})`
Avec le next_url juste en dessous

2023-03-10 15:38 UTC, tonial commented on itou/www/invitations_views/tests/tests_siae_accept.py
> +            reverse("login:activate_siae_staff_account")
idem : réutiliser le next_url en dessous

2023-03-10 15:40 UTC, tonial commented on itou/www/login/tests.py
> +        params_activate = urlencode({"next": "/activate"})
ce sont 2 fois les mêmes non ?

2023-03-10 15:41 UTC, tonial commented on itou/www/login/tests.py
> +
ici je préférerais que tu laisse le test de base, et ajoute à la suite la partie avec le next, comme ça on est sur que l'url fonctionne bien sans le paramètre.

```
url = reverse("login:prescriber")
response = self.client.get(url)
assert response.status_code == 200
self.assertContains(response, "Se connecter avec Inclusion Connect")
self.assertContains(response, reverse("login:activate_prescriber_account"))
self.assertContains(response, "Adresse e-mail")
self.assertContains(response, "Mot de passe")

params = urlencode({"next": "/activate"})
url = f"{reverse('login:prescriber')}?{params}"
response = self.client.get(url)
assert response.status_code == 200
self.assertContains(response, f"{reverse('login:activate_prescriber_account')}?{params}")
```

2023-03-10 15:41 UTC, tonial commented on itou/www/login/tests.py
> +        print(url)
attention au print :)

2023-03-10 15:44 UTC, tonial commented on itou/www/login/tests.py
> +    assertContains(response, f"action=\"{reverse('login:activate_prescriber_account')}?next_url=%2Ftest_join\"")
Dans ce cas, on utilise `f'....'` pour ne pas avoir à échapper les `"`

Si tu peux utiliser des `{urlencode(...)}` à la place de mettre des chaines avec des `%2F` et autre, ce serait super :)

2023-03-13 14:25 UTC, vjousse commented on itou/utils/tests.py
> -class UtilsEmailsTestCase(TestCase):
Oui c'est fait pour, elle ne portait pas vraiment un nom adapté IMHO. Ou alors j'ai loupé un truc ?

2023-03-13 14:29 UTC, tonial commented on itou/utils/tests.py
> -class UtilsEmailsTestCase(TestCase):
Ah, oui, tout à fait, j'ai pas vérifié :ok_hand:

2023-03-13 14:42 UTC, vjousse commented on itou/www/login/tests.py
> +        params_activate = urlencode({"next": "/activate"})
Bien vu ! Ils étaient différents avant et je n'ai pas fait attention en refactorant :+1:

2023-03-13 14:47 UTC, vjousse commented on itou/www/login/tests.py
> +    assertContains(response, f"action=\"{reverse('login:activate_prescriber_account')}?next_url=%2Ftest_join\"")
Oui mais si tu n'échappes pas les ", tu vas devoir échappe les ' de toute façon, non ?

2023-03-13 14:54 UTC, tonial commented on itou/www/login/tests.py
> +    assertContains(response, f"action=\"{reverse('login:activate_prescriber_account')}?next_url=%2Ftest_join\"")
Non parce qu'ils sont dans le les accolades de la f-string

2023-03-13 16:14 UTC, tonial requested changes
Je me suis rendu compte que le formulaire était cassé, du coup j'ai creusé un peu et j'ai du faire des modifs pour que ça passe (voir les commentaires)
Si tu veux, tu peux voir mes modifs ici : https://github.com/betagouv/itou/commit/a3838871ccec92e95e911ff7399961e7d693cc94

2023-03-13 16:14 UTC, tonial commented on itou/www/login/views.py
> +            activate_account_url = add_url_params(activate_account_url, {"next_url": params["next_url"]})
Il faut mettre "next", pas "next_url" car le paramètres vaut "next" sur cette page.
Mais en fait on est juste en train de refaire `self.request.get_full_path()` (que j'aurais du utiliser initialement)
Et en plus, pas besoin de ce paramètre : j'aurais du retirer le action='' parce que je veux renvoyer vers la page actuelle, ce qui est l'action par défaut... ^^'

Comme quoi, c'est bien d'avoir quelqu'un qui repasse sur son code plus tard pour voir tout les trucs mal écrits

2023-03-13 16:14 UTC, tonial commented on itou/www/login/views.py
> +            activate_account_url = add_url_params(activate_account_url, {"next_url": params["next_url"]})
Mais du coup le post avec un paramètre next n'était pas bien prix en compte (il faudrait le tester dans les tests type `test_prescriber_account_activation_view_already_exists`

2023-03-14 10:50 UTC, tonial approved these changes
deux petites modifs non nécessaires, mais sinon, c'est bon pour moi :)

N'oublie pas de squasher les commits (pas la peine de conserver le mien séparé)

2023-03-14 10:50 UTC, tonial commented on itou/www/login/tests.py
> +        url = f"{reverse('login:siae_staff')}"
ce changement n'est pas utile (la f-string est utile pour ajouter un truc à la suite du reverse, mais quand il n'y a rien à ajouter, ce n'est pas la peine)

2023-03-15 10:26 UTC, merged