matomo: Correction d'un bug qui annule certaines écritures :'(
betagouv/itou pull request #2243
Opened 2023-03-09 15:21 UTC by vperron

Sometimes the order of execution makes it possible that we don't write any of the results to metabase.

Explanation: we run 20 dashboard fetches in parallel.

Let's imagine that the 19 first to return get us valid values, but unfortunately the 20th and latest is empty.

We would not detect correctly its emptiness and would make `columns` be [], which would in turn make the subsequent check before updating Metabase fail.

Not only because of this but because the Matomo table structure did change, we need to re-run this from the beginning of 2022.

This is tricky to test though cause the order of the ThreadPoolExecutor is by nature non deterministic so it is difficult to design mocks so that the first URLs are filled and "the last one consulted" is empty.

2023-03-10 15:31 UTC, dejafait approved these changes
LGTM et le meme obligé en bonus !

![image](https://user-images.githubusercontent.com/10533583/224356874-69f61a2d-e842-4918-9a32-389bedf6f392.png)

2023-03-10 16:29 UTC, vperron commented on itou/metabase/management/commands/populate_metabase_matomo.py
>                  continue
Tu as bien raison.

2023-03-14 08:21 UTC, YannickPassa approved these changes
côté data analyst ça me semble bon

2023-03-14 08:38 UTC, laurinehu approved these changes
lgtm

2023-03-14 09:01 UTC, vperron commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +/* NOTE(vperron): il serait bon de m'aider à reprendre cette partie pour ne compter que sur la table _v1 please */
Note pour les data analysts

2023-03-14 09:23 UTC, YannickPassa requested changes
Si tu as bien pris en compte toutes les URLs des TBs privés, les deux CTE `visiteurs_prives` peuvent sauter.
Je n'ai pas l'impression que ça a été fait donc il faudrait soit :
-Faire en sorte que ta table _v1 prenne bien ça en compte
-Modifier les scripts sql, en ajoutant un script temporel qd on requête la table _v1, pour que les CTE `visiteurs_prives` et `visiteurs_prives_0` matchent niveau date.

2023-03-14 09:23 UTC, YannickPassa commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +        suivi_visiteurs_tb_prives_v1 svtp0 /* Nouvelle table créée par Victor qui démarre le 01/01/22 */
Est ce que tu as bien pris en compte les nombreux changements d'url qu'il y a eu pour les TBs privés ?

2023-03-14 09:23 UTC, YannickPassa commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
>  with visiteurs_prives as (
cette CTE peut sauter si tu a bien pris en compte les différentes urls des tbs privés

2023-03-14 09:33 UTC, vperron commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +        suivi_visiteurs_tb_prives_v1 svtp0 /* Nouvelle table créée par Victor qui démarre le 01/01/22 */
Hello, a priori non. Je ne pense d'ailleurs meme pas les connaitre. On va donc probablement devoir les laisser en place.

Question subsidiaire: est-ce que ça sert à quelque chose que je recupere les visites de TB prives entre Aout et Décembre 2022 avec les URLs d'aujourd'hui, ou ces dernières n'existaient pas avant ? Il semblerait que non.

Du coup je vais probablement juste laisser la `_v1` en remplacement de la `_v0` et on considèrera bien que elle commence à Décembre 2022. 

J'ai quelques données avant sur la `_v1`, on les supprime ? Peut-etre jette un oeil avant, on ne sait jamais si tu veux les conserver.

2023-03-14 09:37 UTC, YannickPassa commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +        suivi_visiteurs_tb_prives_v1 svtp0 /* Nouvelle table créée par Victor qui démarre le 01/01/22 */
Entre aout et decembre 2022, certaines existaient, d'autres non. Donc c'est bien de faire commencer tout ça en décembre 2022 en effet.

Si la `_v1` est presque identique à la `_v0` (avec des données en plus si j'ai bien compris), pourquoi tu ne remplaces pas carrément la `_v0` par la `_v1` ?

2023-03-14 09:41 UTC, dejafait approved these changes
LGTM en ce qui me concerne.

2023-03-14 09:41 UTC, dejafait commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +        suivi_visiteurs_tb_prives_v1 svtp0 /* Nouvelle table créée par Victor qui démarre le 01/01/22 */
> les nombreux changements d'url qu'il y a eu pour les TBs privés ?

Je ne suis pas sûr de comprendre de quoi tu parles Yannick. Là comme ça je pense juste au fait que j'ai récemment remplacé `diagnosis_control` par `siae_evaluation` dans quelques URL stats. A la demande de Victor d'ailleurs. Y-a-t'il autre chose ?

2023-03-14 10:02 UTC, vperron commented on itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
> +        suivi_visiteurs_tb_prives_v1 svtp0 /* Nouvelle table créée par Victor qui démarre le 01/01/22 */
Je pense que Yannick parle d'autres URLs de tb privés qui ont changé durant l'année 2022.
Si c'est trop compliqué on peut s'appeler rapidement.

Mais de mon point de vue j'ai ma réponse:
- la nouvelle table v1 est bien la meme chose que la v0 mais sans les trous
- on bascule juste la v0 vers la v1
- fin

2023-03-14 10:20 UTC, merged