Metabase : correctifs pour intégrer un filtre par type de structure sur le tb suivi CAP
betagouv/itou pull request #2244
Opened 2023-03-09 17:50 UTC by laurinehu

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Suivi-du-contr-le-posteriori-Prise-en-compte-de-retours-362f52edf1d5453f9540f54753248397?pvs=4

### Pourquoi ?

Intégrer un filtre par type de structure pour le suivi du CAP

2023-03-09 19:11 UTC, YannickPassa commented on itou/metabase/sql/039_suivi_cap_structures.sql
> +        0
Je te conseille de ne pas utiliser 0/1. Je reconnais que pour nous c'est pratique mais si cette entrée est amenée à être utilisée comme filtre ça peut perturber les utilisateurs/trices

2023-03-09 19:12 UTC, YannickPassa commented on itou/metabase/sql/039_suivi_cap_structures.sql
> +    cap_structures.état
est ce que tu ne traduirais pas les états, écrits en anglais, en français ?

2023-03-09 19:15 UTC, YannickPassa requested changes
Qques petits changements nécessaires selon moi

2023-03-09 19:15 UTC, YannickPassa commented on itou/metabase/sql/038_suivi_cap_criteres.sql
>      case when "cap_criteres"."état" = 'REFUSED_2' then 'REFUSED' else "cap_criteres"."état" end as état,
même remarque qu'en dessous pour l'état

2023-03-09 19:15 UTC, YannickPassa commented on itou/metabase/sql/038_suivi_cap_criteres.sql
>      "structs"."nom_département" as "nom_département",
je te conseille d'aussi rajouter le département. Il me semble qu'il est nécessaire pour que le cablage que fait Vermeer avec le C1 soit efficace

2023-03-09 19:15 UTC, YannickPassa commented on itou/metabase/sql/039_suivi_cap_structures.sql
> +    structures.nom_département as nom_département,
département à rajouter

2023-03-14 15:39 UTC, laurinehu commented on itou/metabase/sql/039_suivi_cap_structures.sql
> +    cap_structures.état
pour le moment je laisse comme tel car j'attends un retour de Joffrey sur les labels utilisés mais je prendrai en compte ensuite !

2023-03-14 15:39 UTC, laurinehu commented on itou/metabase/sql/038_suivi_cap_criteres.sql
>      case when "cap_criteres"."état" = 'REFUSED_2' then 'REFUSED' else "cap_criteres"."état" end as état,
idem

2023-03-14 15:51 UTC, YannickPassa approved these changes
ça me semble bon :)

2023-03-14 16:21 UTC, merged