Correction de la génération du code postal de SIaeFactory
betagouv/itou pull request #2293
Opened 2023-03-21 08:44 UTC by tonial

De temps en temps, le code postal n'est pas d'un département valide

2023-03-21 08:56 UTC, rsebille requested changes

2023-03-21 09:13 UTC, tonial commented on itou/siaes/factories.py
> +    post_code = factory.LazyAttribute(lambda o: _create_fake_postcode())
Sauf que ça indique juste que l'on aura 5 caractères, pas que le département (prefix du code postal) sera bon, si ?

2023-03-21 11:55 UTC, rsebille commented on itou/siaes/factories.py
> +    post_code = factory.LazyAttribute(lambda o: _create_fake_postcode())
Effectivement... Je pensais que c'était [fait dans le provider](https://github.com/joke2k/faker/blob/9da36a88849cdd5e8ea41b085859bd6ee004f3a3/faker/providers/address/__init__.py#L62-L66) mais c'est franco-centrique donc normal que celui-ci soit généraliste.

Mais pour le cas courant tu peux t'en sortir avec ça :
```python
post_code = factory.Faker("pystr_format", string_format="{{department_number}}###", locale="fr_FR")
```

2023-03-21 14:18 UTC, tonial commented on itou/siaes/factories.py
> +    post_code = factory.LazyAttribute(lambda o: _create_fake_postcode())
nice !

2023-03-21 14:21 UTC, tonial commented on itou/siaes/factories.py
> +    post_code = factory.LazyAttribute(lambda o: _create_fake_postcode())
Ah, non ça ne marche pas car department_number peut faire 3 caractères donc on arrive à un post_code de 6 chiffres

2023-03-27 12:02 UTC, rsebille approved these changes

2023-03-27 13:55 UTC, merged