Amélioration UI de la liste des métiers et recrutements
betagouv/itou pull request #2295
Opened 2023-03-22 09:45 UTC by hellodeloo

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/C1-Am-lioration-front-end-M-tiers-et-recrutements-2bc5bedd9bda47058646c8dc42b3ab26?pvs=4

### Pourquoi ?

Respect du thème
Améliorations UX et A11Y

### Captures d'écran (optionnel)

Voir maquette https://www.figma.com/file/lIIF5oH92rH5OgHeEkYNCh/%F0%9F%94%B5Gestion-des-m%C3%A9tiers%2F-Fiche-de-poste?node-id=2403%3A39714&t=ss7lC4Vwa4YRUpO2-1

2023-03-29 08:37 UTC, celine-m-s commented on itou/templates/siaes/job_description_list.html
> +                                <span role="button" data-toggle="tooltip" data-placement="top" title="Trier par Métiers">Métiers</span>
Petite remarque mineure : cette majuscule en milieu de phrase fait un peu mal aux yeux. Je préconise « Trier par métier » (et pareil sur les autres tris).

2023-03-29 08:41 UTC, celine-m-s commented on itou/templates/siaes/job_description_list.html
> +                                    <div id="_delete_modal_{{ job_description.id }}" class="modal fade" tabindex="-1" aria-labelledby="confirmDeleteModal{{ job_description.id }}" aria-hidden="true">
Juste par curiosité, pourquoi préfixer l'ID avec un _ ?

2023-03-29 09:01 UTC, celine-m-s requested changes
Je comprends l'intérêt de faire le tri uniquement en JS mais je pense que ça pose des soucis avec la pagination.
En effet, le tri actuel ne fonctionne pas avec la pagination : il trie des dix premiers résultats mais le passage à la page suivante réinitialise le tri. C'est un peu frustrant.
Il y a un bug avec le tri des numéros. J'ai testé avec le nombre de postes ouverts au recrutement : 10 arrive juste après 1.
Autre petit point frustrant : il faut cliquer deux fois sur l'icône pour déclencher l'action de tri car il n'y a pas de valeur par défaut. C'est frustrant, on s'attend à ce que le clic déclenche une action tout de suite.

Techniquement, je serais plutôt partie sur un tri effectué en back avec des appels HTTP  et HTMX en front pour recharger le tableau. À ton avis ?

2023-03-30 09:53 UTC, hellodeloo commented on itou/templates/siaes/job_description_list.html
> +                                <span role="button" data-toggle="tooltip" data-placement="top" title="Trier par Métiers">Métiers</span>
Merci, oui tu as raison.

2023-03-30 09:54 UTC, hellodeloo commented on itou/templates/siaes/job_description_list.html
> +                                    <div id="_delete_modal_{{ job_description.id }}" class="modal fade" tabindex="-1" aria-labelledby="confirmDeleteModal{{ job_description.id }}" aria-hidden="true">
Aucune idée, c'etait comme ça

2023-04-12 10:37 UTC, rsebille commented on itou/templates/siaes/job_description_list.html
> +                Métier{{ job_pager.paginator.count|pluralize }} exercé{{ job_pager.paginator.count|pluralize }}
Dans les maquettes il y a le nombre avant, oublis ou changement après coup ?

2023-04-12 10:37 UTC, rsebille commented on itou/templates/siaes/job_description_list.html
> +                    <form method="post" action="?page={{ page|default:1 }}" id="block_job_applications_form">
Sur le moment j'ai un doute pour les paramètres GET mais pour moi pas besoin de forger l'URL actuel, il suffit de virer `action`.
```suggestion
                    <form method="post" id="block_job_applications_form">
```

2023-04-12 10:37 UTC, rsebille commented on itou/templates/siaes/job_description_list.html
> +                                <i class="ri-lock-line ri-lg"></i>
Je sais pas si tu l'a traité dans ton autre PR mais peut-être ajouter le `aria-hidden` pour les picto modifiés dans la PR ?

2023-04-12 10:37 UTC, rsebille commented on itou/templates/siaes/job_description_list.html
> +                <a class="btn btn-primary btn-ico justify-content-center mt-3 mt-md-0" href="{% url "siaes_views:edit_job_description" %}?page={{ page|default:1 }}">
Le paramètre `page` ne semble pas utilisé par la vue `edit_job_description` mais seulement pour `job_description_list`
```suggestion
                <a class="btn btn-primary btn-ico justify-content-center mt-3 mt-md-0" href="{% url "siaes_views:edit_job_description" %}">
```

2023-04-12 10:37 UTC, rsebille commented on itou/templates/siaes/job_description_list.html
> +                                                   {% if siae.block_job_applications %} disabled{% endif %}/>
Petit incohérence d'espace entre les deux conditions, ça change pas grande chose vu qu'elles sont chacune sur leur ligne mais je pense que la version avec l'espace en début est la plus _safe_ dans le cas où ça serais reformaté.

2023-04-18 12:09 UTC, xavfernandez reviewed
Tu sembles avoir raté ton split de commit pour le thème :)
Je vois du app.js sur "feat: update job description list ui " et des corrections de test sur "feat: update itou theme to v.0.6.2"

2023-04-18 12:09 UTC, xavfernandez commented on itou/templates/siaes/job_description_list.html
> -                        <button type="button" class="btn btn-outline-primary btn-sm" aria-label="Aperçu dans les résultats de recherche" hx-get="{% url "siaes_views:card_search_preview" %}" hx-target
Si on supprime le bouton, il faudrait idéalement supprimer la vue
https://github.com/betagouv/itou/blob/77200e54a7d8c8e69e93a1d5fdac9d564d4d0266/itou/www/siaes_views/views.py#L82-L98 (avec son url & ses tests), peut-être dans un commit séparé.

2023-04-19 09:13 UTC, xavfernandez commented on itou/templates/siaes/job_description_list.html
> +                                                        <button type="submit" class="btn btn-primary btn-sm" aria-label="Supprimer">Supprimer</button>
J'ai l'impression que ce aria-label ne sert à rien (identique au texte du bouton) ?

2023-04-19 09:13 UTC, xavfernandez commented on itou/templates/siaes/job_description_list.html
> -                        <button type="button" class="btn btn-outline-primary btn-sm" aria-label="Aperçu dans les résultats de recherche" hx-get="{% url "siaes_views:card_search_preview" %}" hx-target
Les commits sont bien séparés mais la vue card_search_preview est toujours là (et ne sert plus à rien une fois ce bouton supprimé)

2023-04-19 09:37 UTC, hellodeloo commented on itou/templates/siaes/job_description_list.html
> +                                                        <button type="submit" class="btn btn-primary btn-sm" aria-label="Supprimer">Supprimer</button>
Effectivement ils ne servent à rien, car n'apportant pas plus d'information.
Cependant, je vais laisser comme ça, car j'essaye de ne pas trop sortir de la demande du ticket dans mes PR, sinon, je peux tirer le fil de la pelote de laine, mais après, je me fais taper sur les doigts parceque y'a trop de trucs mélangés dans une seule PR. 
Bref, pour un autre ticket A11y plutôt

2023-04-19 09:46 UTC, hellodeloo commented on itou/templates/siaes/job_description_list.html
> -                        <button type="button" class="btn btn-outline-primary btn-sm" aria-label="Aperçu dans les résultats de recherche" hx-get="{% url "siaes_views:card_search_preview" %}" hx-target
Bon j'ai essayé de supprimer la vue, mais y'a des erreurs de test htmx maintenant (sur cette vue surement) et comme je peux plus faire fonctionner les tests en local, je ne peux plus rien faire de plus. Si jamais tu veux tirer la PR et fixer les tests, je veux bien, car là, je suis bloqué.

2023-04-19 09:58 UTC, xavfernandez approved these changes

2023-04-19 10:18 UTC, merged