GEIQ : Ouverture du parcours d'auto-prescription et messages contextuels
betagouv/itou pull request #2320
Opened 2023-03-29 09:52 UTC by rsebille

**Carte Notion :**
https://www.notion.so/plateforme-inclusion/1-3-Pack-postuler-en-Geiq-En-tant-qu-employeur-je-r-alise-une-auto-prescription-96bded172c0649f1b421d09370cfa599?pvs=4
https://www.notion.so/plateforme-inclusion/3-3-Pack-postuler-en-Geiq-En-tant-que-postulant-en-GEIQ-je-renseigne-le-message-de-candidature-2d7ef157cfb94926a7adfd67dd9fab82?pvs=4

### Pourquoi ?

Suite au nouvel arrêté relatif aux critères d’éligibilité à l’aide à l’accompagnement GEIQ et à la demande de la FFGEIQ qui souhaite adapter le parcours de candidature aux besoins des GEIQ.

### Comment (optionnel)

Reprise de la même logique que pour l'IAE, avec simplification vu que les cas PASS IAE n'existent pas,

2023-03-29 13:25 UTC, ikarius commented on itou/templates/apply/submit/application/resume.html
> +                                {% if request.user.is_prescriber %}
Pour une tournure :)

2023-03-29 13:39 UTC, ikarius commented on itou/templates/apply/submit/application/resume.html
> +        {% if not request.user.is_siae_staff or geiq_eligibility_diagnosis %}
J'ai écris ce paté pour rien, `is_subject_to_geiq_eligiblity` veux bien dire qu'on a un GEIQ comme utilisateur

2023-03-29 13:40 UTC, ikarius commented on itou/templates/apply/submit/application/resume.html
> +        </button>
Le reformattage est de ton fait ou de `djlint` ?

2023-03-29 13:41 UTC, ikarius commented on itou/templates/dashboard/includes/siae_job_applications_card.html
> +                <li class="d-flex justify-content-between mb-3">
TIL `justify-content-between`

2023-03-29 13:42 UTC, ikarius requested changes
LGTM 
- un test du build claque (je ne sais pas si c'est lié)
- un petit test sur l'aspect du template pour la route ? (le template `resume` commence vraiment à devenir tortueux)

2023-03-29 16:58 UTC, rsebille commented on itou/templates/apply/includes/geiq/geiq_administrative_criteria_form.html
> +{% bootstrap_field form.beneficiaire_des_minimas_sociaux %}
Vu **totalement** par hasard, vu que c'est le premier de la liste j'ai cliqué sur le label pour avoir 1 critère et ça n'a pas coché la case ^^.

2023-03-30 14:51 UTC, rsebille commented
Oui, le test en échec est normal, j'ai push rapidement pour avoir la recette jetable.

Pour le test de `resume.html`, la question c'était déjà posée pour l'IAE et la conclusion était que le risque (c'est quasiment que du wording) ne valait pas le coût de l'écriture des tests (être exhaustif pour ne pas avoir une fausse sensation de sécurité).

2023-04-11 15:59 UTC, xavfernandez approved these changes
Effectivement, beaucoup de if pour du wording, je me demande comment on pourrait rendre tout cela plus digeste...

2023-04-12 08:52 UTC, rsebille commented
Quand j'ai dû ajouter les wording pour l'IAE j'ai commencer avec une solution "maline" mais ça c'est très vite retourné contre nous donc je suis allé vers la simplification d'avoir quasiment toutes les branches quitte à se répéter ou être verbeux.
Et si on souhaitais simplifier je ne n'ai que 2 idées (avec leurs avantages et inconvénients) en têtes :
1. Modifier le wording pour qu'il fonctionne dans tout les cas
2. Déplacer les blocs dans d'autre gabarits

2023-04-12 09:01 UTC, ikarius approved these changes
LGTM
Des parties bien plus claires, nice !

2023-04-12 09:07 UTC, rsebille commented on itou/www/dashboard/tests.py
> +        for kind in [SiaeKind.GEIQ]:
De ce que j'ai compris les 8 cartes de "Déclaration d'embauche + rapide" vont déplacer le parcours actuel "Déclaration d'embauche" vers "Enregistrer une candidature" (les GEIQ sont en avance pour une fois :grin:) donc en théorie oui.

2023-04-13 07:49 UTC, merged