Corrections liées à l'autoaudit d'accessibilité lot#02
betagouv/itou pull request #2337
Opened 2023-04-03 10:26 UTC by hellodeloo

**Carte Notion : **

### Pourquoi ?

Amélioration de l'accessibilité du parcours "Gestion dus PASS IAE"

### Comment

En corrigeant les erreurs liées aux points :
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#6.1

2023-04-04 13:02 UTC, tonial approved these changes

2023-04-05 08:01 UTC, hellodeloo commented on itou/templates/apply/includes/job_seeker_info.html
> +       aria-label="Modifier les informations personnelles de {{ job_application.job_seeker.first_name|mask_unless:can_view_personal_information }} {{ job_application.job_seeker.last_name|mask_unless:
Parcque je galère toujours a savoir ce que qui est disponible dans le context de la vue. 
Done.

2023-04-12 09:51 UTC, rsebille commented on itou/templates/approvals/printable_approval.html
> +                            {% if approval.user.address_line_2 %}
Ça devrais pas plutôt être ça ?
```suggestion
                            {% if siae.address_line_2 %}
```

2023-04-13 09:10 UTC, celine-m-s requested changes

2023-04-18 07:53 UTC, xavfernandez commented on itou/templates/apply/list_for_job_seeker.html
> +                <button class="c-aside-filters__btn__collapse" data-toggle="collapse" href="#job-aside-filters-form" aria-expanded="false" aria-controls="job-aside-filters-form">
Pourquoi mettre un href à la place d'un data-target ?
- bootstrap recommande data-target https://getbootstrap.com/docs/4.6/components/collapse/#example
- href ne fait pas partie des attributs autorisés par le HTML sur un bouton: on se retrouve avec du HTML non valide

(pareil pour les autres filters-form)

2023-04-18 08:03 UTC, hellodeloo commented on itou/templates/apply/list_for_job_seeker.html
> +                <button class="c-aside-filters__btn__collapse" data-toggle="collapse" href="#job-aside-filters-form" aria-expanded="false" aria-controls="job-aside-filters-form">
Bien vu. Effectivement, l'attribut href n'a rien a faire là.

2023-04-19 10:19 UTC, celine-m-s approved these changes

2023-04-20 12:23 UTC, merged