Docker : MAJ de Debian et quelques améliorations au passage
betagouv/itou pull request #2936
Opened 2023-08-24 17:16 UTC by rsebille

### Pourquoi ?

Debian buster ne sera bientôt plus du tout maintenu : https://www.debian.org/releases/buster/.

Je n'ai pas eu de problème particulier de mon coté mais a tester pour ceux qui utilisent MacOS ;).

2023-08-25 08:27 UTC, xavfernandez approved these changes

2023-08-25 08:27 UTC, xavfernandez commented on docker/dev/django/Dockerfile
> +RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
Cf https://github.com/betagouv/itou-backups/pull/20/commits/8752a05b63a8449e78bd0187e5aaa2ad63909c0b

2023-08-29 13:54 UTC, dejafait requested changes
Attention dégradation considérable de performance. Par exemple un simple `time make fix` monte de 13s à 110s (X10). Est-ce que quelqu'un d'autre arrive à reproduire la dégradation ou c'est juste chez moi, et donc lié à MacOS ?

2023-08-29 14:04 UTC, xavfernandez commented
@dejafait tu peux essayer sans le `platform: linux/amd64` dans le `docker-compose.yml` ?

2023-08-29 14:12 UTC, dejafait commented
@xavfernandez En effet, enlever cette ligne ramène à la bonne performance initiale. ✅

2023-08-29 15:18 UTC, rsebille commented
Parfait, je la vire alors :).

2023-09-01 08:53 UTC, dejafait approved these changes
LGTM

2023-09-05 09:24 UTC, merged