Repositionner les boutons actions en haut à droite de la candidature
betagouv/itou pull request #3074
Opened 2023-09-22 13:50 UTC by tonial

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/1-3-page-candidature-Repositionner-les-boutons-actions-en-haut-droite-de-la-candidature-c531a6c4f55b45c5bf6f6e1446f2c1f6?pvs=4

### Pourquoi ?

Rendre plus accessibles les boutons d’actions.

2023-09-27 10:17 UTC, xavfernandez reviewed
Pour une candidature acceptée sans action possible on se retrouve avec une zone vide inutile:
![Screenshot 2023-09-27 at 12-03-43 Les emplois de l'inclusion](https://github.com/betagouv/itou/assets/1089744/4989e19e-0c45-47ea-9bd6-095f93a6c9c1)

2023-09-28 13:10 UTC, tonial commented on itou/templates/apply/includes/siae_hiring_details.html
> +<div>
le soucis c'est que dans ce if il y a plusieurs éléments conditionnel (les actions par statut, l'archivage, le transfert) du coup j'ai pas encore eu de super idée.
Joffrey propose de mettre du texte systématiquement, il faut que je vois ce que ça donne.

2023-10-03 07:52 UTC, tonial commented
@xavfernandez c'est bon, c'est corrigé

2023-10-03 13:28 UTC, xavfernandez requested changes

2023-10-03 13:28 UTC, xavfernandez commented on itou/templates/apply/process_details_siae.html
> +            $(".hide-if-empty").each(function() {
```suggestion
        htmx.onLoad((target) => {
            $(".hide-if-empty", target).each(function() {
```
Pour que le JS soit exécuté quand la page est en partie rechargée.
Et faut-il prévoir le cas où suite à une action htmx, la zone n'est plus vide et il faudrait la "unhide" ?

2023-10-03 14:53 UTC, tonial commented on itou/templates/apply/process_details_siae.html
> +            $(".hide-if-empty").each(function() {
ce qui m'a permis de voir que j'avais écrit `{{ bloc.super }}` (sans le k) et donc que je n'importait pas htmx :roll_eyes:

2023-10-03 15:31 UTC, xavfernandez approved these changes

2023-10-05 07:05 UTC, merged