vgrange/send_more_context_to_sentry
betagouv/itou pull request #316
Opened 2020-08-11 13:53 UTC by vgrange

2020-08-14 08:00 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [On ignore quel utilisateur est concerné par les erreurs 500 en production](https://trello.com/c/9dIsCvTS/917-on-ignore-quel-utilisateur-est-concern%C3%A9-par-les-erreurs-500-en-production)

2020-08-24 08:31 UTC, kemar commented on config/settings/prod.py
> +    send_default_pii=True,
Yes, [c'est la bonne façon de faire](https://docs.sentry.io/platforms/python/django/#behavior) :

> Sentry also excludes personally identifiable information (such as user ids, usernames, cookies, authorization headers, IP addresses) unless you set send_default_pii to True.

Par contre :

> [`send_default_pii=True`](https://github.com/getsentry/sentry-docs/issues/1240#issuecomment-536549806) "opens the floodgates" (first decision) and requires you to think about what data you really want to send to Sentry (second decision)

Est-ce qu'on a bien lu [toute la doc sur PII](https://docs.sentry.io/data-management/sensitive-data/) qui veut dire **Personally Identifiable Information** ? Est-ce qu'on ne devrait pas creuser et s'assurer de ne remonter que l'ID de l'utilisateur ?

2020-08-24 08:31 UTC, kemar requested changes
Discussion ouverte sur le niveau des informations personnelles remontées par Sentry

2020-08-24 14:09 UTC, vgrange commented on config/settings/prod.py
> +    send_default_pii=True,
Après une longue galère j'ai trouvé comment virer email+username en revanche l'IP s'obstine à rester.

Avant :

![image](https://user-images.githubusercontent.com/10533583/91053358-5dce3a00-e62b-11ea-9b92-43b07bf277be.png)

Après :

![image](https://user-images.githubusercontent.com/10533583/91053453-7fc7bc80-e62b-11ea-870b-0b5624971754.png)

2020-09-01 08:28 UTC, kemar approved these changes
LGTM

2020-09-01 14:03 UTC, merged