Ajout d'actions pour les nouvelle candidatures
betagouv/itou pull request #3176
Opened 2023-10-10 08:34 UTC by tonial

**Carte Notion : ** A VENIR

2023-10-10 12:05 UTC, francoisfreitag requested changes
STR :

1. Faire une candidature
2. En tant qu’entreprise ayant reçu la candidature, la décliner depuis la page d’accueil de la candidature

Le bouton décliner est toujours présent. En suivant le process de refus à nouveau, le message “Action déjà effectuée.” s’affiche. La candidature ne semble pas être réellement déclinée, car son état change bien lorsqu’on passe par étudier cette candidature.

À mon avis, c’est pas du boost, et ça mérite des vrais tests.

2023-10-10 12:13 UTC, tonial commented
Damn, il faut adapter le Workflow

2023-10-10 12:32 UTC, tonial commented
J'ai amélioré les tests des transitions qui ne couvraient pas toutes les status de départ possible

2023-10-12 08:22 UTC, tonial commented
@francoisfreitag c'est bon pour re-regarder si tu as le temps

2023-10-12 09:27 UTC, francoisfreitag approved these changes

2023-10-12 09:55 UTC, merged