Stats : Ajout de stats sur les demandes de prolongations pour la DGEFP
betagouv/itou pull request #3276
Opened 2023-10-30 10:17 UTC by YannickPassa

**Carte Notion : ** : https://www.notion.so/plateforme-inclusion/Suivi-des-cartes-b3082fffe3f34eaea8fff8ba69338005?p=88acffe3b0b34aa6973686c9f64ac5e2&pm=c

### Pourquoi ?

Les DDETS et DREETS avaient accès aux TB privé de suivi de demandes de prolongation mais pas la DGEFP, nous corrigeons ici cet oubli.

[PR DDETS/DREETS](https://github.com/betagouv/itou/pull/3099)

### Comment 

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran

2023-10-30 10:18 UTC, YannickPassa commented
J'ai appelé ça `stats_dgefp_iae_follow_prolongation` mais je ne sais pas s'il faut plutot mettre `stats_dgefp_follow_prolongation`

2023-10-30 14:43 UTC, vperron approved these changes
Ca me va mais je laisse @rsebille juger :)

2023-11-06 10:33 UTC, dejafait requested changes
- En effet il faudrait mieux enlever `iae` (`stats_dgefp_iae_follow_prolongation` => `stats_dgefp_follow_prolongation`) sans quoi l'ancien `stats_dgefp_iae` devient particulièrement ambigüe/perturbant avec la nouvelle vue. D'ailleurs pour l'URL tu as "naturellement" évité le `iae` puisque tu as mis `"dgefp/follow_prolongation"` et non pas `"dgefp/iae/follow_prolongation"`
- As-tu pu tester un minimum en local que le branchement fonctionne bien ? Le suspens est : les filtres région/département vont-ils automatiquement bien être remplis comme il faut ?

2023-11-06 11:25 UTC, YannickPassa commented
> As-tu pu tester un minimum en local que le branchement fonctionne bien ? Le suspens est : les filtres région/département vont-ils automatiquement bien être remplis comme il faut ?

Non, je n'ai pas trouvé de compte DGEFP sur l'env de test en local (mais j'ai peut etre mal regardé) et surtout je ne sais pas comment aller sur un vrai TB metabase en local vu que c'est un env de test

Par contre c'est la DGEFP donc ils ont accès a toutes les régions et départements :)

2023-11-07 14:39 UTC, dejafait approved these changes
LGTM pour te débloquer.
Pour le test en local, sujet de fond à suivre dans : https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1699357340454739

2023-11-07 16:53 UTC, rsebille approved these changes
![x0d42ssjarh91](https://github.com/betagouv/itou/assets/20045330/791d21bd-b860-45ee-beeb-2c8ae661e28a)

2023-11-13 11:16 UTC, merged