Changelog: Sprint 74
betagouv/itou pull request #3293
Opened 2023-11-06 11:16 UTC by tonial

2023-11-06 13:15 UTC, celine-m-s requested changes

2023-11-06 13:15 UTC, celine-m-s commented on CHANGELOG.md
> +- Embauche; l'employeur prée le poste à l'embauche
```suggestion
- Embauche : l'employeur précise le poste à l'embauche
```

2023-11-06 13:15 UTC, celine-m-s commented on CHANGELOG.md
> +- Carte candidature: Revue de la carte en vue prescritpeur
```suggestion
- Carte candidature : harmonisation de la carte en vue prescripteur (avec celle des employeurs)
```

2023-11-06 13:15 UTC, celine-m-s commented on CHANGELOG.md
> +- Fiches de poste: permettre de choisir un poste (code ROME) déjà existant
```suggestion
- Fiches de poste: permettre de choisir un poste (code ROME) déjà existant pour créer un poste avec une autre localisation (par exemple).
```

2023-11-06 13:15 UTC, celine-m-s commented on CHANGELOG.md
> +- PASS IAE: modification de la logique d'envoi à PE
```suggestion
- PASS IAE: modification de la logique d'envoi à PE : envoi des PASS démarrés, par une tâche planifiée toutes les 5 minutes.
```

2023-11-07 08:25 UTC, rsebille approved these changes
Et il y a peut-être aussi l'harmonisation de l'espace manquant devant les ":"

2023-11-07 08:25 UTC, rsebille commented on CHANGELOG.md
> +- Admin: Permettre à un employeur de desactiver son compte pour devenir prescritpeur (ou l'inverse)
Petite typo ;).
```suggestion
- Admin: Permettre à un employeur de desactiver son compte pour devenir prescripteur (ou l'inverse)
```

2023-11-07 09:59 UTC, xavfernandez approved these changes

2023-11-07 15:58 UTC, merged