vgrange/restrict_siae_creation
betagouv/itou pull request #349
Opened 2020-08-28 09:28 UTC by vgrange

2020-08-28 15:03 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Je peux créer une antenne dans un département non encore ouvert officiellement](https://trello.com/c/CSAtKKMk/960-je-peux-cr%C3%A9er-une-antenne-dans-un-d%C3%A9partement-non-encore-ouvert-officiellement)

2020-08-28 15:03 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [fonction créer une structure - limiter les types de SIAE possibles](https://trello.com/c/ht313Bgn/459-fonction-cr%C3%A9er-une-structure-limiter-les-types-de-siae-possibles)

2020-09-07 07:37 UTC, ikarius commented on itou/siaes/management/commands/import_siae.py
>  VUE_AF_DATASET_FILENAME = f"{CURRENT_DIR}/data/2020_06_30_fluxIAE_AnnexeFinanciere_29062020_063002.csv"
Pourquoi "en dur" ?

2020-09-07 08:14 UTC, kemar commented on itou/siaes/models.py
> +    def open_departments(self):
Ça me gêne un peu que ça soit une `property` car techniquement ça n'en est pas une. `OPEN_DEPARTMENTS` devrait être une constante et `is_in_open_department` devrait faire le travail de filtre en se basant sur `self.kind`.

2020-09-07 08:18 UTC, kemar commented on itou/www/siaes_views/forms.py
> +                f'<a href="{ SelectSiaeForm.DOC_OPENING_SCHEDULE_URL }" rel="noopener" target="_blank">'
Ça c'est une erreur de ma part, j'aurais dû passer `DOC_OPENING_SCHEDULE_URL` dans les _settings_. Je vais le faire dans ma PR en cours, et je fixerai ici aussi. Je me le note.

2020-09-07 08:19 UTC, ikarius commented on itou/siaes/models.py
> +    def open_departments(self):
Moi ça me gêne pas trop, c'est plus que ça appartient au "domaine" des départements et devrait se retrouver dans ce coin là...

2020-09-07 08:19 UTC, ikarius reviewed
LGTM

2020-09-07 08:20 UTC, kemar requested changes
LGTM avec remarque non bloquante.

2020-09-07 08:22 UTC, kemar commented on itou/siaes/models.py
> +    def open_departments(self):
Oui c'est ce que je dis en disant que `OPEN_DEPARTMENTS` devrait être une constante. Et s'il y a besoin de la personnaliser pour afficher une liste de choix spécifique dans un formulaire, c'est dans le form que ça doit se faire, pas dans une `property` du `model`. Mais on est dans le domaine du pinaillage qu'affectionne tellement @vgrange :)

2020-09-07 08:28 UTC, vgrange commented on itou/siaes/models.py
> +    def open_departments(self):
Je me permets un joker pour les raisons suivantes :
- les jokers sont par définition permis pour les pinaillages
- tout cela sera droppé de toute façon dans 2-3 mois une fois l'ouverture terminée

2020-09-07 08:42 UTC, celine-m-s commented
J'ai eu une erreur dans la recette jetable. C'est normal ? :/ 
Je ne peux pas créer une nouvelle structure car le champ Type est obligatoire. Pourtant c'est un champ non modifiable... 

![image](https://user-images.githubusercontent.com/6150920/92367428-ab9c7500-f0f6-11ea-8f1c-b5ce958df0e8.png)

2020-09-07 08:49 UTC, celine-m-s requested changes

2020-09-07 08:49 UTC, celine-m-s commented on itou/www/siaes_views/forms.py
> +        self.fields["kind"].widget.attrs["disabled"] = "disabled"
Sauf erreur de ma part, le type est désactivé mais n'est pas pré-rempli avec le type de `current_siae`. Il y a donc une erreur que l'utilisateur ne peut pas corriger.

2020-09-07 08:51 UTC, vgrange commented
ah désolé @celine-m-s je crois que j'avais pas remis à jour la review-app, je vais le faire pour vérifier ton souci de suite

2020-09-07 12:25 UTC, vgrange commented
Kudos à @celine-m-s pour avoir détecté un souci sur la form. Mea culpa, je n'ai pas assez testé en réel, j'ai fait trop confiance aux tests qui m'ont trahi, et j'ai failli casser la prod... une raison pour un de ces jours rajouter des tests end-to-end!?

Après avoir galéré sans succès pour faire fonctionner le champ en `disabled` :

![image](https://user-images.githubusercontent.com/10533583/92386596-bec23b80-f11c-11ea-9268-6fc539ecbebb.png)

j'ai finalement jeté l'éponge et fait à la place un dropdown avec un unique choix :

![image](https://user-images.githubusercontent.com/10533583/92386648-da2d4680-f11c-11ea-9588-bef8d5079a67.png)

qui lui marche. Cf review-app à jour.

2020-09-07 13:43 UTC, celine-m-s approved these changes
Avec plaisir !
LGTM!

2020-09-07 14:53 UTC, merged