vgrange/allow_staff_to_create_users_again
betagouv/itou pull request #350
Opened 2020-08-28 09:39 UTC by vgrange

2020-08-28 09:40 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [le staff itou ne peut plus créer d'utilisateurs](https://trello.com/c/JXE8OChm/954-le-staff-itou-ne-peut-plus-cr%C3%A9er-dutilisateurs)

2020-08-28 15:02 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Je peux modifier ma structure existante pour lui donner un département non encore ouvert officiellement](https://trello.com/c/2ZZv1rRd/951-je-peux-modifier-ma-structure-existante-pour-lui-donner-un-d%C3%A9partement-non-encore-ouvert-officiellement)

2020-09-01 08:48 UTC, kemar commented on itou/users/models.py
> -        if not already_exists and hasattr(self, "email") and User.email_already_exists(self.email):
En fait, je pense qu'il s'est passé un truc dans une mise à jour de Django.

Auparavant si tu ne saisissais pas d'email dans l'admin, tu rentrais dans la méthode `save()` ci-dessus sans attribut  `email`. Du coup mon test se bornait à vérifier `hasattr(self, "email")`.

Désormais avec un email vide, tu rentres dans la méthode `save()` avec un attribut `email` vide (une chaîne vide). Et vu qu'il existe déjà un user dans notre DB avec un email vide (`juliencompteasupprimer`), le code considère qu'un email vide existe déjà `raise ValidationError(self.ERROR_EMAIL_ALREADY_EXISTS)`.

Du coup la seule chose à faire est de vérifier qu'il n'es pas vide :

```python
if not already_exists and hasattr(self, "email") and self.email != "" and User.email_already_exists(self.email):
```

Ou plus succinctement sans tester la chaîne vide :

```python
if not already_exists and hasattr(self, "email") and self.email and User.email_already_exists(self.email):
```

2020-09-01 08:50 UTC, kemar requested changes
Il n'y a qu'une condition à changer plutôt que toutes ces lignes que tu as rajoutées, c.f. mon comm.

2020-09-01 13:11 UTC, vgrange commented on itou/users/models.py
> -        if not already_exists and hasattr(self, "email") and User.email_already_exists(self.email):
cf mon dernier commit @kemar 

En fait le reste de mes changements doit rester car il résoud un *autre* bug qui était présent tout du long : quand un admin change l'email d'un user existant, aucun contrôle d'unicité n'était fait et donc on pouvait se retrouver avec plusieurs utilisateurs ayant le même email.  Je viens de checker la db de prod et on a 35 emails avec 2+ utilisateurs :-(

```
select email, count(*)
from users_user
group by email
order by count(*) desc
```

J'ai appliqué ta simplification + viré pas mal de commentaires.

2020-09-01 13:45 UTC, kemar approved these changes
LGTM

2020-09-01 13:45 UTC, kemar commented on itou/users/models.py
> -        if not already_exists and hasattr(self, "email") and User.email_already_exists(self.email):
Ah oui, tu as raison !

Comme quoi c'est définitivement souvent une mauvaise idée de ne pas gérer l'unicité au niveau de la DB.

2020-09-01 14:02 UTC, merged