WIP diagnostics
betagouv/itou pull request #363
Opened 2020-09-07 13:17 UTC by celine-m-s

2020-09-08 14:54 UTC, celine-m-s commented on itou/www/approvals_views/views.py
> +            raise ObjectDoesNotExist
Est-ce vraiment nécessaire ? Je pense qu'on peut s'en passer.

2020-09-08 15:00 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[2/2] Si le diagnostic est réalisé par une SIAE, celui-ci n'est valable que chez elle](https://trello.com/c/qWLqKyJ8/728-2-2-si-le-diagnostic-est-r%C3%A9alis%C3%A9-par-une-siae-celui-ci-nest-valable-que-chez-elle)

2020-09-08 15:00 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Employeur / Ce candidat a un pass IAE en cours de validité mais on me demande de valider les critères d'éligibilité pour valider son embauche](https://trello.com/c/7PpCT5d2/886-c1-employeur-ce-candidat-a-un-pass-iae-en-cours-de-validit%C3%A9-mais-on-me-demande-de-valider-les-crit%C3%A8res-d%C3%A9ligibilit%C3%A9-pour-valider)

2020-09-10 12:17 UTC, kemar requested changes
J'ai un peu de mal à suivre :)

Le truc c'est qu'il y a des nouvelles méthodes sur `EligibilityDiagnosisQuerySet()`, sur `JobApplication()` et sur `User()`.

Est-ce que tu n'aurais pas pu t'en sortir en centralisant des méthodes dans `EligibilityDiagnosis()` ?

Par exemple en pseudo-code :

```python
class EligibilityDiagnosis(models.Model):

    def is_valid():
        OUI si parcours en cours

    def is_valid_for_siae(siae):
        OUI
            si self.is_valid
            OU si dernier pas expiré ET dernier.author_kind == "Prescripteur"
            OU si dernier pas expiré ET dernier.author_siae == siae
```

2020-09-10 12:17 UTC, kemar commented on itou/job_applications/models.py
> +    def has_valid_siae_diagnosis(self):
Je mettrais juste `has_valid_diagnosis` ici car le nom laisse croire qu'on cherche un diagnostic valide effectué par la SIAE alors qu'on cherche dans ceux effectués par les prescripteurs ou par la SIAE destinataire.

2020-09-10 13:22 UTC, celine-m-s commented on itou/job_applications/models.py
> +        return self.job_seeker.latest_valid_approval_is_from_pe
Si le dernier agrément valide est de PE, on considère qu'un diagnostic a été effectué en dehors de la plateforme et que, par conséquent, il n'est pas nécessaire d'en refaire un. 
`has_valid_siae_diagnosis` renvoie donc `True` si un agrément valide existe.

2020-09-10 13:37 UTC, celine-m-s commented
Oui, c'est vrai que je pourrais regrouper des choses dans `EligibilityDiagnosis`. Je vais réfléchir à la question et proposer une seconde version.

2020-09-21 09:56 UTC, closed without merging