vgrange/store_conventions_and_financial_annexes
betagouv/itou pull request #372
Opened 2020-09-10 12:36 UTC by vgrange

2020-10-02 13:06 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Stockage et synchronisation des conventions SIAE et annexes financières dans la db ITOU + visibilité dans l'admin](https://trello.com/c/7JP0jdku/1088-stockage-et-synchronisation-des-conventions-siae-et-annexes-financi%C3%A8res-dans-la-db-itou-visibilit%C3%A9-dans-ladmin)

2020-10-05 08:44 UTC, ikarius commented on itou/siaes/factories.py
> +    siret_signature = factory.fuzzy.FuzzyText(length=13, chars=string.digits, prefix="1")
`length=13` à cause du `prefix` (ajouté pour faire 14) ?

2020-10-05 08:47 UTC, vgrange commented on itou/siaes/factories.py
> +    siret_signature = factory.fuzzy.FuzzyText(length=13, chars=string.digits, prefix="1")
Correct. Exactement comme pour `siae.siret`.

2020-10-05 14:08 UTC, ikarius commented on itou/siaes/migrations/0036_auto_20201002_1214.py
> +                    "is_active",
Ça ressemble plus à un champ logique non ?

2020-10-05 14:20 UTC, vgrange commented on itou/siaes/migrations/0036_auto_20201002_1214.py
> +                    "is_active",
Je n'ai pas compris ta remarque, et le fait qu'elle soit dans une migration me confuse un peu. Tu peux la reformuler directement dans le modèle stp?

2020-10-05 14:21 UTC, ikarius commented on itou/siaes/migrations/0036_auto_20201002_1214.py
> +                    "is_active",
Désolé, je reformule au niveau modèle

2020-10-05 14:25 UTC, ikarius commented on itou/siaes/models.py
> +    )
Ici, c'est mieux. 
C'est le `help_text` qui semble indiquer que ça pourrait être une `property` qui vérifierait si il y a une annexe financière valide ou pas.

2020-10-06 13:53 UTC, kemar requested changes
1ère passe terminée : relativement facile à lire, kudos. Pas mal de questions surtout.

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    exactly one and only one of them which has an ASP source.
> Several siaes can share the same SiaeConvention, however there is always exactly one and only one of them which has an ASP source.

C'est pas super clair pour moi, qu'est-ce que tu veux dire exactement ?

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    kind = models.CharField(verbose_name=_("Type"), max_length=4, choices=Siae.KIND_CHOICES, default=Siae.KIND_EI)
Pourquoi faut-il un champ `kind` sur `SiaeConvention` ? C'est super bizarre d'aller chercher une variable de classe (ici `Siae.KIND_CHOICES`) sur le modèle `Siae`…

De plus `Siae.KIND_CHOICES` englobe `KIND_GEIQ` etc. qui ne sont pas des structures conventionnées.

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    external_id = models.IntegerField(verbose_name=_("ID externe"), null=True, blank=True, db_index=True,)
Du coup, si placé sur ce modèle il n'y a plus aucune ambiguïté et ce champ pourrait se nommer `asp_id` ?

Pourquoi lui laisser la possibilité d'être vide ? Pour créer des objets `SiaeConvention` depuis l'admin ? (alors il faudrait un `created_by` optionnel)

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    STATE_CHOICES = ((state, state) for state in ALL_STATES)
Ici je propose de le faire un tout petit plus clean avec d'abord les `states` :

```python
STATE_VALID
STATE_PROVISIONAL
# etc.
```

Ensuite le `choices` :

```python
STATE_CHOICES
```

Ensuite les groupes :

```python
STATES_ALL
STATES_INACTIVE
STATES_ACTIVE
```

Comme ici [avec des choices](https://docs.djangoproject.com/en/3.1/ref/models/fields/#choices) : https://github.com/betagouv/itou/blob/9d7ef44c304788d4a40b2a7ce5afa89d79b0319f/itou/siaes/models.py#L93-L111

Ou tu peux aussi faire comme là [avec un _enumeration type_](https://docs.djangoproject.com/en/3.1/ref/models/fields/#enumeration-types) : https://github.com/betagouv/itou/blob/9d7ef44c304788d4a40b2a7ce5afa89d79b0319f/itou/prescribers/models.py#L81-L109

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    )
Je ne me souviens plus pourquoi `convention_number` n'est pas un champ du modèle `SiaeConvention` ? Du coup c'est bizarre de voir ce champ ici.

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +    )
Oui, même remarque pourquoi ne pas calculer ça à la volée via une méthode ou _property_ ?

2020-10-06 13:53 UTC, kemar commented on itou/siaes/models.py
> +        "SiaeConvention", on_delete=models.RESTRICT, blank=True, null=True, related_name="siaes",
Pourquoi tu ne `CASCADE` pas lors d'un _delete_ ?

2020-10-06 13:53 UTC, kemar commented on itou/utils/validators.py
> +        raise ValidationError(_("Numéro de convention incorrect."))
Aucun de tes validateurs n'est testé https://github.com/betagouv/itou/blob/748e839e8f8e83060aab76c39cd4361251585f44/itou/utils/tests.py#L277

2020-10-06 13:53 UTC, kemar commented on itou/siaes/factories.py
> +MAIN_EXTERNAL_ID = 18
Il faut absolument une constante _harcodée_ ?

2020-10-06 13:53 UTC, kemar commented on itou/siaes/management/commands/_import_siae/vue_af.py
> +    df["number"] = df.number_prefix + "A" + df.renewal_number.astype(str) + "M" + df.modification_number.astype(str)
OMG

2020-10-06 16:02 UTC, vgrange reviewed
Application des suggestions.

2020-10-07 15:59 UTC, kemar commented on itou/siaes/models.py
> +        "SiaeConvention", on_delete=models.RESTRICT, blank=True, null=True, related_name="siaes",
OK compris

2020-10-07 16:01 UTC, kemar commented on itou/siaes/models.py
> +    )
Alors c'est exactement ce que tu viens d'expliquer qu'il faudrait mettre en commentaire dans le code au dessus de `is_active` pour expliquer pourquoi ça ne peut pas être une `property`.

2020-10-07 16:03 UTC, kemar commented on itou/siaes/models.py
> +    )
Wow je comprends maintenant… mais je comprends pas pourquoi ils peuvent avoir des numéros de conventions différents, c'est fou ça ! C'est pas une anomalie ASP ?

2020-10-08 13:40 UTC, vgrange commented on itou/siaes/models.py
> +    )
Une structure ASP peut avoir plusieurs conventions ASP. C'est pas choquant. Par exemple deux conventions qui se suivent dans le temps.

On a choisi d'abstraire cela en considérant pour simplifier qu'une structure ITOU a seulement *une* convention ITOU.

2020-10-08 13:47 UTC, vgrange commented on itou/siaes/models.py
> +    )
```
    # Ideally convention.is_active would be a property and not a field.
    # However we have to live with the fact that some of ASP's data is
    # randomly weeks or even months late, as DIRECTTE sometimes take so
    # much time to input the data of their department into the ASP extranet.
    # Thus our staff will regularly need to manually reactivate a convention
    # for weeks or months until we get up-to-date data for it.
    # This is why this field is needed. It is manipulated only by:
    # 1) our staff
    # 2) the `import_siae.py` script
    is_active = models.BooleanField(
```

2020-10-08 15:13 UTC, merged