vgrange/fix_fixtures_after_convention_refactoring
betagouv/itou pull request #429
Opened 2020-10-19 14:11 UTC by vgrange

2020-10-19 14:53 UTC, celine-m-s requested changes
C'est top, j'allais justement travailler sur la démo ! Est-ce que les fixtures peuvent bien être utilisées sur la demo et sont anonymisées en conséquence ?

2020-10-19 14:53 UTC, celine-m-s commented on Makefile
> +	docker exec -e PGPASSWORD='password' -ti itou_postgres psql -h postgres -U postgres -c 'CREATE DATABASE itou OWNER itou'
Désolée mais j'ai un peu de mal à comprendre l'intérêt de cette commande. Pourquoi ne pas tout simplement faire un `docker-compose down -v` puis `make run` ? Cela supprime la DB et la recrée.

2020-10-19 14:53 UTC, celine-m-s commented on Makefile
> +# make --silent django_admin COMMAND="dumpdata siaes.Siae" > itou/fixtures/django/02_siaes.json
:+1: 
Merci :)

2020-10-19 14:59 UTC, ikarius commented on Makefile
> +# make --silent django_admin COMMAND="dumpdata siaes.Siae" > itou/fixtures/django/02_siaes.json
nice! la fixture `02_siaes.json` passe crème maintenant

2020-10-19 14:59 UTC, ikarius approved these changes
LGTM

2020-10-19 15:12 UTC, kemar commented on Makefile
> +	docker exec -e PGPASSWORD='password' -ti itou_postgres psql -h postgres -U postgres -c 'CREATE DATABASE itou OWNER itou'
Il profite de mon absence pour éditer le Makefile :D

2020-10-19 15:27 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Les fixtures sont cassées](https://trello.com/c/iWYC4vFN/1139-les-fixtures-sont-cass%C3%A9es)

2020-10-20 09:43 UTC, vgrange commented on Makefile
> +	docker exec -e PGPASSWORD='password' -ti itou_postgres psql -h postgres -U postgres -c 'CREATE DATABASE itou OWNER itou'
Nickel ta commande Céline, je remplace.

2020-10-20 09:49 UTC, vgrange commented
@celine-m-s 

A propos de l'anonymité des fixtures

- les emails des siaes semblent avoit été générés par faker ou autre - donc OK
- les téléphones des siaes sont réels :-(
- prescribers : pareil, emails ok mais phones réels
- le reste : ok

2020-10-20 09:54 UTC, merged