vgrange/populate_metabase_with_all_iae_data
betagouv/itou pull request #432
Opened 2020-10-20 14:58 UTC by vgrange

2021-01-27 09:46 UTC, celine-m-s approved these changes
LGTM
Pour info, je n'ai pas testé mais tu as déjà dû le faire plein de fois alors ce n'est pas forcément la peine. Beau boulot en tous cas !:clap:

2021-01-27 09:46 UTC, celine-m-s commented on itou/metabase/management/commands/populate_metabase_fluxiae.py
> +- esm = FIXME
esm = FIXME ?

Un petit oubli peut-être ? :)

2021-01-27 10:36 UTC, kemar requested changes
Besoin d'une clarification sur l'utilisation de `sqlalchemy` mais le reste est OK.

2021-01-27 10:36 UTC, kemar commented on itou/metabase/management/commands/_database.py
> +PG_ENGINE = create_engine(
Oh wait… what?  Même avec ce commentaire je ne comprends pas pourquoi on a besoin de `sqlalchemy` ? Est-ce que tu peux clarifier ? Est-ce `pandas` qui ne peut pas fonctionner autrement ?

2021-01-27 16:47 UTC, ikarius commented on itou/metabase/management/commands/populate_metabase_fluxiae.py
> +        for column_name in df.columns.tolist():
Pour le coup, tu seras vraiment sur :)

2021-01-27 17:26 UTC, ikarius approved these changes
LGTM
On commence à parler de sessions dev2dev...
En tant qu'utilisateur des fonctionnalités classiques de pandas / numpy
et étant amené à faire des extractions et des manips de df, je suis assez preneur d'une session dev2dev sur le sujet

2021-01-28 14:38 UTC, vgrange commented on itou/metabase/management/commands/_database.py
> +PG_ENGINE = create_engine(
Nouveau commentaire :

```
"""
Required for using pandas.to_sql method in `populate_metabase_fluxiae.py`.

As stated in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html
pd.to_sql expects a sqlalchemy engine, not our usual psycopg2 engine.
So we have to use sqlalchemy just for this purpose ¬_¬

See also https://stackoverflow.com/questions/23103962/how-to-write-dataframe-to-postgres-table
"""
PG_ENGINE = create_engine(
```

En fait avec du bricolage je pourrais peut-être arriver à m'en sortir avec `psycopg2` sans `sqlalchemy` mais cela va me prendre du temps, ça fera plus de code compliqué, ce n'est pas sûr que ça fonctionne au bout du compte, et il y a un risque que la performance en patisse (le script durant déjà 2h+) et que du coup je doive passer encore plus de temps à retrouver la performance initiale.

Alors que là un simple `df.to_sql` et `sqlalchemy` et pouf ça marche.

Verdict? @kemar

2021-01-28 14:44 UTC, kemar commented on itou/metabase/management/commands/_database.py
> +PG_ENGINE = create_engine(
Ok @vgrange ça serait bien de mettre ce lien en commentaire du coup, non ? https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#sql-queries

> Database abstraction is provided by SQLAlchemy if installed
> If SQLAlchemy is not installed, a fallback is only provided for sqlite

2021-01-28 16:06 UTC, merged