Désactivation des membres pour les SIAE et les organisations de prescripteurs
betagouv/itou pull request #433
Opened 2020-10-21 17:47 UTC by ikarius

TBD

2020-11-04 15:18 UTC, kemar requested changes
Les retours sont surtout de surface sauf le kill de session dont il faut qu'on parle.

2020-11-04 15:18 UTC, kemar commented on itou/www/prescribers_views/views.py
> +                kill_sessions_for_user(membership.user.pk)
Je comprends pas pourquoi tu vas _kill_ les sessions ? À chaque requête HTTP le code va passer dans le middleware et voir qu'il ne fait plus partie de l'org => c'est là qu'il faut faire quelque chose je pense !

2020-11-04 15:18 UTC, kemar commented on itou/utils/sessions.py
> +    for session in Session.objects.all():
Ouais si on peut éviter de scanner toute la table pour chaque manip je veux bien éviter. On en parle !

2020-11-04 15:18 UTC, kemar commented on itou/www/prescribers_views/tests.py
> +        # User must have been notified of deactivation (we're human after all)
> we're human after all

![Robot-no-meme](https://user-images.githubusercontent.com/281139/98128408-31029280-1eb8-11eb-952c-ea106372ea4f.jpg)

2020-11-04 15:18 UTC, kemar commented on itou/www/siaes_views/views.py
> +    deactivated_members = (
Elle n'est plus utilisée dans le template cette _query_, tu peux la dégager.

2020-11-04 15:18 UTC, kemar commented on itou/www/siaes_views/views.py
> +        raise SuspiciousOperation
`raise Http404()` OSEF

2020-11-04 15:18 UTC, kemar commented on itou/www/siaes_views/views.py
> +        raise SuspiciousOperation
Ou alors un [re_path](https://docs.djangoproject.com/en/3.1/ref/urls/#re-path) dans tes routes avec les valeurs autorisées dans une regex et t'as même plus à checker.

2020-11-10 09:02 UTC, ikarius commented on itou/prescribers/models.py
> +        return self.active_members.filter(prescribermembership__is_admin=True, prescribermembership__organization=self)
tout à fait

2020-11-10 09:04 UTC, ikarius commented on itou/prescribers/models.py
> +        assert user
La plupart des `assert` que je laisse sont des résidus du process de dev. 
A discuter, mais au final je les trouve pas si idiomatiques et utiles en production (si la couverture de test est suffisante).
En plus, c'est pas une portion très critique

2020-11-10 09:08 UTC, ikarius commented on itou/siaes/migrations/0038_auto_20201019_1007.py
> +# Generated by Django 3.1 on 2020-10-19 08:07
J'ai déjà fait le squash, mais j'ai quand même laissé les fichiers de migrations originels.
(j'ai du lire ça dans la doc Django, c'est assez logique et prudent)
Mais on peut le faire tout de suite si tout est ok, ça évite de le faire plus tard et de faire une boulette.

2020-11-10 09:24 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                                {% translate "Voir / inviter / retirer des collaborateurs" %}
Oui, "retrait" ça fait un peu Hitman

2020-11-10 09:27 UTC, ikarius commented on itou/templates/prescribers/email/new_member_activation_email_body.txt
> +- {% translate "Nom" %}  : {{ siae.display_name }}
arg, `rg` à la rescousse

2020-11-10 09:35 UTC, ikarius commented on itou/templates/prescribers/email/add_admin_email_body.txt
> +Un administrateur peut ajouter ou retirer:
`rg '[[:alpha:]]:' -g '*.txt'`

2020-11-10 09:37 UTC, ikarius commented on itou/templates/prescribers/email/add_admin_email_body.txt
> +{% translate "Vous étes administrateur d'une structure sur la Plateforme de l'inclusion" %}
QWERTY UK mon amour

2020-11-10 09:44 UTC, ikarius commented on itou/templates/prescribers/email/add_admin_email_body.txt
> +- {% translate "Nom" %}  : {{ organization.display_name }}
Punaise, fallait la voir celle-là

2020-11-10 10:40 UTC, ikarius commented on itou/templates/prescribers/members.html
> +                        {% if member.user in organization.active_admin_members %}
Super intéressant et tu as raison. 
Les appels à la `property` `active_members` effectuent un call DB systématiquement. 
Je corrige sur cette partie et sur la partie SIAE

2020-11-10 10:54 UTC, ikarius commented on itou/templates/prescribers/members.html
> +                                {% if member.user != user and user in organization.active_admin_members %}
Oui, redondant

2020-11-10 11:01 UTC, ikarius commented on itou/templates/siaes/email/new_member_deactivation_email_body.txt
> +{% translate "Si vous estimez qu'il peut s'agir d'une erreur, contactez un des administrateurs cette structure sur la Plateforme de l'inclusion." %}
Pas forcément via la plateforme, via email par ex si il connait un des admins

2020-11-10 11:26 UTC, ikarius commented on itou/www/siaes_views/views.py
> +        raise SuspiciousOperation
une 400 on était sur que quelque chose de pas normal se passe, ça ne doit pas arriver (sécu).
Mais je préfère encore mieux le `re_path`, je modifie avec les tests correspondants.

2020-11-11 15:10 UTC, vgrange requested changes
Gros boulot et gros morceau, bien joué Fred. J'ai quelques remarques, la plus importante c'est sur une faille potentielle des querysets qui ferait qu'un membre actif d'une structure serait également considéré toujours actif sur toutes ses autres structures.

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        guest = siae.members.all()[1]
Peut-être que `admin, guest = siae.members.all()` marche.

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        # Whereever guest land should give a 200 OK
`s/whereever/wherever/`

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        # Whereever guest land should give a 200 OK
`s/land/lands/`

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        # Check reponse context, only one SIAE should remain
`s/reponse/response/`

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        # Check reponse context, only one SIAE should remain
and then they were none

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/tests.py
> +        guest = siae.members.all()[1]
ou sinon `admin, guest = list(siae.members.all())`

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/views.py
> +    user_is_admin = user in siae.active_admin_members
`siae.has_admin(user)`

2020-11-11 15:10 UTC, vgrange commented on itou/www/siaes_views/views.py
> +                kill_sessions_for_user(membership.user.pk)
En fait je comprends pas bien ce besoin de vouloir supprimer les sessions. Si notre middleware fait bien son job et bloque les utilisateurs non légitimes c'est bon non?

2020-11-11 15:16 UTC, ikarius commented on itou/www/siaes_views/views.py
> +                kill_sessions_for_user(membership.user.pk)
J'ai eu des cas bizarres, ou j'ai eu des états "flaky". 
Mais plutôt que de faire ça j'aurais du chercher une solution via le middleware.
Je n'ai pas reproduit ce cas depuis, et le kill switch a été supprimé depuis (?!)

2020-11-11 15:18 UTC, ikarius commented on itou/www/siaes_views/views.py
> +                kill_sessions_for_user(membership.user.pk)
My bad, je ne l'avais supprimé que pour les prescripteurs. Fixed.

2020-11-11 15:20 UTC, ikarius commented on itou/www/prescribers_views/views.py
> +    user_is_admin = user in organization.active_admin_members
Carrément. Merci

2020-11-11 15:21 UTC, ikarius commented on itou/www/prescribers_views/tests.py
> +        self.client.logout()
Non...
Il y avait qq chose aprés, j'ai mal nettoyé

2020-11-11 15:28 UTC, ikarius commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Mais oui, mais ça y était avant et je l'ai viré !
En plus, c'était un tes tests qui m'avait rappelé à l'ordre

2020-11-11 17:16 UTC, kemar commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Je ne voulais pas intervenir mais je trouve votre conversation étonnante.

L'ORM de Django implémente l'*Active Record pattern* en ce qui concerne les classes qui représentent un modèle.

En clair : une instance de modèle Django est toujours liée à une seule ligne de la table correspondante.

Donc `self` dans les méthodes implique **toujours** un filtre automatique sur la ligne en question : tu n'as pas besoin d'être redondant en précisant à nouveau `prescribermembership__prescriberorganization=self`.

Il suffit de vérifier le SQL généré par l'ORM sans cet ajout :

```python
org = PrescriberOrganization.objects.first()
str(org.active_members.query)
```

```sql
SELECT *
FROM "users_user"
INNER JOIN "prescribers_prescribermembership" ON ("users_user"."id" = "prescribers_prescribermembership"."user_id")
WHERE (
    "prescribers_prescribermembership"."organization_id" = 1
    AND "users_user"."is_active"
    AND "prescribers_prescribermembership"."is_active"
)
```

2020-11-11 17:24 UTC, celine-m-s requested changes
Gros gros boulot ! Bravo :clap: 
Par contre je ne sais pas si tu as bien commité certains changements car j'ai retrouvé des double espaces un peu partout. 
Concernant les gabarits, je propose de supprimer tout le code dupliqué en créant des _partials_ . Ce sera bien plus pratique à maintenir.
Il reste encore à résoudre le souci de la session en cours (scan de la DB).

2020-11-11 17:24 UTC, celine-m-s commented on itou/utils/perms/context_processors.py
> +            memberships = current_user.prescribermembership_set.select_related("organization").filter(is_active=True)
On ne mettrait pas le filtre avant le `select_related` ?

2020-11-11 17:24 UTC, celine-m-s commented on itou/utils/perms/middleware.py
> +                                "nouveau sur la Plateforme."
:+1:

2020-11-11 17:24 UTC, celine-m-s commented on itou/utils/perms/middleware.py
> +                if user.is_prescriber_with_org:
Ah, ça explique le fait qu'on ne filtre pas par `user.is_active`.

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/invitations_views/forms.py
> +        # even if they already received and invitation
Petite faute de frappe : an/~and~ .

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/invitations_views/forms.py
> +        # even if they already received and invitation
Idem : an/~and~

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/invitations_views/tests/tests_prescriber_organization.py
> +        # Invite user (the revenge)
https://www.youtube.com/watch?v=MVrpEcpe6jE

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/invitations_views/tests/tests_prescriber_organization.py
> +        )
Hum... Le dictionnaire me semble identique à `self.post_data`, alors pourquoi le mettre à jour ?

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/invitations_views/tests/tests_siae.py
> +        invitation_query = self.invitations_model.objects.filter(siae=self.siae)  # .order_by("-created_at")
La fin de la requête est commentée. Un oubli ? :wink:

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/prescribers_views/views.py
> +        organization.prescribermembership_set.filter(is_active=True)
`organization.active_members` ?

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/siaes_views/tests.py
> +        # Whereever guest land should give a 200 OK
Idem dans l'autre test (version prescripteur).

2020-11-11 17:24 UTC, celine-m-s commented on itou/www/siaes_views/views.py
> +    members = siae.siaemembership_set.filter(is_active=True).select_related("user").all().order_by("joined_at")
`siae.active_members` ?

2020-11-11 19:12 UTC, vgrange commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Je viens de retester `siae.active_admin_members` sans le `siaemembership__siae=self` et ça fait bien péter les tests. Je creuse davantage vendredi pour la conclusion. Suspense!

2020-11-11 19:29 UTC, vgrange commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Ok je pense avoir trouvé et c'est sacrément tordu. Fix, simplification et débrief vendredi après-midi côté siae. En attendant tu peux ignorer mes remarques @ikarius car je pense que ton code est ok sans ma suggestion. Néanmoins je te recommande d'ajouter un test similaire à `test_active_admin_members` côté prescripteur pour être tranquille. Ce souci côté siae m'avait fait des noeuds au cerveau. Conclusion vendredi après-midi.

2020-11-11 20:00 UTC, kemar commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Ok compris.

Le problème se pose quand on commence à chaîner les *querysets* car `filter(A, B)` et `filter(A).filter(B)` se comportent de façon différente avec les `ManyToManyField` et `ForeignKey` :

> https://docs.djangoproject.com/en/3.1/topics/db/queries/#spanning-multi-valued-relationships

Dans `Siae` on voit bien qu'on chaîne depuis une autre `property` (`active_members`) ce qui donne un `filter(A).filter(B)` et des *inner joins* chelou :

```python
@property
def active_admin_members(self):
    return self.active_members.filter(siaemembership__is_siae_admin=True, siaemembership__siae=self)
```

Du coup je comprends pourquoi il faut répéter `prescribermembership__prescriberorganization=self` mais il faudrait l'expliquer clairement dans un commentaire pour le suivant.

On pourrait être plus propre en combinant des objets `Q` plutôt que des `filters` mais c'est pas urgent, cette PR traîne depuis longtemps.

Ailleurs sur le sujet :

- https://djangotricks.blogspot.com/2018/05/queryset-filters-on-many-to-many-relations.html
- https://hacksoft.io/django-filter-chaining/

2020-11-12 08:47 UTC, ikarius commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Je résume les différents points:
- sans la référence à `self`,  les tests claquent
- ça doit être uniforme sur les prescripteurs ET les SIAE (je pense à un pb de commit de mon coté)
- cette PR traîne trop
- merci pour les retours techniques, je vais les reprendre plus en profondeur

2020-11-12 09:06 UTC, kemar commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Tu as 2 options **rapides** pour les cas où des `querysets` sur des `ManyToManyField` ou `ForeignKey` sont **chaînés** :

1. laisser une re-référence à `self` en chaînant depuis la *property* `active_members`
    ```python
    @property
    def active_admin_members(self):
        return self.active_members.filter(prescribermembership__is_admin=True, prescribermembership__prescriberorganization=self)
    ```
1. passer au _REPEAT YOURSELF_ en passant toujours par `self.members`
    ```python
    @property
    def active_members(self):
        return self.members.filter(is_active=True, prescribermembership__is_active=True)

    @property
    def active_admin_members(self):
        return self.members.filter(is_active=True, prescribermembership__is_active=True, prescribermembership__is_admin=True)
    ```

---

L'option 2 est la plus "propre" en termes d'*inner joins* générés par l'ORM.

L'option 3 est d'utiliser des objets `Q` pour pouvoir chaîner mais demande plus de temps.

J'espère que c'est clair ?

2020-11-12 09:39 UTC, ikarius commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Ça l'est, merci. J'avais pris la 2. Je vérifie par des tests

2020-11-12 10:06 UTC, ikarius commented on itou/prescribers/models.py
> +        related_name="prescriber_organization_membership_updated_by",
J'admets, le nom est pourri

2020-11-12 10:24 UTC, ikarius commented on itou/prescribers/models.py
> +        related_name="prescriber_organization_membership_updated_by",
Pareil pour les SIAE:
`updated_siaemembership_set`

2020-11-12 10:32 UTC, ikarius commented on itou/prescribers/models.py
> +        self.updated_at = timezone.now()
Juste. Merci

2020-11-12 13:36 UTC, ikarius commented on itou/siaes/models.py
> +        return self.members(is_active=True, siaemembership__is_active=False)
Voir discussion plus haut.
Je rajoute 2 tests pour border.

2020-11-12 13:54 UTC, ikarius commented on itou/users/models.py
> +        return self.is_siae_staff and self.siaemembership_set.filter(is_active=True).exists()
Ajout d'un commentaire, pour clarifier.
Par actif, j'entendais qui "a un rattachement actif", pas `user.is_active`

2020-11-12 13:57 UTC, ikarius commented on itou/www/prescribers_views/tests.py
> +        Lambda users can't update admin members
C'est bien ça, commentaire modifié

2020-11-12 14:14 UTC, ikarius commented on itou/www/siaes_views/tests.py
> +        guest = siae.members.all()[1]
la déconstruction fonctionne effectivement

2020-11-12 14:33 UTC, ikarius commented on itou/templates/prescribers/members.html
> +</div>
J'ai trouvé ça déroutant de ne jamais voir avec quel compte/user/structure on travaillais

2020-11-12 15:23 UTC, ikarius commented on itou/templates/prescribers/email/new_member_activation_email_subject.txt
> +{% blocktranslate %}[Réactivation] Vous avez été ajouté en tant que membre d'une organisation{% endblocktranslate %}
Je le mets avec les templates génériques

2020-11-12 15:31 UTC, ikarius commented on itou/templates/prescribers/email/remove_admin_email_subject.txt
> +{% endblock %}
Done.
Les templates sont dans `itou/templates/common/emails`

2020-11-12 16:46 UTC, ikarius commented on itou/templates/siaes/deactivate_member.html
> +{% endblock %}
Non, c'est juste.
Tout est factorisé maintenant

2020-11-12 16:46 UTC, ikarius commented on itou/templates/siaes/members.html
> +{% with active_admin_members=siae.active_admin_members %}
Done

2020-11-12 18:15 UTC, ikarius commented on itou/templates/siaes/deactivate_member.html
> +{% endblock %}
Done

2020-11-12 18:15 UTC, ikarius commented on itou/templates/siaes/members.html
> +{% with active_admin_members=siae.active_admin_members %}
Done

2020-11-12 18:18 UTC, ikarius commented on itou/www/invitations_views/tests/tests_siae.py
> +        invitation_query = self.invitations_model.objects.filter(siae=self.siae)  # .order_by("-created_at")
Oui, à virer ...

2020-11-12 18:25 UTC, ikarius commented on itou/www/prescribers_views/views.py
> +        organization.prescribermembership_set.filter(is_active=True)
Euh non ,c'est les `memberships` actives

2020-11-12 18:25 UTC, ikarius commented on itou/www/siaes_views/views.py
> +    members = siae.siaemembership_set.filter(is_active=True).select_related("user").all().order_by("joined_at")
Idem plus-haut (memberships)

2020-11-12 18:26 UTC, ikarius commented on itou/utils/perms/context_processors.py
> +            memberships = current_user.prescribermembership_set.select_related("organization").filter(is_active=True)
oui

2020-11-13 15:07 UTC, vgrange commented on itou/prescribers/models.py
> +        return self.members.filter(is_active=True, prescribermembership__is_active=True)
Merci au vacancier d'avoir creusé et éclairci tout ça :-)

J'ai rajouté un commentaire et un pointeur vers ce thread précieux à l'instant : https://github.com/betagouv/itou/commit/e49e9b5635983802af48cc9ee8bfce2a78e63269

2020-11-16 11:22 UTC, celine-m-s commented on itou/templates/siaes/deactivate_member.html
> +{% endblock %}
Merci @ikarius , c'est bien plus clair !! :clap:

2020-11-16 11:25 UTC, celine-m-s commented on itou/www/siaes_views/views.py
> +    members = siae.siaemembership_set.filter(is_active=True).select_related("user").all().order_by("joined_at")
Pardon, j'avais les yeux qui se croisaient.

2020-11-16 11:26 UTC, celine-m-s approved these changes
LGTM!!
Bravooooo ! 
Gros boulot ! :clap: :clap: :clap: :beers: 
PS : :warning: Attention, les tests plantent dans la CI.

2020-11-16 11:35 UTC, celine-m-s commented
Je viens de faire des tests manuels sur la revue et tout fonctionne très bien ! Bravoooo ! 
Une dernière petite pacotille : il manque le nom de la structure dans le sujet des mails.
![image](https://user-images.githubusercontent.com/6150920/99247974-0bef1780-2808-11eb-9aca-9880da6ad8ed.png)

2020-11-17 16:33 UTC, merged