vgrange/allow_siae_admin_users_to_manage_their_convention
betagouv/itou pull request #435
Opened 2020-10-23 08:32 UTC by vgrange

2020-10-23 09:03 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1/2] en tant qu'employeur je n'ai pas d'interface pour visualiser et corriger mes annexes financières](https://trello.com/c/CgVEqj5p/1152-c1-2-en-tant-quemployeur-je-nai-pas-dinterface-pour-visualiser-et-corriger-mes-annexes-financi%C3%A8res)

2020-11-16 17:13 UTC, celine-m-s requested changes
Comme discuté entre nous sur Slack, je trouve qu'il y a trop de code dans cette PR pour que je puisse la revoir posément. On aurait dû la découper en plus petites parties.

Voici quelques points dont nous pourrons parler avec grand plaisir jeudi.

Concernant le formulaire de sélection, je pense qu'on aurait pu le présenter autrement afin de simplifier la vie de l'utilisateur. En effet, je suppose que les administrateurs de structure ne connaissent pas par coeur le numéro d'AF en cours. Or la liste déroulante ne donne que peu d'infos...
Instinctivement, j'aurais cherché le bouton "Activer" dans la liste des annexes financières, à droite de chaque annexe, ainsi que les dates de début et de fin associées. Comme les boutons d'action "Ajouter en tant qu'administrateur" ou "Retirer de la structure" de [la PR de Fred](https://github.com/betagouv/itou/pull/433).

Concernant le comportement global, il me semble que ces structures conditionnelles ajoutent trop de complexité. J'aurais plutôt préconisé une vérification dans un _middleware_ puis une redirection vers la bonne page (sélection de l'AF ou message d'erreur invitant à contacter l'admin de la structure). 

La gestion des droits admin / pas admin ajoute pas mal de code et ne concerne pas directement cette fonctionnalité. C'est un prérequis qui aurait dû faire l'objet d'une PR en soi pour être revue de manière isolée et sereine. Là, tout se mélange et je suis un peu perdue.  J'aurais aimé avoir une discussion plus en amont pour parler architecture.

2020-11-16 17:13 UTC, celine-m-s commented on itou/www/dashboard/views.py
> +            can_show_financial_annexes = siae.has_admin(request.user)
Voir mon commentaire plus haut. A mon avis, toute cette logique devrait être dans le middleware avec un gros redirect vers la page de sélection de la SIAE.

2020-11-16 17:13 UTC, celine-m-s commented on itou/www/siaes_views/forms.py
> +    )
Je m'arrête ici car je n'ai plus le cerveau pour revoir la suite... Désolée...

2020-11-18 15:50 UTC, kemar requested changes
Je voudrais tenter de simplifier le côté permissions de cette PR.

Je ne me suis pas penché sur l'interface et son fonctionnement. J'aimerais une validation fonctionnelle des intras avant de passer du temps sur cet aspect des choses.

2020-11-18 15:50 UTC, kemar commented on itou/siaes/models.py
> +    def is_active_or_in_grace_period(self):
Je suis plutôt pour avoir des méthodes ou _properties_ qui font une seule chose à la fois :

```python
siae.is_active() or siae.in_grace_period()
```

2020-11-18 15:50 UTC, kemar commented on itou/siaes/models.py
> +            # the siae is over its grace period.
Je suis pas certain de bien capter dans quel cas ça peut se produire ? C'est pour une SIAE _user created_ ?

2020-11-18 15:50 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                {% trans "Veuillez dès que possible régulariser votre situation en sélectionnant une annexe financière valide" %}
Quand tu navigues avec un lecteur d'écran de lien en lien tu n'as pas de contexte quand le curseur passe sur "ici" : le lecteur d'écran va juste énoncer "ici". Alors que si tu mets le lien sur une partie de phrase qui permet de comprendre le contexte, c'est tout de suite plus accessible.

2020-11-18 15:50 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                            Aucune action possible.
Quel intérêt d'afficher "Aucune action possible" ?

2020-11-18 15:50 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                    {% if user_is_siae_admin and current_siae.is_active %}
Je trouve ça encore assez lisible pour le coup.

2020-11-18 15:50 UTC, kemar commented on itou/utils/perms/middleware.py
> +                    )
Cette suite de conditions est très bizarre. Je comprend qu'on veuille privilégier une structure active mais en lisant ça on a l'impression que les deux premières conditions sont redondantes : 1ère active ou (1ère active ou en période de grâce).

2020-11-18 15:50 UTC, kemar commented on itou/utils/perms/siae.py
> +    return decorator
Ce fichier de perms est difficile à comprendre. Je veux bien qu'on en discute pour comprendre les besoins et envisager une solution plus simple.

J'ai l'impression qu'on aurait pu s'en sortir en détectant un ou deux cas spéciaux dans un middleware et en laissant le reste intact.

Là, alors qu'au final il y a peu de nouvelles vues, tu as du repasser sur quasi toutes les vues déjà existantes pour modifier les permissions.

On es tous perdants :

- en temps de code
- en temps de revue
- en complexité

2020-11-18 15:50 UTC, kemar commented on itou/www/apply/views/list_views.py
> +@require_current_siae_is_active_or_in_grace_period()
Je suis d'accord. Parlons-en pour trouver une alternative plus simple.

2020-11-18 16:53 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +                    {% if user_is_siae_admin and current_siae.is_active %}
C'est lisible en soi mais ça ajoute une condition avant chaque lien à afficher.

2020-12-04 14:30 UTC, closed without merging