Notifications - alternative avec un champ JSONB
betagouv/itou pull request #444
Opened 2020-11-04 11:14 UTC by celine-m-s

2020-11-04 16:27 UTC, celine-m-s commented on itou/siaes/models.py
> +    return {"unsubscribed": []}
J'aurais préféré mettre cette fonction dans `SiaeMembership` mais je n'ai pas trop trouvé comment l'appeler ensuite dans la variable de classE.

2020-11-05 07:57 UTC, kemar commented on itou/users/models.py
> +    notifications = models.JSONField(verbose_name=("Préférences de notification"), default=notifications_default)
En réfléchissant hier soir je pense que ça marche pas de mettre ce champs sur `User`. A priori ça ne permet pas d'avoir des notifications différentes par structure : je veux les notifs des candidatures de la structure A, mais pas celles de B ni de C.

De plus il faut (peut-être) anticiper une granularité au niveau de la fiche de poste. Je veux une notif pour telle fiche de poste, pas pour l'autre.

2020-11-05 17:27 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [(C1) je veux désactiver les notifications e-mails de réception d'une candidature](https://trello.com/c/HYX0w8sv/1145-c1-je-veux-d%C3%A9sactiver-les-notifications-e-mails-de-r%C3%A9ception-dune-candidature)

2020-11-11 15:32 UTC, ikarius commented on itou/job_applications/notifications.py
> +        return self.siae.siaemembership_set.filter(self.subscribed_lookup, user__is_active=True).values_list(
Dans le filtre, `user__is_active` ne sera pas suffisant.
La PR 433 ajoute un champ `is_active` sur l'objet `membership`

2020-11-11 15:33 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        return self.siae.siaemembership_set.filter(self.subscribed_lookup, user__is_active=True).values_list(
Merci pour le rappel @ikarius ! :)

2020-11-11 15:58 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        return self.siae.siaemembership_set.filter(self.subscribed_lookup, user__is_active=True).values_list(
cf https://github.com/betagouv/itou/pull/433/files#diff-ed4f79f2f0786c08bd1fe718b21a561b5b2aa96e106e9f41c7c36ecfe98167a3R221

2020-11-11 16:10 UTC, ikarius approved these changes
LGTM
Quelques remarques de surface.
J'aime beaucoup:
- l'aspect déclaratif (on "enrobe" de notifications que ce qui est utile).
- pas besoin de dépendances
- la concision du code !

Faudra voir aussi une partie admin pour la gestion des notifications si besoin (et si cette piste est choisie)

2020-11-11 16:10 UTC, ikarius commented on itou/utils/notifications.py
> +from itou.job_applications.notifications import NewJobApplicationSiaeEmailNotification  # noqa: ignore=E402
D'ou le `noqa`: nice !

2020-11-11 16:10 UTC, ikarius commented on itou/utils/notifications.py
> +
Pourquoi cette vérification ?

2020-11-11 16:11 UTC, ikarius commented on itou/job_applications/notifications.py
> +        return self.siae.siaemembership_set.filter(self.subscribed_lookup, user__is_active=True).values_list(
Merci, j'ai toujours du mal à faire les liens github (doigts palmés)

2020-11-18 13:27 UTC, kemar requested changes
J'ouvre la discussion sur 2 points qui me semblent importants.

2020-11-18 13:27 UTC, kemar commented on itou/utils/notifications/base_class.py
> +        return self.__class__.__name__
Ça va te renvoyer du _CamelCase_. Même si c'est pour stocker du JSON (et qu'il n'y a aucune obligation), la convention en Django et Django Rest Framework c'est du _snake_case_.

Je suis partisan d'un élément de classe qui porterait le nom comme un attribut ou une _property_ :

```python
@property
    def name(self):
        return "new_job_application_siae_email"
```

Avantage, tu peux être flexible si tu dois passer à des notifs au niveau d'un objet (par exemple une notif pour les candidatures à tel poste et pas un autre :

```python
@property
    def name(self):
        return f"new_job_application_{self.object.id}_siae_email"
```

2021-01-19 10:16 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] En tant qu'utilisateur, je veux me désabonner de certaines notifications qui me sont envoyées automatiquement.](https://trello.com/c/9Xy1srfR/1177-c1-en-tant-quutilisateur-je-veux-me-d%C3%A9sabonner-de-certaines-notifications-qui-me-sont-envoy%C3%A9es-automatiquement)

2021-01-21 13:14 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        return self.__class__.__name__
Tu as tout à fait raison ! Je viens de modifier cet aspect.

2021-01-21 14:16 UTC, celine-m-s commented on itou/utils/notifications/list.py
> +from django.utils.module_loading import autodiscover_modules
J'avais envie d'utiliser `autodiscover_modules`, tout simplement. :smile: 

Blague à part, je me suis laissée entraîner par mon envie d'avoir un endroit où recenser toutes les notifications. Quand j'ai découvert `autodiscover_modules`, j'ai trouvé ça génial et j'ai cru avoir une bonne piste. Puis je me suis rendue compte que j'avais quand même besoin de réaliser des imports absolus... Bref, j'ai mélangé deux pistes et créé UN MONSTRE ! :laughing: 

Je suis en train de mettre en place tes recommandations, notamment en supprimant ce fichier. Je lance une V2 tout à l'heure, tu me diras ce que tu en penses.

2021-01-25 16:52 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] En tant qu'utilisateur, je veux me désabonner de certaines notifications qui me sont envoyées automatiquement.](https://trello.com/c/9Xy1srfR/1177-c1-en-tant-quutilisateur-je-veux-me-d%C3%A9sabonner-de-certaines-notifications-qui-me-sont-envoy%C3%A9es-automatiquement)

2021-01-25 17:17 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        return self.email.send()
Ce return n'est probablement pas nécessaire.

2021-01-26 10:27 UTC, celine-m-s commented on itou/utils/notifications.py
> +        filters = {f"notifications__{self.class_name}__subscribed": True}
Ajouté dans la doc de la classe. Merci du retour !

2021-01-26 10:28 UTC, celine-m-s commented on itou/utils/notifications.py
> +        obj.notifications[self.class_name]["subscribed"] = False
Effectivement, tu as raison. J'ai résolu ce point en forçant l'ajout de la clé si elle n'existe pas et en ajoutant de la doc au niveau de la classe. Ce sera assez, à ton avis ?

2021-01-26 10:28 UTC, celine-m-s commented on itou/utils/notifications.py
> +from itou.job_applications.notifications import NewJobApplicationSiaeEmailNotification  # noqa: ignore=E402
Finalement j'ai supprimé ce fichier qui n'apportait pas grand chose à part de la complexité supplémentaire. :)

2021-01-26 10:42 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        active_memberships = job_application.to_siae.siaemembership_set.filter(is_active=True, user__is_active=True)
On pourrait probablement créer un `QuerySet` au niveau du modèle `SiaeMembership` pour gérer ce cas, même si on n'en a pas vraiment eu besoin jusqu'alors. A votre avis ?

2021-01-26 10:46 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        active_memberships = job_application.to_siae.siaemembership_set.filter(is_active=True, user__is_active=True)
On pourrait probablement créer un QuerySet au niveau du modèle SiaeMembership pour gérer ce cas, même si on n'en a pas vraiment eu besoin jusqu'alors. A votre avis ?

2021-01-26 10:46 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +                self.subscribe(recipient=recipient)
Je ne pense pas que ce soit optimal car ça génère un `save()` au niveau de chaque objet alors qu'un `bulk update` pourrait être plus performant. A votre avis, est-ce que ça vaut le coup que je retravaille cette partie ?

2021-01-27 10:18 UTC, kemar requested changes
Beau travail. Quelques remarques de surface et une autre qui nécessite de bien réfléchir et de faire un changement soit de nom de variable, soit d'endroit pour stocker les notifications.

2021-01-27 10:18 UTC, kemar commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
Ici je pense que le type de données qu'on attend en entrée dans `recipients_qs` n'est pas explicite.

En lisant le code à cet endroit, on s'attendrait à devoir passer un `QuerySet` d'objets `User` dans `recipients_qs`, or c'est bien des `SiaeMembership` qui sont passés dans `NewJobApplicationSiaeEmailNotification` un peu plus haut.

Je pense qu'il faut être plus clair et appeler un chat un chat : 

```python
def __init__(self, membership_qs):
    self.membership_qs = membership_qs
```

De cette manière il n'y a aucune ambiguïté sur ce qu'on manipule. Le fait que l'on cible des `recipients` sera exprimé par le nom des méthodes.

Mais si cette ambiguïté existe, peut-être que ça veut dire que l'objet `User` serait finalement un meilleur endroit pour stocker les notifications ? Auquel cas il faudrait les préfixer de `siae_ID` par exemple ?

2021-01-27 10:18 UTC, kemar commented on itou/utils/notifications/base_class.py
> +    def email(self):
Ça c'est top car ça laissera la possibilité d'envisager d'autres modes de notifications 👍

2021-01-27 10:18 UTC, kemar commented on itou/utils/notifications/base_class.py
> +                self.subscribe(recipient=recipient)
Oui c'est pas déconnant d'envisage un `bulk` ici car il y a des organisations qui ont des tas de membres ! À choisir, le ferais tout de suite cette optim.

2021-01-27 10:25 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        return "new_job_application_siae_email"
A vrai dire, j'ai mis le nom dans une propriété pour pouvoir le modifier dynamiquement à partir de `job_application` par exemple. Cela nous sera très utile pour désabonner les employeurs de certaines offres (`SiaeJobDescription`).

2021-01-27 10:35 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
Tu as tout à fait raison et j'ai d'ailleurs rencontré quelques difficultés au moment d'écrire la doc exactement à cause de ça. Peut-être qu'un jour nous serons amenés à conserver les préférences de notifications au niveau du `User`, soit parce que cela concerne toutes les typologies d'utilisateurs, soit parce que le compte n'est relié à aucune organisation.
Cela explique le nom de l'argument: `recipient_qs` et non `membership_qs`.

> Mais si cette ambiguïté existe, peut-être que ça veut dire que l'objet `User` serait finalement un meilleur endroit pour stocker les notifications ? 

Effectivement, je me dis que ce serait plus logique. Toutes les préférences seraient donc conservées à un seul et même endroit au niveau de l'utilisateur. Mais cela rajoute de la complexité car le dictionnaire sera forcément plus profond. A voir ce qu'en pensent les autres devs.
  
> Auquel cas il faudrait les préfixer de `siae_ID` par exemple ?

Effectivement, c'est une bonne idée.

2021-01-27 10:36 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +    def email(self):
C'est ce que je me suis dit ! :)

2021-01-27 10:37 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        active_memberships = job_application.to_siae.siaemembership_set.filter(is_active=True, user__is_active=True)
Ca marche ! Merci de l'avis !

2021-01-27 10:40 UTC, kemar commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
Peut-être qu'il faut simplement stocker à plusieurs endroits les notifications :

- celles qui concernent toutes les typologies d'utilisateurs dans la table `User`
- celles qui concernent une organisation ou une SIAE dans les tables `Membership`

2021-01-27 10:43 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
C'est bien ce qu'on s'était dit, mais alors le nom de l'argument peut difficilement refléter les deux. Ou alors je mets `obj` pour que ce soit super neutre mais je ne trouve pas ça très explicite.

2021-01-27 10:51 UTC, kemar commented on itou/job_applications/notifications.py
> +        return "new_job_application_siae_email"
Je ne comprends pas ton point… `name` est sensé être commun à toutes les instances d'une même classe non ?

C'est à dire `NewJobApplicationSiaeEmailNotification.name` renverra toujours `"new_job_application_siae_email"`, non ?

2021-01-27 10:58 UTC, kemar commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
Ok je comprends. Dans ce cas il faut peut-être explicite dans la documentation en précisant tous les objets qui peuvent être autorisés en entrée.

Ou alors… commencer à utiliser les **Type Hints** de Python… mais… êtes vous PRÊT ? 🤣

2021-01-27 11:09 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        return "new_job_application_siae_email"
> C'est à dire NewJobApplicationSiaeEmailNotification.name renverra toujours "new_job_application_siae_email", non ?

Ici, oui. Mais je ne sais pas encore comment je vais gérer le désabonnement d'un certain type de métier par un employeur. On peut en discuter si tu veux car je ne suis pas sure d'être très claire.

```
class JobApplication(xwf_models.WorkflowEnabled, models.Model):
  # ...
      # Jobs in which the job seeker is interested (optional).
    selected_jobs = models.ManyToManyField(
        "siaes.SiaeJobDescription", verbose_name=_("Métiers recherchés"), blank=True
    )
```

2021-01-27 11:09 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
> êtes vous PRÊTS ? :rofl: 

Toujours ! :laughing: 
On peut en discuter ?

2021-01-27 12:59 UTC, celine-m-s commented on itou/job_applications/notifications.py
> +        return "new_job_application_siae_email"
D'ailleurs, cela fait suite à [une remarque de ta part](https://github.com/betagouv/itou/pull/444#discussion_r526085863).

2021-01-27 15:34 UTC, ikarius commented on itou/job_applications/notifications.py
> +        active_memberships = job_application.to_siae.siaemembership_set.filter(is_active=True, user__is_active=True)
On peut peut-étre en déduire que:
quand on voit une query qui chaîne différents modèles / app, et que l'on est encore obligé de filtrer de manière complexe 
on se trouve devant un cas métier à reporter dans le modèle cible

2021-01-27 15:38 UTC, ikarius commented on itou/job_applications/notifications.py
> +        return "new_job_application_siae_email"
Je dois avouer être perdu sur ce point

2021-01-27 15:47 UTC, ikarius commented on itou/utils/notifications/base_class.py
> +        self.recipients_qs = recipients_qs
Vous trouvez ça comment les type hints pour la lisibilité du code ?

2021-01-27 16:04 UTC, ikarius approved these changes
LGTM
Ça prends forme
Toujours admiratif devant la qualité de ton code, et plus particulièrement celui des tests.
Ils deviennent un support supplémentaire à la compréhension du code.
Kudos!

2021-01-28 14:36 UTC, celine-m-s commented
> Toujours admiratif devant la qualité de ton code, et plus particulièrement celui des tests.
> Ils deviennent un support supplémentaire à la compréhension du code.
> Kudos!

MERCI @ikarius ! <3

2021-01-28 14:37 UTC, kemar approved these changes
LGTM

2021-01-28 14:56 UTC, merged