Boost design
betagouv/itou pull request #503
Opened 2021-01-05 15:01 UTC by celine-m-s

Le titre et la description sont en français et au format texte.

## SIAE > liste des candidatures > Nouveau badge
Mise en avant des auto-prescriptions à travers l'ajout d'un badge.
![image](https://user-images.githubusercontent.com/6150920/103661567-296e7100-4f6f-11eb-9d96-7f5f4c75e657.png)

2021-01-07 14:42 UTC, kemar requested changes
Un peu de logique à sortir des templates.

2021-01-07 14:42 UTC, kemar commented on itou/templates/apply/includes/list_card_body.html
> +                    {% if siae == job_application.sender_siae %}
Je préfèrerais qu'on encapsule cette logique dans le modèle via une property ou une méthode plutôt que de mettre la logique dans le template si c'est possible ?

2021-01-07 14:42 UTC, kemar commented on itou/templates/apply/process_base.html
> +                                        Disponible au téléchargement après le {{cancellation_date}}
Des petits espaces dans `{{ cancellation_date }}` pour rester constant ?

2021-01-07 14:42 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
À la place de mettre la logique dans le template, il vaudrait mieux utiliser les méthodes déjà existantes, par exemple https://github.com/betagouv/itou/blob/1648bcbbb5a9187681cd648f50fb3da2cdcd8812/itou/siaes/models.py#L255-L256 quitte à faire un appel dans la vue (c'est @vgrange qui m'a suggéré ça dans ma PR) si ça n'est pas faisable dans le template !

2021-01-07 14:45 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
J'avais pensé à cette méthode mais elle ne fait pas ce que je veux, à savoir vérifier que la `current_siae` n'a qu'un seul membre. Tu préfères que je rajoute une méthode dans le modèle juste pour ça ?

2021-01-07 14:51 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
Je ne comprends pas le pourquoi un seul membre en fait ?

2021-01-07 14:55 UTC, vgrange requested changes
2 remarques à discuter. Le boost dev va en jeter sur le changelog ;-)

2021-01-07 14:55 UTC, vgrange commented on itou/job_applications/models.py
> +        (STATE_POSTPONED, _("Candidature en liste d'attente")),
Pas besoin de migration c'est ça?

2021-01-07 14:55 UTC, vgrange commented on itou/templates/apply/includes/list_card_body.html
> +                    {% if siae == job_application.sender_siae %}
Quand est-ce que `siae == job_application.sender_siae` peut être faux? Vu qu'on a `job_application.sender_kind == job_application.SENDER_KIND_SIAE_STAFF` c'est forcément une auto-prescription non?

2021-01-07 14:55 UTC, vgrange commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
Est-ce que le filtre de 1 membre est vraiment le bon? Si dès le second jour un autre membre rejoint la struture, le message disparait bien avant 7 jours.

En fait tu veux montrer ce message pendant 7 jours au *premier* membre non? Il te faut donc préparer dans le contexte et donc dans la vue un booléen `is_siae_first_user` je dirais.

2021-01-07 18:54 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
Les utilisateurs ont du mal à comprendre que le premier inscrit soit automatiquement administrateur. D'où mon idée de montrer ce message après l'inscription, pour que les utilisateurs le voient en premier, et que cela disparaisse assez vite (une semaine ou à l'arrivée d'autres membres).

J'ai voulu trouver une solution sans trop de dev car ça reste du Boost Design. J'ai aussi pensé qu'ajouter une méthode au modèle alors qu'elle ne serait utilisée que dans un seul gabarit était peut-être excessif. 

Cela étant, vous avez tous les deux raison. Un `count` dans un gabarit, c'est moche. Quant au besoin métier, cette conversation prouve que le ticket est trop flou et qu'on n'est pas d'accord sur la solution envisagée.

Voici donc ma nouvelle proposition : 
- Je reviens en arrière en supprimant le nouveau message du tableau de bord. Effectivement, ce n'est pas assez logique.
- J'affiche le message informatif sur la page "Collaborateurs" uniquement, sans limitation de durée, si l'utilisateur est le premier inscrit et qu'il est encore administrateur. Pour ce faire, j'ajoute une propriété sur les modèles des établissements qui vérifie si le premier inscrit est encore administrateur. Je récupère ça dans la vue `members` puis dans le gabarit. C'est plus propre.

Qu'en pensez-vous ?

2021-01-07 18:55 UTC, celine-m-s commented on itou/job_applications/models.py
> +        (STATE_POSTPONED, _("Candidature en liste d'attente")),
Exactement ! Django m'a dit que ça ne valait pas le coup. :wink:

2021-01-07 19:08 UTC, celine-m-s commented on itou/templates/apply/includes/list_card_body.html
> +                    {% if siae == job_application.sender_siae %}
> Quand est-ce que siae == job_application.sender_siae peut être faux?

Très juste. 
Le gabarit `list_card_body.html` est utilisé à trois endroits : dans la liste des DE, celle des prescripteurs et celle des employeurs. Mais je me suis trompée dans ma vérification. J'aurais pu tout simplement vérifier que l'utilisateur est un employeur. Je change.

2021-01-07 19:22 UTC, celine-m-s commented on itou/templates/apply/process_base.html
> +                                        Disponible au téléchargement après le {{cancellation_date}}
Bien vu ! Merci !!

2021-01-08 15:25 UTC, vgrange commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
> et que cela disparaisse assez vite (une semaine ou à l'arrivée d'autres membres).
Mes 2 cts. Oublie juste l'arrivée d'autres membres. Le délai d'un semaine suffit.

Par exemple :

```
{% if user.joined_recently %}
        {% include "welcoming_tour/includes/message.html" %}

        {% if user_is_siae_admin %}
```

Et voilà. Simple. `user_is_siae_admin` vient directement du context_processor hein.

2021-01-11 10:25 UTC, celine-m-s commented on itou/templates/dashboard/dashboard.html
> +        {% if current_siae and current_siae.members.count == 1 %}
Après en avoir discuté avec Zohra, nous n'allons rien afficher du tout.

2021-01-11 10:29 UTC, kemar approved these changes
LGTM

2021-01-11 10:51 UTC, vgrange approved these changes
LGTM

2021-01-11 10:53 UTC, merged