Boost Design
betagouv/itou pull request #513
Opened 2021-01-13 14:39 UTC by celine-m-s

## Page d'accueil : affichage des prochains webinaires

Utilisateur connecté : 
![image](https://user-images.githubusercontent.com/6150920/104466451-8bedef80-55b5-11eb-9858-c897fa69547a.png)

Utilisateur non connecté : 
![image](https://user-images.githubusercontent.com/6150920/104466374-74166b80-55b5-11eb-9a2e-3d9c5d559fdd.png)

2021-01-13 16:40 UTC, kemar requested changes
Je pense qu'il manque un `super` (j'en suis presque certain) ;)

2021-01-13 16:40 UTC, kemar commented on itou/templates/home/home.html
> +{% block script %}
Je pense qu'il te manque un `{{ block.super }}` ici.

2021-01-14 09:47 UTC, celine-m-s commented on itou/templates/home/home.html
> +{% block script %}
Bien vu ! Merci !

2021-01-14 09:48 UTC, kemar approved these changes
LGTM

2021-01-14 09:58 UTC, merged