Ajout du modèle JobSeekerProfile + refactoring référentiels ASP
betagouv/itou pull request #553
Opened 2021-02-23 13:49 UTC by ikarius

### Quoi ?

- ajout d'un modèle `JobSeekerProfile`
- modification de certains référentiels ASP

### Pourquoi ?

Ajouter les informations du demandeur d'emploi relatives au fiches salarié (un "profil"), mais sans surcharger le modèle existant `User`.

Simplification de certains modèles de l'app `asp`, avec un versionning trop lourd et très probablement inutile.

Le code est plus lisible (j'espère), et surtout moins trompeur.

Une fois cette portion validée,  

### Comment ?

- suppression du versionning certains modèles ASP, et mise à plat sous forme de `TextChoices`
- ajout d'un modèle one-to-one `JobSeekerProfile` pour le modèle `User`
- ajout d'une migration custom qui détruit les anciens modèles de référentiels obsolètes
- ajout des fixtures correpondantes

### Autre (optionnel)

- nécessitera un nouvel import des fixtures de référentiels ASP

---

2021-02-24 09:53 UTC, kemar requested changes
Deux retours mais pas grand chose :

- une question sur `primary_key=True`, est-ce volontaire ?
- le champ `poleemploi_*` => si tu pouvais ajouter un underscore pour `pole_emploi_*` ?

2021-02-24 09:53 UTC, kemar commented on itou/asp/models.py
> +            return cls.OTHER
Du coup la méthode de @celine-m-s est parfaite pour ne pas dupliquer les `kind` ici en les _hardcodant_ !

> https://github.com/betagouv/itou/pull/554#pullrequestreview-596649316

C'est malin cette `@classmethod`, j'adore :)

2021-02-24 09:53 UTC, kemar commented on itou/external_data/models.py
> +        get_user_model(), verbose_name=_("Demandeur d'emploi"), on_delete=models.CASCADE, primary_key=True
Es-tu certain de vouloir un attribut `primary_key=True` ici et pourquoi ?

2021-02-24 09:53 UTC, kemar commented on itou/users/models.py
> +        primary_key=True,
Pareil, j'ai un doute sur `primary_key=True` et sur la nécessité ou pas de le mettre ici.

2021-02-24 09:53 UTC, kemar commented on itou/users/models.py
> +    poleemploi_since = models.CharField(
Il y a un tiret dans `pole_emploi_id`, `prescriber_pole_emploi_safir_code` etc. est-ce qu'on peut conserver cette convention ? => `pole_emploi_since`

2021-02-24 10:00 UTC, ikarius commented on itou/asp/models.py
> +            return cls.OTHER
C'est précisément à ça que je pensais dans ma remarque sur les type de SIAE quand je disais que ça me donnais des idées.

2021-02-24 10:10 UTC, ikarius commented on itou/external_data/models.py
> +        get_user_model(), verbose_name=_("Demandeur d'emploi"), on_delete=models.CASCADE, primary_key=True
Certain, jamais :)
Mais c'est une agrégation (au sens UML): un `JobSeekerProfile` ne peut pas exister sans un `User`
Dans ce cas, pourquoi avoir une clé primaire différente ?
Peut-être n'est-ce pas idiomatique Django, mais j'avais vu [un exemple dans la doc](https://docs.djangoproject.com/en/3.1/topics/db/examples/one_to_one/).

2021-02-24 10:13 UTC, ikarius commented on itou/users/models.py
> +        primary_key=True,
Voir plus haut

2021-02-24 16:28 UTC, celine-m-s approved these changes
LGTM!
Top, le profil utilisateur ! J'ai juste laissé un petit commentaire pour une éventuelle autre PR.

2021-02-24 16:28 UTC, celine-m-s commented on itou/users/models.py
> +class JobSeekerProfile(models.Model):
Je me demande si on ne pourrait pas importer les données du modèle `external_data.models.JobSeekerExternalData` dans celui-ci et le supprimer ? Celui-ci est bien mieux ! :sunglasses:

2021-02-24 16:46 UTC, kemar approved these changes
LGTM

2021-02-24 16:50 UTC, merged

2021-02-26 15:29 UTC, vgrange commented on itou/users/models.py
> +    It will first be used by employee record model / system to serialize data for ASP tranfers.
Ok j'ai compris la différence `JobSeekerProfile` vs `EmployeeRecord`.