Installations des extensions PostgreSQL via les migrations
betagouv/itou pull request #569
Opened 2021-03-04 11:28 UTC by stephane

https://trello.com/c/bnU2H5IN/1546-c1-mettre-les-extensions-postgresql-dans-les-migrations-django

### Pourquoi ?

```./manage test``` ne fonctionne pas car les migrations s'appuie sur des fonctionnalités uniquement disponibles dans les extensions mais celles ci ne sont pas installées lorsque le test runner crée la DB.

Il n'y pas de mécanisme en place pour installer ces extensions à la création de la base de tests (sauf template1).
L'environnement Docker effectue un appel à un script externe d'installation de ces migrations avant de lancer les tests.

### Quoi ?

Il est assez naturel d'installer les extensions dans des migrations au fur et à mesure des besoins, le faire a posteriori est nettement plus compliqué car il faut ajouter une migration dans le passé et antérieure à toute migration qui en dépend.

### Comment ?

J'ai essayé plusieurs approches, au final, le point d'entrée de l'app 'users' m'a semblé le plus naturel car la majorité des apps en dépendent. En première version, j'ai simplement ajouté les opérations dans `users.0001_initial` mais si nous souhaitons donner de la visibilité à cette migration, il faut l'extraire dans un fichier à part, le principal inconvénient est de devoir maintenir la cohérence de l'historique sur une base existante (si le check des migrations est effectué, uniquement hors WSGI et donc prod).
J'ai ajouté un commentaire avec la requête qui assure la cohérence.

Autre bémol, l'utilisateur de dev doit avoir le droit d'installer des extensions.

---

Liens intéressant :

- https://trello.com/c/bnU2H5IN/1546-c1-mettre-les-extensions-postgresql-dans-les-migrations-django

2021-03-04 13:14 UTC, kemar requested changes
PTAL Je demanderais juste un peu plus de commentaires pour qu'on puisse bien avoir la big picture dans plusieurs semaines

2021-03-04 13:14 UTC, kemar commented on docker/dev/postgres/psql_init.sh
> +  ALTER USER $ITOU_POSTGRES_USER CREATEDB SUPERUSER;
Le `SUPERUSER ` c'est pour avoir le droit d'installer des extensions via les migrations ? Ça serait bien de le documenter ici non ?

2021-03-04 13:14 UTC, kemar commented on itou/users/migrations/0001bis_create_extensions.py
> +    where app = 'users' and name = '0001_initial';
Du coup c'est vachement mieux expliqué dans la description de la PR. Si je lis ça hors contexte je suis pas certain de comprendre correctement. Est-ce qu'on peut expliquer ici un peu l'historique et qu'on a du créer cette migration a posteriori et pourquoi tu as choisi l'app `User` etc. ?

2021-03-04 13:17 UTC, stephane commented on docker/dev/postgres/psql_init.sh
> +  ALTER USER $ITOU_POSTGRES_USER CREATEDB SUPERUSER;
La doc là où c'est utile, quelle bonne idée ;)

2021-03-04 13:23 UTC, stephane commented on itou/users/migrations/0001bis_create_extensions.py
> +    where app = 'users' and name = '0001_initial';
Idem et je pensais aussi ajouter une date dans le commentaire pour dire si vous voyez ce code en commentaire dans 1 mois, vous pouvez le supprimer. Même si check ne s'effectue pas en prod, il faut passer cette query en prod pour que les dumps soit clean mais idéalement sans migration.

2021-03-04 15:11 UTC, stephane commented
À noter que si la migration était fusionnée avec users.0001_initial, la petite requête serait inutile.

2021-03-04 15:47 UTC, celine-m-s approved these changes
LGTM! :+1:

2021-03-04 15:47 UTC, celine-m-s commented on .github/workflows/review-app-creation.yml
> -
Ca fait toujours du bien de voir du code en moins ! :-D

2021-03-04 15:47 UTC, celine-m-s commented on itou/users/migrations/0001bis_create_extensions.py
> +    users.0001_initial.
Petit pinaillage sur la concordance des temps : `this query would not be required... had been merged...`.

2021-03-08 09:51 UTC, stephane commented
@kemar est-ce que les nouveaux commentaires sont suffisamment clairs ?

2021-03-08 09:57 UTC, kemar commented on docker/dev/postgres/psql_init.sh
> +# The PostgreSQL user should be able to create extensions.
J'en rajouterais une couche :

> The PostgreSQL user should be able to create extensions **that are defined in migrations**.

2021-03-08 09:58 UTC, kemar approved these changes
LGTM

2021-03-08 14:13 UTC, stephane commented
Avec le merge, vous devrez lancer la query suivante sur une DB existante :

```sql
insert into django_migrations (app, name, applied)
select 'users', '0001bis_create_extensions', applied + interval '00:00:00.00001'
from django_migrations
where app = 'users' and name = '0001_initial';
```

2021-03-08 14:13 UTC, merged

2021-03-08 14:14 UTC, stephane commented
Comment passe t'on cette query en prod (la prod ne check pas les migrations mais nous voulons des dumps clean).