Boost Dev #2 du Sprint #14
betagouv/itou pull request #583
Opened 2021-03-12 09:10 UTC by vgrange

## Améliorations mineures du script import_pe_approvals

- Barre de progression sexy avec tqdm
- Stats en plus
- Wording qui clarifie que 0 nouveaux objets est normal en dry run

A l'occasion de mon premier import de ce type.

J'ai aussi fait une petite maj de doc côté repo privé, sans review : betagouv/itou-private@019a791

2021-03-12 09:35 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1 - Visibilité des postes] Ma SIAE n'est pas visible dans ma propre ville](https://trello.com/c/37Sj2YT5/1554-c1-visibilit%C3%A9-des-postes-ma-siae-nest-pas-visible-dans-ma-propre-ville)

2021-03-12 09:35 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Importer les agréments de la semaine + améliorations mineures du script](https://trello.com/c/CkPLk4xO/1534-c1-importer-les-agr%C3%A9ments-de-la-semaine-am%C3%A9liorations-mineures-du-script)

2021-03-12 15:22 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter le champ "Date de création" dans l'export des Pass IAE](https://trello.com/c/2fqpKJ2u/1575-ajouter-le-champ-date-de-cr%C3%A9ation-dans-lexport-des-pass-iae)

2021-03-12 15:30 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] : Prescripteurs : je ne sais pas que les coordonnées de contact sont visibles](https://trello.com/c/sU3Q9uXS/1502-c1-prescripteurs-je-ne-sais-pas-que-les-coordonn%C3%A9es-de-contact-sont-visibles)

2021-03-18 10:06 UTC, stephane requested changes
C'était pour moi l'occasion de découvrir tqdm

2021-03-18 10:06 UTC, stephane commented on itou/templates/search/prescribers_search_results.html
> +                {% blocktranslate %}à <b>{{ distance }} Km</b> du centre de <b>{{ city }}</b>{% endblocktranslate %}
idem pour tous les km

2021-03-18 10:06 UTC, stephane commented on itou/approvals/management/commands/import_pe_approvals.py
> +            pbar.update(1)
Top !

2021-03-18 10:06 UTC, stephane commented on itou/approvals/export.py
> +            _format_date(ja.approval.created_at),
Pas évident de faire le lien entre la colonne et sa valeur quand le nombre de colonnes est important.
Une approche pourrait être d'utiliser des enums pour référencer les positions `row[WS1_PRENOM]`.

2021-03-18 10:55 UTC, kemar commented on itou/templates/search/prescribers_search_results.html
> +        {% blocktranslate %}Prescripteurs à {{ distance }} Km du centre de {{ city }}{% endblocktranslate %}
C'est [bibi qui a fait ça](https://github.com/betagouv/itou/commit/21e4409eb43b595deba46d7fb4a427e13666f412#diff-0d998b8d2eec0f7db74a47cb9b1afedb92ae56b8621c65d398ed0efe4ee9a62dR49), c'est pas de sa faute :)

2021-03-18 10:56 UTC, kemar approved these changes
LGTM

2021-03-18 15:15 UTC, vgrange commented on itou/approvals/management/commands/import_pe_approvals.py
> +        self.stdout.write(f"New objects: {count_after - count_before} (in case of dry run this will always be zero)")
On voit déjà le nombre d'objets qui seront potentiellement injectés en db plus haut dans le tqdm.

![image](https://user-images.githubusercontent.com/10533583/111649833-67a8cc00-880d-11eb-88b8-a559834f1166.png)

Par contre pas de moyen simple de prédire en dry run combien seront effectivement insérés car non présents en db.

2021-03-18 15:18 UTC, vgrange commented on itou/templates/search/prescribers_search_results.html
> +        {% blocktranslate %}Prescripteurs à {{ distance }} Km du centre de {{ city }}{% endblocktranslate %}
Ok pour un `s/Km/km/` et TIL https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable par contre j'ai pas compris où tu voulais le mettre. 

Sur https://fr.wikipedia.org/wiki/Kilom%C3%A8tre je ne vois aucune mention d'espace insécable.

2021-03-18 15:19 UTC, vgrange commented on itou/templates/search/prescribers_search_results.html
> +        {% blocktranslate %}Prescripteurs à {{ distance }} Km du centre de {{ city }}{% endblocktranslate %}
@kemar joue au physicien ! ;-)

La notation Km (avec un K majuscule) est à proscrire, car, dans le système international d'unités (SI), le K majuscule est le symbole du kelvin, unité de température thermodynamique. Km serait donc le symbole de l'unité physique Kelvin.mètre.

2021-03-18 15:19 UTC, vgrange commented on itou/templates/search/prescribers_search_results.html
> +        {% blocktranslate %}Prescripteurs à {{ distance }} Km du centre de {{ city }}{% endblocktranslate %}
Ou alors K comme Kemar ?

2021-03-18 15:25 UTC, vgrange commented on itou/approvals/export.py
> +            _format_date(ja.approval.created_at),
Tout à fait. Perso j'aurai utilisé une dataframe pandas comme je l'ai fait dans pas mal d'autres scripts.

2021-03-18 15:33 UTC, merged

2021-03-18 15:35 UTC, stephane commented on itou/templates/search/prescribers_search_results.html
> +        {% blocktranslate %}Prescripteurs à {{ distance }} Km du centre de {{ city }}{% endblocktranslate %}
Dans « 5 km » entre 5 et km pour éviter les mauvais retours à la ligne.
Exemple :
bla 5
km du centre