Quelques commits relatifs à la qualité du code
betagouv/itou pull request #588
Opened 2021-03-16 13:59 UTC by stephane

### Quoi ?

Paramétrage des linters et applications de quelques corrections avec ses outils.

### Pourquoi ?

Ces changements permettent d'améliorer la conformité du code. Quand le nombre de warnings/errors des linters
est trop important nous avons tendance à les ignorer.

### Comment ?

Fournit le git pre commit hook pour Black et isort et un fichier de configuration pour pylint.

2021-03-16 15:23 UTC, kemar commented
C'est marrant, j'avais viré Pylint pour le remplacer par Flake8 car il mettait une plombe à passer https://github.com/betagouv/itou/commit/9d95bb7b3c94caf396f94aef0259bf8f195a69bf

Y a-t-il un intérêt à conserver les deux ?

S'il faut le conserver, est-ce que tu peux adapter les commandes du Makefile à tes modifications si nécessaire. Je pense par exemple à `make quality` et `make setup_git_pre_commit_hook`.

2021-03-16 15:24 UTC, kemar requested changes
Quelques questions dans la PR

2021-03-16 15:34 UTC, ikarius commented on Makefile
> +	./manage.py graph_models --group-models jobs users siaes prescribers job_applications approvals eligibility invitations asp --pygraphviz -o itou-graph-models.png
TIL graph_models

2021-03-16 15:38 UTC, ikarius commented on itou/asp/tests.py
>          self.assertIsNone(find_lane_type_aliases("XXX"))
TIL `assertEquals` est deprecated

2021-03-16 15:39 UTC, stephane commented
J'ai ajouté tardivement le fichier .pylintrc que j'avais en local car je n'étais pas chaud que l'on utilise flake8 et pylint mais malgré l'overlap, ils fournissent des choses différentes, je me suis dit qu'il fallait le proposer dans ma PR.

Du coup, selon ce que vous en pensez, je l'ajoute au CI mais comme une métrique (genre score > 9.5/10) -> green
Pendant que j'y suis je vais ajouter le coverage...

2021-03-16 15:41 UTC, ikarius approved these changes
LGTM
Curieux de voir le vainqueur entre `pylint` et `flake8`.
A moins qu'à deux ils permettent une meilleure couverture ?

2021-03-16 15:46 UTC, stephane commented on Makefile
> +	./manage.py graph_models --group-models jobs users siaes prescribers job_applications approvals eligibility invitations asp --pygraphviz -o itou-graph-models.png
La majorité des commandes du Makefile utilise docker, je propose d'utiliser un prefix pour les versions non docker ainsi je modifie `graph_models_itou` en `docker exec bla bla` et je créé une autre entrée 
`no_bullshit_graph_models_itou` (ou suffixe, `graph_models_itou_like_a_boss` ;) pour les dev env locaux.
Une idée de prefix ?

2021-03-16 15:54 UTC, kemar commented
Donc Pylint uniquement en CI ? Pourquoi pas… On verra bien ce que ça donne.

2021-03-16 15:57 UTC, kemar commented on Makefile
> +	./manage.py graph_models --group-models jobs users siaes prescribers job_applications approvals eligibility invitations asp --pygraphviz -o itou-graph-models.png
T'es le seul à pas utiliser Docker, trouve toi un préfixe :)

2021-03-16 16:09 UTC, celine-m-s reviewed
> selon ce que vous en pensez, je l'ajoute au CI mais comme une métrique (genre score > 9.5/10) -> green

Ca me va mais je sens que ça va me soûler s'il faut que je fasse tourner la CI pour avoir le résultat. 
Si tu penses que les deux sont complémentaires, alors je mets à jour mon `hook` git pour y ajouter `pylint`. C'est rapide ou pas ?

Par contre, j'ai un peu de mal à comprendre l'intérêt de `.pre-commit-config.yaml`. J'ai l'impression qu'il faut utiliser un autre outil mais j'aurais aimé que cet aspect soit documenté dans la description de la PR et en commentaire de ce fichier.

2021-03-16 16:21 UTC, stephane commented on setup.cfg
> +# E203: Whitespace before ':'
Je pense que ce n'est pas bien d'ignorer cette erreur.

Cela autorise :
```python
yield lst[i : i + n]
```

et un truc similaire ailleurs.

Je modifie...

2021-03-16 16:24 UTC, stephane commented on setup.cfg
> +# E203: Whitespace before ':'
Oh wait! En conflit avec Black!
Donc je laisse avec commentaire.

2021-03-16 16:42 UTC, stephane commented on .pre-commit-config.yaml
> +        language_version: python3
C'est bien ça.

```
pip install pre-commit
pre-commit install
```

qui va créer le script `.git/hooks/pre-commit` comme le fait le 'echo' du Makefile pour Docker.

J'ai ajouté une règle dans le Makefile.

2021-03-16 16:43 UTC, stephane commented on itou/www/prescribers_views/views.py
> +def member_list(request, template_name="prescribers/members.html"):
Redéfinition de `members` quelques lignes plus tard...

2021-03-16 16:49 UTC, celine-m-s commented on .pre-commit-config.yaml
> +        language_version: python3
OK, merci ! Je viens de voir que la lib figurait dans les requirements.txt de dev, ça avait échappé à ma revue.

2021-03-16 17:05 UTC, stephane commented
J'ai changé d'avis, pylint mange du CPU comme un ouf et nous sommes loin d'avoir une sortie clean (le run actuel vient d'ailleurs de faire passer la note de 9,66 à 9,57 en une semaine), donc dans un premier temps, je propose que l'on lance la commande sur nos machines pour être `aware` (TM Jean-Claude V.) des warnings et ensuite, on avise.

2021-03-16 17:12 UTC, kemar commented
> J'ai changé d'avis, pylint mange du CPU comme un ouf

Oui c'est bien ce que j'avais dans mon souvenir… C'était déjà lent sur une base de code plus petite de 2/3…

2021-03-17 10:59 UTC, stephane commented
@kemar pour merger cette PR, il nous reste à statuer sur pylint.
Nous avons discuté du sujet ce matin avec Céline :
- je ne suis pas chaud de le faire tourner dans le CI sur chaque commit (trop de CPU qui tue les bébés phoques et ralenti le feedback) pour juste fournir un score
- @celine-m-s propose d'utiliser le système d'étiquette quand nous nécessaire

Perso, je l'utilise à la volée dans vscode. On en reparle demain soir au debrief tech ?

2021-03-17 12:55 UTC, kemar commented
> […] il nous reste à statuer sur pylint. […] On en reparle demain soir au debrief tech ?

@stephane OK on en reparle demain.

A priori je ne suis pas chaud pour Pylint car je n'y vois pas d'avantage évident. Mais si tu as des arguments on verra ce qu'en pense l'équipe.

2021-03-18 09:19 UTC, merged