Possibilité pour les conseils départementaux de visualiser les organisations conventionnées
betagouv/itou pull request #589
Opened 2021-03-16 17:06 UTC by kemar

### Quoi ?

Possibilité pour les conseils départementaux de visualiser l'activité des organisations conventionnées pour le suivi des BRSA

### Pourquoi ?

TODO

### Comment ?

TODO

### Captures d'écran

TODO

2021-03-17 17:00 UTC, kemar commented on itou/prescribers/models.py
> +            setattr(self, f"is_kind_{kind.value.lower()}", kind == self.kind)
Est-ce que ça vaut vraiment le coup ?

2021-03-17 17:00 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                                <span class="badge badge-info">{% translate "Nouveau" %}</span>
J'ai retiré les anciens badges "Nouveau" au passage.

2021-03-17 17:02 UTC, kemar commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Les CD n'ont pas de visibilité sur l'activité des orga conventionnées CD (carte validée par l'équipe)](https://trello.com/c/FyA5sm43/1437-c1-les-cd-nont-pas-de-visibilit%C3%A9-sur-lactivit%C3%A9-des-orga-conventionn%C3%A9es-cd-carte-valid%C3%A9e-par-l%C3%A9quipe)

2021-03-18 10:31 UTC, stephane requested changes

2021-03-18 10:31 UTC, stephane commented on itou/prescribers/models.py
>          on_delete=models.SET_NULL,
Un peu plus haut, typo sur Préfet (Prefect) ?

2021-03-18 10:31 UTC, stephane commented on itou/prescribers/models.py
> +            setattr(self, f"is_kind_{kind.value.lower()}", kind == self.kind)
Je ne trouve pas et cela laisse penser que le champ existe en base.

2021-03-18 10:31 UTC, stephane commented on itou/prescribers/models.py
> +        if org.is_kind_dept and org.is_authorized:
Je me suis demandé ce que signifiait `is_kind_dept`. org.kind == Kind.DEPT est nettement plus clair pour moi.

2021-03-18 10:31 UTC, stephane commented on itou/templates/prescribers/list_accredited_organizations.html
> +        {% translate "Liste des organisations conventionnées" %}
J'ai la conviction que ces pages ne seront jamais traduites et que l'on s'embête pour rien avec des balises `translate/blocktrans` partout. Si certaines pages sont un jour traduites, j'imagine que ce seront uniquement celles destinées à certains candidats ? Il sera bien temps d'ajouter les tags là où nécessaire et d'ajouter les contextes qui manquent actuellement aux traducteurs (titre, action, bouton, etc).

2021-03-18 10:32 UTC, stephane commented
LGTM pour moi après le changement concernant le `is_kind_foo`.

2021-03-18 10:34 UTC, kemar commented on itou/prescribers/models.py
> +            setattr(self, f"is_kind_{kind.value.lower()}", kind == self.kind)
Ouais j'ai eu un gros doute et c'est un peu ce que je me disais aussi…

2021-03-18 10:36 UTC, kemar commented on itou/templates/prescribers/list_accredited_organizations.html
> +        {% translate "Liste des organisations conventionnées" %}
Ouais ça se défend. Avoir mis les balises de trad partout n'est pas inutile dans le sens où ça servira à tout le monde de savoir comment ça marche pour un éventuel futur projet.

On peut décider en équipe de laisser tomber ce mécanisme si on a un consensus.

2021-03-18 10:47 UTC, kemar commented on itou/prescribers/models.py
>          on_delete=models.SET_NULL,
Pas typo mais trad inutile peut-être :D

![Capture d’écran 2021-03-18 à 11 46 52](https://user-images.githubusercontent.com/281139/111614242-a6279200-87df-11eb-8110-2145ac7e6e5f.png)

2021-03-18 11:57 UTC, stephane commented on itou/prescribers/models.py
>          on_delete=models.SET_NULL,
TIL!

2021-03-18 11:58 UTC, stephane approved these changes
Let's go!

2021-03-18 14:43 UTC, vgrange approved these changes
LGTM! Logique de droits bien propre et spécifique. Bien moins fourre-tout que `user.is_stats_vip` =D

2021-03-18 15:14 UTC, merged