Les extensions COVID ne sont pas prises en compte
betagouv/itou pull request #599
Opened 2021-03-23 10:46 UTC by celine-m-s

…longation

Le titre et la description sont en français et au format texte.

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

---

Liens intéressant :

- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8

2021-03-23 15:02 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] [Bug dans la délivrance de PASS IAE reprenant des agréments qui doivent prendre en compte une prolongation COVID]](https://trello.com/c/AS7aOi1p/1562-c1-bug-dans-la-d%C3%A9livrance-de-pass-iae-reprenant-des-agr%C3%A9ments-qui-doivent-prendre-en-compte-une-prolongation-covid)

2021-03-23 16:36 UTC, kemar requested changes
Presque LGTM. Il manque juste un bon commentaire métier à mon sens.

2021-03-23 16:36 UTC, kemar commented on itou/approvals/models.py
> +    def display_end_at(self):
Pour moi une _docstring_ ne serait pas superflue ici. Elle reprendrait l'explication du paragraphe **Pourquoi** de ta PR de sorte que quelqu'un qui n'a jamais lu le code puisse comprendre pourquoi on fait ça ici.

2021-03-23 17:52 UTC, kemar approved these changes
LGTM

2021-03-24 09:31 UTC, merged

2021-03-24 10:04 UTC, stephane reviewed
LGTM

2021-03-24 10:04 UTC, stephane commented on itou/approvals/models.py
> +        return self.end_at
J'ai cru en lisant le commentaire que « > » signifiait supérieur et j'étais perdu c'est un sous-section en fait, genre « -> »