Mentionne le niveau d'accessibilité dans le footer
betagouv/itou pull request #601
Opened 2021-03-23 15:52 UTC by Anna-Livia

Cette PR/issue ajoute la mention "Accessibilité : non conforme" à votre footer.

La mention "Accessibilité : non conforme" est obligatoire pour les sites du service public et réellement utile pour les personnes en situation de handicap.

## Première étape : mention du niveau d'accessibilité dans le footer

En tant que site faisant partie du service public, nous avons un certain nombre d'obligation. 

L'une d'elle est la [**transparence du niveau d'accessibilité de votre site**](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#mention-obligatoire-sur-la-page-daccueil). 

Pour cela, il faut afficher le niveau de conformité dans le footer :

![](https://storage.gra.cloud.ovh.net/v1/AUTH_0f20d409cb2a4c9786c769e2edec0e06/imagespadincubateurnet/uploads/upload_0b915dfac42811371f8e93b6b4941d5b.png)
 
Tant que le niveau de conformité est inconnu, il est considéré comme **non conforme**.

Après avoir effectué un audit, on peut afficher : 
- Accessibilité : non conforme : score inférieur à 50 %.
- Accessibilité : partiellement conforme : score de 50% ou plus
- Accessibilité : totalement conforme : score est de 100%.

Pour connaître son score, il est donc nécessaire d'effectuer un audit auprès d'un cabinet d'expert qui mesurera le taux de conformité. Rejoignez le [**programme ACCESS**](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/accessibilite-et-rgaa/acces) pour bénéficier d'un audit.

### Prochaine étape : création de la page "Déclaration d'accessibilité"

Cette mention obligatoire doit ensuite être un lien vers une **déclaration d'accessibilité**. 

Voici quelques exemples :

- La [page Accessibilité de signal.conso.gouv.fr](https://signal.conso.gouv.fr/accessibilite) qui affiche le score de l'audit.
- La [page Accessibilité du site des Designers Transverses](https://design.incubateur.net/accessibility/) qui indique que le site n'a pas encore été audité, mais rassure les utilisateurs concernés sur les mesures qui ont été prises.
- Le [générateur de déclaration d'accessibilité](https://betagouv.github.io/a11y-generateur-declaration/#create) pour obtenir un exemple de déclaration conforme en quelques clics.

### De l'aide en plus

En attendant, vous trouverez aussi plus d'infos :
- sur le [Kit Accessibilité](https://doc.incubateur.net/design/ressources-design/kit-accessibilite) de la documentation design
- sur [#domaine-accessibilité](https://app.slack.com/client/T04C2PSNY/C015LNMTTJ9/thread/C0135ELJ6TV-1616511717.002400) sur le Slack
- sur le [programme ACCESS](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/accessibilite-et-rgaa/acces) d'accompagnement des Startups d'Etat pour vous aider à accélérer votre accessibilité. On peut financer un audit et un accompagnement pour vous !

Je reste à dispo si vous avez des questions :)

2021-03-23 16:12 UTC, kemar commented
Merci pour ces informations.

Cela dit, en quoi la mention "non conforme" est-elle utile pour les personnes en situation de handicap ?

D'autre part, nous avons une personne malvoyante au sein de l'équipe qui nous aide à améliorer le service au fur et à mesure.

Et que vaut un niveau de conformité évalué à un instant T ? On sait tous qu'un projet évolue tous les jours et que l'accessibilité est un travail de fond auquel tout les développeurs doivent être sensibilisés.

Désolé, mais la PR en l'état avec tous les liens donne un peu l'impression de se faire engloutir par la bureaucratie…

2021-03-23 18:07 UTC, stephane requested changes

2021-03-23 18:07 UTC, stephane commented on itou/templates/layout/base.html
> +                                  {% translate "Accessibilité : non conforme" %}
Ce n'est pas un lien, il est curieux de le placer au milieu des autres éléments.
Manque l'espace insécable avant « : ».
Augmente la hauteur du footer d'une ligne car appliqué sur la colonne la plus haute.

Il aurait bien de discuter de cette PR en amont, non ?

2021-03-24 09:35 UTC, LeryJ commented
Hello,
Je souhaite vous donner un peu de contexte.
Au sein de l’équipe transverse, avec anne-so et anna-livia, on essaie d’outiller les équipes sur les sujets d’accessibilité.
On le fait avec une démarche bienveillante même si, vu que nous somme au début de la démarche, parfois un peu maladroite.  :
- en suggérant des PR ou des issues à toutes les équipes en accélération (on a poussé 20 PR ou issues hier)
- en proposant des formations, des kits...
- en proposant des audits et un accompagnement concret
La force des produits beta c’est d’avoir des repos ouverts aux contributions (la joie de l’open source).
C’est super si vous êtes déjà impliqués sur ce sujet.

2021-03-24 09:43 UTC, celine-m-s commented
Salut @LeryJ !
Merci du commentaire et des explications ! C'est vrai que la forme est assez cavalière et cela nous a surpris. Je ne pense pas que ce soit la meilleure manière d'inciter des équipes à ajouter une mention ni, plus globalement, à s'intéresser à ce thème. 
Personnellement, j'aurais préféré que vous ouvriez une `issue` pour qu'on puisse en discuter tranquillement. Cela nous aurait permis de réfléchir à l'endroit adéquat, selon nous, pour cette mention.

2021-03-24 09:46 UTC, LeryJ commented
Mea-culpa.

2021-03-24 09:48 UTC, kemar commented
Cette PR transpire l'amateurisme du fond à la forme.

Je vous encourage à ouvrir une issue la prochaine fois ou à informer les développeurs sur le canal Slack idoine.

2021-03-24 09:53 UTC, Anna-Livia commented on itou/templates/layout/base.html
> +                                  {% translate "Accessibilité : non conforme" %}
Ce n'est pas un lien pour le moment, mais ça a vocation à le devenir.
Il me semble que le footer est l'endroit le plus approprié et la colonne la plus haute est audit la seule avec ce type de lien (en tout cas sur mon écran).
L'autre option d'emplacement, à mon sens, était en dessous de `mention légales` mais je trouvais que ça donnais un coté plus administratif à la démarche.

2021-03-24 09:55 UTC, LeryJ commented
"Cette PR transpire l'amateurisme du fond à la forme." C'est dommage de lire ça.
On a entendu le feedback. On a reconnu une erreur. Mais cette phrase ne m'aide pas beaucoup.

2021-03-24 09:56 UTC, celine-m-s commented on itou/templates/layout/base.html
> +                                  {% translate "Accessibilité : non conforme" %}
> je trouvais que ça donnais un coté plus administratif à la démarche

En soi cette PR l'est déjà pas mal ! :smile: 

> Ce n'est pas un lien pour le moment, mais ça a vocation à le devenir.

Dans ce cas, pourquoi ne pas ajouter le lien dès à présent dans ta PR ?

2021-03-24 10:04 UTC, kemar commented
> "Cette PR transpire l'amateurisme du fond à la forme." C'est dommage de lire ça.
> On a entendu le feedback. On a reconnu une erreur. Mais cette phrase ne m'aide pas beaucoup.

C'est dit et vous avez une idée de la façon dont votre message a été réceptionné chez nous.

On va prendre votre contribution mais ne décidez pas de quoi mettre à quel endroit quand il y a derrière ce projet une équipe de 20 personnes qui prend des décisions par consensus.

2021-03-24 10:48 UTC, LeryJ commented
Merci @kemar pour l'échange en visio.
Au plaisir de se reparler ;-)

2021-03-24 10:50 UTC, kemar commented
@LeryJ @Anna-Livia du coup je vous présente mes excuses pour le ton de mes commentaires. Les choses sont claires maintenant.

@Anna-Livia j'ai tenté de te joindre au téléphone sans succès, la remarque sur l'amateurisme était déplacée, désolé.

2021-03-25 13:10 UTC, merged

2021-03-25 13:25 UTC, kemar commented
Ça y est, la mention figure dans notre pied de page en prod https://emplois.inclusion.beta.gouv.fr