Ajout d'un timeout aux appels à PDF Shift
betagouv/itou pull request #603
Opened 2021-03-24 11:31 UTC by celine-m-s

Le titre et la description sont en français et au format texte.

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

---

Liens intéressant :

- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8

2021-03-24 17:17 UTC, stephane requested changes
J'aurais été plus radical en remplaçant`requests` par l'excellent `httpx` qui contient notamment un timeout par défaut !

2021-03-24 17:17 UTC, stephane commented on itou/utils/requests_adapters.py
> +def itou_requests_config(func):
J'aurais plutôt vu une définition globale où on l'importe notre `requests` patché.

2021-03-24 17:17 UTC, stephane commented on itou/www/approvals_views/tests/tests.py
> +    @patch("requests.post", side_effect=requests_exceptions.Timeout)
Est-ce qu'il serait possible de définir un timeout très très court à la place du mock pour vérifier réellement le timeout ?

2021-03-24 20:01 UTC, celine-m-s commented
`httpx` a l'air en beta, non ? Ca pourrait être une bonne option ([lien vers la doc](https://www.python-httpx.org/quickstart/#timeouts)) mais il faudrait remplacer requests dans tout le projet. Qu'en penses-tu @kemar ?

2021-03-24 20:01 UTC, celine-m-s commented on itou/www/approvals_views/tests/tests.py
> +    @patch("requests.post", side_effect=requests_exceptions.Timeout)
On peut, mais alors les tests ne pourront plus être lancés sans connexion à internet, si ?

2021-03-24 20:04 UTC, celine-m-s commented on itou/utils/requests_adapters.py
> +def itou_requests_config(func):
Je ne comprends pas très bien... [Ca, par exemple ?](https://github.com/betagouv/itou/pull/603/commits/a1db452a2eed3370336153d25b24b7706b8524b6)

2021-03-24 20:10 UTC, celine-m-s commented
Bon, j'ai essayé de configurer un  `retry` sans avoir à passer par le système de session mais je n'y parviens pas.

```python
def itou_requests_config(func):
    def wrapper(*args, **kwargs):
        requests.adapters.DEFAULT_RETRIES = settings.REQUESTS_MAX_RETRIES
        requests.adapters.TimeoutSauce = ItouTimeout
        func(*args, **kwargs)
    
    return wrapper
```

Avant d'y passer trop de temps, j'aimerais savoir si : 
- on a besoin de configurer un `retry`. Si c'est le cas, est-ce que ça vous va si j'utilise la lib [backoff](https://github.com/litl/backoff/) ? C'est d'ailleurs ce que conseille [l'article de Mathieu Leplatre](https://blog.mathieu-leplatre.info/handling-requests-timeout-in-python.html).
- je suis sur la bonne voie avec mon décorateur ou si vous aviez complètement autre chose en tête ?
- on part sur `httpx` ou si on garde `requests`.

Merci par avance pour vos lumières ! :zap: :bulb:

2021-03-25 13:46 UTC, kemar commented
> httpx a l'air en beta, non ? Ca pourrait être une bonne option (lien vers la doc) mais il faudrait remplacer requests dans tout le projet. Qu'en penses-tu @kemar ?

Je suis plutôt conservateur en général et je tente d'éviter les beta. Maintenant si @stephane dit que c'est cool j'ai tendance à lui faire confiance surtout si ça peut nous éviter du taf ?

2021-03-25 14:52 UTC, stephane commented
En fait, il me semble que cette PR traite 2 sujets :
**1. le timeout sur nos requêtes HTTP**
Comme évoqué nous aurions pu ajouter un timeout explicite et adapté à chaque requête **ou** pour éviter l'oubli du timeout, créer un module *utils.requests*-like qui serait patché avec l'adapter de cette PR mais que ce soit avec un décorateur ou un module spécifique, on risque quand même de faire un import direct à requests au fin fond d'une management command et ainsi oublier le timeout.
Si la dépendance n'est pas dans le projet, le warning va s'allumer tout seul et donc je propose d'utiliser `httpx` (qui contient un timeout par défaut de 5 secondes) et de supprimer la dépendance sur `requests` (même si je crains qu'elle n'existe de manière indirecte).
Je n'aime pas l'idée que httpx ne soit pas en v1.0 mais vu l'utilisation ultra basique que l'on en fait, je serais surpris que cela pose problème (pas async, pas HTTP2) et de l'autre côté le code de requests est assez `legacy` (la situation est meilleure depuis que Kenneth Reitz a quitté le projet[1]

C'est quand même un projet de Tom Christie qui contient 619 tests et 100 % de coverage.
```
+ coverage report --show-missing --skip-covered --fail-under=100
Name    Stmts   Miss  Cover   Missing
-------------------------------------
-------------------------------------
TOTAL    6286      0   100%
```

_Nouvelles tentatives_
Je trouve l'utilisation de backoff non triviale, est-ce qu'est simple log Sentry de la requête en erreur est suffisant (et avons nous les moyens de la rejouer avec les données concernées qui sont bien présentes en DB/fichier) ?

**2. la suppression du wrapper de PDF Shift**
Cool, sans le wrapper, je trouve le code encore meilleur.
Sinon est-ce acceptable que les données des PASS soient maintenant traités par AWS ?

[1] avec un peu d'aide extérieure ;)

2021-03-25 16:17 UTC, kemar commented
Du coup pas de veto sur `httpx` car l'argument de l'oubli de `itou_requests_config` est bon !

Et comme `httpx` propose le timeout, ce dernier doit être bien testé dans la lib, ce qui pourrait nous économiser des tests côté Itou.

L'idée de base c'est de ne pas geler l'application en cas d'appel à un service externe en rade et de pouvoir afficher une erreur à l'utilisateur.

2021-03-26 09:56 UTC, celine-m-s commented
Merci pour vos retours ! 

1. HTTPX

Va pour HTTPX alors ! En revanche, on utilise beaucoup `requests` dans le projet. On est bien d'accord que l'idée c'est de remplacer la lib partout ? Je viens d'ailleurs de découvrir qu'on utilise [`requests-mock`](https://github.com/jamielennox/requests-mock) dans les tests du module `external_data`. J'avais oublié ! :smile: 

2. Nouvelles tentatives

Je trouve aussi que l'installation d'une librairie uniquement à cet effet est disproportionné par rapport à notre usage. 

>  est-ce qu'est simple log Sentry de la requête en erreur est suffisant ?
A mon avis, oui.

> avons nous les moyens de la rejouer avec les données concernées qui sont bien présentes en DB/fichier
Cela dépend. Dans le cas de cet appel à PDF Shift, on a les données mais cela ne ferait pas trop sens, sauf si un utilisateur contacte le support pour recevoir le PDF. Dans tous les cas, je pense qu'on pourra se dépatouiller pour rejouer la requête à la main au besoin.

3. AWS

> Sinon est-ce acceptable que les données des PASS soient maintenant traités par AWS ?
Bonne question. Je viens d'envoyer un mail à PDF Shift pour savoir si leur API y tourne aussi et / ou s'ils ont prévu de migrer sur des serveurs français prochainement. Ils proposent, de manière optionnelle, [d'enregistrer les fichiers générés sur AWS](https://docs.pdfshift.io/#saving-the-document-to-amazon-s3) et de renvoyer non pas le PDF mais une URL vers le `bucket`. Nous, nous ne faisons que générer les PDF sans les enregistrer chez eux. Avec un peu de chance, leur API est hébergée en France.

2021-03-26 15:16 UTC, celine-m-s commented
@stephane @kemar, j'ai fini d'intégrer vos retours. J'ai pu remplacer `requests` dans tout le projet sauf dans le module allauth_adapters car les tests héritent de [ceux de allauth qui ont besoin de requests pour tourner](https://github.com/pennersr/django-allauth/blob/master/allauth/tests.py#L44-L68). Il faudrait que j'essaie de surcharger les tests de allauth avec un mock manuel mais je crains que ça ne fragilise nos tests.

2021-03-29 16:11 UTC, kemar approved these changes
LGTM Pour sécuriser le tout je passerais quand même en dur un `timeout=x` (je sais plus l'unité utilisée) aux derniers endroits on on fait des appels avec `requests`

2021-03-30 09:11 UTC, merged