Replacement de l’email d’assistance par le portail assistance
betagouv/itou pull request #609
Opened 2021-03-26 10:40 UTC by Keirua

### Quoi ?

Replacement de l’email direct d’assistance par [le portail assistance](https://assistance.inclusion.beta.gouv.fr) dans toute l’application.

### Pourquoi ?

Pour favoriser l’utilisation du portail et ainsi simplifier la gestion des tickets support.

### Comment ?

J’ai remplacé l’email direct d’assistance par [le portail assistance](https://assistance.inclusion.beta.gouv.fr) dans toute l’application :
 - emails
 - PDF du Pass
 - formulaires siae (siret incorrect au signup et à la création)

### Captures d'écran
Le signup, mais c’est pareil partout :

![Capture d’écran de 2021-03-26 11-37-03](https://user-images.githubusercontent.com/1223316/112619676-e31b0680-8e27-11eb-9619-601a846c114b.png)

2021-03-29 15:55 UTC, kemar requested changes
Un tout petit `rel="noopener"` et on est OK :)

2021-03-29 15:55 UTC, kemar commented on itou/www/siaes_views/forms.py
> +            assistance_html = f'<a href="{assistance_url}" target="_blank" class="alert-link">{assistance_url}</a>'
Comme on a pas mal de vieux browsers on ajoute en général un `rel="noopener"` quand il y a un `target="_blank"` https://mathiasbynens.github.io/rel-noopener/

Et est-ce qu'on ajoute aussi un `target="_blank"` dans les templates un peu plus haut pour rester constant ?

2021-03-30 12:15 UTC, Keirua commented on itou/www/siaes_views/forms.py
> +            assistance_html = f'<a href="{assistance_url}" target="_blank" class="alert-link">{assistance_url}</a>'
Corrigé. Merci pour ce lien ! La démo ne fonctionne plus (browser récent) mais à l’époque c’était incroyable.

2021-03-31 08:37 UTC, celine-m-s approved these changes
LGTM

2021-03-31 08:38 UTC, merged