CV maison
betagouv/itou pull request #621
Opened 2021-04-06 13:45 UTC by celine-m-s

Le titre et la description sont en français et au format texte.

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

---

Liens intéressant :

- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8

2021-05-05 09:11 UTC, kemar requested changes
Première passe terminée, cool :)

Tu peux éditer aussi le README du projet pour enlever les infos de l'ancien hack.

Il manque peut-être une doc de haut niveau pour dire claiement comment ça fonctionne, mais c'est peut-être l'objet de ton travail dans le repo privé ?

Je conseille d'attendre plusieurs revues pour mutualiser la prise en compte des feedbacks.

2021-05-05 09:11 UTC, kemar commented on config/settings/base.py
> +        "key_path": "resume",
Si je comprends bien c'est le nom du répertoire de stockage.

Mais est-ce qu'on va stocker tous les fichiers de tous les environnements (dev, staging, demo etc?) dans le même répertoire ?

2021-05-05 09:17 UTC, celine-m-s commented on itou/utils/storage/s3.py
> +    def generate_signature(self, string_to_sign):
Nous utilisons `boto` pour communiquer avec le bucket uniquement en dev. Pour la génération des creds, cette manière de faire est celle préconisée par [la documentation officielle](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html).

[Doc d'Amazon](https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html) : 

> If you are using one of the AWS SDKs (including the SDK for C++, SDK for Go, SDK for Java, AWS SDK for JavaScript, AWS SDK for .NET, SDK for PHP, SDK for Python (Boto3), or SDK for Ruby), you do not have to manually perform the steps of deriving a signing key and adding authentication information to a request. The SDKs perform this work for you. *You need to manually sign requests only if you are directly making HTTP or HTTPS requests.*

2021-05-05 09:23 UTC, celine-m-s commented on config/settings/base.py
> +        "key_path": "resume",
C'est de ma faute, c'est dans la documentation manquante. :)
Le bucket est indiqué en tant que variable d'environnement (`STORAGE_BUCKET_NAME`).
Ici, j'ai fait le choix d'un bucket par environnement pour les raisons suivantes : 
- le code est plus simple car on n'a pas à spécifier un chemin différent par environnement,
- apparemment, les 100 premiers mégas sont gratuits mais la doc est un peu contradictoire à ce sujet.
On peut bien sûr en discuter.

2021-05-05 09:27 UTC, celine-m-s commented on itou/templates/apply/submit_step_application.html
> +            {% bootstrap_field form.selected_jobs label_class="h5" %}
Cela permettait de faire ressortir les titres, sinon ils n'étaient pas assez grands.

J'avais fait cela quand je proposais à l'utilisateur le choix entre l'ajout d'un CV ou un lien. Il fallait alors mieux distinguer les grandes zones du formulaire (métiers, réponse et CV) car sinon ils se trouvaient au même niveau visuellement.
Mais tu as raison, ce n'est plus nécessaire. Je vais modifier cela.

2021-05-05 09:29 UTC, celine-m-s commented on itou/templates/apply/submit_step_application.html
> +        <h5>{{ form.resume_link.label }}</h5>
Il s'agit bien d'un titre car le champ associé est caché. Tu penses que je devrais en faire un label ?

2021-05-05 09:30 UTC, celine-m-s commented on itou/templates/apply/submit_step_send_resume.html
>  {% endblock %}
Bien vu ! Je le supprime d'emblée.

2021-05-05 09:31 UTC, celine-m-s commented on requirements/dev.txt
> +boto3==1.17.53  # https://github.com/boto/boto3
Tiens, c'est bizarre, il me semblait l'avoir transféré de `base.txt` à `dev.txt`. Cela a dû sauter avec le `rebase`. Merci, je corrige ça tout de suite.

2021-05-05 09:34 UTC, celine-m-s commented on itou/templates/storage/s3_upload.html
> +<script src='{% static "vendor/dropzone/dropzone.min.js" %}'></script>
Hum, non, je ne crois pas. Le CSS oui, mais pas le JS. 
Ce n'est pas très propre, en effet, mais je ne vois pas comment charger le CSS à partir du gabarit inclus.

2021-05-05 09:38 UTC, celine-m-s commented on itou/templates/apply/submit_step_application.html
> +            {% bootstrap_field form.selected_jobs label_class="h5" %}
Je trouve ça moins clair, surtout concernant le champ "Métiers recherchés", mais bon, c'est cohérent avec le reste de l'app.

![localhost_8080_apply_3850_step_application](https://user-images.githubusercontent.com/6150920/117122506-43da1f00-ad96-11eb-9eba-aca70dfb3b4f.png)

2021-05-05 09:40 UTC, celine-m-s commented on itou/templates/apply/submit_step_application.html
> +        <h5>{{ form.resume_link.label }}</h5>
J'en ai fait un label. A voir ce qu'en pensent les autres. :)

2021-05-05 09:41 UTC, kemar commented on itou/templates/storage/s3_upload.html
> +<script src='{% static "vendor/dropzone/dropzone.min.js" %}'></script>
Ah oui, j'ai pris le CSS pour du JS, désolé.

2021-05-05 09:44 UTC, kemar commented on itou/utils/storage/s3.py
> +    def generate_signature(self, string_to_sign):
Je pensais qu'il y aurait un truc avec `from botocore.auth import SigV4Auth`.

2021-05-05 09:49 UTC, celine-m-s commented on itou/templates/apply/process_details.html
> +        {% endif %}
Tu as raison ! Merci !

2021-05-05 10:04 UTC, celine-m-s commented on config/settings/base.py
> +AWS_S3_BUCKET_ENDPOINT_URL = "https://%s.%s" % (STORAGE_BUCKET_NAME, STORAGE_ENDPOINT_DOMAIN)
Tu as raison, c'est modifié.

2021-05-05 13:04 UTC, Keirua reviewed
Pareil que marc, première passe, pfiou ! Ya pas mal de boulot. C’est surtout des petits trucs et des demandes de précisions en ce qui me concerne

2021-05-05 13:06 UTC, celine-m-s commented on config/settings/base.py
> +        "timeout": 20000,  # in ms
C'est nous qui "timoutons" :laughing: . Je peux augmenter sans souci. Qu'en penses-tu ?

2021-05-05 13:07 UTC, celine-m-s commented on itou/static/css/itou.css
> +    border-style: dashed !important;
Eh oui, sinon `dropzone` prend l'ascendant.

2021-05-05 13:08 UTC, celine-m-s commented on itou/templates/storage/s3_upload.html
> +<script type="text/javascript">
:-/
Nous pourrons en rediscuter jeudi soir en équipe, je pense, car ce point a été soulevé par Stéphane dans Slack.

2021-05-05 13:12 UTC, celine-m-s commented on itou/utils/storage/s3.py
> +        config = settings.STORAGE_UPLOAD_KINDS[kind]
Si la clé n'est pas trouvée, une `KeyError` sera automatiquement levée par `settings.STORAGE_UPLOAD_KINDS[kind]`. J'ai hésité et j'ai pris le parti de la concision. 
A voir ce qu'en pensent les autres. :)

2021-05-05 13:14 UTC, celine-m-s commented on itou/utils/storage/s3.py
> +            key = key.encode("utf-8")
[C'est le protocole S3](docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html#sigv4-post-signature-calc) qui veut ça, il n'est pas possible de sélectionner un autre encodage. 
Mais je peux mettre la valeur en variable de classe.

2021-05-06 08:54 UTC, ikarius commented on config/settings/base.py
> +        "key_path": "resume",
J'ai vu les prix de stockage chez Clever, ça va c'est pas la mer à boire ...

2021-05-06 09:06 UTC, ikarius commented on config/settings/prod.py
> +S3_STORAGE_BUCKET_ENDPOINT_URL = "https://%s.%s" % (S3_STORAGE_BUCKET_NAME, S3_STORAGE_ENDPOINT_DOMAIN)
Pourquoi dupliquer les settings qui sont déjà dans `base.py` ?

2021-05-06 09:08 UTC, ikarius commented on itou/job_applications/factories.py
> +    resume_link = "https://server.com/rockie-balboa.pdf"
Eye of the Tiger

2021-05-06 09:10 UTC, ikarius commented on itou/job_applications/models.py
> +    resume_link = models.URLField(max_length=500, verbose_name="Lien vers un CV", blank=True)
Donc rattachement à la candidature ou au candidat. Cool ça !

2021-05-06 09:18 UTC, celine-m-s commented on config/settings/prod.py
> +S3_STORAGE_BUCKET_ENDPOINT_URL = "https://%s.%s" % (S3_STORAGE_BUCKET_NAME, S3_STORAGE_ENDPOINT_DOMAIN)
Etant donné que les deux derniers se basent sur `S3_STORAGE_ENDPOINT_DOMAIN`, j'ai besoin de sa valeur dans l'environnement actuel et pas dans celui de `base.py`.

Mais ce n'est pas idéal, je te l'accorde. Je vais réfléchir à ça.

2021-05-06 14:08 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1-Qualité des candidatures] Faire un système d'upload de CV propre]](https://trello.com/c/H01pX7sy/1491-c1-qualit%C3%A9-des-candidatures-faire-un-syst%C3%A8me-dupload-de-cv-propre)

2021-05-12 18:11 UTC, stephane reviewed
Première passe. Le code est concis, c'est cool.
Je refais une passe semaine prochaine sur l'utilisation (test réseau, etc) et ce sera tout bon pour moi.

2021-05-12 18:11 UTC, stephane commented on itou/templates/storage/s3_upload_script.html
> +            "{{ key }}": "{{ value }}",
s3_form_values semble uniquement venir de la propriété `form_values` de S3Upload qui ne contient rien de fourni par l'utilisateur donc c'est safe sinon il faut utiliser https://docs.djangoproject.com/fr/3.2/ref/templates/builtins/#json-script mais est-ce que ce n'est pas une bonne pratique que d'utiliser json_script pour passer toute la conf de s3_upload_script et retirer ainsi le templating Django du code JS (qui pourrait alors être un vrai `.js`) ?

2021-05-12 18:11 UTC, stephane commented on itou/utils/storage/s3.py
> +        config = default_options | config
Python moderne :heart_eyes:

2021-05-12 18:11 UTC, stephane commented on itou/templates/storage/s3_upload_form.html
> +</div>
Très chouette ce visuel sur ce qui est attendu de l'utilisateur :clap:

2021-05-13 12:16 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
> À quoi sert ; dans a href="#;" ?

Sans ça, l'utilisateur est rerouté en haut de la page après le transfert. Mais il y a peut-être une manière plus propre de le faire ?

2021-05-13 12:20 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h5">{% include "includes/icon.html" with icon="upload" size="30" %}</div>
J'ai un peu de mal à comprendre le commentaire sur l'accessibilité" : le `h5` est une classe ici, pas une balise HTML. Il y a un lien ?
J'ai utilisé les classes `h5` et `h6` pour utiliser le même espacement que pour les titres. Mais je peux mettre des `mb-2` si tu trouves que c'est mieux.

```
/* bootstrap */ 
.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
    margin-bottom: .5rem;
    font-weight: 500;
    line-height: 1.2;
}
```

2021-05-13 12:24 UTC, celine-m-s commented on itou/templates/storage/s3_upload_script.html
> +            $.post("{% url 'home:sentry_debug' %}", {
> Avec le SDK JS, il est aussi possible pour le client de polluer notre Sentry mais au moins, il passe pas par notre serveur et cela collecte plus d'infos.

J'y ai pensé aussi mais je me suis dit, comme toi, qu'importer une nouvelle lib JS pour une seule route était un peu disproportionné. 
Dans la mesure où notre code source est ouvert, n'importe qui peut connaître cette route sans même lire ce script. Est-ce que cela te semble dangereux ?

Je peux également enlever cette alerte, mais cela me semble important qu'on soit au courant si un problème a lieu dans l'échange. Qu'en penses-tu ?

2021-05-13 12:25 UTC, celine-m-s commented on itou/utils/resume/forms.py
>          widget=forms.TextInput(attrs={"placeholder": "https://www.mon_cv.fr/dfROS"}),
Ah oui, je peux même le supprimer ! Bien vu, merci !

2021-05-13 12:42 UTC, celine-m-s commented on itou/templates/storage/s3_upload_script.html
> +            alert("Ce document n'a pas pu être envoyé à cause d'un problème technique. Nous vous invitons à contacter notre support.");
C'est fait ! :)

2021-05-13 12:44 UTC, celine-m-s commented on itou/templates/storage/s3_upload_script.html
> +    submit_button.tooltip({"title": "Merci d'attendre la fin du transfert"});
Remplacé

2021-05-13 12:59 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
La façon "propre" de faire c'est de désactiver le comportement par défaut du lien en passant par le DOM avec `event.preventDefault();` et de ne lui attribuer que le comportement que tu souhaites.

2021-05-13 13:22 UTC, celine-m-s commented on itou/templates/storage/s3_upload_script.html
> +            "{{ key }}": "{{ value }}",
Super ! Je ne connaissais pas. 
J'ai donc remplacé les deux confs par ce mécanisme mais je préfère garder le _templating_ Django car cela me permet de regrouper le maximum de code dans `s3_upload_script.html`.

2021-05-13 13:39 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +</div>
Merci ! Je me suis inspirée du rendu actuel (Typeform).

2021-05-13 14:06 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
Merci de la réponse ! Je suppose que ceci n'est pas aussi propre ?

```
<a href="" onclick="event.preventDefault()">Choisissez un fichier</a>
```

J'aimerais éviter d'ajouter un sélecteur dans `s3_upload_script.html`.

2021-05-13 14:19 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
Non… car les attributs _inline_ viennent casser la [_Content Security Policy_](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy) et c'est un point sur lequel j'aimerais bien qu'on commence à travailler.

2021-05-13 14:30 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
Ca marche ! :ok_hand: Je modifie ça alors.

2021-05-13 14:45 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h6"><a href="#;">Choisissez un fichier</a> ou <b>glissez ici</b>.</div>
Est-ce que ça te paraît mieux ? https://github.com/betagouv/itou/pull/621/commits/ba67656b929389304890c09f5a2de11f41a18204

2021-05-18 13:34 UTC, stephane commented on itou/templates/storage/s3_upload_form.html
> +        <div class="h5">{% include "includes/icon.html" with icon="upload" size="30" %}</div>
Tu as raison.

2021-05-18 16:09 UTC, stephane reviewed
Je te propose que l'on fasse une passe finale finale demain :
- test en local sur mon poste
- schéma n°2, itou-private
- pur JS

et que l'on merge enfin cette PR \o/

2021-05-18 16:09 UTC, stephane commented on itou/templates/dashboard/edit_user_info.html
> -    {% bootstrap_form form exclude="resume_link" %}
Il n'y plus de form dans ce template ?!
Quid de la classe `js-submit-with-typeform`, est elle encore utile ?

2021-05-18 16:09 UTC, stephane commented on itou/templates/storage/s3_upload_script.html
> +            $.post("{% url 'home:sentry_debug' %}", {
Il ne manque plus que 2 arguments pour en faire un fichier JS pur !

2021-05-19 09:20 UTC, celine-m-s commented on config/settings/base.py
> +S3_STORAGE_ACCESS_KEY_ID = os.environ.get("S3_STORAGE_ACCESS_KEY_ID", "")
OK, c'est changé !

2021-05-19 09:21 UTC, celine-m-s commented on itou/templates/dashboard/edit_job_seeker_info.html
> +    {% bootstrap_form form %}
C'est un oubli, tout simplement ! Bien vue ! C'est modifié.

2021-05-19 09:26 UTC, celine-m-s commented on itou/templates/dashboard/edit_user_info.html
> -    {% bootstrap_form form exclude="resume_link" %}
:scream: 
Incroyable, j'ai supprimé le formulaire et ça ne se voit dans aucun test ! Merci !
J'ai l'ai donc remis et j'en ai profité pour supprimer la classe, désormais inutile, dans les trois formulaires où elle était encore mentionnée.

2021-05-19 09:35 UTC, stephane commented on itou/templates/dashboard/edit_user_info.html
> -    {% bootstrap_form form exclude="resume_link" %}
Penses tu pouvoir dormir sereinement maintenant que tu sais qu'il manque un test ?
:smiling_imp:

2021-05-19 09:54 UTC, celine-m-s commented on itou/templates/dashboard/edit_user_info.html
> -    {% bootstrap_form form exclude="resume_link" %}
Bah non... Rhaaaa. Mais dans ce cas on devrait tester ça partout, non ? Actuellement, on ne vérifie pas que les formulaires sont bien affichés.

2021-05-19 15:46 UTC, kemar approved these changes
LGTM

Bravo pour ce taf !

Quelques remarques de surface à traiter si elles font sens pour toi.

2021-05-19 15:46 UTC, kemar commented on itou/static/js/s3_upload.js
> +"use strict";
🤩

2021-05-19 15:46 UTC, kemar commented on itou/static/js/s3_upload.js
> +  );
Si tu regardes les autres fichiers `.js` dans `itou/static/js/`, tu verras qu'on utilise jamais les `;`.

Mais bon, vu qu'on a pas décidé d'une convention là dessus… 🙈 

Promis, je ne dirai rien non plus sur les classes CSS en `camelCase` alors qu'on a du `kebab-case` partout 🤣

2021-05-19 15:46 UTC, kemar commented on itou/templates/apply/submit_step_job_seeker_create.html
> +                Continuer avec un CV
Ça fait bizarre d'avoir un seul bouton "Continuer avec un CV". On va continuer de toute façon. Je laisserais "Continuer" seul.

![avecCV](https://user-images.githubusercontent.com/281139/118842229-4de93b00-b8c9-11eb-8249-ca6d51145fc2.png)

2021-05-19 15:46 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Ici l'icône de succès en forme de `v` apparaît de manière peu visible en transparence. J'ai testé sous plusieurs navigateurs. Ça doit venir de Dropzone…

![ok](https://user-images.githubusercontent.com/281139/118842602-a7516a00-b8c9-11eb-8342-8e3eb9794100.png)

2021-05-19 15:50 UTC, celine-m-s commented on itou/static/js/s3_upload.js
> +"use strict";
Copyright @stephane !

2021-05-19 15:52 UTC, celine-m-s commented on itou/templates/apply/submit_step_job_seeker_create.html
> +                Continuer avec un CV
La disparition du bouton "Continuer avec un CV" peut donner l'impression qu'on ne peut plus joindre de CV, surtout que l'étape a également été supprimée.
Pour ne pas troubler l'utilisateur, je pensais laisser ce bouton un mois pour le renommer en "Continuer". Le métier et Damien étaient d'accord. Qu'en penses-tu ?

2021-05-19 15:52 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Oui, ça vient de Dropzone. C'est le comportement par défaut.
On pourra le changer plus tard au besoin.

2021-05-19 15:54 UTC, kemar commented on itou/templates/apply/submit_step_job_seeker_create.html
> +                Continuer avec un CV
Ça m'est égal.

2021-05-19 15:54 UTC, celine-m-s commented on itou/templates/apply/submit_step_job_seeker_create.html
> +                Continuer avec un CV
Cette réponse me convient parfaitement !

2021-05-19 15:58 UTC, stephane commented on itou/static/js/s3_upload.js
> +  );
J'ai travaillé sur des projets sans `;` et finalement, je trouve que c'est mieux avec. Je suis tombé sur des pièges mais je ne sais plus lesquels...

:+1 pour les class CSS :)

2021-05-19 16:00 UTC, kemar commented on itou/static/js/s3_upload.js
> +  );
> J'ai travaillé sur des projets sans ; et finalement, je trouve que c'est mieux avec.

J'ai travaillé sur des projets avec `;` et finalement, je trouve que c'est mieux sans 🤣

2021-05-19 16:01 UTC, stephane commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
> On pourra le changer plus tard au besoin.

Ça commence à se voir que tu as envie de merger :rofl:

2021-05-19 16:01 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Clairement, j'insiste pas… mais on te fera la remarque un jour !

2021-05-19 16:02 UTC, stephane commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Sondage, @kemar as tu eu envie de cliquer sur la croix rouge qui s'affiche en cas d'erreur ?

2021-05-19 16:04 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
J'ai cliqué dessus mais genre, _like crazy_

2021-05-19 16:05 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Et rien ne se passait 🤣

2021-05-19 16:05 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
> Ça commence à se voir que tu as envie de merger :rofl:

En effet ! :-D
Je pense qu'il s'agit d'une V1 et qu'on pourra toujours modifier le rendu si on a des retours. Sauf si ça vous paraît vraiment gênant ? Auquel cas ça nous rajoute un peu de dev + de la revue métier et je fusionne au retour du séminaire.

2021-05-19 16:05 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
En rapide, je peux modifier l'opacité pour la rendre 100% opaque. Ca t'irait ?

2021-05-19 16:06 UTC, kemar commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Écoute c'est pas bloquant et je sais que ça vient de Dropzone. Donc on peut partir là dessus pour moi.

2021-05-19 16:11 UTC, celine-m-s commented on itou/templates/storage/s3_upload_form.html
> +        <div class="small">Type de fichier : PDF</div>
Ok !

2021-05-20 08:07 UTC, merged