Export CSV des candidatures
betagouv/itou pull request #622
Opened 2021-04-06 15:04 UTC by Keirua

### Quoi ?

Génère un export CSV de la liste des candidatures pour les prescripteurs et SIAE (resp. `/apply/prescriber/list` et `/apply/siae/list`).

### Pourquoi ?

Pour s’intégrer avec les outils, SI et habitudes de travail des différents acteurs.

### Comment ?

 - Ajout d’un lien vers un écran de téléchargement depuis le dashboard
 - L’écran de téléchargement contient des exports groupés par mois.
 - On peut télécharger tous les exports d’un mois donné au format CSV.

Le gros du problème c’est de prendre une `job_application` et de le convertir en un tableau pour le transmettre à un `csv_writer`.

J’ai opté pour une approche similaire à l’export excel `approvals.export_approvals` (export dispo dans une commande et une route admin). Ce qui me semble un bon compromis avec d’autres approches:

 - `serializer drf` (on ne veut pas du REST, c’est plus objet mais la sémantique est moins bonne)
 - `[django-rest-framework-csv](https://github.com/mjumbewu/django-rest-framework-csv/issues?q=is%3Aissue+is%3Aclosed)`, pareil, et ne semble pas maintenu

Contrairement à la route `ApprovalAdmin.export_approval`, on peut streamer le contenu de la réponse directement depuis le csv_writer, sans créer un fichier temporaire.

En l’état, je permets aux utilisateurs cet export de manière **synchrone**. Afin de réduire la sélection, malgré le groupement par mois, on pourra prévoir d’ajouter utiliser des filtres. Il est possible qu’un jour la sélection soit quand même trop grosse et que la requête soit trop longue.
Il sera alors sans doute nécessaire de générer cet export de [manière asynchrone](https://stackoverflow.com/questions/59729837/django-rest-framework-export-csv-data-from-models-in-background), puis de stocker le fichier généré, envoyer une notif mail lorsque l’export est disponible, etc.

### Captures d'écran

#### Un lien de plus dans le dashboard
(ici coté prescripteur, mais un bouton équivalent est dispo coté siae)

![Capture d’écran de 2021-04-06 17-02-01](https://user-images.githubusercontent.com/1223316/113732405-da64e300-96f9-11eb-917a-526c0597c09e.png)

#### La liste de exports

![Capture d’écran de 2021-04-06 17-02-09](https://user-images.githubusercontent.com/1223316/113732410-dafd7980-96f9-11eb-9248-09e32736ba83.png)

2021-04-13 10:52 UTC, celine-m-s requested changes
Bravo, gros boulot !! :muscle: :rocket: 

J'ai néanmoins vu quelques erreurs en testant manuellement. Par exemple, j'ai réalisé une auto-prescription (candidature spontanée par un employeur) : 
- le nom du candidat est son prénom et est entre guillemets, 
- son prénom est son nom, 
- le nom du prescripteur est le nom du candidat 
- le type de prescripteur est "Orienteur" alors qu'il s'agit d'une auto-prescription. Mais je pense qu'en fait j'ai mal compris ce champ. C'est la personne qui a effectué le diagnostic, c'est ça ? Si c'est le cas, je suggère de l'indiquer comme tel.

Je pense que cela est dû, en grande partie, à la construction du CSV à la main qui associe deux listes (en-tête et valeurs). Utiliser un dictionnaire permettrait d'éviter cela.

![image](https://user-images.githubusercontent.com/6150920/114540955-6a54e080-9c56-11eb-9db4-a4dd9dba0aab.png)

J'ai également décelé une utilisation inhabituelle, à mon sens, des vues dans Django ainsi que quelques méthodes qui auraient plutôt leur place dans les méthodes de QuerySet du modèle. N'hésite pas à me demander si ces points ont besoin d'être éclaircis.

2021-04-13 10:52 UTC, celine-m-s commented on itou/job_applications/models.py
> +        return self.sender_kind
Cette méthode, bien qu'utile, me perturbe.
`prescriber_type` laisse entendre que la méthode renvoie le type de prescripteur, alors qu'en fait elle renvoie le type de l'expéditeur. Elle devrait s'appeler `sender_kind`... sauf qu'un attribut porte déjà ce nom.
Que penses-tu de `display_sender_kind` ? 

```
    @property
    def display_sender_kind(self):
        kind = "Candidature spontanée"
        if self.sender_kind == JobApplication.SENDER_KIND_SIAE_STAFF:
            kind = "Auto-prescription"
        elif self.sender_kind == JobApplication.SENDER_KIND_PRESCRIBER:
            kind = "Orienteur"
            if self.is_sent_by_authorized_prescriber:
                kind = "Prescripteur habilité"
        return kind
```

Dans ce cas, les méthodes `_get_job_application_origin` et `_getprescriber_kind` deviennent inutiles.

2021-04-13 10:52 UTC, celine-m-s commented on itou/job_applications/csv_export.py
> +    if ja.sender_kind == JobApplication.SENDER_KIND_PRESCRIBER:
Voir également le commentaire sur la `property` `display_sender_kind`.

2021-04-13 10:52 UTC, celine-m-s commented on itou/www/apply/views/list_views.py
> +    job_applications = get_prescriber_job_application_list(request)
La répétition de ce code ne me choque pas car chaque vue est indépendante et explicite. En la lisant, on doit appréhender rapidement : 
- Le gabarit utilisé
- Les objets provenant de la base de données et la manière dont ils ont été récupérés (donc la requête). Si cette requête est utilisée dans une autre vue, alors une optimisation est envisageable [avec une méthode de `QuerySet`](https://docs.djangoproject.com/en/3.1/topics/db/managers/#from-queryset) ou de [`Manager`](https://docs.djangoproject.com/en/3.1/topics/db/managers/). [Lire à ce sujet notre doc interne](https://github.com/betagouv/itou-private/blob/master/docs/development/django.md#querysets)
- Les variables sont passées au gabarit
- Le type de réponse 
 
Appeler une méthode `get_prescriber_job_application_list` dans une vue qui concerne les demandeurs d'emploi me dérange beaucoup.

2021-04-13 10:52 UTC, celine-m-s commented on itou/www/apply/views/list_views.py
> +    job_applications_by_month = get_job_applications_by_month(job_applications)
Voir mes remarques précédentes. :)

2021-04-13 10:52 UTC, celine-m-s commented on itou/www/apply/views/list_views.py
> +    return generate_csv_export_for_download(job_applications, f"candidatures-{export_month}.csv")
Une réponse explicite est attendue ici, que ce soit avec un `render` ou une `HttpResponse`. Voir mes remarques précédentes concernant les vues.

2021-04-13 10:52 UTC, celine-m-s commented on itou/templates/apply/list_of_available_siae_exports.html
> +{% endblock %}
Je pense que ce bloc est inutile car tu ne lui passes rien.

2021-04-13 10:52 UTC, celine-m-s commented on itou/templates/apply/list_of_available_siae_exports.html
> +{% endblock %}
Beaucoup de code est partagé entre `list_of_available_siae_exports` et `list_of_available_prescriber_exports`. A mon avis, [un `include`](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#include) aurait été le bienvenu. :)

2021-04-13 10:52 UTC, celine-m-s commented on itou/templates/apply/list_of_available_prescriber_exports.html
> +    {% if not job_applications_by_month %}
Pourquoi commencer par la négation ? Je trouve `if job_applications_by_month` plus lisible.

2021-04-13 10:52 UTC, celine-m-s commented on itou/templates/apply/includes/info_csv.html
> +                	<li>Jeu de caractères: Unicode (UTF-16)</li>
En français, il y a toujours une espace avant et après les deux points (contrairement à l'anglais).

2021-04-13 13:24 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    return get_choice(choices=JobApplication.SENDER_KIND_CHOICES, key=ja.sender_kind)
Le problème de renvoyer `ja.sender_kind` c’est que ce n’est pas traduit (`prescriber`). Je peux mettre:

```suggestion
    return _(JobApplication.SENDER_KIND_CHOICES[ja.sender_kind])
```
mais j’ai l’impression que c’est équivalent à `get_choice`

2021-04-13 13:26 UTC, Keirua commented on itou/templates/apply/includes/info_csv.html
> +</div>
Faudra prévoir une règle de linter pour préserver sa santé fragile dans ce cas !

2021-04-13 13:38 UTC, kemar commented on itou/templates/apply/includes/info_csv.html
> +</div>
git le dit normalement, non ? "No newline at end of file"

> https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file

2021-04-13 13:39 UTC, kemar commented on itou/templates/apply/includes/info_csv.html
> +                	<li>Jeu de caractères: Unicode (UTF-16)</li>
Au fait, pourquoi `utf-16` et pas `utf-8` ?

2021-04-13 14:00 UTC, Keirua commented on itou/templates/apply/list_of_available_prescriber_exports.html
> +    {% if not job_applications_by_month %}
C’est vrai. J’ai repris la structure de `list_for_siae.html`.

2021-04-14 10:05 UTC, kemar commented on itou/templates/apply/list_of_available_prescriber_exports.html
> +    {% if not job_applications_by_month %}
Ça c'est un avis personnel de chaque développeur.

Je commence souvent par tester la condition négative afin d'éliminer l'erreur ou l'absence d'information car le l'action a effectuer est souvent très courte (ici le message "Aucune candidature pour le moment") VS la logique positive très longue.

Il n'y a pas de bon choix :)

2021-04-14 12:23 UTC, kemar commented on itou/job_applications/csv_export.py
> +    for job_application in job_applications.iterator():
Je pense qu'`iterator` est utilisé pour des raisons de performances de l'ORM :)

> https://docs.djangoproject.com/en/3.1/topics/db/optimization/#use-iterator

Tu confirmes ?

2021-04-14 12:25 UTC, kemar requested changes
Pas grand chose à rajouter après la revue pointilleuse de @celine-m-s !

Pas mal de points à traiter dans ses commentaires mais la base est bonne, c'est surtout des _best-practices_ Django à s'approprier :)

2021-04-14 12:27 UTC, celine-m-s commented on itou/job_applications/csv_export.py
> +    for job_application in job_applications.iterator():
Oh, super ! Je ne connaissais pas !

2021-04-15 08:51 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    return response
Je n’ai pas compris le premier point ? Il faut renvoyer une HttpResponse en dernière étape d’un controller, mais est-ce que le problème c’est que:
 - a) je renvoie cet objet depuis une fonction
  -b) la fonction en question n’est pas dans la vue ?
Concernant le second point je regarde pour utiliser une FileResponse, effectivement je vais pouvoir faire quelques adaptations.

2021-04-15 09:15 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    return dt.strftime(DATE_FMT) if dt else ""
Je m’en sers pour formatter toutes les dates, et des fois on en a pas (ex: pas d’approval).

2021-04-15 09:42 UTC, Keirua commented on itou/www/apply/views/list_views.py
> +    job_applications = get_prescriber_job_application_list(request)
Alors j’ai les points en tête mais je ne vois pas en quoi ils ne sont pas respectés ici. Une indirection par un appel de fonction ne masque pas l’intention et au contraire avec un nommage adapté on gagne en clarté. Des controlleurs qui font ~2 lignes avec des conditions en font finalement 2.
Par ailleurs je suis sceptique quand à l’idée qui consiste à dupliquer 3x le même bout de code.

2021-04-15 09:51 UTC, Keirua commented on itou/templates/apply/includes/info_csv.html
> +</div>
Sans doute mais j’ai pas encore saisi l’importance du truc (esthétique?).
Un [.editorconfig](https://editorconfig.org/), éventuellement un plugin [si éditeur qui ne le supporte pas nativement](https://editorconfig.org/#download) et on en parle plus jamais hein.

2021-04-15 13:05 UTC, Keirua commented on itou/templates/apply/includes/info_csv.html
> +                	<li>Jeu de caractères: Unicode (UTF-16)</li>
Aucune bonne raison (mais ça devait résoudre un truc pendant les tests) finalement.
Passer en UTF-8 corrige le bug de Libreoffice qui affiche la première colonne (le nom) avec des guillemets. Toutes les colonnes ont des guillemets pour des raisons d’échappement.

2021-04-15 13:06 UTC, Keirua commented on itou/templates/apply/list_of_available_prescriber_exports.html
> +    {% if not job_applications_by_month %}
je laisse tel quel

2021-04-15 13:06 UTC, Keirua commented on itou/templates/apply/list_of_available_siae_exports.html
> +{% endblock %}
J’ai factorisé pour n’utiliser qu’un template

2021-04-15 13:07 UTC, Keirua commented on itou/www/apply/views/list_views.py
> +    job_applications = get_prescriber_job_application_list(request)
appel de fonction supprimé

2021-04-15 13:08 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    for job_application in job_applications.iterator():
J’ai utilisé un `csv.DictWriter` et `iterator`.

2021-04-15 13:08 UTC, Keirua commented on itou/www/apply/views/list_views.py
> +    job_applications = job_applications.filter(created_at__year=year, created_at__month=month)
done

2021-04-15 13:09 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    return prescriber_name
Corrigé via `JobApplication.display_sender_kind`

2021-04-15 13:10 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    return get_choice(choices=JobApplication.SENDER_KIND_CHOICES, key=ja.sender_kind)
Corrigé via `JobApplication.display_sender_kind`

2021-04-15 13:11 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    "Prénom candidat",
2 bugs corrigés:
 - un par libreoffice pour de l’utf-8
 - les bonnes colonnes via le `DictWriter` qui permet de mieux s’y retrouver.

2021-04-15 13:11 UTC, Keirua commented on itou/job_applications/csv_export.py
> +    if ja.sender_kind == JobApplication.SENDER_KIND_PRESCRIBER:
Corrigé via `JobApplication.display_sender_kind`

2021-04-15 13:13 UTC, Keirua commented on itou/job_applications/csv_export.py
> +from itou.metabase.management.commands._utils import get_choice
supprimée avec `display_sender_kind`

2021-04-15 13:14 UTC, Keirua commented on itou/templates/apply/includes/info_csv.html
> +</div>
Corrigé à la main pour cette fois-ci, je rajouterais un .editorconfig dans une autre PR.

2021-04-15 13:14 UTC, Keirua commented on itou/www/apply/views/list_views.py
> +    job_applications_by_month = get_job_applications_by_month(job_applications)
done

2021-04-15 13:14 UTC, Keirua commented on itou/templates/apply/list_of_available_siae_exports.html
> +{% endblock %}
supprimé

2021-04-15 13:16 UTC, Keirua commented on itou/www/apply/views/list_views.py
> +    )
introduction de `JobApplicationQuerySet.with_monthly_counts` pour y répondre.

2021-04-27 09:17 UTC, Keirua commented
@kemar je pense que https://github.com/betagouv/itou/pull/622/commits/85cc2a0b87b241333c7b5fa20dcf4e1bf4b6fa24 colle plus à ce qu’on veut

2021-04-27 09:58 UTC, kemar approved these changes
LGTM 👍 

Remarques minimes :

1. une petite typo à corriger
1. je vois toujours le "No newline at end of file" dans `info_csv.html` ?

2021-04-27 09:58 UTC, kemar commented on itou/templates/apply/includes/info_csv.html
> +                Les exports sont au <a href="https://fr.wikipedia.org/wiki/Comma-separated_values" target="_blank" rel="noreferrer noopener">format CSV</a>: il s’agit d’un format texte lisible dans E
Il manque un "e" dans "séparée par un**E** virgule". Est-ce bien sensé ? 🤣 

Il manque aussi un espace insécable à la fin de la phrase.

Pour arroser le tout d'un peu de _bike-shedding_ : l'escpace insécable se matérialise-t-il par une entité HTML `&nbsp;` ou par un caractère unicode ` ` ? Vous avez deux heures.

2021-04-27 09:58 UTC, kemar commented on itou/job_applications/csv_export.py
> +        eligibility = "oui"
Il y a probablement une ambiguïté ici pour les exports du passé à cause de la complexité des règles métier de `EligibilityDiagnosis`. Mais on vivra avec pour le moment.

2021-04-27 09:58 UTC, kemar commented on itou/job_applications/csv_export.py
> +    seeker = job_application.job_seeker
C'était fatiguant d'écrire `job_seeker` ? 🤣

2021-04-27 12:12 UTC, Keirua commented on itou/templates/apply/includes/info_csv.html
> +                Les exports sont au <a href="https://fr.wikipedia.org/wiki/Comma-separated_values" target="_blank" rel="noreferrer noopener">format CSV</a>: il s’agit d’un format texte lisible dans E
Et pourtant, en matière de microtypographie, on peut noter les apostrophes courbes !

2021-04-27 16:05 UTC, celine-m-s approved these changes
LGTM! Le code est très agréable à lire, c'est top.
J'ai juste remarqué un petit détail : le premier zéro du numéro de téléphone est échappé chez moi (LibreOffice sans style particulier). Ce n'est pas important et ça ne mérite pas d"investigation, à mon avis, mais je le mentionne au cas où.
![image](https://user-images.githubusercontent.com/6150920/116274436-f6045c00-a782-11eb-990b-69089410adc5.png)
Je pense que c'est dû à LibreOffice.

2021-04-28 07:27 UTC, Keirua commented
Bien vu ! C’est bien [un souci avec libreoffice](https://ask.libreoffice.org/en/question/246295/how-can-i-import-a-csv-in-calc-with-the-leading-zeros-that-are-in-the-csv-file/). Là où c’est particulièrement traitre, c’est que dans l’aperçu les numéros sont bien affichés avec le 0 initial, mais une fois importé la colonne est transformé en type "nombre" et le zéro est carrément enlevé. J’ajoute une précision à ce sujet dans la zone d’info. Je ne peux pas tester avec Office.

2021-04-28 08:00 UTC, merged