Améliorations mineures metabase
betagouv/itou pull request #625
Opened 2021-04-08 15:04 UTC by vgrange

### Quoi ?

Au menu :

- un refacto suggéré par @stephane 
- l'ajout des codes INSEE dans metabase

### Comment reviewer ?

Commit par commit.

2021-04-08 15:05 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [en tant qu'utilisateur de Metabase, j'ai besoin d'une table de correspondance entre les codes communes et la latitude/longitude](https://trello.com/c/yejx4qmu/1637-en-tant-quutilisateur-de-metabase-jai-besoin-dune-table-de-correspondance-entre-les-codes-communes-et-la-latitude-longitude)

2021-04-09 09:07 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter la colonne date de création de la fiche de poste à la table "fiches de poste"](https://trello.com/c/CiMZgt7k/1643-ajouter-la-colonne-date-de-cr%C3%A9ation-de-la-fiche-de-poste-%C3%A0-la-table-fiches-de-poste)

2021-04-23 14:28 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C2] prévenir injections SQL](https://trello.com/c/JcgJ0efa/1680-c2-pr%C3%A9venir-injections-sql)

2021-04-23 14:28 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Industrialisation d'une requête SQL](https://trello.com/c/JJrsEIuO/1667-industrialisation-dune-requ%C3%AAte-sql)

2021-04-27 08:42 UTC, stephane requested changes
Il faut reconnaître que l'escaping des arguments est pénible à réaliser et que dans notre situation cela se discute car nous maîtrisons (normalement) la chaîne d'injection, mais plus la management command devient complexe plus c'est rassurant d'avoir ce mécanisme en place.

Et en cas de doute, je relis ce warning ;)
https://www.psycopg.org/docs/usage.html#the-problem-with-the-query-parameters

Je n'ai pas en tête solution évidente à te proposer pour stocker les résultats intermédiaires des queries. Une piste serait d'utiliser l'API de cache de Django :

https://docs.djangoproject.com/en/dev/topics/cache/#django.core.caches.cache.get_or_set

2021-04-30 13:14 UTC, vgrange commented on itou/metabase/management/commands/_job_applications.py
> +        "lambda": get_job_application_origin,
Oui bon point, c'est souvent une lambda mais parfois une fonction. Will do.

2021-04-30 13:18 UTC, vgrange commented on itou/metabase/management/commands/_job_applications.py
> +            "Origine détaillée de la candidature (employeur EI, ACI..." " candidat, orienteur, prescripteur PE, ML...)"
Un petit hiccup de black qui arrive parfois. Bien vu, je fixe.

2021-04-30 13:21 UTC, vgrange commented on itou/metabase/management/commands/_job_seekers.py
> +        "lambda": lambda o: len(
`o.job_applications.all()` est déjà chargé par un prefetch_related en amont, donc ne cause aucune requête SQL en plus.

En revanche si je fais `o.job_applications.filter(...).count()` à la place, alors là bam, je cause 10K requêtes SQL car mon prefetch_related n'est plus utilisé.

2021-04-30 13:22 UTC, vgrange commented on itou/metabase/management/commands/_organizations.py
> +        "comment": "Code SAFIR Pôle Emploi",
Bien vu. Will fix.

2021-04-30 13:24 UTC, vgrange commented on itou/metabase/management/commands/_siaes.py
> +        # We have to do all this in python to benefit from prefetch_related.
Cf ma réponse plus haut.

2021-04-30 13:37 UTC, vgrange commented on itou/metabase/management/commands/_siaes.py
> +            [ja for ja in o.job_applications_received.all() if ja.sender_kind == JobApplication.SENDER_KIND_SIAE_STAFF]
Non tant qu'il y a un `prefetch_related("job_applications_received")` en amont. Mais ton insistance me donne un doute, je vais donc faire un test complet pour tirer ça au clair.

2021-04-30 13:53 UTC, vgrange commented on itou/metabase/management/commands/_siaes.py
> +            [ja for ja in o.job_applications_received.all() if ja.sender_kind == JobApplication.SENDER_KIND_SIAE_STAFF]
Je viens de faire un test complet, en activant les logs SQL en local etc. J'ai testé uniquement le champ `total_embauches` de `_job_seekers` sur un dry run suite à ton commentaire initial plus haut. Et j'ai commenté tous les autres prefetch_related que `"job_applications"`.

J'obtiens ceci : https://www.evernote.com/l/ABIpc4iU68JCEbfJkysz0qkuO1JLdrjEESs

Tu peux observer qu'il ne fait pas une requête à chaque user pour récupérer ses job_applications, mais qu'il récupère bien toutes les job_applications en amont en 1-2 requêtes seulement. Je les ai mises en gras rouge dans l'output.

2021-04-30 13:58 UTC, vgrange commented on itou/metabase/management/commands/populate_metabase.py
>      _approvals,
Ca rejoint la discussion sur le prefixe `_`.
Ce que je pourrais faire c'est :
- un dossier pour les libs de populate_metabase
- un dossier pour les libs de populate_metabase_fluxiae
- un dossier pour les libs communes aux deux
T'en dis quoi ?

2021-04-30 13:59 UTC, vgrange commented on itou/metabase/management/commands/populate_metabase.py
> +        extras.execute_values(self.cur, insert_query, data, template=None)
Ok si tu veux.

2021-04-30 14:01 UTC, vgrange commented on itou/metabase/management/commands/populate_metabase.py
>          self.cur.execute(f"CREATE TABLE {table_name}_new ({statement});")
A suivre au prochain épisode ;-)

2021-04-30 14:01 UTC, vgrange commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +            when mission_descriptif ilike '%AIEHPAD%'
Joker.

2021-04-30 14:02 UTC, vgrange commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +    CONCAT(
Joker.

2021-04-30 14:05 UTC, merged

2021-05-03 05:42 UTC, stephane commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +            when mission_descriptif ilike '%AIEHPAD%'
Où se trouve le code de création de la table fluxIAE_Mission pour que je puisse effectuer un test et proposer un index?

2021-05-03 05:43 UTC, stephane commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +    CONCAT(
Que veux dire « Joker » ici ? Plus tard, OSEF, why not? :)

2021-05-03 08:24 UTC, vgrange commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +            when mission_descriptif ilike '%AIEHPAD%'
C'est la méthode `populate_fluxiae_view` dans `populate_metabase_fluxiae.py`.

Tu veux typiquement lui rajouter un paramètre pour dire quelles colonnes indexer.

Par exemple `def populate_fluxiae_view(self, vue_name, skip_first_row=True, columns_to_index=[]):`

2021-05-03 08:26 UTC, vgrange commented on itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
> +    CONCAT(
Joker dans le sens "je passe" =)

Perso je préfère `CONCAT`, plus explicite.

Par ailleurs je n'ai pas modifié ce script, donc c'est un peu hors sujet de cette PR. Je l'ai juste déplacé, d'où le fait qu'il apparait dans le diff de cette PR, mais il n'est ni nouveau ni modifié par cette PR.

2021-05-06 12:20 UTC, stephane commented on itou/metabase/management/commands/_siaes.py
> +            [ja for ja in o.job_applications_received.all() if ja.sender_kind == JobApplication.SENDER_KIND_SIAE_STAFF]
Autant pour moi, `job_applications` est une relation chargée par prefetch_related ici.