Possibilité d’éditer l’email d’un demandeur (tant que l’email n’est pas confirmé)
betagouv/itou pull request #630
Opened 2021-04-13 13:04 UTC by Keirua

### Quoi ?

Possibilité, pour les professionnels, d’éditer l’email d’un demandeur (tant que l’email n’est pas confirmé).

### Pourquoi ?

Les professionnels ne peuvent pas modifier l'adresse email du candidat

### Comment ?

Ajout de l’email dans le formulaire d’édition d’un utilisateur, dans les cas concernés.

### Captures d'écran (optionnel)

![Capture d’écran de 2021-04-13 15-03-02](https://user-images.githubusercontent.com/1223316/114556871-6b433d80-9c69-11eb-839c-c49511cae1a4.png)

2021-04-13 15:13 UTC, stephane requested changes
Bravo, belle PR !
LGTM pour moi après prise en compte des remarques.

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        job_application.job_seeker.save()
Un autre approche pour éviter le save() serait de faire (mais c'est du pinaillage à toi de voir ce qui te paraît plus clair) :
```python
siae = SiaeWithMembershipFactory()
job_application = JobApplicationSentByPrescriberFactory(to_siae=siae, job_seeker__created_by=siae.members.first())
```
Il y a aussi certainement moyen de faire un truc un peu trop smart avec Factory Boy...

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        self.client.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = job_application.to_siae.pk
Petite astuce ORM Django, pour éviter le chargement de l'instance `to_siae` lorsque seul l'ID est nécessaire, c'est de faire `job_application.to_siaie_id`.

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        job_seeker = get_user_model().objects.get(id=job_application.job_seeker.id)
Dans ma PR sur les invitations, j'ai remplacé les `get_user_model` par `from itou.users.models import User` comme discuté à notre dernière réunion.

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        self.assertEqual(job_seeker.email, new_email)
Nickel !

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        response = self.client.post(confirm_email_url)
Le but ici n'est pas de validé que le mécanisme de confirmation des email fonctionne.
J'aurais plutôt simplement modifié le modèle pour noter l'email comme confirmé.
Cela peut faciliter la maintenance des tests si la méthode de validation change, cela rend les tests plus rapides.

2021-04-13 15:13 UTC, stephane commented on itou/www/dashboard/tests.py
> +        response = self.client.post(url, data=post_data)
Est-ce que tu peux ajouter un test pour confirmer que le POST est pris en compte (et que le champ `email` est ignoré) pour valider que si le nouvel email est ignoré ce n'est pas à cause des données POST non valides.

2021-04-14 09:28 UTC, kemar requested changes
Deux choses qui me paraissent importantes à modifier :

- vérifier dans les tests le pattern post/redirect/get
- pas la peine de vérifier le mécanisme de confirmation d'email

2021-04-14 09:28 UTC, kemar commented on itou/www/dashboard/tests.py
> +        new_email = "bidou@yopmail.com"
Wesh bidou :D

2021-04-14 09:28 UTC, kemar commented on itou/www/dashboard/tests.py
> +        job_application.job_seeker.save()
Je sais que tu t'es basé sur le test existant pour écrire celui-ci, mais IMO la suggestion de @stephane est plus lisible avec moins de lignes.

En règle générale on se repose beaucoup sur Factory Boy pour économiser des `save()` dans les tests.

2021-04-14 09:28 UTC, kemar commented on itou/www/dashboard/tests.py
> +        response = self.client.post(confirm_email_url)
+1 sur cette remarque, le mécanisme de confirmation est déjà bien testé dans la lib tierce et dans les tests des tunnels d'inscription.

2021-04-14 09:28 UTC, kemar commented on itou/www/dashboard/tests.py
> +        response = self.client.post(url, data=post_data)
Après un `post`, on conseille de déclencher un `self.assertEqual(response.status_code, 302)` pour s'assurer qu'on a pas oublié la sécurité post/redirect/get.

2021-04-14 15:37 UTC, stephane commented on itou/www/dashboard/tests.py
> +        self.client.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = job_application.to_siae.pk
En fait, cette ligne est un NOP car https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.Client.session
(je viens de découvrir cela à l'instant).
Je n'ai pas testé mais je pense que le middleware ItouCurrentOrganizationMiddleware fait déjà le job.

2021-04-15 13:33 UTC, Keirua commented on itou/www/dashboard/tests.py
> +        response = self.client.post(confirm_email_url)
En effet, j’ai piqué un exemple un peu plus loin sans trop faire gaffe au contexte (le changement d’email: là on peut avoir envie d’un test de bout en bout)

2021-04-15 13:42 UTC, Keirua commented on itou/www/dashboard/tests.py
> +        response = self.client.post(url, data=post_data)
Ha ! Je l’avais justement enlevé pour alléger le test (avec l’idée que ce cas est déjà géré par les nombreux autres tests) mais c’est quand même un bonne idée de l’avoir.

2021-04-15 14:01 UTC, Keirua commented on itou/www/dashboard/tests.py
> +        response = self.client.post(confirm_email_url)
```
EmailAddress.objects.create(user=job_seeker, email=job_seeker.email, verified=True)
```
et tout le bloc disparait, tss

2021-04-15 14:17 UTC, Keirua commented on itou/www/dashboard/tests.py
> +        self.client.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = job_application.to_siae.pk
En effet la ligne concernée n’est pas nécessaire

2021-04-15 14:25 UTC, Keirua commented on itou/www/dashboard/tests.py
> +        self.client.session[settings.ITOU_SESSION_CURRENT_SIAE_KEY] = job_application.to_siae.pk
géré par le middleware

2021-04-19 18:13 UTC, kemar approved these changes
LGTM

2021-04-20 06:59 UTC, stephane approved these changes
LGTM
Je note au passage que faisons un filter sur l'adresse e-mail seule (ce qui est cohérent avec les contraintes de DB) contrairement à ce que fais allauth avec un check sur le couple user et email.

2021-04-20 08:46 UTC, merged

2021-06-17 09:17 UTC, Keirua commented
https://trello.com/c/mhIfhubn/1628-c1-je-veux-modifier-lemail-du-candidat-que-jai-orient%C3%A9