Changement du schéma de numérotation des PASS IAE
betagouv/itou pull request #641
Opened 2021-04-20 14:15 UTC by kemar

### Quoi ?

Changement du schéma de numérotation des PASS IAE.

### Pourquoi ?

L'ancien schéma de numérotation nous aurait permis de délivrer au maximum **99.999** par an.

Or on s'achemine vers davantage de PASS IAE délivrés cette année.

### Comment ?

On passe du schéma :

> PRÉFIX (5 caractères) + ANNEE (2 caractères) + NUMÉRO (5 caractères)

Au schéma :

> PRÉFIX (5 caractères) + NUMÉRO (7 caractères)

Le maximum possible passera à **9.999.999**.

### Autre

À voir avec le métier : à partir de quand on déploie ce système ?

2021-04-20 14:16 UTC, kemar commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Nouvelle numérotation des PASS](https://trello.com/c/iHVv1Ubx/1648-c1-nouvelle-num%C3%A9rotation-des-pass)

2021-04-21 10:03 UTC, stephane requested changes

2021-04-21 10:43 UTC, ikarius commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
Pourquoi un problème d'unicité ?

2021-04-21 11:07 UTC, kemar commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
> Nous avons ici un potentiel problème d'unicité

Tout à fait :) [Il existe en prod même s'il est rare](https://sentry.io/organizations/itou/issues/2327742622/?project=5671910&query=is%3Aunresolved). Il est lié à la boucle `while` plus haut, là où tu as trouvé le commentaire sur `UPSERT`.

Dans mes souvenirs ça n'était pas trivial de mettre l'`UPSERT` et je n'ai pas pris le temps de creuser.

Je vais regarder le `select_for_update` auquel je n'ai pas pensé et profiter de cette PR pour l'implémenter !

Je la repasse en `draft` et je reviens vers toi en si j'ai besoin d'un conseil.

2021-04-21 12:32 UTC, kemar commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
@stephane je veux bien ton avis sur https://github.com/betagouv/itou/pull/641/commits/be162a68a9d4cb55cf6a7eb625203cdaa39b3ef8 car je suis pas hyper familier

2021-04-21 12:33 UTC, kemar commented
J'en profite pour utiliser l'index lol

![Capture d’écran 2021-04-21 à 13 28 48](https://user-images.githubusercontent.com/281139/115554153-74a65880-a2ae-11eb-9f94-c0f50430ac17.png)

2021-04-21 12:39 UTC, kemar commented on itou/approvals/models.py
> +                if Approval.objects.filter(number=self.number).exists():
Je passerai les `if` sur une seule ligne au terme de la revue.

2021-04-21 13:14 UTC, stephane commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
Comme discuté en visio, `get_next_number` seulement dans le save et drop du field dans l'admin (et drop du if).

2021-04-21 14:05 UTC, kemar commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
Du coup logique de numérotation centralisée ici https://github.com/betagouv/itou/pull/641/commits/ad86b53a98dba9870ca083e24c86bd05c80ff47b c'est bien mieux mais il reste cette incompréhension de la logique transactionnelle…

2021-04-21 14:24 UTC, stephane approved these changes
C'est simple et c'est beau parce que c'est simple !
LGTM

2021-04-21 17:13 UTC, kemar commented
Après discussion avec le support, le champ `number` doit pouvoir accepter une valeur arbitraire afin de pouvoir délivrer un agrément Pôle emploi déjà existant https://github.com/betagouv/itou/pull/641/commits/a54db0bf090fe7d6ac9b0397909ec8f186927595

Ça ne change pas la logique de fond.

2021-04-23 09:13 UTC, vgrange requested changes
Une question pour ma curiosité, et une demande de lever une exception le jour où on dépasse la limite.

Sinon, LGTM !

2021-04-23 09:13 UTC, vgrange commented on itou/approvals/models.py
> +            return f"{Approval.ASP_ITOU_PREFIX}{next_number:07d}"
Je propose de lever une exception le jour où on dépasse le max (99 99999).

Les développeurs du futur lointain en seront reconnaissants.

2021-04-25 09:21 UTC, kemar commented on itou/approvals/tests.py
> +        Approval.objects.all().delete()
Ça ne servait à rien en effet, j'ai supprimé les commits concernés.

2021-04-25 09:26 UTC, kemar commented on itou/approvals/models.py
> +            Approval.objects.filter(number__startswith=Approval.ASP_ITOU_PREFIX).order_by("created_at").last()
Tout est clair maintenant… https://github.com/betagouv/itou/pull/641/commits/7dac0c4958dbf8baf1fc41953f216f0a70f4b9f9 😱

2021-04-26 09:22 UTC, stephane commented
Et tout devient plus clair :grin:

C'est justement l'occasion de ne pas l'activer !
Je peux faire une review de toutes les vues pour l'ajouter où c'est manquant et faire une doc pour expliciter tout ça.

2021-04-26 09:24 UTC, stephane requested changes
Je ne suis pas d'accord avec l'activation de ATOMIC_REQUESTS.
Je serais même d'avis de passer en autocommit off (mais c'est un autre débat).

2021-04-26 09:25 UTC, kemar commented
> Je ne suis pas d'accord avec l'activation de ATOMIC_REQUESTS.

Moi je suis pour au contraire. On va en débattre au point tech.

2021-04-26 13:46 UTC, kemar commented on itou/approvals/models.py
> +            return f"{Approval.ASP_ITOU_PREFIX}{next_number:07d}"
Ok vendu

2021-04-27 15:58 UTC, kemar commented on itou/www/apply/views/process_views.py
> +@transaction.atomic
> **mais le décorateur me va aussi...**

À moi aussi 🤣 Libre à toi de remplacer par des `with transaction.atomic()` au moment de ton cleanup.

> Cette vue est intéressante car elle contient un try avec un save() et dans ce cas, les 2 premiers forms sont bien enregistrés même si la transition a échoué. Est-ce bien ce que l'on veut ici ?

Tu es certain de ce que tu avances ? Je ne trouve pas ce point [dans la documentation de Django](https://docs.djangoproject.com/en/3.2/topics/db/transactions/) ?

2021-04-27 16:09 UTC, celine-m-s approved these changes
LGTM

2021-04-28 06:44 UTC, stephane commented on itou/www/apply/views/process_views.py
> +@transaction.atomic
Grâce à toi, je suis certain que je viens de dire une connerie ! Merci.

« If there is an exception, the changes are rolled back. »
Exception catchée ou non, et ça c'était pas clair pour moi en lisant la doc, j'ai écrit un bout de code pour le vérifier.

2021-04-28 08:40 UTC, merged