Liste des fiches salarié par statut
betagouv/itou pull request #665
Opened 2021-05-05 13:30 UTC by ikarius

### Quoi ?

Une liste des fiches salarié disponibles et à traiter pour les SIAE

### Pourquoi ?

Première étape du traitement des fiches salarié par les SIAE, cette liste permet
de filtrer les F.S. par état et d'accéder aux actions possibles.

A noter qu'au début du cycle de vie de la F.S, elle n'est encore qu'une candidature (`JobApplication`).

La liste est donc mixte et contient:
- une liste de `JobApplication` pour l'état 'Nouvelle fiche salarié"
- une liste d' `EmployeeRecord` une fois les informations manquantes saisies par l'utilisateur pour les autres statuts

### Comment ?

Une liste avec navigation et un sélecteur de statut

### Captures d'écran (optionnel)

### Autre (optionnel)

Les CTA ne sont pas implémentés, ils seront reliés lors de l'implémentation de la deuxième partie, qui permettra de compléter et de valider les informations des F.S.

Le lien du dashboard permettant l'accès sera désactivé avant de fusionner / MEP

This is not pixel perfect. 

---

2021-05-06 08:31 UTC, kemar commented
> This is not pixel perfect.

https://www.joshwcomeau.com/css/pixel-perfection/

2021-05-06 09:59 UTC, kemar requested changes
Première passe OK. Voici mes retours.

2021-05-06 09:59 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +                <p class="m-0">Numéro de PASS IAE (agrément) : <b>{{ item.approval.number }}</b></p>
Tu peux utiliser `item.approval.number_with_spaces` ici pour une meilleure lisibilité.

2021-05-06 09:59 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +        <div class="p-2">
Le `if` devrait se situer après le `</div>` fermant.

2021-05-06 09:59 UTC, kemar commented on itou/templates/employee_record/list.html
> +{% block title %}{{ siae.display_name }}{{ block.super }}{% endblock %}
"Fiches salarié ASP" à ajouter aussi dans le bloc `title`, comme dans le `<h1>`, c'est ce qui sera affiché en nom de bookmark.

2021-05-06 09:59 UTC, kemar commented on itou/www/employee_record_views/views.py
> +    ]
Il y a 2 choses qui me démangent : 

1. ça fait 4 requêtes SQL
2. les données sont très liées au formulaire et il faut aller voir dans le template pour comprendre avec le zip que les données sont liées

Pour le point 1, une seule requête avec des `annotate`s serait plus performante.

Pour le point 2 est une préférence personnelle, donc très discutable.

2021-05-06 09:59 UTC, kemar commented on itou/www/employee_record_views/forms.py
> +]
En général on pousse ces données dans une constante de classe `STATUS_CHOICES` du formulaire quand ça ne doit pas faire partie du modèle.

Tu peux regarder par exemple `DISTANCE_CHOICES` dans https://github.com/betagouv/itou/blob/3e58045d01d8f65f898291dff9ff0c57ba8cfc99/itou/www/search/forms.py

2021-05-06 09:59 UTC, kemar commented on itou/www/employee_record_views/tests/test_list.py
> +        self.assertContains(response, self.user.get_full_name())
Le mécanisme du filtre de statut n'est pas testé ici.

2021-05-06 09:59 UTC, kemar commented on itou/www/employee_record_views/views.py
> +        messages.info(request, message)
Toute cette logique purement liée à l'affichage (les messages `INFO_MSG_NEW` etc., le dict `message`, et le `messages.info`) pourrait bouger dans le template et être des messages permanents.

2021-05-06 09:59 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +        {% endif %}
Il y a quelques problèmes d'indentation dans les templates, ici le `{% endif %}` mais je peux vivre avec :)

2021-05-06 11:59 UTC, ikarius commented on itou/job_applications/models.py
> +            self.filter(state=JobApplicationWorkflow.STATE_ACCEPTED, to_siae=siae)
Merci, je n'avais qu'à lever le nez

2021-05-06 12:02 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +                <p class="m-0">Numéro de PASS IAE (agrément) : <b>{{ item.approval.number }}</b></p>
Je ne savais même pas qu'il y avait ce genre de helper. Merci

2021-05-06 12:11 UTC, ikarius commented on itou/www/employee_record_views/views.py
> +    ]
Très juste, je vais me pencher sur le annotate

2021-05-06 12:12 UTC, ikarius commented on itou/www/employee_record_views/views.py
> +        messages.info(request, message)
Oui, je ne suis pas content en plus de la tête de l'affichage des infos. Je ne vais pas passer par les messages Django je pense

2021-05-06 12:38 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                        <a href="{% url 'siaes_views:configure_jobs' %}">Publier/gérer les fiches de postes</a>
Et peut-être y coller les annexes financières pour une thématique ASP ? poke @vgrange

2021-05-06 12:39 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +]
Merci pour la good-practice, Je modifie

2021-05-06 13:00 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +        <div class="p-2">
euh, non. Il ferme le `<div class="row"> ` uniquement pour le status `NEW` 
(j'ai du repasser tous les tags cette nuit pour le mettre à plat celui là)

2021-05-06 13:01 UTC, ikarius commented on itou/templates/employee_record/list.html
> +{% block title %}{{ siae.display_name }}{{ block.super }}{% endblock %}
Correct. Merci

2021-05-06 13:11 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +        {% endif %}
Non, je fixe

2021-05-06 13:33 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +        <div class="p-2">
T'as besoin de le mettre qu'une fois à la fin le `</div>` fermant, pas dans chaque condition.

2021-05-06 13:53 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +        <div class="p-2">
Euh, oui. :dumb:

2021-05-17 09:35 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                        <a href="{% url 'siaes_views:configure_jobs' %}">Publier/gérer les fiches de postes</a>
En cours de design par Damien, je l’intégrerais lors de la prochaine PR

2021-05-17 12:42 UTC, kemar commented on itou/employee_record/migrations/0008_auto_20210512_1538.py
> +    ]
Tu peux _squasher_ tes migrations dans ta PR stp

2021-05-17 12:46 UTC, kemar commented on itou/job_applications/models.py
> +    def eligible_as_employee_record(self, siae):
À tester "unitairement" dans `itou/job_applications/tests.py`.

2021-05-17 12:47 UTC, kemar commented on itou/siaes/models.py
> -    siret = models.CharField(verbose_name="Siret", max_length=14, validators=[validate_siret], db_index=True)
Les constantes viennent avant les champs. Pourquoi passer `siret` au dessus de `ELIGIBILITY_REQUIRED_KINDS` ?

2021-05-17 12:50 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                        <a href="{% url 'siaes_views:configure_jobs' %}">Publier/gérer les fiches de postes</a>
Du coup il faut masquer ce lien aussi dans un commentaire ?

2021-05-17 12:51 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                    {# Commenté le temps du dev #}
Commentaire en FR :trollface:

2021-05-17 12:51 UTC, kemar commented on itou/templates/dashboard/dashboard.html
> +                    {# Commenté le temps du dev #}
Mais du coup c'est même pas commenté, tu comptes le faire plus tard ?

2021-05-17 12:52 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                        <a href="{% url 'siaes_views:configure_jobs' %}">Publier/gérer les fiches de postes</a>
Par encore, ca reste en l'état tant qu'il a pas fini

2021-05-17 12:53 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +        <div>
Je ne comprends pas l'arborescence HTML avec un `</div>` fermant juste après le `if`. Regarde les autres pages contenant des tableaux pour voir comment on fait ça proprement.

2021-05-17 12:57 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                    {# Commenté le temps du dev #}
Oui

2021-05-17 12:58 UTC, kemar commented on itou/www/employee_record_views/views.py
> +# @user_passes_test(lambda u: u.is_superuser)
Commentaire a _drop_ du coup si tu préfères commenter la route.

2021-05-17 13:00 UTC, kemar requested changes
Encore quelques changements à faire stp

2021-05-17 13:03 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +        <div>
On l'avais discuté la dernière fois, juste dans le cas de NEW, la balise ROW est fermée.
Pas pour les autres cas,  ou il ya une autre colonne contenant status et la balise row continue

2021-05-17 13:03 UTC, ikarius commented on itou/templates/employee_record/includes/list_item.html
> +        <div>
C'est moi qui ai la tete dans le chou ?

2021-05-17 13:07 UTC, kemar commented on itou/templates/employee_record/includes/list_item.html
> +        <div>
Ok, je vais pas perdre de temps là dessus, je repasserai dessus plus tard

2021-05-17 13:10 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
> +                    {# Commenté le temps du dev #}
Parce que Damien est en train regarder la recette

2021-05-17 14:57 UTC, merged

2021-06-11 15:51 UTC, vgrange reviewed
LGTM good job!