Sebastienreuiller/update cookies header
betagouv/itou pull request #701
Opened 2021-05-28 12:59 UTC by SebastienReuiller

### Quoi ?

Mise à jour de tarteaucitron et ajout du consentement pour Livestorm 

### Pourquoi ?

Pour respecter les nouvelles règles sur les cookies à savoir un bouton pour refuser tout aussi simple et accessible que le bouton accepter tout  

### Autre

- j'ai ajouter le consentement pour Livestorm car le flux d'évènements sur la page d'accueil génère des cookies
-

2021-05-31 08:13 UTC, kemar commented
@SebastienReuiller est-ce que tu peux mettre un _screenshot_ du résultat dans le texte de description de la PR stp ? Et donner un titre à la PR aussi :)

2021-05-31 10:00 UTC, kemar requested changes
Quelques questions et changements demandés

2021-05-31 10:00 UTC, kemar commented on itou/templates/layout/base.html
> +                    return tarteaucitron.engage(id);
Pourquoi on enlèverai pas tout simplement le `<div>` Livestorm du DOM ?

2021-06-01 10:31 UTC, SebastienReuiller commented on itou/templates/home/home.html
> +{% endblock %}
Pour le "endblock script", je ne l'ai pas remplacé par un "endblock", c'est que j'ai supprimé tout le bloc JS.
A oui, pas de nouvelle ligne à la fin, je vais configurer mon éditeur de code pour éviter ça.

2021-06-01 10:33 UTC, SebastienReuiller commented on itou/templates/layout/base.html
> +        const tablet_width = 750;
je n'ai pas l'explication, j'ai juste reconduit l'existant.

2021-06-01 10:38 UTC, SebastienReuiller commented on itou/templates/layout/base.html
> +                    return tarteaucitron.engage(id);
Pour le coup, j'ai repris le service générique de type "iframe" fournit par tarteaucitron dans `tarteaucitron.services.js`. D'ailleurs, je pourrai leur faire une PR un peu plus générique pour Livestorm.

2021-06-01 10:42 UTC, SebastienReuiller commented on itou/templates/home/home.html
> +            <div id="livestorm_iframe" class="tac_livestorm" data-url="https://app.livestorm.co/itou/upcoming?limit=3" title="Événements des emplois de l'inclusion | Livestorm" width="100%" height="9
c'est noté !

2021-06-01 11:48 UTC, kemar commented on itou/templates/layout/base.html
> +        const tablet_width = 750;
OK, compris :)

2021-06-01 11:50 UTC, kemar commented on itou/templates/layout/base.html
> +                    return tarteaucitron.engage(id);
Ok, j'ai capté avec les _screenshots_, merci.

2021-06-01 11:50 UTC, kemar approved these changes
LGTM

2021-06-07 10:04 UTC, merged