Modification de la classe de base des notifications
betagouv/itou pull request #705
Opened 2021-06-01 09:53 UTC by SebastienReuiller

### Quoi ?
Supprimer la liste des destinataires par défaut

### Pourquoi ?
Pour que la liste des destinataires soit mieux maîtrisée par les utilisateurs de la classe BaseNotification (notamment pour bien cibler les utilisateurs actifs). 

### Comment ?
Suppression de la valeur par défaut du paramètre type QuerySet + ajustement des tests unitaires

2021-06-01 10:41 UTC, stephane requested changes

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/base_class.py
> +        `recipients_qs`: Django QuerySet leading to this notification recipients (Ex: itou.siaes.models.SiaeMembershipQuerySet).
(Ex: blabla) -> (e.g. blabla).

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/tests.py
> +        self.membership = self.siaemembership_set.filter(user__is_active=True).first()
Ce filtre est nécessaire car la factory génère 4 memberships différent, dans ce cas, il est préférable d'ajouter le membership dont on a besoin dans le seul test concerné (cf commentaire suivant).

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/tests.py
> +        self.siae = SiaeWith4MembershipsFactory()
Attention ici ce sont tous les tests qui sont ralentis par le passage de 1 membre à 4.

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/tests.py
> +        self.assertEqual(self.siaemembership_set.filter(user__is_active=True).count(), len(recipients))
Pour faire simple, je ferai un test `siaemembership_set.count()` est égal à 2  puis un `len(recipients)` est égal à 1 pour test le filtrage `.active() interne à la classe.

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/tests.py
> +    def test_desactivate_user_not_in_recipients_email(self):
Tu peux ajouter un membre inactif à la SIAE avec :
```python
factory.SiaeMemberShipFactory(siae=self.siae, user__is_active=False, is_siae_admin=False)
```

et ainsi éviter de modifier la factory du `setUp()`.

2021-06-01 10:41 UTC, stephane commented on itou/utils/notifications/tests.py
>  BaseNotification = NewSpontaneousJobAppEmployersNotification
Je ne comprends pas ce renommage et il m'a induit en erreur car `BaseNotification` existe dans `notifications.py`.
À virer AMHA, cc @celine-m-s

2021-06-01 10:43 UTC, stephane commented
N'hésites pas à utiliser `git commit --amend` et `git push --force` quand tu corriges des typos (ou `git rebase -i` avant merge).

2021-06-01 12:05 UTC, celine-m-s commented on itou/utils/notifications/tests.py
>  BaseNotification = NewSpontaneousJobAppEmployersNotification
C'est bizarre, il me semblait que tu l'avais enlevé quand tu avais refondu les tests. :thinking: 
On peut le virer, oui.

2021-06-01 12:06 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +    def __init__(self, recipients_qs):
Pourquoi supprimer les annotations de type ? C'est bien utile pour comprendre clairement le type attendu par `recipients_qs`.

2021-06-01 12:07 UTC, kemar commented on itou/approvals/notifications.py
> +        super().__init__(recipients_qs=SiaeMembershipQuerySet)
Cette classe n'a pas besoin de `recipients_qs` à l'initialisation.

Il y a un unique destinataire de l'email ici https://github.com/betagouv/itou/blob/52ac81deed2ace7230b8b8a4f6a5455888ff872a/itou/approvals/notifications.py#L19 Et vu que le `to` n'est pas un QuerySet mais `self.prolongation.validated_by.email` je n'ai pas pu passer par `recipients_qs`.

En fait je me sert de la classe `BaseNotification` juste pour rassembler les notifs au même endroit…

Peut-être que c'est _overkill_…

2021-06-01 12:07 UTC, celine-m-s commented on itou/utils/notifications/base_class.py
> +        Ex: itou.siaes.models.SiaeMembershipQuerySet
`For example` ou `e.g.` :)

2021-06-08 15:45 UTC, SebastienReuiller commented on itou/utils/notifications/tests.py
>  BaseNotification = NewSpontaneousJobAppEmployersNotification
Ok, je vais l'enlever. Par contre, j'utilise toujours la classe NewSpontaneousJobAppEmployersNotification pour les tests ?

2021-06-09 07:47 UTC, celine-m-s commented on itou/utils/notifications/tests.py
>  BaseNotification = NewSpontaneousJobAppEmployersNotification
Oui, normalement tu peux sans problème.

2021-06-10 08:23 UTC, SebastienReuiller commented on itou/utils/notifications/tests.py
> +    def test_desactivate_user_not_in_recipients_email(self):
Merci pour le tuyau

2021-06-10 08:24 UTC, SebastienReuiller commented on itou/utils/notifications/tests.py
> +        self.membership = self.siaemembership_set.filter(user__is_active=True).first()
C'est vrai !

2021-06-10 08:25 UTC, SebastienReuiller commented on itou/utils/notifications/tests.py
>  BaseNotification = NewSpontaneousJobAppEmployersNotification
OK

2021-06-15 09:20 UTC, stephane approved these changes
Commentaire sur une fonction.
Tu peux grouper les 3/4 commits de typo et merger.

2021-06-15 09:20 UTC, stephane commented on itou/utils/notifications/tests.py
> +    def test_desactivate_user_not_in_recipients_email(self):
Je cherchais l'action `desactivate` mais c'est un test sur un utilisateur inactif.
Pour le nom de fonction, je propose `test_inactive_user_not_in_recipients`

2021-06-17 09:32 UTC, SebastienReuiller commented on itou/utils/notifications/tests.py
> +    def test_desactivate_user_not_in_recipients_email(self):
Bien vu !

2021-06-17 12:16 UTC, merged