Suppression de la fenêtre surgissante sur le formulaire d'embauche
betagouv/itou pull request #716
Opened 2021-06-08 14:12 UTC by SebastienReuiller

### Quoi ?

Suppression de la fenêtre surgissante

### Pourquoi ?

Parce que la fenêtre surgissante ne permet de voir quand il y a des erreurs sur un champs

### Comment ?

Le contenu de la fenêtre surgissante est déplacé en lieu et place du bouton qui déclenchait son apparition. 

### Captures d'écran

Avant :

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

---

Liens intéressant :

- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8

2021-06-09 09:17 UTC, kemar commented on itou/templates/apply/process_accept.html
> +                        onClick="$(&quot;input[name='hiring_without_approval']&quot;).val('True')">
Je sais que ça n'est pas ton code mais il faudrait profiter de cette PR pour retirer le `onclick` en ligne.

Ça va poser des problèmes :

- quand on va mettre en place une [Content Security Policy](https://csp.withgoogle.com/docs/adopting-csp.html) parce que c'est un vecteur d'XSS
- si un jour on remplace jQuery on va forcément oublier le code dans les `onclick`

C'est toujours plus propre aussi d'avoir du *unobtrusive JavaScript* quand c'est possible :)

Est-ce que tu veux bien changer ce mécanisme pour le faire marcher sans JS ?

2021-06-09 09:18 UTC, kemar requested changes
C'est nickel mais il faudrait remplacer le `onclick`.

2021-06-10 11:30 UTC, kemar commented on itou/www/apply/forms.py
> +            self.cleaned_data["hiring_without_approval"] = True
Ici ça serait pas mal d'ajouter un commentaire qui explique qu'on a besoin de faire ça car on a plusieurs boutons `submit` dans le template.

Le prochain dev à travailler là dessus te remerciera :)

2021-06-14 14:59 UTC, merged

2021-06-17 19:47 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Fenêtre modale affichée avant la validation du form](https://trello.com/c/abIUDOvY/1675-c1-fen%C3%AAtre-modale-affich%C3%A9e-avant-la-validation-du-form)