FIX: Configuration de Huey / Redis
betagouv/itou pull request #722
Opened 2021-06-13 22:07 UTC by ikarius

### Quoi ?

Une modification de la configuration de Huey.

### Pourquoi ?

Suite au problème survenu sur l'instance Redis le 12.06.2021 (OOM), il est nécessaire de modifier 
la configuration de Huey dans Django.

### Comment ?

Huey dispose d'une classe `huey.RedisExpireHuey` permettant de gérer l'expiration des résultats de traitements (contenus dans la clé `huey.results`).

La commande ``FLUSHALL` utilisée en mode manuel à complètement effacé les résultats de traitements, libérant ainsi la quasi intégralité de la RAM de l'instance Redis.

Avec l'utilisation de cette classe, les résultats sont éliminés au bout d'une journée (valeur par défaut).

Il est également possible de les supprimer immédiatement, mais cela rendrait un éventuel dépannage en cas d'incident plus difficile

Liens intéressant :

- https://github.com/coleifer/huey/blob/345857dd01293af70a3a72dcb8052e34b38574b1/huey/api.py#L1077
- https://huey.readthedocs.io/en/latest/api.html#RedisExpireHuey

2021-06-14 09:35 UTC, stephane approved these changes
LGTM avec un lien vers https://github.com/betagouv/itou-private/blob/master/docs/development/post_mortems.md
pour donner plus d'info.

2021-06-15 07:57 UTC, kemar approved these changes
LGTM

2021-06-15 09:51 UTC, stephane requested changes
Suite discussion d'hier.
Je retire mon LGTM pour une version sans stockage des résultats.
PR à suivre.

2021-06-15 12:18 UTC, kemar commented
> Je retire mon LGTM pour une version sans stockage des résultats.

Ça a l'air fait ici https://github.com/betagouv/itou/pull/722/commits/95efe59aa01b7b43460d58c7b9d31b8fd969182c

2021-06-15 12:20 UTC, stephane commented
Conflit de patches qui font la même chose ! ;)
https://github.com/betagouv/itou/pull/732

2021-06-15 12:23 UTC, stephane commented
J'ai fait une PR à part car je ne voulais pas du patch qui ajoute Expire et je ne savais pas si @ikarius  était sur le coup.

2021-06-15 12:28 UTC, kemar commented
Ok OSEF, juste ne mergez pas les 2 :D

2021-06-15 12:35 UTC, closed without merging