Fiche salarié : UI création et modification
betagouv/itou pull request #723
Opened 2021-06-14 06:53 UTC by ikarius

### Quoi ?

La deuxième partie de l'interface de saisie et modification des fiches salarié.

Plus quelques corrections suite à la phase de test de transfert effectuée avec l'ASP semaine du 31.05.2021

### Pourquoi ?

Permettre aux SIAE concernées la saisie et la modification (en cas de retour en erreur) des fiches salarié.

### Comment ?

- Accès à une liste navigable des candidatures / embauches à transformer en fiches salarié (partie 1)
- Passer par un tunnel de saisie pour récolter les informations nécessaires à l'établissement d'une fiche salarié
- Permettre la modification (lorsque c'est possible) et la visualisation du détail d'une fiche salarié

### Divers

- en cours de relecture
- une passe UX à finaliser sur la partie tunnel / formulaire de saisie 
- une prochaine PR contiendra les aspects techniques du déclenchement du transfert des fiches vers l'ASP

2021-06-16 08:49 UTC, ikarius commented on itou/templates/employee_record/includes/create_step_3.html
> +{# A vérifier / optimiser #}
Je sais c'est pas très beau, je suis preneur de mieux

2021-06-16 16:22 UTC, kemar requested changes
Moitié de revue, je continue demain mais c'est du bon job :)

2021-06-16 16:22 UTC, kemar commented on itou/templates/employee_record/includes/create_step_3.html
> +<script src="{% static "vendor/jquery-3.4.1/jquery.min.js" %}"></script>
Effectivement. Déjà tu n'as pas besoin de chercher jQuery une nouvelle fois car il est inséré dans le template de base.

Ensuite tu as un composant tout prêt dans Bootstrap.

> https://getbootstrap.com/docs/4.6/components/collapse/

Y a-t-il une raison pour ne pas l'avoir utilisé ?

Et enfin, c'est pas une bonne pratique d'insérer un `<script>` en plein dans la page. C'est autorisé mais ça rend la maintenance du code difficile car il faut aller chercher du JS à plein d'endroits.

Idéalement on utilise un composant Bootstrap : c'est testé, ça dégrade bien, ça évite du JS et un template tag (`fold_class`) superflus.

2021-06-16 16:22 UTC, kemar commented on itou/templates/layout/base.html
>      {% block script %}
Typiquement si tu dois ajouter un `<script>` dans une page (et que tu n'as pas d'autre choix) tu surcharges ce `block` avec un `super` pour y mette ton code.

2021-06-16 16:45 UTC, ikarius commented on itou/employee_record/mocks/asp_test_siaes.py
> +]
Non, c'est effectivement pas super utile. Je vais me copier le fichier quelque part et nettoyer.
Si jamais pour un dernier test avec l'ASP

2021-06-16 17:33 UTC, ikarius commented on itou/templates/employee_record/includes/create_step_3.html
> +<script src="{% static "vendor/jquery-3.4.1/jquery.min.js" %}"></script>
OMG !
Je ne l'avais pas utilisé parce que le comportement sur checkbox n'était pas ok (le checkbox n'apparaissait pas coché)

Mais je viens de refaire une passe après ta remarque et j'ai trouvé un post sur Stackoverflow avec une astuce fonctionnelle:
Il suffit d'enrober le composant input / checkbox par un `label` et ca marche !

Donc je vais pouvoir faire péter le code javascript, l'import dégueulasse et simplifier le code du formulaire !

2021-06-17 07:51 UTC, ikarius commented on itou/employee_record/serializers.py
> +    def get_nomUsage(self, obj):
Oui, c'est le format attendu par l'ASP

2021-06-17 09:56 UTC, vgrange approved these changes
LGTM phenomenal job ! 👍 

Quelques questions pour ma curiosité.

2021-06-17 09:56 UTC, vgrange commented on itou/employee_record/models.py
> +        PROCESSED = "PROCESSED", "Intégrée"
C'est normal que l'état `ARCHIVED` ait été viré ici ?

EDIT oublie, j'ai compris. Cf ci-dessous.

```
    @property
    def is_archived(self):
        """
        Once in final state (PROCESSED), an EmployeeRecord is archived.
        See model save() and clean() method.
        """
        return self.status == self.Status.PROCESSED and self.json is not None
```

2021-06-17 09:56 UTC, vgrange commented on itou/employee_record/models.py
> +        self.test_asp = test_asp
Cet attribut ne semble jamais utilisé, c'est normal ?

2021-06-17 09:56 UTC, vgrange commented on itou/templates/dashboard/dashboard.html
>                      {# Commenté le temps du dev #}
Tu peux virer du coup non ?

2021-06-17 09:59 UTC, ikarius commented on itou/templates/dashboard/dashboard.html
>                      {# Commenté le temps du dev #}
J'attends juste de voir si on part sur cette présentation du dashboard ou pas. Mais oui très probablement !

2021-06-17 10:01 UTC, stephane commented on itou/templates/employee_record/includes/employee_record_summary.html
> +                    A : {{ employee.birth_place }} ({{ employee.birth_place.department_code }})
À

2021-06-17 10:02 UTC, stephane commented on itou/templates/employee_record/list.html
> +                <p>A ce stade, seule la visualisation des informations de la fiche est possible.</p>
À

2021-06-17 10:04 UTC, ikarius commented on itou/employee_record/models.py
> +        self.test_asp = test_asp
Un oeil perçant. Plus utilisé depuis ... des lustres. Je vire. Merci !

2021-06-17 10:07 UTC, ikarius commented on itou/employee_record/mocks/asp_test_siaes.py
> +]
Je vais le garder en tant que commentaire structuré (pas comme du code commenté). Le temps que les tests avec l'ASP soient de l'histoire ancienne si ok pour toi.

Après on pourra virer tout ça et les serializers de test.

2021-06-17 10:17 UTC, kemar requested changes
2ème passe de retours. Il me reste encore quelques fichiers à lire mais tu peux déjà peut-être répondre ou traiter certains points.

2021-06-17 10:17 UTC, kemar commented on itou/www/employee_record_views/views.py
> +        employee_record.save()
```suggestion
        employee_record, _created = EmployeeRecord.objects.get_or_create(job_application=job_application)
```

2021-06-17 10:17 UTC, kemar commented on itou/www/employee_record_views/views.py
> +    employee_record = EmployeeRecord.objects.get(job_application=job_application)
`get_object_or_404` pour une sécurité supplémentaire.

2021-06-17 10:17 UTC, kemar commented on itou/www/employee_record_views/views.py
> +    employee_record = EmployeeRecord.objects.get(job_application=job_application)
`get_object_or_404` pour une sécurité supplémentaire.

2021-06-17 10:17 UTC, kemar commented on itou/www/autocomplete/views.py
> +            .annotate(similarity=TrigramSimilarity("name", term))
Ce genre de requêtes nécessite un `GinIndex` sur ton modèle, or il n'y en a pas. Ça doit être très cher du coup. À vérifier dans la _debug toolbar_.

2021-06-17 10:17 UTC, kemar commented on itou/utils/templatetags/collapse.py
> +def collapse(field_value):
`def collapse` une fois ici  (1/2).

2021-06-17 10:17 UTC, kemar commented on itou/utils/templatetags/folds.py
> +def collapse(field_value):
`def collapse` une fois là (2/2).

Ne peut-on pas se passer ce de _tag cutom_ ?

2021-06-17 10:17 UTC, kemar commented on itou/templates/employee_record/includes/create_step_4.html
> +    {% bootstrap_form form %}
On s'était dit qu'on adoptait cette convention `{% bootstrap_form form alert_error_type="all" %}`.

2021-06-18 08:44 UTC, ikarius commented on itou/www/employee_record_views/views.py
> +    return siae, job_application, job_application.job_seeker.jobseeker_profile if check_profile else None
Merci. 
Sur cette phase,  j'ai pu gagner:
- une requête sur la liste
-  2 sur les tests de permissions sur les phases du tunnel, 
-  plus une remplacée par un `count()` au lieu d'un fetch vide

2021-06-18 09:01 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +        if self.cleaned_data["rsa_allocation"]:
Oui, exact, le clean est joufflu parce qu'il y a des interactions / validations entre plusieurs champs. Mais pour les tests de validation qui portent que sur un seul champ, un clean spécialisé est préférable.
Je fixe

2021-06-21 06:58 UTC, ikarius commented on itou/www/employee_record_views/views.py
> +def check_permissions(request, job_application_id, check_profile=True):
Je suis en train de regarder comment faire ça ...

2021-06-21 13:11 UTC, ikarius commented on itou/utils/templatetags/folds.py
> +def collapse(field_value):
Deja il ya en un de trop (fold.py): j'ai oublié de le virer. Ensuite je regarde si je peux virer ...

2021-06-22 15:47 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +            self.cleaned_data["birth_place"] = Commune.objects.by_insee_code(commune_code)
Correct.
Anodin en apparence, mais ta remarque a levé un lièvre et j'ai du modifier du code et du test (plus que prévu en tout cas). 
Donc, merci !

2021-06-23 08:52 UTC, ikarius commented on itou/utils/templatetags/collapse.py
> +def collapse(field_value):
Supprimé

2021-06-23 08:52 UTC, ikarius commented on itou/utils/templatetags/folds.py
> +def collapse(field_value):
Supprimé et modifié le template (sans custom tag)

2021-06-23 09:12 UTC, ikarius commented on itou/employee_record/serializers.py
> +    def get_nomUsage(self, obj):
(prefixe `get_` nécessaire pour le sérialiseur et le format d'affichage attendu en sortie. D'ou le mix bizarroïde.

A ce propos, je dois avouer être de moins en moins convaincu par les serialiseurs DRF, en tout cas en mode lecture seule et avec un seul format de sortie au final (JSON).

Pas une énorme plus-value par rapport à un formatage manuel.

2021-06-23 09:20 UTC, ikarius commented on itou/employee_record/serializers.py
> +        return unidecode(obj.last_name).upper()
Alphabétique sans diacritique, avec tiret et espace possible. On pourrait être plus fin, mais unidecode fait le job

2021-06-23 13:08 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +        if self.cleaned_data["rsa_allocation"]:
Je vois pas quel(s) champ(s) associer à une méthode `clean_` spécifique, étant donné qu'ils sont tous dépendants d'autres champs.
Je manque peut-être un truc ...

2021-06-24 08:47 UTC, kemar requested changes
PTAL
On y est presque et c'est très lisible :)
Encore un dernier effort pour traiter quelques retours importants (la fusion des migrations et la 404 dans la validation de form notamment)

2021-06-24 08:47 UTC, kemar commented on itou/templates/employee_record/includes/create_step_3.html
> +<form method="POST" action="{% url "employee_record_views:create_step_3" job_application.id %}" class="js-prevent-multiple-submit">
Information d'importance capitale : c'est terminé le temps du `POST` en uppercase.

> https://stackoverflow.com/questions/7790576/what-are-http-method-capitalization-best-practices

2021-06-24 08:47 UTC, kemar commented on itou/templates/employee_record/includes/create_step_4.html
> +    {% bootstrap_form form alert_error_type="all" %}
Tu crois que tu peux virer le `{% bootstrap_form_errors form %}` du dessus si tu as la ligne `{% bootstrap_form form alert_error_type="all" %}` sinon j'ai l'impression qu'on aura deux fois le bloc d'erreur du dessus ?

2021-06-24 08:47 UTC, kemar commented on itou/templates/employee_record/includes/create_step_5.html
> +            <p>La création de cette fiche salariée est maintenant terminée .</p>
```suggestion
            <p>La création de cette fiche salariée est terminée.</p>
```

2021-06-24 08:47 UTC, kemar commented on itou/www/employee_record_views/forms.py
> +        if self.cleaned_data["rsa_allocation"]:
Pas de problème, c'était juste pour info.

2021-06-24 08:47 UTC, kemar commented on itou/www/employee_record_views/forms.py
> +        if hasattr(self, "instance"):
Dans un `ModelForm` l'attribut `instance` est toujours présent, du coup on doit toujours rentrer dans cette condition en fait, je dirais que tu peux t'en passer.

2021-06-24 08:47 UTC, kemar commented on itou/www/employee_record_views/forms.py
> +            commune = get_object_or_404(Commune.objects.current().by_insee_code(commune_code))
On ne déclenche pas des 404 dans une validation de formulaire.

Il vaut mieux afficher clairement l'erreur et dire à la personne que la ville n'existe pas et lui laisser l'opportunité de corriger. Sinon elle ne va pas comprendre ce qui se passe.

Ça pour le coup ça peut être dans une méthode `clean_insee_commune_code`.

2021-06-24 13:17 UTC, ikarius commented on itou/job_applications/migrations/0031_alter_jobapplication_hiring_start_at.py
> +    ]
Merci de ton oeil. J'ai pas fait de rebase récemment, je vais m'occuper de ce point en tout dernier lieu et faire un check complet des migrations

2021-06-24 14:01 UTC, ikarius commented on itou/templates/employee_record/includes/create_step_3.html
> +<form method="POST" action="{% url "employee_record_views:create_step_3" job_application.id %}" class="js-prevent-multiple-submit">
Je me sens vieux sur celle-là

2021-06-24 14:03 UTC, vgrange commented on itou/templates/employee_record/includes/create_step_3.html
> +<form method="POST" action="{% url "employee_record_views:create_step_3" job_application.id %}" class="js-prevent-multiple-submit">
Itou o_O de mon temps les majuscules ça rendait mieux.

2021-06-24 14:07 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +        if hasattr(self, "instance"):
Un peu trop défensif sur le coup, oui ça passe très bien. Merci !

2021-06-24 14:18 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +            commune = get_object_or_404(Commune.objects.current().by_insee_code(commune_code))
Oui j'étais pas super sur pour le coup. Ça m'a aussi semblé bizarre (mais faisait le taf).

J'ai déplacé un test d'existence préliminaire dans `clean_insee_commune_code`

BTW, le chapitre sur les clean field est fait pour moi:
https://docs.djangoproject.com/en/3.2/ref/forms/validation/#form-field-default-cleaning

2021-06-24 15:25 UTC, kemar approved these changes
LGTM AFAICT Les derniers retours sont laissés à ton appréciation.

2021-06-24 15:25 UTC, kemar commented on config/urls.py
> +    path("employee_record/", include("itou.www.employee_record_views.urls")),
Ordre alphabétique si possible, sinon je ne dors pas la nuit…

2021-06-24 15:25 UTC, kemar commented on itou/asp/models.py
> +        Lookup a Commune objects by INSEE code
```suggestion
        Lookup a Commune object by INSEE code
```

2021-06-24 15:25 UTC, kemar commented on itou/www/employee_record_views/forms.py
> +        )
Je viens de le voir mais un [`ModelChoiceField`](https://docs.djangoproject.com/en/3.2/ref/forms/fields/#modelchoicefield) pour le champ `financial_annex` aurait pu t'éviter ce `get()` en te donnant directement une instance de modèle en sortie.

2021-06-24 15:29 UTC, ikarius commented on config/urls.py
> +    path("employee_record/", include("itou.www.employee_record_views.urls")),
:)
C'est faisable je pense

2021-06-24 15:42 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +        )
Je me le garde sous le coude dès que je fais le cron ...

2021-06-24 16:39 UTC, ikarius commented on itou/www/employee_record_views/forms.py
> +        )
Bon, finalement non, j'ai modifié pour ajouter un `ModelChoiceField`

2021-06-28 08:03 UTC, merged