Désactivation des conventions sans AF 2021
betagouv/itou pull request #726
Opened 2021-06-14 14:23 UTC by vgrange

### Quoi ?

FIXME

### Pourquoi ?

FIXME

### Comment ?

FIXME

2021-06-14 14:24 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Les structures n'ayant toujours pas d'AF 2021 valide à ce jour doivent être désactivées](https://trello.com/c/gQeYLeT1/1825-les-structures-nayant-toujours-pas-daf-2021-valide-%C3%A0-ce-jour-doivent-%C3%AAtre-d%C3%A9sactiv%C3%A9es)

2021-06-15 09:16 UTC, kemar requested changes
Quelques questions pour toi.

2021-06-15 09:16 UTC, kemar commented on itou/siaes/management/commands/_import_siae/convention.py
> +DEACTIVATE_CONVENTIONS = True
Ok mais si je comprend bien, passer cette constante de `False` à `True` et vice versa est une opération manuelle qu'il faudra faire tous les 6 mois.

Du coup est-ce qu'on ne devrait pas plutôt désactiver uniquement de début juillet à fin décembre et rendre ça automatique ?

2021-06-15 09:16 UTC, kemar commented on itou/siaes/management/commands/_import_siae/convention.py
> +                assert deactivations <= 200
J'ai l'impression que c'est une goupille de sécurité au cas où on aurait oublié de modifier `DEACTIVATE_CONVENTIONS` avant le 1er janvier ?

2021-06-17 09:16 UTC, vgrange commented on itou/siaes/management/commands/_import_siae/convention.py
> +DEACTIVATE_CONVENTIONS = True
Il faut garder espoir que les données ASP soient à jour dès le 1er janvier de l'année. Ou qu'au moins le rattrapage dure seulement 1-2 mois et non 6 mois!

- le 1er janvier, passer de `True` à `False`
- quelques mois plus tard, dès que le rattrapage est jugé suffisamment bon, repasser à `True`

Je recommande donc de garder le process manuel pour remettre la pression chaque année sur l'ASP, en espérant qu'ils améliorent leurs délais.

Dans tous les cas la goupille plus bas empêche supportix de faire *la* boulette (désactiver les 4000 conventions le 1er janvier).

2021-06-17 09:17 UTC, vgrange commented on itou/siaes/management/commands/_import_siae/convention.py
> +                assert deactivations <= 200
Correct. Cela empêche supportix de faire *la* boulette, c a d désactiver 100% des SIAE le 1er janvier.

2021-06-17 09:18 UTC, vgrange commented
re @kemar

2021-06-17 09:23 UTC, kemar commented on itou/siaes/management/commands/_import_siae/convention.py
> +DEACTIVATE_CONVENTIONS = True
D'accord. Est-ce qu'il faut documenter ça dans le repo privé ?

2021-06-17 09:24 UTC, kemar approved these changes
LGTM Ne devrait-on pas documenter ça dans le repo privé ?

2021-06-17 09:28 UTC, vgrange commented on itou/siaes/management/commands/_import_siae/convention.py
> +DEACTIVATE_CONVENTIONS = True
Oui c'est une très bonne idée. Je prends.

2021-06-25 09:10 UTC, vgrange commented on itou/siaes/management/commands/_import_siae/convention.py
> +DEACTIVATE_CONVENTIONS = True
https://github.com/betagouv/itou-private/pull/57

2021-06-28 08:36 UTC, merged