Ajout du formulaire de situation avec l'inscription d'un demandeur d'emploi
betagouv/itou pull request #727
Opened 2021-06-14 14:41 UTC by SebastienReuiller

### Quoi ?

Les SIAE reçoivent des candidatures autonomes de candidats non éligibles à l'IAE

### Pourquoi ?

On vise une meilleure qualification des candidatures pour :
- éviter la déception des candidats
- diminuer le traitement des candidatures par les SIAE

### Comment ?

On ajoute une étape dans le workflow du parcours d'inscription candidat.
Le candidat doit déclarer sur l'honneur être dans l'une des situations administratives concernées pour pouvoir poursuivre son inscription
S'il n'est pas dans l'une des situations mentionnées, on l'invite à se rapprocher d'un prescripteur

### Captures d'écran

L'URL d'inscription d'un candidat est modifiée pour afficher ce formulaire :

![capture_formulaire_situation](https://user-images.githubusercontent.com/17601807/121909569-539e3900-cd2e-11eb-9b43-e49df0f67cb7.png)

Si au moins un des critères d'éligibilité est coché, l'utilisateur est redirigé vers le formulaire d'inscription.
Si "Autre" est coché seul, la page spécifique suivante est affichée : 

![capture_page_redirection__vers_prescripteur](https://user-images.githubusercontent.com/17601807/121909809-94964d80-cd2e-11eb-8611-8d71404ca026.png)

### Autre

Si aucune case n'est cochée, le formulaire affiche un message spécifique. Or, le message "inline" de Boostrap ne semble pas fonctionner : 

![capture_invalid-feedback_not_display](https://user-images.githubusercontent.com/17601807/121910174-ec34b900-cd2e-11eb-97dd-71c580b3f58d.png)

2021-06-14 14:45 UTC, SebastienReuiller commented on itou/www/signup/tests.py
> +        post_data = {"some": "data"}
@kemar je ne sais pas si tu as déjà eu ce cas mais si j'envoie rien ici, ça ne lève pas l'erreur du formulaire. Comme le formulaire n'a qu'un champs, j'envoie une clé et une valeur de test.

2021-06-15 09:05 UTC, kemar requested changes
Cool PR 😎
Un seul changement important à faire, retirer `widget=MultipleSwitchCheckboxWidget()`.
Le reste c'est des remarques de surface.

2021-06-15 09:05 UTC, kemar commented on itou/www/signup/tests.py
> +        post_data = {"some": "data"}
Je pense que c'est parce que si tu ne mets rien, Django considère que [ton *form* est *unbound*](https://docs.djangoproject.com/en/3.2/ref/forms/api/#ref-forms-api-bound-unbound).

Ça fera peut-être l'affaire :

```python
post_data = {"situation": []}
```

2021-06-15 09:58 UTC, SebastienReuiller commented on itou/www/signup/tests.py
> +        post_data = {"some": "data"}
oui, ça doit être pour ça. Ça ne fonctionne pas non plus avec une liste vide comme tu le suggère, aucune erreur n'est levée dans ce cas.

2021-06-15 09:59 UTC, SebastienReuiller commented on itou/www/signup/urls.py
> +    ),
Carrément, merci !

2021-06-15 11:01 UTC, kemar approved these changes
LGTM (sous réserve de validation métier)

2021-06-17 12:22 UTC, merged

2021-06-17 19:44 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1-qualité des candidatures] Trop de candidatures autonomes pas qualifiées inondent les SIAE (validé le 01/03/2021)](https://trello.com/c/B8trmMiJ/1480-c1-qualit%C3%A9-des-candidatures-trop-de-candidatures-autonomes-pas-qualifi%C3%A9es-inondent-les-siae-valid%C3%A9-le-01-03-2021)