Refonte de la recherche des employeurs
betagouv/itou pull request #730
Opened 2021-06-15 07:54 UTC by stephane

### Quoi ?

En première étape, seule la ville doit maintenant être renseignée.
Les filtres permettent ensuite d'affiner la recherche.

### Pourquoi ?

Pour offrir une sélection plus restreinte de résultats.

### Comment ?

En ajoutant de nouveaux filtres tout en offrant une bonne ergonomie.

### Captures d'écran (optionnel)

![Capture d’écran de 2021-06-15 09-52-58](https://user-images.githubusercontent.com/1815/122014533-89d7c900-cdbf-11eb-9522-58c8cd49e20c.png)

### Autre

Optimisation de la recherche.

2021-06-15 13:23 UTC, stephane commented
Les cas à la marge que j'ai en tête :
- vous pouvez checker le responsive et notamment le comportement des filtres dans ce cas.
- le cas où les filtres ne donnent aucun résultat (en seconde passe).

2021-06-15 14:03 UTC, kemar requested changes
Bravo, chouette PR ! J'ai quand même quelques questions et suggestions avant de merger

2021-06-15 14:27 UTC, stephane commented on itou/static/css/itou.css
> +.itou-text-wrap {
Bien vu.

2021-06-15 14:32 UTC, stephane commented on itou/utils/address/departments.py
> +# The value is the number of districts of the department
En fait, non le test s'effectue alors sur une liste et non une simple value.
Je corrige le commentaire qui n'a pas suivi l'évolution de la branche.

2021-06-15 14:42 UTC, stephane commented on itou/www/search/forms.py
> +            data = MultiValueDict({**{k: [v] for k, v in initial.items()}, **data})
On veut utiliser les valeurs « initial » comme valeurs par défaut lorsqu'elles ne sont pas soumises par l'utilisateur.
MultiValueDict c'est le type de data, j'ai ajouté une annotation et un commentaire mais je ne sais pas faire plus simple.
Je trouve chaque fois assez perturbant le traitement de initial dans les forms Django.

2021-06-15 14:46 UTC, stephane commented on itou/www/search/forms.py
> +        def format_district(post_code):
Done.

2021-06-15 14:48 UTC, stephane commented on itou/www/search/forms.py
> +    def add_field_districts(self, department, districts):
La liste des choices est déterminée après le `init` et le `is_valid` donc je ne peux pas.

2021-06-15 14:48 UTC, stephane commented on itou/www/search/forms.py
> +    DISTANCES = [10, 15, 25, 50, 75, 100]
Restoré et j'évoque le point avec les UX.

2021-06-15 16:16 UTC, stephane commented on itou/www/search/forms.py
> +    KIND_CHOICES = [(k, f"{v} ({k})") for k, v in Siae.KIND_CHOICES if k != Siae.KIND_ACIPHC]
Question posée à Damien

2021-06-15 16:18 UTC, stephane commented on itou/templates/home/home.html
> +                {% include "search/includes/siaes_search_form.html" with form=siae_search_form  align="center"%}
Si, bonne remarque.
Je me charge des prescripteurs demain.

2021-06-15 16:26 UTC, stephane commented on itou/www/search/tests.py
> +        # The title "Prenez contact avec un employeur solidaire" isn't direclty rendered...
Yes, vu ensemble du coup. Search supprimée et test déplacé.

2021-06-16 07:05 UTC, stephane commented on itou/www/search/forms.py
> +    KIND_CHOICES = [(k, f"{v} ({k})") for k, v in Siae.KIND_CHOICES if k != Siae.KIND_ACIPHC]
Modifié.

2021-06-16 09:16 UTC, merged