Journal des changements version 20
betagouv/itou pull request #743
Opened 2021-06-17 20:09 UTC by celine-m-s

### Quoi ?

Comme son nom l'indique.

### Pourquoi ?

Pour communiquer au monde notre génie.

### Comment ?

En listant point par point nos avancées.

2021-06-18 07:43 UTC, Keirua requested changes
Des petites typos et un truc manquant déployé sur le fil, sinon c’est top !

2021-06-18 07:43 UTC, Keirua commented on CHANGELOG.md
> +- Suppression de l'adresse contact@ des notififications courriel concernant les PASS IAE
```suggestion
- Suppression de l'adresse contact@ des notifications courriel concernant les PASS IAE
```

2021-06-18 07:43 UTC, Keirua commented on CHANGELOG.md
> +
```suggestion
 - Possibilité d'importer un agrément Pôle Emploi afin de le prolonger ou le suspendre depuis la plateforme
```

2021-06-18 07:43 UTC, Keirua commented on CHANGELOG.md
> +- Seuls les administrateurs peuvent modification la fiche publique de leur établissement
```suggestion
- Seuls les administrateurs peuvent modifier la fiche publique de leur établissement
```

2021-06-18 09:46 UTC, vgrange commented on CHANGELOG.md
> +- 4 nouvelles tables ASP dans Metabase
Normalement ces deux items sont C2 donc pas à mettre dans le changelog C1.

Mais bon pourquoi pas ça me fait un peu de pub ;-)

2021-06-18 09:47 UTC, vgrange commented on CHANGELOG.md
> +- Traitement des structures créées par le support (fin de l'immunité)
Ok

2021-06-18 09:48 UTC, vgrange approved these changes
LGTM

Les sujets C2 ont pas forcément leur place ici mais pourquoi pas.

2021-06-21 07:10 UTC, merged

2021-06-21 07:10 UTC, celine-m-s commented
Merci pour vos retours !! :eyes: :hugs: