Nouvelle page "Déclaration d'accessibilité"
betagouv/itou pull request #748
Opened 2021-06-22 15:16 UTC by kemar

## Quoi ?

Nouvelle page en bonne et due forme pour la déclaration d'accessibilité.

Au passage ajout d'un lien vers le tableau de bord de disponibilité UptimeRobot et groupement des liens dans le footer (interne/externe).

## Pourquoi ?

La déclaration d'accessibilité était juste un lien externe vers celle de beta.gouv mais nous avons besoin :

- de spécifier le responsable légal
- de donner un point de contact chez nous en cas de problème d'accessibilité rencontré par un usager

### Captures d'écran

![footer](https://user-images.githubusercontent.com/281139/122951443-9343d100-d37d-11eb-94cb-b7154ba58f49.png)

2021-06-22 15:16 UTC, kemar commented
![](https://github.trello.services/images/mini-trello-icon.png) [Nouvelle page "Déclaration d'accessibilité"](https://trello.com/c/0VFNoPja/1855-nouvelle-page-d%C3%A9claration-daccessibilit%C3%A9)

2021-06-23 13:28 UTC, Keirua requested changes
Une erreur d’email sinon c’est nickel.

2021-06-23 13:28 UTC, Keirua commented on itou/templates/static/accessibility.html
> +        <li>E-mail : <a href="mailto:contact@beta.gouv.fr">{{ ITOU_EMAIL_CONTACT }}</a></li>
```suggestion
        <li>E-mail : <a href="mailto:{{ ITOU_EMAIL_CONTACT }}">{{ ITOU_EMAIL_CONTACT }}</a></li>
```

2021-06-23 15:28 UTC, kemar commented on itou/templates/static/accessibility.html
> +        <li>E-mail : <a href="mailto:contact@beta.gouv.fr">{{ ITOU_EMAIL_CONTACT }}</a></li>
Oups, bien vu, merci !

2021-06-23 15:28 UTC, merged