Nouveau motif de prolongation (contexte sanitaire)
betagouv/itou pull request #784
Opened 2021-07-20 12:30 UTC by celine-m-s

### Quoi ?

Ajout du motif de prolongation "Contexte sanitaire".

2021-07-20 15:57 UTC, stephane requested changes
Pinaillages :)

2021-07-20 15:57 UTC, stephane commented on itou/approvals/migrations/0016_alter_prolongation_reason.py
> +                        "Difficultés particulières qui font obstacle à l'insertion durable dans l’emploi "
Quote basique ou stylée, il faut choisir ;)

2021-07-20 15:57 UTC, stephane commented on itou/approvals/migrations/0016_alter_prolongation_reason.py
> +                        "Difficultés particulières qui font obstacle à l'insertion durable dans l’emploi "
Je mettrais bien des espaces insécables après chaque chiffre pour éviter les césures malencontreuses.

2021-07-20 15:57 UTC, stephane commented on itou/approvals/tests.py
> +        self.assertEqual(max_end_at, expected_max_end_at)
Je manque de temps pour creuser le test mais `expected_max_end_at` est ici une date naïve.
J'imagine que le test passe parce que l'on utilise une date absolue et que dans ce cas, le CEST est le même.

2021-07-20 15:59 UTC, stephane commented on itou/approvals/migrations/0016_alter_prolongation_reason.py
> +                        "Difficultés particulières qui font obstacle à l'insertion durable dans l’emploi "
Vu la capture c'est peu probable sur cet écran (mais pas exclu ailleurs à l'avenir).

2021-07-20 15:59 UTC, celine-m-s commented on itou/approvals/tests.py
> +        self.assertEqual(max_end_at, expected_max_end_at)
Oui, j'ai simplement repris ce qui était au-dessus. Mais tu as raison, ça vaut le coup de les retravailler.

2021-07-20 16:16 UTC, stephane commented
Tu peux merge sans relecture ensuite c'était vraiment des remarques mineures.

2021-07-21 07:20 UTC, celine-m-s commented on itou/approvals/tests.py
> +        self.assertEqual(max_end_at, expected_max_end_at)
`get_max_end_at` utilise une date absolue donc pas d'erreur de fuseau horaire.

2021-07-21 07:29 UTC, celine-m-s commented on itou/approvals/migrations/0016_alter_prolongation_reason.py
> +                        "Difficultés particulières qui font obstacle à l'insertion durable dans l’emploi "
C'est fait.

2021-07-21 07:49 UTC, merged