Ouverture progressive des fonctionnalités des fiches salarié
betagouv/itou pull request #787
Opened 2021-07-21 14:10 UTC by ikarius

### Quoi ?

Ouverture progressive des fonctionnalités concernant les fiches salarié.

### Pourquoi ?

- pour éviter de se faire submerger par les "edge-cases" du transfert SFTP vers l'ASP (qui arriveront inévitablement),
- parce que l'ASP n'a pas mis en place d'ouverture progressive.

### Comment ?

- on module le nombre de SIAE pouvant accéder à la fonctionnalité en agissant sur le champ `asp_id` (via ... un modulo 100 dans le paramètre `settings.EMPLOYEE_RECORD_ASP_ID_MODULO`),
- on se laisse la liberté de choisir manuellement certaines SIAE de "tests" en ajoutant leur ID au paramètre `settings.EMPLOYEE_RECORD_CUSTOM_ASP_ID_LIST`.

Pour permettre une mise en fonction rapide et éviter un déploiement complet, on passe par des variables d'environnement, qui si modifiées, permettent un redéploiement en une dizaine de secondes :
- ajouter ou enlever une SIAE "custom" nécessite un redéploiement complet (modification des `settings`),
- stopper le déploiement progressif ou augmenter le nombre de SIAE ne nécessite qu'un redéploiement rapide.

2021-07-22 09:52 UTC, celine-m-s commented on config/settings/base.py
> +EMPLOYEE_RECORD_CUSTOM_ASP_ID_LIST = []
Si je comprends bien, `EMPLOYEE_RECORD_ASP_ID_MODULO` représente le pourcentage d'objets ASP qui sont ouvertes.
`EMPLOYEE_RECORD_CUSTOM_ASP_ID_LIST` permet d'ouvrir individuellement les droits.
C'est bien ça ?

2021-07-22 10:24 UTC, celine-m-s reviewed
LGTM
J'aurais bien ajouté un test pour vérifier que le modulo fonctionne. J'avoue que c'est assez abstrait pour moi car je ne suis pas très familière avec ce concept. Je sais bien sûr ce que fait le `%` en Python mais c'est la première fois que je le vois utilisé dans ce cadre.

Je préfère donc ne pas me prononcer. Je te fais confiance et je laisse @stephane donner son avis. :)

2021-07-22 10:24 UTC, celine-m-s commented on itou/www/dashboard/tests.py
> +        self.assertContains(response, "en cours de déploiement")
Le modulo n'est donc pas testé, c'est bien ça ?

2021-07-26 14:01 UTC, vgrange requested changes
Une erreur (je pense) dans les `curated_siaes` et je suis d'accord avec Céline il faut un test du modulo car pas trivial. Quelques remarques aussi.

2021-07-26 14:01 UTC, vgrange commented on itou/employee_record/utils.py
> +    modulo_q = Q(idmod__lt=modulo)
Ici il y a une subtilité pas triviale du tout qu'il faudrait expliquer je trouve.

Un résidu modulo 100 donne une valeur de 0 à 99.
Du coup c'est bien `lt` et non `lte` qu'il faut.
Pour 1%, avec `lt` on matche bien seulement la valeur `0`.
Avec `lte` on aurait matché `0` et `1` donc 2%.

2021-07-26 14:02 UTC, vgrange commented on config/settings/base.py
> +EMPLOYEE_RECORD_ASP_ID_MODULO = int(os.environ.get("EMPLOYEE_RECORD_ASP_ID_MODULO ", 2))
Pourquoi pas juste 1% ?

2021-07-29 13:49 UTC, vgrange approved these changes
LGTM bon compromis, go et puis on virera cette logique au final une fois à 100%.

2021-07-29 13:49 UTC, vgrange commented on itou/employee_record/utils.py
> +    - within a percentge of all eligible SIAEs
`s/percentge/percentage/`

2021-07-29 13:49 UTC, vgrange commented on itou/employee_record/utils.py
> +    eligible_ids = (eligible_siaes[:limit]).values_list("id", flat=True)
Ah ok du coup pour simplifier le code tu abandonnes le modulo et l'asp id.
A la place tu fais un pourcentage basé sur l'id des siae.
Du coup
=> tu montreras l'UI FS d'abord aux plus anciennes siaes (id petit)
=> quand plusieurs structures ont le même asp_id, certaines verront l'interface et d'autres pas
=> c'est un peu lourd en db car `(eligible_siaes[:limit]).values_list("id", flat=True)` va charger plusieurs milliers d'ids quand le pct sera 50 ou 100. Mais le `values_list` mitige bien donc ça ira, et puis après tout c'est un dispositif temporaire, tu le vireras avec plaisir quand on sera à 100 ;-)

2021-08-02 10:10 UTC, celine-m-s commented on itou/employee_record/utils.py
> +    eligible_ids = (eligible_siaes[:limit]).values_list("id", flat=True)
Je m'incruste un peu mais pourquoi avoir supprimé la logique du modulo ? Ça avait l'avantage d'être plus léger, non ?

2021-08-04 09:16 UTC, merged