Ajustements au tunnel d'inscription des prescripteurs
betagouv/itou pull request #791
Opened 2021-07-27 18:39 UTC by stephane

### Quoi ?

- nouveau formulaire de saisie du SIRET
- nouvelle interface pour l'API Entreprise
- contrôles supplémentaires des données
- amélioration des tests
- mise en forme SIRET/SIREN
- mock plus fin de l'API

### Pourquoi ?

Ces améliorations ont pour but de rendre l'interface plus agréable et le code plus robuste mais une refonte complète de l'UX est nécessaire (voir la carte associée).

### Comment ?

La librairie respx permet de ne mocker que les appels HTTP ainsi il est possible de tester le code d'erreur et le traitement de la réponse.

Pour éviter que l'utilisateur saisisse un SIRET différent de celui utilisé pour la recherche d'établissement et pour éviter qu'il est l'impression de saisir une seconde fois la même information, la partie SIREN est positionné en lecture seule devant le champ
de saisie des 5 derniers chiffres du SIRET.

### Captures d'écran 

Est-ce une amélioration ?

![Capture d’écran de 2021-07-27 20-38-03](https://user-images.githubusercontent.com/1815/127209462-a1298c4a-a146-4302-b75b-2efc539b5df2.png)

### Autre

Cf la carte Trello.

- https://lundberg.github.io/respx/

2021-07-28 11:06 UTC, celine-m-s requested changes
C'est vrai que le parcours actuel pourrait être amélioré... Même si l'utilisateur n'a pas à saisir deux fois le SIREN, c'est assez pénible d'avoir à retrouver son SIRET après avoir donné son SIREN. Je me demande pourquoi on ne demande pas le SIRET dès le début en fait ? On pourrait peut-être sauter une étape dans ce cas ?

En tous cas, j'aime beaucoup ta proposition qui rend cette étape plus lisible. J'ai testé le parcours actuel à l'instant et j'ai mis une seconde à me rendre compte que je n'avais pas besoin de taper une seconde fois mon SIREN. Pas évident...

Super factorisation des tests et du code ! Je ne connaissais pas les `dataclasses` et c'est vrai qu'elles sont idéales dans ce cas-là ! Très bonne idée le `format_siret` !

En revanche, je me demande pourquoi tu as supprimé tous les points en fin de phrase. J'aime bien, moi, quand une phrase commence par une majuscule et finit par un point...

Je mets "request changes" car il reste des "FIXME" dans le code, or tu en laisses rarement, et à cause d'une espace manquante.

2021-07-28 12:45 UTC, stephane commented on itou/utils/apis/api_entreprise.py
> +        address_line_1=address["l4"],
Cela ne concerne pas le code de cet PR mais je vais le traiter très bientôt avec l'information du siège de ma prochaine carte.

2021-07-28 12:46 UTC, stephane commented on itou/www/signup/forms.py
> +            raise forms.ValidationError("La base Sirene indique quel'établissement est fermé.")
Bien vu. Merci.

2021-07-28 12:48 UTC, stephane commented on itou/www/signup/tests.py
> +        api_entreprise_route = respx.get(f"{settings.API_ENTREPRISE_BASE_URL}/etablissements/{siret}").mock(
Peut être pas dans api_entreprise.py mais dans peut être un `test.py` dans le répertoire de `api_entreprise.py` ?

2021-07-28 12:50 UTC, stephane commented on itou/www/signup/views.py
> +        return HttpResponseRedirect(reverse("signup:prescriber_siren"))
En fait, je n'aimais pas le fait que `next_url` soit défini à la mauvaise valeur dans le cas du test `is_pole_emploi` positif.

2021-07-28 12:54 UTC, stephane commented on itou/www/signup/views.py
> +# FIXME GET method with side-effect (session update)
Oui et j'ai noté le problème dans la carte car j'espère qu'un nouveau worflow va permettre de résoudre cela soit :
- en utilisant un POST
- en remplaçant la modification de session par un passage de params GET

Je peux facilement le remplacer par un POST (même si non adapté pour ce qui devrait être une recherche) dans cette PR mais je ne souhaite pas reprendre le mécanisme de stockage sans refonte du workflow. Quand penses tu ?

2021-07-28 12:56 UTC, stephane commented on itou/www/signup/views.py
> +    # Request Sirene API to validate SIRET
C'est fait par la form et comme c'est pas trivial (la preuve :), je l'ai indiqué dans le commentaire.
Penses tu (moi oui) qu'il faudrait sortir ce traitement du form ?

2021-07-28 12:58 UTC, stephane commented on itou/utils/apis/api_entreprise.py
> +        address_line_1=address["l4"],
> Je me demande pourquoi on ne demande pas le SIRET dès le début en fait ? On pourrait peut-être sauter une étape dans ce cas ?

C'est aussi ce que j'ai proposé à @SebastienReuiller mais il pense que c'est perturbant d'afficher ensuite les établissements de l'entreprise (recherche initiale des orga). J'ai donc créé la carte Trello pour demander aux UX de trancher.

2021-07-28 14:02 UTC, celine-m-s commented on itou/utils/apis/api_entreprise.py
> +        address_line_1=address["l4"],
> ...il pense que c'est perturbant d'afficher ensuite les établissements de l'entreprise.

D'acc, ça se comprend. Hâte de voir ce que diront les UX.

2021-07-28 14:12 UTC, celine-m-s commented on itou/www/signup/tests.py
> +        api_entreprise_route = respx.get(f"{settings.API_ENTREPRISE_BASE_URL}/etablissements/{siret}").mock(
Hum... Ca me semble un peu lourd alors. Sinon on laisse comme ça mais si un jour l'URL change, on devra la changer partout.

2021-07-28 14:16 UTC, celine-m-s commented on itou/www/signup/views.py
> +        return HttpResponseRedirect(reverse("signup:prescriber_siren"))
Hum... J'ai un peu de mal à comprendre comme ça, mais oublie ma remarque.

2021-07-28 14:18 UTC, celine-m-s commented on itou/www/signup/views.py
> +# FIXME GET method with side-effect (session update)
>  je ne souhaite pas reprendre le mécanisme de stockage sans refonte du workflow.

Effectivement, la refonte sera un bon moment pour reprendre ce mécanisme-là aussi. Je remplacerais bien "FIXME" par "TODO" afin de rester cohérents. "FIXME" me laisse penser qu'un problème important est là mais qu'on ne le traite pas.

2021-07-28 14:29 UTC, celine-m-s commented on itou/www/signup/views.py
> +    # Request Sirene API to validate SIRET
Ah d'accord, je vois ! C'est fait dans `PrescriberSiretForm.clean_siret`.
Ça fait sens que ce soit dans le formulaire car c'est une sorte de validation mais c'est vrai que c'est inhabituel. 
Je modifierais bien le commentaire pour être plus explicite : 

```
`PrescriberSiretForm` performs several API calls to the SIRENE API to:
- validate the SIRET existence,
- get organization information such as the address (form.org_data).
See PrescriberSiretForm.clean_siret.
```

2021-07-28 14:32 UTC, celine-m-s commented
> Ah et pour les points en fin de ligne, je n'ai pas d'avis mais parfois ils étaient présents parfois non, j'ai fait un choix au pif. Je peux les remettre (partout).

Je vote pour les points partout. :muscle:

2021-07-28 15:44 UTC, stephane commented on itou/www/signup/views.py
> +# FIXME GET method with side-effect (session update)
Done.

2021-07-28 15:52 UTC, stephane commented on itou/www/signup/views.py
> +    # Request Sirene API to validate SIRET
Il y a un seul appel à Sirene et un autre à Adresse API mais j'ai pris le comment avec ajustements. Merci.

2021-07-29 08:42 UTC, celine-m-s commented on itou/www/signup/views.py
> +    # See PrescriberSiretForm.clean_partial_siret.
Probablement un petit souci de copier / coller mais on peut vivre avec. :)

2021-07-29 08:42 UTC, celine-m-s approved these changes
LGTM

2021-07-29 09:06 UTC, stephane commented on itou/www/signup/views.py
> +    # See PrescriberSiretForm.clean_partial_siret.
Absolument pas ! Merci.

2021-07-29 09:16 UTC, merged