Notes de version du sprint 23
betagouv/itou pull request #796
Opened 2021-07-29 14:41 UTC by stephane

2021-07-29 16:19 UTC, vgrange approved these changes
LGTM

2021-07-29 16:20 UTC, celine-m-s requested changes
Quelques petites modifs rapides. Merci. :)

2021-07-29 16:20 UTC, celine-m-s commented on CHANGELOG.md
> +- Exclusion des URLS de connexion/déconnexion de l'intergiciel des permissions
```suggestion
```

Ces URLs sont encore présentes dans l'intergiciel.

2021-07-29 16:20 UTC, celine-m-s commented on CHANGELOG.md
> +- Affichage du recherche envoyé à l'API Sirene en cas d'erreur
Il manque peut-être un mot ?

2021-07-29 16:20 UTC, celine-m-s commented on CHANGELOG.md
> +- Transfert des ressources utilisées par les applications de revue dans une
```suggestion
- Transfert des ressources utilisées par les recettes jetables dans une
```

2021-07-29 16:20 UTC, celine-m-s commented on CHANGELOG.md
> +- Possibilité d'accepter une candidature précédemment refusée
```suggestion
- Possibilité d'accepter une candidature précédemment annulée
```

2021-07-30 12:55 UTC, Keirua approved these changes
RÀS en ce qui me concerne

2021-08-02 07:34 UTC, stephane commented on CHANGELOG.md
> +- Exclusion des URLS de connexion/déconnexion de l'intergiciel des permissions
OK

2021-08-02 07:34 UTC, stephane commented on CHANGELOG.md
> +- Affichage du recherche envoyé à l'API Sirene en cas d'erreur
Corrigé.

2021-08-02 07:35 UTC, stephane commented on CHANGELOG.md
> +- Possibilité d'accepter une candidature précédemment refusée
Corrigé.

2021-08-02 07:36 UTC, stephane commented on CHANGELOG.md
> +- Transfert des ressources utilisées par les applications de revue dans une
Corrigé.

2021-08-02 07:38 UTC, merged