Un candidat peut postuler s'il a un diagnostic valide
betagouv/itou pull request #805
Opened 2021-08-04 15:36 UTC by celine-m-s

### Quoi ?

Donner la possibilité à un candidat de postuler s'il dispose d'un diagnostic valide, même s'il est en période de carence.

### Pourquoi ?

Actuellement, un candidat qui est en délai de carence ne peut pas postuler même si un prescripteur habilité a réalisé un diagnostic.
Le support a reçu plusieurs retours à ce sujet de la part de prescripteurs qui s'en étonnaient.
Nous adaptons donc le code au besoin métier.

### Comment ?

Mise à jour d'une méthode qui contourne la période de carence dans certains cas.
Mise à jour de l'interface.

### Captures d'écran

#### Candidat :
AVANT : 

MAINTENANT : 
![image](https://user-images.githubusercontent.com/6150920/128209940-0ee0062f-c033-4241-8fdd-a263d2258d94.png)

#### Employeur
AVANT : 

MAINTENANT : 
![image](https://user-images.githubusercontent.com/6150920/128210276-3dfa03df-8c4f-4b23-876c-2bac2cd83daa.png)

#### Prescripteur
AVANT : 

MAINTENANT : 
![image](https://user-images.githubusercontent.com/6150920/128210099-49e63efd-aa2d-4f3e-a850-be1dec5c801c.png)

2021-08-09 13:13 UTC, kemar requested changes
Avant d'aller plus loin j'ai un doute sur la condition métier permettant de se soustraire à la période de carence. Il faudrait le faire confirmer par le métier (j'en suis sûr à titre perso).

2021-08-09 13:13 UTC, kemar commented on itou/users/models.py
> +        return EligibilityDiagnosis.objects.has_considered_valid(job_seeker=self, for_siae=for_siae)
Ici je pense que tu peux utiliser la relation inverse pour éviter un import :

```python
return self.eligibility_diagnoses.has_considered_valid(job_seeker=self)
```

D'autre part, et plus important, je pense que la logique est fausse et qu'il faut uniquement autoriser un diagnostic établi par un **prescripteur habilité**.

Une auto-prescription émise par une SIAE ne saurait servir de passe-droit à la période de carence.

2021-08-09 13:29 UTC, celine-m-s commented on itou/users/models.py
> +        return EligibilityDiagnosis.objects.has_considered_valid(job_seeker=self, for_siae=for_siae)
Ah oui, merci pour la relation inverse ! :+1: 

Ici nous sommes sur `User` et nous remarquons que `for_siae` est `None` par défaut. Dans ce cas,  `EligibilityDiagnosis.objects.has_considered_valid(job_seeker)` renvoie le dernier diagnostic réalisé **par un prescripteur habilité** uniquement et non par une SIAE. 

Nous appelons cette méthode dans  `Approval.cannot_bypass_waiting_period` sans indiquer la SIAE afin justement de ne pas prendre en compte les auto-prescriptions. [C'est d'ailleurs testé ici](https://github.com/betagouv/itou/pull/805/files#diff-83b5e3e3af2056e43f037c37edd67b3ea593c34f13fc7134859e4300be31ba84R729).

Mais j'ai peut-être loupé un truc ?

Cela étant, ça mérite probablement un bon commentaire car ça ne saute pas aux yeux.

2021-08-09 13:36 UTC, kemar commented on itou/users/models.py
> +        return EligibilityDiagnosis.objects.has_considered_valid(job_seeker=self, for_siae=for_siae)
Oui tu as raison… J'ai lu trop vite ! Cela dit le commentaire sera bienvenu 😅 Je continue la revue du coup.

2021-08-09 13:49 UTC, kemar approved these changes
LGTM

2021-08-11 07:58 UTC, merged

2021-08-11 08:28 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [Relier le diagnostic d'éligibilité au candidat](https://trello.com/c/Kc0cMOQg/1839-relier-le-diagnostic-d%C3%A9ligibilit%C3%A9-au-candidat)