Déploiement d'une recette jetable en fonction de l'activité d'une branche
betagouv/itou pull request #807
Opened 2021-08-05 12:31 UTC by celine-m-s

Le titre et la description sont en français et au format texte.

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

---

Liens intéressant :

- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8

2021-08-09 12:18 UTC, kemar requested changes
Je ne suis pas certain à 100% de la pertinence de ma remarque sur l'envoi du code local en recette. J'aimerais ton avis sur la question.

2021-08-09 12:18 UTC, kemar commented on Makefile
> +	git push clever_review_app HEAD:master
C'est pas un peu bizarre d'envoyer du code local sur une recette jetable, dans le sens où on risque d'oublier de le pousser dans la branche idoine sur _origin_ ?

Ne faudrait-il pas envoyer le code de la branche plutôt que le code local ?

2021-08-09 12:50 UTC, celine-m-s commented on .github/workflows/review-app-creation.yml
> +        $CLEVER_CLI create $REVIEW_APP_NAME -t python --org $REVIEW_APPS_ORGANIZATION_NAME --region par --alias $REVIEW_APP_NAME --github ${{ github.event.repository.owner.login }}/${{ github.event.r
C'est une bonne idée, je vais le rajouter.
Idéalement, on devrait passer à cet endroit-là la branche à suivre. Malheureusement, on ne peut pas... ou alors on doit utiliser l'API de Clever et je ne pense pas que le jeu en vaille la chandelle.

2021-08-09 12:53 UTC, celine-m-s commented on Makefile
> +	git push clever_review_app HEAD:master
Oui, tu as raison. Je vais modifier le script pour vérifier que la branche est bien à jour avec `origin`.
Nous ne pouvons pas "envoyer" le code de la branche sur Clever autrement que manuellement : il faut aller dans l'interface, puis dans l'application de la recette jetable,  sélectionner la branche à suivre puis cliquer de nouveau pour lancer un déploiement.
J'ai trouvé que ce petit script était plus rapide. Qu'en penses-tu ?

2021-08-09 12:57 UTC, kemar commented on Makefile
> +	git push clever_review_app HEAD:master
Ah, ok compris. En effet plus pragmatique quand on a le contexte :)

2021-08-09 14:23 UTC, SebastienReuiller reviewed
Quand tu dis "perte de temps et d'énergie", tu penses au côté serveur ? Car pour ma part, quand j'ai eu à mettre à jour une recette jetable, j'ai retiré le label et l'ai remis, ça ne m'a pas pris longtemps.

2021-08-09 15:54 UTC, celine-m-s commented
> Car pour ma part, quand j'ai eu à mettre à jour une recette jetable, j'ai retiré le label et l'ai remis, ça ne m'a pas pris longtemps.

Oui, je pense au temps que GitHub met pour créer l'app. Ca met environ dix minutes alors qu'un redéploiement n'en demande qu'une ou deux... Ca, encore, on peut vivre avec.
Le plus pénible (et c'est ce qui m'est arrivé jeudi) c'est quand tu crée un jeu de données pour la recette et que tu veux le garder. Actuellement, ce n'est pas possible car on doit tout détruire. :cry:

2021-08-11 09:35 UTC, kemar approved these changes
LGTM 🤩

2021-08-11 16:07 UTC, merged