Correctif concernant la récupération des agréments délivrés par Pôle emploi
betagouv/itou pull request #813
Opened 2021-08-11 16:22 UTC by celine-m-s

:warning: En lien avec la PR de Clément : https://trello.com/c/9Udzp4Gh/1990-c1-bug-dans-le-module-de-reprise-dagrément-sil-a-déjà-été-repris-par-un-autre-employeur-avant
Reprendre sa PR avant de soumettre celle-ci car tout le code a changé.

### Quoi ?

...

### Pourquoi ?

...

### Comment ?

...

2021-08-12 13:57 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Bug dans le module de reprise d'agrément s'il a déjà été repris par un autre employeur avant](https://trello.com/c/9Udzp4Gh/1990-c1-bug-dans-le-module-de-reprise-dagr%C3%A9ment-sil-a-d%C3%A9j%C3%A0-%C3%A9t%C3%A9-repris-par-un-autre-employeur-avant)

2021-08-12 13:57 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reprise d'agrément : le bon agrément n'est pas trouvé](https://trello.com/c/tDNYLHCS/2006-reprise-dagr%C3%A9ment-le-bon-agr%C3%A9ment-nest-pas-trouv%C3%A9)

2021-08-12 14:27 UTC, kemar approved these changes
LGTM

2021-08-12 15:33 UTC, stephane requested changes
Tu as bien creusé le sujet, bravo !

2021-08-12 15:33 UTC, stephane commented on itou/approvals/models.py
> +            return approvals.order_by("-start_at")
On retourne aussi les non valides ?

2021-08-12 15:33 UTC, stephane commented on itou/approvals/models.py
> +            approvals_numbers = approvals.values_list("number", flat=True)
Pour éviter une requête SQL (plus lente), j'aurai effectué la mise à plat avec un list comprehension ici.
```python
approvals_numbers = [approval.number for approval in approvals]
```

2021-08-12 15:33 UTC, stephane commented on itou/approvals/models.py
> +            return approvals.order_by("-start_at")
Pour éviter une requête, il est possible de faire :
```python
approvals = Approval.objects.filter(number=self.number[:12]).order_by("-start_at")

if approvals:
    return approvals
```

2021-08-12 15:33 UTC, stephane commented on itou/templates/approvals/pe_approval_search_found.html
> +            <a class="btn btn-outline-primary" href="{% url 'apply:start' siae_pk=siae.id %}?job_seeker_pk={{ approval.user.pk }}">
Tiens au fait, ne devrions nous pas toujours utiliser `.pk` ?

2021-08-12 15:33 UTC, stephane commented on itou/templates/approvals/pe_approval_search_found.html
> -            </form>
:+1:

2021-08-12 15:33 UTC, stephane commented on itou/approvals/models.py
> +        approvals: Queryset or list of Approval objects.
Ce ne sont pas toujours des `Approval` mais aussi des `PoleEmploiApproval`.

Le terme `merged_approvals` pourrait être utilisé ici aussi pour indiquer que nous sommes sur une fusion ou `common_approval` pour faire référence au mixin.

2021-08-17 12:38 UTC, celine-m-s commented on itou/approvals/models.py
> +            approvals_numbers = approvals.values_list("number", flat=True)
Très bonne idée, merci !

2021-08-17 12:39 UTC, celine-m-s commented on itou/approvals/models.py
> +            return approvals.order_by("-start_at")
Bien vu ! Merci !

2021-08-17 12:41 UTC, celine-m-s commented on itou/approvals/models.py
> +        approvals: Queryset or list of Approval objects.
Très juste, merci.

2021-08-17 12:45 UTC, celine-m-s commented on itou/templates/approvals/pe_approval_search_found.html
> +            <a class="btn btn-outline-primary" href="{% url 'apply:start' siae_pk=siae.id %}?job_seeker_pk={{ approval.user.pk }}">
Bien vu !

2021-08-17 14:43 UTC, celine-m-s commented on itou/approvals/models.py
> +            return approvals.order_by("-start_at")
Non, que les valides. En tous cas c'est  le comportement d'origine. C'est la méthode qui est utilisée lors du processus de candidature et j'avoue que j'ai les doigts qui tremblent quand j'y touche ! :smile:

2021-08-19 07:28 UTC, stephane commented on itou/approvals/models.py
> +            return approvals.order_by("-start_at")
Je ne vois pas trop la logique mais OK !
que penses tu d'un commentaire du style « Retourne tous les agréments si la liste contient au moins un agrément valide »

2021-08-19 07:36 UTC, stephane approved these changes
Pleins de détails, beau boulot !

2021-08-19 08:16 UTC, kemar approved these changes
LGTM 👏 Quelques suggestions sur la forme

2021-08-19 08:16 UTC, kemar commented on itou/templates/approvals/pe_approval_search_found.html
> +                    L'agrément <strong>{{ approval.number|slice:12 }}</strong> a été délivré pour <strong>{{ approval.first_name|title }} {{ approval.last_name|title }}</strong>.
```suggestion
                    L'agrément <strong>{{ approval.number|slice:12 }}</strong> a été délivré pour <strong>{{ approval.get_full_name|title }}</strong>.
```

2021-08-19 08:16 UTC, kemar commented on itou/templates/approvals/pe_approval_search_user.html
> +    <h3 class="text-secondary">{{pe_approval.first_name}} {{pe_approval.last_name}}</h3>
```suggestion
    <h3 class="text-secondary">{{ pe_approval.first_name|title }} {{ pe_approval.last_name|title }}</h3>
```

2021-08-19 10:53 UTC, celine-m-s commented on itou/templates/approvals/pe_approval_search_found.html
> +                    L'agrément <strong>{{ approval.number|slice:12 }}</strong> a été délivré pour <strong>{{ approval.first_name|title }} {{ approval.last_name|title }}</strong>.
Merci pour l'idée mais malheureusement ça ne fonctionne pas. :cry: L'objet `Approval` n'a pas la méthode `get_full_name`.

2021-08-19 11:23 UTC, merged