Amélioration du tunnel d'inscription des prescripteurs
betagouv/itou pull request #814
Opened 2021-08-12 10:42 UTC by stephane

### Quoi ?

Offrir une action aux prescripteurs non inscrits qui souhaite rejoindre une organisation.

### Pourquoi ?

Dans les organisations ayant de nombreux membres, il est difficile pour un prescripteur de savoir qui contacter pour rejoindre l'organisation à laquelle il souhaite être rattaché.

### Comment ?

En affichant un bouton de demande d'invitation dans les résultats de recherche.
L'utilisateur ne dispose pas encore de compte, il doit saisir ses coordonnées :
- nom
- prénom
- email

Le mail envoyé au prescripteur (automatiquement sélectionné) contient un lien permettant
de faciliter l'envoi de l'invitation en pré-remplissant le formulaire d'invitation.

### Captures d'écran

![avant](https://user-images.githubusercontent.com/1815/129176862-1f2e65a5-23b1-4c76-a80e-537f9b51156a.png)

![après](https://user-images.githubusercontent.com/1815/129176888-d79a1cb8-7feb-498a-a2ad-16d64f1c49e4.png)

![nouveau-prescripteur-form](https://user-images.githubusercontent.com/1815/129177046-ed36cec4-d6af-41e2-98f3-22818195c44a.png)

### Autre

- https://trello.com/c/9M5uXywO/1983-c1-action-de-sortie-quand-lorganisation-existe-lors-de-linscription-dun-prescripteur
- https://whimsical.com/parcours-visiteur-inscription-Uumm66AYuEU9cFHFiKN1Cu

2021-08-17 14:48 UTC, kemar requested changes
Que des retours de surface sauf un qui me semble important : je crois qu'il y a un bug dans le sujet de l'e-mail qui est envoyé.

2021-08-17 14:48 UTC, kemar commented on itou/templates/common/emails/request_for_invitation_body.txt
> +Bonjour {{ to.first_name|capfirst }} {{ to.last_name|capfirst }},
```suggestion
Bonjour {{ to.get_full_name|title }},
```

Avantage : on gère les benêts qui entrent leur patronyme en mode CAPS LOCK fury :)

2021-08-17 14:48 UTC, kemar commented on itou/templates/common/emails/request_for_invitation_body.txt
> +{{ requestor.first_name|capfirst }} {{ requestor.last_name|capfirst }} a demandé à rejoindre votre organisation « {{ organization.display_name }} ».
```suggestion
{{ requestor..get_full_name|title }} a demandé à rejoindre votre organisation « {{ organization.display_name }} ».
```

2021-08-17 14:48 UTC, kemar commented on itou/templates/common/emails/request_for_invitation_body.txt
> +Si vous acceptez d'inviter cette personne dans votre organisation, cliquer sur le lien <a href="{{ invitation_url }}"></a>.
```suggestion
Si vous acceptez d'inviter cette personne dans votre organisation, cliquez sur le lien <a href="{{ invitation_url }}"></a>.
```

On conserve le mode impératif pour rester constant.

2021-08-17 14:48 UTC, kemar commented on itou/templates/common/emails/request_for_invitation_subject.txt
> +Demande pour rejoindre {{ structure.display_name }}
Je pense que c'est `organization` qui est passé dans le contexte et pas `structure`.

Il manque peut-être un bout de test sur le `subject` dans `test_form_to_request_for_an_invitation`.

2021-08-17 14:48 UTC, kemar commented on itou/templates/signup/prescriber_siren.html
> +                                {# Ordered by -is_admin and date_joined. #}
Si je lis le commentaire comme ça sans contexte, je ne comprends pas comment est fait ce tri.

On pourrait préciser que le tri est fait par le truchement de `prefetch_active_memberships` dans la vue, ça ferait gagner du temps à quelqu'un qui découvre.

2021-08-17 14:48 UTC, kemar commented on itou/www/signup/views.py
> +            " a été envoyée par courriel."
Dans cette PR j'ai lu :

- courriel
- e-mail
- mail

Je dis ça, je dis rien 😺

2021-08-18 07:18 UTC, stephane commented on itou/templates/common/emails/request_for_invitation_body.txt
> +Si vous acceptez d'inviter cette personne dans votre organisation, cliquer sur le lien <a href="{{ invitation_url }}"></a>.
Mais carrément et surtout je me rends compte que le lien est vide !

2021-08-18 08:18 UTC, stephane commented on itou/templates/signup/prescriber_siren.html
> +                                {# Ordered by -is_admin and date_joined. #}
Carrément.

2021-08-18 08:18 UTC, stephane commented on itou/templates/common/emails/request_for_invitation_body.txt
> +{{ requestor.first_name|capfirst }} {{ requestor.last_name|capfirst }} a demandé à rejoindre votre organisation « {{ organization.display_name }} ».
Fait.

2021-08-18 08:18 UTC, stephane commented on itou/templates/common/emails/request_for_invitation_body.txt
> +Si vous acceptez d'inviter cette personne dans votre organisation, cliquer sur le lien <a href="{{ invitation_url }}"></a>.
Et fix HTML. Fait.

2021-08-18 08:42 UTC, stephane commented on itou/templates/common/emails/request_for_invitation_subject.txt
> +Demande pour rejoindre {{ structure.display_name }}
Fixed. Merci.

2021-08-18 13:54 UTC, merged