Archivage des anciennes fiches salarié
betagouv/itou pull request #822
Opened 2021-08-18 15:53 UTC by ikarius

### Quoi ?

- ajout d'un nouveau statut `ARCHIVED` pour les fiches salarié,
- ajout d'une option de management command pour procéder à l'archivage des fiches salarié impactées

### Pourquoi ?

La plateforme de l'inclusion a signé un contrat avec la DGEFP concernant la destruction des données personnelles des utilisateurs
envoyées à l'ASP et n'ayant pas vocation a être stockées sur le long terme.

En fait, la plupart des informations restent stockées car désormais partie intégrante de la plateforme, seules:
- les données de "preuves" d'envoi de la fiche,
- les métadonnées des fichiers envoyés,
- 
sont supprimées après un délai de 13 mois après intégration de la fiche par l'ASP

### Comment ?

- suppression des données de preuve de transfert (champ sérialisé)
- CRON executé à intervalle régulier via la management command `transfer_employee_records` (à 23.05 tous les jours ouvrés)

2021-08-20 08:47 UTC, vgrange approved these changes
LGTM + une suggestion pour de renommer `update_as_archived`.

Mes 2 cts : je trouve la commande `transfer_employee_records` un peu grosse. Plutôt que de lui rajouter l'option `--archive`, pourquoi ne pas juste faire une commande dédiée `archive_employee_records` séparée et dédiée ?

2021-08-20 08:47 UTC, vgrange commented on itou/employee_record/models.py
> +    def update_as_archived(self):
Je trouve `update_as_archived` un peu confusant. `mark_as_archived` ?

2021-08-23 09:44 UTC, ikarius commented on itou/employee_record/models.py
> +    def update_as_archived(self):
J'ai appelé toutes mes méthodes `update_at_` + status pour les changements

2021-08-23 13:09 UTC, kemar requested changes
Une demande de mutualisation de `30 * settings.EMPLOYEE_RECORD_ARCHIVING_DELAY_IN_MONTHS` qui est utilisé au moins 4 fois => on risquerait d'oublier de le modifier quelque part.

Le reste c'est des questions de surface dont une qui cache peut-être un problème de performance.

2021-08-23 13:09 UTC, kemar commented on itou/employee_record/tests.py
> +        command.handle(archive=True)
Pour la forme, il y a [un truc dans Django](https://docs.djangoproject.com/en/3.2/ref/django-admin/#django.core.management.call_command) un chouïa plus explicite :

```python
from django.core import management
management.call_command('transfer_employee_records', archive=True)
```

2021-08-23 13:14 UTC, ikarius commented on itou/employee_record/management/commands/transfer_employee_records.py
> +                    er.update_as_archived()
Mmm. justement, on ne sait pas trop encore quelle sera la volumétrie sur un mois. Je vais faire une approximation sur la moyenne des candidatures acceptées sur une journée et on va voir

2021-08-23 13:16 UTC, ikarius commented on itou/employee_record/models.py
> +        # => approximate 1 month to 30 days
Merci du retour, je vais nommer / convertir tout ça en jours ce sera plus homogène

2021-08-23 13:18 UTC, ikarius commented on itou/employee_record/models.py
> +        processed_delta = timezone.timedelta(days=30 * settings.EMPLOYEE_RECORD_ARCHIVING_DELAY_IN_MONTHS)
Ach ja, genau!

2021-08-23 13:19 UTC, ikarius commented on itou/employee_record/models.py
> +        self.archived_json = None
A priori comme on y touche plus après, ça devrait être le `updated_at`.
Je n'ai pas encore vu de cas d'utilisation pour ...

2021-08-23 13:20 UTC, ikarius commented on itou/employee_record/tests.py
> +        command.handle(archive=True)
C'est effectivement plus lisible et explicite sur le nom de la M.C. J'adopte

2021-08-23 13:54 UTC, ikarius commented on itou/employee_record/models.py
> +        processed_delta = timezone.timedelta(days=30 * settings.EMPLOYEE_RECORD_ARCHIVING_DELAY_IN_MONTHS)
Je vais le passer en jours de toute façon

2021-08-23 16:11 UTC, ikarius commented on itou/employee_record/management/commands/transfer_employee_records.py
> +                    er.update_as_archived()
On parle de quelques centaines d'enregistrements, répartis sur une journée.
On peut répéter le cron plusieurs fois par jour au lieu d'une seule fois actuellement, et / ou faire un batch update (et décaler un peu de métier dans la management command)

2021-08-23 16:17 UTC, kemar commented on itou/employee_record/management/commands/transfer_employee_records.py
> +                    er.update_as_archived()
Je ferais un batch perso, mais ça peut faire l'objet d'une autre carte.

2021-08-23 17:30 UTC, ikarius commented on itou/employee_record/management/commands/transfer_employee_records.py
> +                    er.update_as_archived()
Va pour le batch. On aura l'esprit tranquille, je commenterais et je mets ça en ligne demain

2021-08-24 08:33 UTC, kemar approved these changes
LGTM 🙏

2021-08-24 08:43 UTC, merged