Retraitement de la donnée de la table fluxIAE_AnnexeFinanciere
betagouv/itou pull request #827
Opened 2021-08-20 13:25 UTC by SoumiaAHLOUCH

### Quoi ?

- Extraire le numéro du département à partir du numéro de l'annexe financière
- Récupérer le type de structure de la colonne af.af_mesure_dispositif_code
- Retraiter les variables dates qui sont au format string dans la table fluxIAE_AnnexeFinanciere

### Pourquoi ?

Simplifier les requêtes Metabase

2021-08-20 13:37 UTC, vgrange requested changes
Requête OK mais pas mal de remarques sur le style du code.

Je propose de toujours indenter de 4 espaces à chaque fois. Même si la ligne du dessus est longue. Sinon on termine avec des indentations extrêmes :-D

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +                     af.af_mesure_dispositif_code from 1 for char_length(af.af_mesure_dispositif_code)-3
Mmm là tu indentes de +12 espaces au lieu de +4 espaces. Je comprends pourquoi, parce que `substring(` au dessus est un peu long. Mais je te propose qu'on indente toujours de 4 espaces, peu importe la ligne du dessus. Même remarque plusieurs fois plus bas.

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +               ) as af_date_fin_effet_v2,
Au lieu de :

```
        to_date(
                   af.af_date_fin_effet, 'dd/mm/yyyy'
               ) as af_date_fin_effet_v2,
```

je propose donc :

```
        to_date(
            af.af_date_fin_effet, 'dd/mm/yyyy'
        ) as af_date_fin_effet_v2,
```

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +                /* Retirer le type de structure du numéro de l'annexe financière par exemple on passe de ACI034150012 à 034150012 */
Commentaire décalé.

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +	            par exemple on passe de 034150012 à 034 */
Commentaire décalé.

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +		            on récupère les 2 cacartères qui suivent le 0 */
Pourquoi +8 espaces et pas juste +4 ?

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +		                             trim(af_numero_annexe_financiere_v4) from 1 for 3)
Wow l'indentation de cette ligne est tellement loin :-D

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +    dept_af.nom_region as nom_departement_af ,
Attention, pas d'espace avant les virgules.

2021-08-20 13:37 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +    af_id_structure
Euh quel intérêt de trier ? C'est une création de table.

2021-08-20 14:05 UTC, SoumiaAHLOUCH commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +    af_id_structure
Pas d'intérêt dans la création de la table, c'était pour moi quand je faisais les tests au moment de la construction de la requête, je vire

2021-08-23 09:30 UTC, vgrange approved these changes
2-3 indentations à corriger et LGTM 🚀

2021-08-23 09:30 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +            from
Oups ce `from` doit être désindenté d'un cran non ?

2021-08-23 09:30 UTC, vgrange commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +                    trim(af_numero_annexe_financiere_v4) from 2 for 2
`trim` à indenter

2021-08-23 10:28 UTC, SoumiaAHLOUCH commented on itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
> +            from
I agree et j'ai fait le nécessaire :)

2021-08-23 10:50 UTC, merged