Identification via FranceConnect
betagouv/itou pull request #844
Opened 2021-08-30 07:17 UTC by stephane

### Quoi ?

Prise en charge de l'identification via FranceConnect.

### Pourquoi ?

Pour permettre d'obtenir des informations fiables et facilement de la part des candidats.

### Comment ?

En ajoutant les URL nécessaires à la dance oauth2 sur laquelle s'appuie FranceConnect.
Zéro nouvelle dépendance.
Création d'une nouvelle data pour le state.
La méthode de stockage des informations issues de FC est juste une ébauche.

J'ajouterais peut être la prise en charge des codes INSEE pour la commune ou le pays dans la journée.

### Captures d'écran (optionnel)

![Capture d’écran de 2021-08-25 11-13-40](https://user-images.githubusercontent.com/1815/131300375-5061d9bc-c505-431e-9cdf-046d989e3759.png)

![Capture d’écran de 2021-08-25 22-06-35](https://user-images.githubusercontent.com/1815/131300394-1e17a9cb-8a94-48dc-a2bd-164ccf6e96f4.png)

2021-08-31 15:18 UTC, kemar requested changes
Kudos 👏  Beau boulot et sans aucune dépendance !

Quelques retours et questions de surface.

Je sais que le mécanisme JSON du stockage des informations n'est pas définitif mais vu comme ça j'ai peur qu'on parte vers du temporaire qui va devenir permanent…

2021-08-31 15:24 UTC, Keirua approved these changes
Gros boulot, bravo ! Des petits pinaillages mais dans le principe ça semble très bien

2021-08-31 15:24 UTC, Keirua commented on envs/secrets.env.template
> +# Ddefault values of the integration platform are not confidentials
```suggestion
# Default values of the integration platform are not confidentials
```

2021-08-31 15:31 UTC, ikarius commented on envs/secrets.env.template
> +# Ddefault values of the integration platform are not confidentials
s/confidentials/confidential

2021-08-31 15:44 UTC, ikarius commented on itou/france_connect/views.py
> +    username: str
C'est plus informatif qu'autre chose

2021-08-31 16:41 UTC, stephane commented on config/urls.py
> +    path("callback", france_connect_views.france_connect_callback),
Oops c'est une contrainte d'intégration (comme indiquer dans d'autres commentaires) que j'aurais dû supprimer dans ma PR.

2021-08-31 16:42 UTC, stephane commented on requirements/base.txt
> +sentry-sdk==1.3.1  # https://github.com/getsentry/sentry-python
Je fais des appels `.capture` mais je peux les supprimer et passer simplement par le logger.
Je vais faire ça (et en cascade, restaurer la dépendance dans son fichier initial).

2021-08-31 16:44 UTC, stephane commented on itou/france_connect/views.py
> +def france_connect_authorize(request):
Je ne sais pas comment vous souhaitez mettre tout ça en musique, je me suis dit qu'exposer les URL sans le bouton pouvait permettre de tester avant une release qui contiendrait le bouton...

2021-08-31 16:47 UTC, stephane commented on itou/france_connect/views.py
> +    return user, created
Oui c'est aussi ce que j'ai pensé (je pensais à un `serializers.py`) mais avant de passer plus de temps sur le traitement du endpoint je me suis dit qu'il fallait déjà validé la méthode.
Il manque aussi des setters et override `save()` dans User pour maintenir les sources et dates.

2021-08-31 16:48 UTC, stephane commented on itou/france_connect/models.py
> +        return self.filter(created_at__lte=timezone.now() - datetime.timedelta(hours=1)).delete()
Bah en fait, si !
Commit à suivre.

2021-08-31 17:12 UTC, stephane commented on itou/france_connect/views.py
> +    # birth_place_id from user_data["birthplace"]
Je dirais dead code qu'il faut coder, j'ai commencé (dans un stash) qui recherche dans les données ASP mais j'étais juste en temps.

2021-08-31 17:12 UTC, stephane commented on itou/france_connect/views.py
> +    FranceConnectState.objects.cleanup()
Tout à fait.
Je modifie.

2021-09-01 13:48 UTC, stephane commented on config/urls.py
> +    path("callback", france_connect_views.france_connect_callback),
Fait.

2021-09-01 14:07 UTC, stephane commented on requirements/base.txt
> +sentry-sdk==1.3.1  # https://github.com/getsentry/sentry-python
Fait.

2021-09-01 14:11 UTC, stephane commented on itou/france_connect/models.py
> +        return self.filter(created_at__lte=timezone.now() - datetime.timedelta(hours=1)).delete()
Fait.

2021-09-01 14:11 UTC, stephane commented on itou/france_connect/views.py
> +    return user, created
Déplacé dans models

2021-09-01 14:15 UTC, stephane commented on itou/france_connect/views.py
> +    FranceConnectState.objects.cleanup()
Fait.

2021-09-01 14:16 UTC, stephane commented on envs/secrets.env.template
> +# Ddefault values of the integration platform are not confidentials
Fait.

2021-09-06 14:16 UTC, kemar commented
Résumé de l'état des lieux du chantier FranceConnect avec @stephane 

## Scénarios d'usage

2 scénarios possibles pour utiliser FranceConnect sur les emplois.

### 1) Par un prescripteur

En tant que prescripteur qui accompagne un DE (ils sont dans le même bureau) : le prescripteur a une session Itou ouverte et clique sur le bouton FranceConnect puis donne le clavier au DE pour que ce dernier saisisse ses informations.

Il n'y a pas d'`authenticate` à la fin du scénario => donc pas de session ouverte sur Itou, on a juste récupéré les informations du DE via FranceConnect.

Ce scénario est implémenté en partie.

**TODO** :

- faire un travail d'UX pour imaginer où mettre ce bouton dans les parcours
- faire un logout de FranceConnect dans la foulée

### 2) Par un DE autonome

Ce scénario n'est pas encore implémenté. Il suffit de rajouter un `authenticate` à la fin.

**TODO** : implémenter ce scénario (en pratique, juste un `authenticate`)

## Stockage des données de FranceConnect

Les données sont stockées dans un champ JSON sur le modèle `User`.

**TODO** :

- faire un `setter` propre qui aurait deux arguments `valeur` et `source` (`FranceConnect`, `PE Connect` ou `Itou` dans le cas d'une saisie utilisateur)
- le `setter` aurait aussi pour rôle de venir invalider une donnée récupérée par FranceConnect ou PE Connect dans le cas ou une saisie utilisateur viendrait surcharger une valeur récupérée à l'extérieur
- remplacer la mécanique de l'app `external_data` par une écriture dans le champ JSON du modèle `User` cc @ikarius 

## Notes d'architecture

Le choix d'implémentation a été de le faire directement dans Django en mode "bas niveau" (validation manuelle du `state`, utilisation de la crypto Django etc.).

Autres choix qui auraient pu être possibles, davantage "haut niveau" :

- utiliser `keycloak` en mode client oAuth
- utiliser `httpx-oauth`

## Suite des opérations

On propose de fusionner la PR de @stephane  en l'état "en masquant" le bouton.

L'implémentation des TODO listés ci-dessus sera prise en charge par un autre dev chez nous pour continuer sur cette base.

2021-09-06 15:03 UTC, ikarius commented
Je suis peut-être hors-contexte...
Concernant l'ajout de données directement dans `User`, bien que `ExternalData` ne soit pas optimal, je ne sais pas si c'est une bonne idée. 
A mon avis `User` devrait être un modèle à minima, et les metadonnées qui gravitent autour peuvent être modélisées sous forme de "profils" specifiques à chaque "domaine" ou "source" (comme `ExternalData` ou plus clean, `JobSeekerProfile` pour les F.S.).
En plus l'emploi du JSON brut dans le modèle, même si j'y ai cédé plusieurs fois, est rarement une bonne idée pour la réutilisation des metadonnées.

It was my 2 cents ...

2021-09-07 21:34 UTC, stephane commented
@ikarius  Avec un JSON générique pour décrire la source et l'heure du champ, on offre la possibilité d'avoir des setters très simples (et sans jointure SQL cachée) quelque soit la source du champ.

C'est quoi l'astuce pour ignorer l'avertissement GitGuardian (un markup qui va bien ?) ?

2021-09-08 08:12 UTC, kemar commented
> En plus l'emploi du JSON brut dans le modèle, même si j'y ai cédé plusieurs fois, est rarement une bonne idée pour la réutilisation des metadonnées.

Moi je vois un JSON field ici et quelques meta données en dehors (source, status, date de création) : https://github.com/betagouv/itou/blob/41870fc258a8578db40abac6a39f4fdb3c76d529/itou/external_data/models.py#L50

Je ne comprends pas les raisons pour lesquelles y stocker aussi les métadonnées serait une mauvaise idée ? @ikarius

2021-09-08 12:15 UTC, ikarius commented
Pour reprendre sur les meta-données, construire un modèle est AMHA préférable, plutôt que quelque chose de non-typé comme du JSON. 
C'est valable et rapide pour stocker des trucs qu'on regarde presque jamais, qu'on exploite peu (par ex. la preuve de transmission des fiches salarié, ou le rapport des `ExternalData`).
Mais même si c'est un bon compromis à court-terme tant qu'on ne sait pas trop quoi faire des données, il vaut mieux modéliser et affiner dès qu'on a des cas d'utilisations concrets.

2021-09-08 12:59 UTC, kemar commented
> Pour reprendre sur les meta-données, construire un modèle est AMHA préférable, plutôt que quelque chose de non-typé comme du JSON.

@ikarius je ne vois toujours pas d'argument qui me satisfasse.

Je propose qu'on en discute de vive voix pour tomber d'accord et tenter de trouver un mécanisme global à la place de :

- un champ JSON sur `User`
- `external_data` d'un côté
- `JobSeekerProfile` d'un autre côté

@stephane 

- est-ce que le résumé du reste à faire est OK pour toi ? https://github.com/betagouv/itou/pull/844#issuecomment-913683706
- de quel avertissement GitGuardian parles-tu ?

2021-09-10 08:14 UTC, stephane commented
@kemar 
- nickel pour le résumé 
- GitGuardian Security Checks de cet PR (2 secrets uncovered).

2021-09-10 12:54 UTC, kemar commented
@stephane 

> * GitGuardian Security Checks de cet PR (2 secrets uncovered).

Il a pas aimé  les secrets dans `envs/secrets.env.template` même si ce sont des valeurs non confidentielles.

Il doit y avoir une option pour faire un *ignore* mais je pense que tu iras plus vite à passer ces valeurs en variables d'env.

2021-09-16 16:03 UTC, stephane commented
Git Guardian is happy! Et j'ai nettoyé l'historique (même si ce sont biens des clefs publiques).

2021-09-16 16:14 UTC, merged

2021-09-16 16:14 UTC, stephane commented
Bon courage pour la suite @Keirua 
Si tu as besoin d'infos n'hésites pas à me contacter...