Mise à jour de la liste des prescripteurs habilités
betagouv/itou pull request #857
Opened 2021-09-07 14:22 UTC by SebastienReuiller

### Quoi ?

Ajout de types d'organisation pour les prescripteurs habilités

### Pourquoi ?

En application de la loi du 14 décembre 2020 - [Arrêté du 1er septembre 2021 fixant la liste des critères d'éligibilité des personnes à un parcours d'insertion par l'activité économique et des prescripteurs mentionnés à l'article L. 5132-3 du code du travail](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000044011220)

### Comment ?

Ajout des nouveaux types sur le modèle "Prescripteur"

### Captures d'écran

Affichage des nouveaux types lors de l'inscription d'un prescripteur

![Affichage des nouveaux types lors de l'inscription d'un prescripteur](https://user-images.githubusercontent.com/17601807/132360329-d00fb7db-b0a3-4b8c-98a3-cb2d0e6d5d99.png)

2021-09-08 15:11 UTC, celine-m-s requested changes
Ça commence à faire une longue liste... Est-ce qu'on pourrait trier les acronymes par ordre alphabétique afin d'en faciliter la lecture ?

2021-09-09 08:21 UTC, SebastienReuiller commented
> Ça commence à faire une longue liste... Est-ce qu'on pourrait trier les acronymes par ordre alphabétique afin d'en faciliter la lecture ?

Oui, ça fait un peu de lecture. Je vais trier par ordre alphabétique dans l'immédiat mais je pense qu'il faudrait trouver une autre solution pour ces longues listes. Pourquoi pas un champs texte qui filtrerai la liste ?

2021-09-09 08:29 UTC, celine-m-s commented
> Pourquoi pas un champs texte qui filtrerai la liste ?

C'est une bonne idée ! Peut-être à proposer pour un Boost Design ?

2021-09-09 10:16 UTC, celine-m-s approved these changes
LGTM, merci !

2021-09-09 12:09 UTC, merged