Ajout d'une étape au processus de candidature si le candidat existe déjà
betagouv/itou pull request #858
Opened 2021-09-07 15:10 UTC by celine-m-s

### Quoi ?

Ajout d'une étape de confirmation pour s'assurer que l'e-mail entré est bien le bon.

### Pourquoi ?

Des prescripteurs ou des employeurs utilisent une même adresse e-mail pour plusieurs candidats.

### Comment ?

- Ajout d'une modale avec des informations sur le candidat trouvé en base
- Modifications diverses de l'interface

### Captures d'écran

#### Pendant le processus de candidature

Si le prescripteur est orienteur :
![image](https://user-images.githubusercontent.com/6150920/132367802-950ad80a-3809-4fc8-975f-befee16a6419.png)

Si l'utilisateur est employeur ou prescripteur habilité :
![image](https://user-images.githubusercontent.com/6150920/132368620-5ba389b9-5c84-4df4-8c16-6a91cb7249d4.png)

#### Clic sur « Ce n'est pas mon candidat  » :
![image](https://user-images.githubusercontent.com/6150920/132368004-bb53b443-0a67-46f4-8682-ec4a70421cf6.png)

#### Clic sur « Continuer »

Aucun changement.

#### Page de candidature
![image](https://user-images.githubusercontent.com/6150920/132368313-e2c7c84f-4ed5-4ebb-90a2-2b7801918e6c.png)

#### Page de modification des informations du candidat

![image](https://user-images.githubusercontent.com/6150920/132368416-4b6b56eb-2887-46f1-bc6a-5afa2c0cca0c.png)

### Autre

Changements par rapport aux maquettes :
- J'ai remplacé les guillemets ("") par les guillemets français («»).
- Message « Email existant » : « les informations personnelles du candidat pour **qui** vous allez postuler » par « les informations personnelles du candidat pour **lequel** vous allez postuler ».
- le message qui apparaît après avoir cliqué sur « Ce n'est pas mon candidat » est tout en haut et non après le titre. Pour des raisons techniques, c'est plus pratique. Si vraiment il faut l'indiquer après, vous pouvez me le dire et je ferai une modification plus poussée.
- Toujours concernant ce message, j'ai remplacé le texte souligné par du gras pour éviter toute confusion avec un lien hypertexte. Et même remarque que ci-dessus (qui par lequel).

2021-09-09 09:37 UTC, SebastienReuiller commented on itou/www/apply/views/submit_views.py
> +                    f"L'email <b>{ form.data['email'] }</b> est déjà utilisé par un autre candidat "
Pour ce message, ma proposition de simplification que j'avais faite dans la carte semblait convenir, à savoir :
"L'email [Email du candidat] est déjà utilisé par un autre candidat.
Merci de bien renseigner l'adresse email personnelle du candidat pour lequel vous souhaiter postuler."

2021-09-09 09:47 UTC, kemar requested changes
Je soulève un point qui me paraît un peu dur à comprendre pour discussion.

2021-09-09 09:47 UTC, kemar commented on itou/templates/apply/submit_step_job_seeker.html
> +                        </div>
J'imagine que vous en avez parlé mais je donne quand même mon avis 😛 

Quand la modale s'ouvre on ne voit plus l'email que l'on vient de saisir et on a du mal à comprendre pourquoi on parle d'identité alors qu'on vient de saisir un email.

Ne faudrait-il pas afficher clairement l'email saisi dans la modale pour :

- ne pas le perdre de vue
- comprendre le lien entre e-mail et identité ?

![skitch](https://user-images.githubusercontent.com/281139/132663238-9fff0cc2-f944-464d-b51b-7cfa01a65217.png)

2021-09-09 10:02 UTC, SebastienReuiller commented on itou/www/apply/views/submit_views.py
> +    preview_mode = False
Pourquoi un test sur `job_seeker_name` ne suffit pas ?

2021-09-15 10:34 UTC, celine-m-s commented on itou/www/apply/views/submit_views.py
> +    preview_mode = False
J'aime bien que les gabarits soient facilement compréhensibles et je pense que si on lit `if preview_mode`, on comprend plus facilement que `if job_seeker_name`. Qu'en penses-tu ?

2021-09-15 12:48 UTC, merged

2021-09-15 13:49 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] En tant que prescripteur, je modifie les informations du mauvais candidat pendant la candidature.](https://trello.com/c/zHVB4Hvi/1893-c1-en-tant-que-prescripteur-je-modifie-les-informations-du-mauvais-candidat-pendant-la-candidature)