Evolution des tableaux de bord Metabase des CD et des DDETS
betagouv/itou pull request #868
Opened 2021-09-17 12:35 UTC by vgrange

### Quoi ?

FIXME

### Pourquoi ?

FIXME

### Captures d'écran (optionnel)

FIXME

2021-09-17 13:57 UTC, vgrange commented on itou/institutions/models.py
> +        return self.kind == self.Kind.DDETS
J'en ai eu besoin pour résoudre un import loop entre User et Institution.

2021-09-17 13:57 UTC, vgrange commented on itou/users/models.py
> +            and current_institution.is_ddets
J'en ai eu besoin pour résoudre un import loop entre User et Institution.

2021-09-17 14:11 UTC, vgrange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Evolution des tableaux de bord Metabase des CD et des DDETS](https://trello.com/c/Ty4wV3fz/2153-evolution-des-tableaux-de-bord-metabase-des-cd-et-des-ddets)

2021-09-20 12:17 UTC, celine-m-s requested changes
Il me semble que certains points pourraient être améliorés. Rien de bloquant néanmoins.

2021-09-20 12:17 UTC, celine-m-s commented on itou/users/models.py
> +        return self.can_view_stats_cd(current_org=current_org) or self.can_view_stats_ddets(
Je pense que `current_institution` est accessoire car `current_org` et `current_institution` héritent de `OrganizationAbstract` et que les méthodes appelées font une vérification sur le type de l'organisation.

2021-09-20 12:17 UTC, celine-m-s commented on itou/institutions/models.py
> +        return self.kind == self.Kind.DDETS
C'est bizarre d'avoir une propriété pour un seul type. J'ai fait une proposition plus bas, à toi de voir si ça te paraît pertinent.

2021-09-20 12:17 UTC, celine-m-s commented on itou/users/models.py
> +            and current_institution.is_ddets
Est-ce que `current_institution.kind == current_institution.Kind.DDETS` pourrait fonctionner ?

2021-09-23 12:32 UTC, celine-m-s commented on itou/users/models.py
> +            and current_institution is not None
Supprimé dans mon dernier commit.

2021-09-23 12:32 UTC, celine-m-s commented on itou/users/models.py
> +        )
Deux lignes supprimées dans mon dernier commit.

2021-09-23 12:33 UTC, celine-m-s commented on itou/institutions/models.py
> +        return self.kind == self.Kind.DDETS
Supprimé dans mon dernier commit.

2021-09-23 12:34 UTC, kemar requested changes
Je suis d'accord avec tes remarques @celine-m-s

2021-09-23 12:34 UTC, kemar commented on itou/institutions/models.py
> +        return self.kind == self.Kind.DDETS
Ça me paraît superflu également.

2021-09-23 12:34 UTC, kemar commented on itou/users/models.py
> +            and current_institution is not None
[Dans ce cas là a priori](https://github.com/betagouv/itou/blob/5f88e7cfa7d01072d8c03423d6cc085861a520fd/itou/www/stats/views.py#L90-L91). Mais dans tous les cas `is not None` est superflu.

La question que je me pose : ne faudrait-il pas séparer les contrôles entre `is_stats_vip` et `can_view_stats_ddets` ? J'ai l'impression qu'on pourrait économiser des requêtes SQL.

2021-09-23 12:34 UTC, kemar commented on itou/users/models.py
> +            and current_institution.is_ddets
Oui ça pourrait :) Remplaçons-le et éliminons une _property_ inutile.

2021-09-23 12:34 UTC, kemar commented on itou/users/models.py
> +            and current_org.department in settings.CD_STATS_ALLOWED_DEPARTMENTS
Si. Le dernier test contient déjà ces contrôles, ça fait de la répétition.

2021-09-23 12:34 UTC, kemar commented on itou/users/models.py
> +            return "01"
C'est quoi l'intérêt de montrer uniquement le département 01 à tous les VIPs ? Autant bloquer le système, non ?

2021-09-23 12:45 UTC, celine-m-s commented on itou/users/models.py
> +            and current_institution is not None
Aaah, bien vu ! Merci !
Je regarde si on peut séparer les contrôles.

2021-09-23 12:51 UTC, celine-m-s commented on itou/users/models.py
> +            and current_institution is not None
Pas évident comme ça et je ne veux pas trop toucher à la logique de Vermeer.
J'ai cependant enlevé la condition sur `current_institution` qui est inutile.

2021-09-23 12:52 UTC, celine-m-s commented on itou/users/models.py
> +            return "01"
Les VIPs sont des membres de notre équipe uniquement (de ce que j'en ai compris). Donc ça sert à regarder comment fonctionne le système.

2021-09-23 12:52 UTC, celine-m-s commented on itou/users/models.py
> +            return "01"
@SoumiaAHLOUCH

2021-09-23 13:14 UTC, celine-m-s commented on itou/users/models.py
> +            and current_org.department in settings.CD_STATS_ALLOWED_DEPARTMENTS
OK, supprimé !

2021-09-23 15:52 UTC, merged

2021-09-27 12:19 UTC, vgrange commented on itou/users/models.py
> +            and current_institution is not None
Pas de souci, je vais bientôt virer le rôle VIP 🔪

2021-09-27 12:21 UTC, vgrange commented on itou/users/models.py
> +        return self.can_view_stats_cd(current_org=current_org) or self.can_view_stats_ddets(
Ah oui bonne idée donc current_org pourrait être polymorphe (soit une institution soit une orga prescripteur) avec un code plus simple. Je me le note. Merci ! 🙏  @celine-m-s

2021-09-27 12:23 UTC, vgrange commented on itou/users/models.py
> +            and current_institution.is_ddets
Bien vu merci @celine-m-s !
Pour mémoire mon import loop "insoluble" se produisait avec `current_institution.kind == Institution.Kind.DDETS`. Mais `current_institution.Kind.DDETS` contourne le souci avec succès, super !