Intégration du thème bootstrap de la plateforme de l'inclusion
betagouv/itou pull request #871
Opened 2021-09-20 10:04 UTC by madjid-asa

### Quoi ?
Intégrer le [thème Bootstrap de la Plateforme de l'inclusion](https://github.com/betagouv/itou-theme) au C1.

### Pourquoi ?
Suite à discussion avec @daviddeloo le thème est dans un état d'avancement suffisant pour pouvoir être intégré.

Il reste des validations côté UX à obtenir (sur les parties signalées avec des icônes de pinceau) mais ça pourra être des mises à jour éventuelles au fil de l'eau.

### Comment ?

### Captures d'écran (optionnel)

### Autre (optionnel)
- Il reste plusieurs point à voir avec David et les UX notamment sur la navigation

2021-10-04 10:49 UTC, celine-m-s requested changes
Gros boulot !!! Bravo !!!
J'ai tout de même quelques questions et quelques suggestions. ^_^

2021-10-04 10:49 UTC, celine-m-s commented on itou/templates/layout/base.html
> +            "showIcon": true, /* Show cookie icon to manage cookies */
Pourquoi afficher l'icône de Tarte au Citron ? Elle est maintenant sur le logo « Donner mon avis ».

2021-10-04 10:49 UTC, celine-m-s commented on itou/templates/search/includes/generic_search_home.html
> +</section>
Même remarque que précédemment.

2021-10-04 10:49 UTC, celine-m-s commented on itou/utils/templatetags/theme_inclusion.py
> +This template tags have for goal to mutualize all the dependencies and specifics component from the itou theme
```suggestion
This template tags have for goal to mutualize all the dependencies and specifics component from the itou theme.
```

2021-10-04 10:49 UTC, celine-m-s commented on itou/utils/templatetags/theme_inclusion.py
> +And you need to paste it into the folder `itou/static/vendor/theme-inclusion`
Comment assurerons-nous la mise à jour automatique du thème ?
Ce serait sympa d'avoir une commande Make. On pourrait alors l'utiliser en local et l'ajouter [aux hooks post-déploiement Clever](https://github.com/betagouv/itou/blob/master/clevercloud/python.json#L6).

2021-10-07 08:21 UTC, kemar commented on .prettierrc
> +}
C'est abusé qu'il n'y ait pas une option pour [l'espacement entre les sélecteurs](https://prettier.io/docs/en/options.html) 😮

2021-10-07 08:22 UTC, kemar commented on itou/static/css/itou.css
> +}
On a une config sensée mettre les lignes de fin automatiquement ici https://github.com/betagouv/itou/blob/master/.editorconfig Est-ce que ton éditeur la prend en compte ?

2021-10-07 08:26 UTC, kemar commented on itou/utils/templatetags/theme_inclusion.py
> +And you need to paste it into the folder `itou/static/vendor/theme-inclusion`
C'est intéressant, je propose d'en faire une carte Trello.

2021-10-07 09:01 UTC, madjid-asa commented on itou/templates/layout/base.html
> +            "showIcon": true, /* Show cookie icon to manage cookies */
c'est changé, maintenant c'est en bas à gauche

2021-10-07 09:10 UTC, celine-m-s commented on itou/templates/layout/base.html
> +            "orientation": "bottom", /* Banner position (top - bottom) */
Hum, d'accord, mais j'ai le souvenir qu'on l'avait mis en haut pour que ce soit plus visible pour les personnes malvoyantes.

2021-10-07 10:23 UTC, madjid-asa commented on README.md
> +```
Au final, j'ai trouvé je pense une meilleur solution en ajoutant directement [un fichier `.gitattributes`](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/). Du coup j'ai retiré ce point du README.

2021-10-07 10:45 UTC, celine-m-s commented on itou/templates/layout/base.html
> +            "orientation": "bottom", /* Banner position (top - bottom) */
Merci ! :)

2021-10-11 15:09 UTC, celine-m-s commented on itou/templates/layout/_footer.html
> +              <img src="{% static_theme_images 'logo-accelere-betagouv.svg'%}" alt="Accéléré par Beta.gouv.fr">
Re @madjid-asa :)

2021-10-11 15:16 UTC, celine-m-s commented on itou/static/css/itou.css
> +}
Re @madjid-asa :)

2021-10-11 15:16 UTC, celine-m-s commented on itou/templates/layout/_footer.html
> +          {# External links. #}
Re @madjid-asa :)

2021-10-11 15:17 UTC, celine-m-s commented on itou/templates/layout/_footer.html
> +</footer>
Re @madjid-asa :)

2021-10-11 15:18 UTC, celine-m-s commented on itou/templates/layout/_header.html
> +        <a href="/"><img src="{% static_theme_images 'logo-emploi-inclusion.svg' %}" alt="L'emploi de l'inclusion"></a>
Re @madjid-asa :)

2021-10-11 15:56 UTC, madjid-asa commented on itou/static/css/itou.css
> +}
Je ne l'avais pas mis en place, mais maintenant c'est fait normalement, il ne devrait plus y avoir de soucis à ce niveau :)

2021-10-11 16:14 UTC, madjid-asa commented on itou/templates/layout/_footer.html
> +              <img src="{% static_theme_images 'logo-accelere-betagouv.svg'%}" alt="Accéléré par Beta.gouv.fr">
yes je l'ai rajouté, et j'en ai profité pour rajouté celui de la plateforme de l'inclusion aussi

2021-10-13 07:28 UTC, celine-m-s commented on itou/templates/layout/base.html
> +    {% import_static_CSS_theme_inclusion %}
C'est pas très clair pour moi mais ce n'est pas un point bloquant. :)

2021-10-13 13:36 UTC, merged