Ccamin/france connect demandeurs
betagouv/itou pull request #883
Opened 2021-09-28 14:51 UTC by Keirua

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

2021-09-30 14:45 UTC, Keirua commented
Mail envoyé à FC car je ne comprends pas pourquoi j’ai une erreur sur la déconnection à leur service
```
J’ai un petit souci pour finaliser l’implémentation de France Connect, sur la déconnection. Le but est de déconnecter l’usager de chez nous, de chez vous et le rediriger sur notre home, comme prévu dans votre cinématique.
J’ai une erreur systématiquement : "Une erreur technique est survenue lors de la déconnexion", sans plus de détails, et l’usager n’est pas redirigé sur notre url de redirection.

J’ai pourtant l’impression de faire ce qui est indiqué dans votre documentation (https://partenaires.franceconnect.gouv.fr/fcp/fournisseur-service#sign_out):

    une redirection GET sur https://fcp.integ01.dev-franceconnect.fr/api/v1/logout, avec 3 paramètres (id_token_hint, state, post_logout_redirect_uri)
    c’est aussi ce qu’on peut trouver dans votre implémentation d’exemple, cette partie n’a pas bougé depuis un moment et hardcode le state: https://github.com/france-connect/service-provider-example/blame/b9dc5edeb33c212878d05a919a6c728607c3380f/controllers/oauthAuthentication.js#L88-L96
    j’ai aussi regardé les implémentations d’autres startups d’état et je ne vois rien de plus (eux mettent un state aléatoire), ex: https://github.com/betagouv/service-national-universel/blob/14960fa6e9507f027ab89ee125f351ec5eb855a1/app/src/scenes/inscription/components/FranceConnectCallback.js#L29-L34

Mon implémentation est là: https://github.com/betagouv/itou/blob/0a98865017d72c5710c7e0d0e0cb5ebd6c6f783e/itou/france_connect/views.py#L170-L186

Je re-transmets les token/state générés lors de la connection et conservés en session. J’ai essayé les méthodes citées au dessus, sans plus de résultat.

On peut constater le problème ici:
https://c1-review-ccamin-france-connect-demandeurs.cleverapps.io/accounts/login/?account_type=job_seeker
```

2021-10-04 15:37 UTC, Keirua commented
Connection/déconnection France Connect (testable sur la review apps avec [les identifiants de recette proposés par France Connect](https://github.com/france-connect/identity-provider-example/blob/master/database.csv)):



https://user-images.githubusercontent.com/1223316/135880953-d4a11ea3-c6bb-4fca-9bb8-8a66b1add3ca.mp4

2021-10-05 09:29 UTC, kemar requested changes
Quelques questions et demandes de modifications. C'est normal qu'on ne vire pas plus de trucs de l'app `external_data` ?

2021-10-05 09:29 UTC, kemar commented on itou/www/dashboard/views.py
> +        fc_state = self.request.session.get("franceconnect_state")
Ça vaudrait pas le coup de mettre les chaînes `franceconnect_id_token` et `franceconnect_state` dans les _settings_ ?

2021-10-05 09:29 UTC, kemar commented on itou/www/dashboard/views.py
> +            # redirection is not performed
Ça vaudrait pas le coup de solliciter leur support pour avoir des explications ?

2021-10-05 09:29 UTC, kemar commented on itou/users/models.py
> +    def update_external_data_source_history(self, provider_name, field, value):
Ici un peu de doc expliquant à quoi sert et comment fonctionne cette méthode assez centrale pour les données externes ne serait pas du luxe.

Est-ce que tu peux expliquer un peu pour quelqu'un qui lirait le code pour la première fois ?

Le nom est aussi un peu trompeur car :

- il contient `update_` alors on s'attend à voir une opération en DB quelque part mais on ne la trouve pas
- on manipule le champ `provider_json` à l'intérieur

2021-10-05 09:29 UTC, kemar commented on itou/users/models.py
> +            return {"source": source, "created_at": now, "value": value}
Je vous plus trop l'intérêt de `_get_field_provider_info()`.

On pourrait mettre `now` en variable dans la méthode et déclarer explicitement :

```python
self.provider_json[field] = {"source": provider_name, "value": value, "created_at": now}
```

2021-10-05 09:29 UTC, kemar commented on itou/users/models.py
> +        return has_performed_update
Je vois bien l'interface pour peupler le JSON mais pas celle pour aller récupérer les informations, est-ce que ça vaut le coup d'y réfléchir tout de suite ?

Ça serait l'interface pour répondre à la question "d'où vient la date de naissance" par exemple.

2021-10-05 09:29 UTC, kemar commented on itou/external_data/apis/pe_connect.py
> +PE_CONNECT_PROVIDER = "poleemploi_connect"
À déplacer dans les *settings*.

2021-10-05 09:29 UTC, kemar commented on itou/france_connect/models.py
> +FRANCE_CONNECT_PROVIDER = "france_connect"
À déplacer dans les _settings_.

2021-10-05 09:29 UTC, kemar commented on itou/france_connect/views.py
> -    return JsonResponse({"message": "L'utilisateur a été déconnecté de FranceConnect."})
L'ancien retour en JSON était pensé pour être en mode "Aidant Connect", il faut bien garder ça en tête.

2021-10-05 11:49 UTC, Keirua commented on itou/france_connect/views.py
> -    return JsonResponse({"message": "L'utilisateur a été déconnecté de FranceConnect."})
c’est cette vue qui est (sera) appellée dans les 2 configurations, FC n’a qu’une seule URL de callback ; quand l’usager s’est connecté chez FC, ils nous envoient les infos là. Mon idée:
 - si on est pas connecté -> faire un login dans l’app, après récupération des infos du compte chez FC
 - si on est connecté en tant qu’aidant -> rester connecté, créer/remplir un compte demandeur pour usage dans l’app

2021-10-05 11:53 UTC, Keirua commented on itou/www/dashboard/views.py
> +        fc_state = self.request.session.get("franceconnect_state")
ce n’est pas un settings (truc variabilisable qui change en fonction du contexte) mais une constante, mais oui on peut

2021-10-05 16:08 UTC, Keirua commented on itou/www/dashboard/views.py
> +            # redirection is not performed
Demande déjà effectuée (cf mail au dessus). J’ai eu la réponse pour le staging (ça marche), pour le dev j’ai beau utiliser la même config j’ai cette erreur sans précisions. J’ai passé beaucoup trop de temps sur cette branche de if, c’est sans doute idiot.
Le but c’est de déconnecter entièrement le compte FC, en dev c’est moins génant si c’est pas fait. Si c’est bloquant je suis preneur d’une seconde paire d’yeux pour avancer là dessus.

2021-10-05 16:09 UTC, Keirua commented on itou/users/models.py
> +        return has_performed_update
Il n’y a rien à ce sujet à ce moment, perso je préfère les petites PRs plutôt que les PR multifonctions, d’autant que rien n’est discuté à ce sujet.

2021-10-07 12:50 UTC, Keirua commented on itou/users/models.py
> +    def update_external_data_source_history(self, provider_name, field, value):
amélioré (j’espère) dans https://github.com/betagouv/itou/pull/883/commits/1c56d1e23fec0e9e55605880074f723cd7d17820

2021-11-04 14:26 UTC, Keirua commented
Mises à jour suite au redesign et aux retours de validation:

# Écran login

![Sélection_146](https://user-images.githubusercontent.com/1223316/140329168-dde9d6b9-400e-409a-8bb1-17b7ff021799.png)

# Pas de modification de mot de passe pour les comptes france connect (qui n’en ont pas)

![Sélection_147](https://user-images.githubusercontent.com/1223316/140329235-93831a60-596b-4ce0-acd3-4d8c654ea5ac.png)

# Texte explicatif sur l’écran de modification de mot de passe
(concerne les gens non-france connecté du coup)
![Sélection_145](https://user-images.githubusercontent.com/1223316/140329349-a6bd52a3-1701-4e4b-82f7-f8d11c2729a3.png)

2021-11-09 17:05 UTC, Keirua commented
Plusieurs scénarios subtils sont carrés:
  - clarification du changement de mot de passe pour les utilisateurs passés par un login FC (le changement concerne uniquement le compte local)
  - un usager FC peut changer son MDP (via réinitialisation du mot de passe: au départ, l’utilisateur ne connait pas son mot de passe)
  - un usager FC peut modifier son email (ce qui entraine sa déconnection, y compris de FC)
  - on peut modifier son email puis se connecter à nouveau avec un compte FC
  - la déconnection déconnecte systématiquement de FC
  - la déconnection de FC fonctionne partout, y compris en dev
  - si connection avec un compte FC -> réinitialisation de mot de passe -> nouveau mot de passe (ouf!), on peut se connecter par email/mot de passe avec son email fourni par france-connect et le mot de passe choisi. À la première connection ainsi, un email pour confirmer l’email de l’utilisateur est envoyé.

2021-11-09 17:05 UTC, Keirua commented on itou/www/dashboard/views.py
> +            # redirection is not performed
done

2021-11-12 10:57 UTC, Keirua commented
Mise à jour des landing suite au redesign et échanges de ce matin, affichage vertical des différentes options:
## Inscription
![Sélection_148](https://user-images.githubusercontent.com/1223316/141456147-66318a1f-512c-4e3d-94f7-fcfd771951ed.png)
## Connection
![Sélection_149](https://user-images.githubusercontent.com/1223316/141456149-53e58fd5-3b6f-43e5-893f-495903aae0fe.png)

2021-12-07 14:57 UTC, kemar requested changes
Bravo pour ce gros boulot. Encore quelques retours plutôt de surface et quelques questions.

2021-12-07 14:57 UTC, kemar commented on itou/external_data/signals.py
> +def log_out_from_france_connect(request, user):
C'est bizarre car ça n'est jamais appelé nulle part sauf en dessous dans le code commenté. Est-ce normal ? Est-ce toujours un `signal` ? Car si ça n'est pas le cas, il faudrait le mettre ailleurs que dans le fichier `signals.py`.

2021-12-07 14:57 UTC, kemar commented on itou/templates/signup/includes/france_connect_button.html
> +        <img class="img-fluid mb-1 itou-france-connect">
Il manque un attribut `alt="Se connecter avec FranceConnect "` pour l'accessibilité.

2021-12-07 14:57 UTC, kemar commented on itou/templates/utils/widgets/duet_date_picker_widget.html
> +    {% if widget.attrs.disabled %}disabled="disabled"{% endif %}
```suggestion
    {% if widget.attrs.disabled %}disabled{% endif %}
```

Ça suffit car [c'est un attribut booléen](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).

2021-12-07 14:57 UTC, kemar commented on itou/users/migrations/0037_merge_0036_merge_20211019_1014_0036_user_nir.py
> +    operations = []
Ça serait cool de fusionner les migrations qui concernent le même modèle dans la PR !

2021-12-07 14:57 UTC, kemar commented on itou/www/dashboard/forms.py
> +        request = kwargs.pop("request")
Ouais, à la limite tu pourrais lui passer juste un booléen `is_user_france_connected` plutôt que l'objet `request` complet mais je chipote.

2021-12-15 13:04 UTC, merged

2021-12-16 14:42 UTC, Keirua commented on itou/france_connect/models.py
>  def create_or_update_user(fc_user_data: FranceConnectUserData):
Je vois l’idée et je pense que c’est bien. Dans le cas présent, j’ai l’impression qu’on revient sur le problème l’imports circulaires (modele `User` <-> modele `FranceConnectUserData`) dont on parlait il y a quelques jours. Tu mettrais un import dans la classe `UserManager` pour résoudre le problème ? ou tu enlèverais l’annotation ?