Donner plus de visibilité sur la période de recrutement
betagouv/itou pull request #924
Opened 2021-10-19 16:11 UTC by madjid-asa

### Problème
En tant que prescripteur/candidat je souhaite savoir si la fiche de poste qui est publiée par un employeur est destinée à un recrutement immédiat (poste ouvert ) ou à un vivier (poste à venir)

En tant qu'employeur je ne peux pas distinguer mes besoins immédiats et mes besoins à venir

Verbatim prescripteur "on ne sait pas s'il y a un poste ouvert ou si c'est juste un métier affiché par l'employeur"

### Objectif roadmap rempli

- Accélérer le recrutement
- Améliorer la visibilité des fiches de poste

2021-10-27 12:52 UTC, kemar submitted a review, later dismissed
Good job ! Encore quelques retours à traiter et des tests à ajouter.

À titre personnel ne suis pas convaincu par l'utilisation d'une modale pour la prévisualisation, d'autant que la section "Voir les métiers exercés au sein de la structure" est repliée par défaut et nécessite une double action : clic sur "Prévisualier les modifications" puis clic sur "Voir les métiers exercés au sein de la structure".

**Par contre je suis désolé**, je n'ai pas capté au moment du passage de la carte dans les priorités Trello qu'il y a avait tellement de boulot au sein d'une seule carte !

Il aurait clairement fallu découper cette carte en plusieurs cartes et faire plusieurs PR !

Là la PR est très grosse et difficile à _reviewer_. Je suis probablement passé à côté de certains trucs.

2021-11-03 15:23 UTC, SebastienReuiller requested changes
Good job ! mais quelques ajustements à faire ;)

2021-11-03 15:23 UTC, SebastienReuiller commented on itou/www/siaes_views/views.py
> +            count_active_job_descriptions = int(job.is_active) + count_active_job_descriptions
Perso, je préfère utiliser la syntaxe `+=` pour incrémenter qui me semble plus lisible. Sympa le int() sur un booléen ;)

2021-11-03 15:23 UTC, SebastienReuiller commented on itou/templates/siaes/card.html
> +                        <span class="h4">Cette structure vous interesse ?</span>
"intéresse"

2021-11-03 15:23 UTC, SebastienReuiller commented on itou/templates/siaes/job_description_card.html
> +            <h2 class="h3">Consultez les recrutement(s) en cours dans cette structure</h2>
le(s) recrutement(s)

2021-11-03 15:23 UTC, SebastienReuiller commented on itou/siaes/models.py
> +            .order_by("-updated_at", "-created_at")
Je ne sais pas si ce tri est évident. J'aurai spontanément fait un tri alphabétique.

2021-11-03 17:08 UTC, madjid-asa commented on itou/www/siaes_views/views.py
> +            count_active_job_descriptions = int(job.is_active) + count_active_job_descriptions
yes bien vu ! c'est plus class et lisible :)

2021-11-03 17:14 UTC, madjid-asa commented on itou/siaes/models.py
> +            .order_by("-updated_at", "-created_at")
Enfaite c'est une demande UX, quand on ajoute une offre elle est en haut du tableau, du coup l'idée c'est de retrouver à chaque fois les offres dans le même ordre

2021-11-04 07:32 UTC, madjid-asa commented on itou/static/css/itou.css
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='none' d='M0 0h24v24H0z'/%3E%3Cpath d='M12 16l-6-6h12
On ne peux pas utiliser ça, puis qu'on est dans le fichier css :/ 
Je pense que la solution la plus clean, c'est d'avoir ce composant dans le thème global, ou au moins d'avoir l'icone dans le thème, je check avec @hellodeloo pour au moins rajouter l'icone dans le thème global.

2021-11-04 07:38 UTC, madjid-asa commented on itou/static/css/itou.css
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='none' d='M0 0h24v24H0z'/%3E%3Cpath d='M12 16l-6-6h12
Il l'avait déjà rajouté entre temps donc j'ai changé là :)

2021-11-04 08:26 UTC, SebastienReuiller approved these changes

2021-11-04 17:23 UTC, SebastienReuiller approved these changes

2021-11-04 17:24 UTC, merged