Ajout des évolutions du sprint 30 au journal des modifications
betagouv/itou pull request #962
Opened 2021-11-05 12:43 UTC by madjid-asa

### Quoi ?

Ajout des évolutions du sprint 30 au journal des modifications .

### Pourquoi ?

Pour maintenir un historique des évolutions de l'application.

### Comment ?
Parcours des `Pull request` mergé sur master depuis le début du sprint.

Utilisation des filtres Github en utilisant la requête suivante : 
[`is:pr closed:>2021-10-25 `](https://github.com/betagouv/itou/pulls?q=is%3Apr+closed%3A%3E2021-10-25)

2021-11-05 14:16 UTC, vgrange approved these changes
LGTM + quelques remarques. Il y a plusieurs choses (admin + C2) dont la présence dans le changelog C1 me parait pas pertinente, mais ouverte à discussion.

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +- Ajout d'un message dans la déclaration de fiches salarié à l'ASP, on informe désormais les employeurs qu'ils doivent avoir une annexe financière valide pour pouvoir déclarer une fiche salariée dans
`s/salariée/salarié/` à la fin

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +  - Les employeurs peuvent prolonger un PASS IAE sans l'avis d'un prescripteur habilité pour deux motifs _CDI conclu avec une personne âgée de + de 57 ans_ et _Fin de formation_.
Ligne à désindenter non ?

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +  - Montrer l'ID ASP de structure ASP.
Lignes 13 à 21 : je ne pense pas que les changements de l'admin aient vocation à être dans ce changelog, car ils sont visibles qu'à notre équipe en interne. Mais je me trompe peut-être, quelqu'un d'autre peut confirmer/infirmer ?

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +- Ajout d'un indicateur pour le suivi du nombre de salariés en insertion.
C'est du pur C2 donc pas le bon changelog. Le changelog C2 vit sa vie sur https://communaute.inclusion.beta.gouv.fr/doc/journal-des-modifications/ pour info, et est maintenu par Soumia.

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +- Correction du test de validité des communes de naissance dans le formulaire de déclaration de fiches salarié à l'ASP
Ces lignes finissent sans point. Celles d'avant avaient un point. Je propose de garder la même convention partout, verifier ce qu'il en était dans les changelogs précédents.

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +  - Limitation des données analysées pour le suivi. _Les données n'étaient pas limitées, dorénavant, nous analysons les données sur les deux dernières années et l'année en cours._
Lignes 32 à 35 c'est du C2 pas du C1.

2021-11-05 14:16 UTC, vgrange commented on CHANGELOG.md
> +  - Remise de la fonctionnalité de modification des mots de passe utilisateurs depuis l'interface d'admin.
Lignes 36 à 41 : admin donc pas sa place ici ? Désolé pour ton temps perdu :-/

2021-11-05 17:27 UTC, madjid-asa commented on CHANGELOG.md
> +- Ajout d'un indicateur pour le suivi du nombre de salariés en insertion.
👌

2021-11-05 17:27 UTC, madjid-asa commented on CHANGELOG.md
> +  - Limitation des données analysées pour le suivi. _Les données n'étaient pas limitées, dorénavant, nous analysons les données sur les deux dernières années et l'année en cours._
👌

2021-11-05 17:29 UTC, madjid-asa commented on CHANGELOG.md
> +  - Remise de la fonctionnalité de modification des mots de passe utilisateurs depuis l'interface d'admin.
Ben j'ai l'impression dans les précédents sprints, les changements d'admin y sont, mais on verra au pire j'enlèverai. 
Vaut mieux que ça soit en trop que le contraire 😅

2021-11-05 17:30 UTC, madjid-asa commented on CHANGELOG.md
> +- Correction du test de validité des communes de naissance dans le formulaire de déclaration de fiches salarié à l'ASP
FInalement j'ai vu que la norme été plutôt au sans point :)

2021-11-08 16:26 UTC, Keirua approved these changes
Rien qui me concerne (vacances + pas de gros trucs C1 mergés) mais ça semble cool.

2021-11-08 16:42 UTC, kemar requested changes
Presque bon. 2 petites remarques à corriger.

2021-11-08 16:42 UTC, kemar commented on CHANGELOG.md
> +  - Admin des structures :
Je crois qu'il y a une mauvaise indentation ici sur la ligne avant ou après les `:`.

2021-11-08 16:42 UTC, kemar commented on CHANGELOG.md
> +  - Environnement de développement
Cette ligne est bizarre, est-ce une erreur ou bien il manque un `:` et une indentation à la suite ?

2021-11-09 09:06 UTC, kemar approved these changes
LGTM

2021-11-09 09:30 UTC, merged