Correction d'erreurs Sentry relatives au fiches salarié
betagouv/itou pull request #967
Opened 2021-11-09 16:26 UTC by ikarius

### Quoi ?

Corrections des erreurs restantes remontées sur Sentry, relatives au fiche salarié.

### Pourquoi ?

- nettoyage du Sentry
- correction d'un bug du au décallage possible de l'état de la convetion d'une SIAE entre deux imports ASP

### Comment ?

- tests de la validité de la convention lors de la saisie -> notification à l'utilisateur
- rafraîchissement du SIRET et de l'ID ASP avant envoi de la fiche
- correction d'un bug mineur sur la géoloc

2021-11-10 09:06 UTC, SebastienReuiller approved these changes

2021-11-11 10:04 UTC, vgrange requested changes
Un edge case important à traiter (`SOURCE_STAFF_CREATED`) et sinon LGTM 🚀

2021-11-11 10:04 UTC, vgrange commented on itou/employee_record/models.py
> +        if siae.source == Siae.SOURCE_USER_CREATED:
Il y a un troisième cas `siae.source == Siae.SOURCE_STAFF_CREATED`.
Dans ce cas la plupart du temps la structure n'a pas de convention donc fait péter `ERROR_NO_CONVENTION_AVAILABLE` plus haut.
Mais il peut arriver qu'elle ait une convention. Auquel cas ici il faut aussi aller repêcher le SIRET de la SIAE mère et ne surtout pas retourner le SIAE de la structure créé par le support.

Bref changer en `if siae.source in [Siae.SOURCE_USER_CREATED, Siae.SOURCE_STAFF_CREATED]:`

2021-11-11 10:04 UTC, vgrange commented on itou/employee_record/models.py
> +        if siae.source == Siae.SOURCE_USER_CREATED:
Plus simple, élégant et future proof : `if siae.source != Siae.SOURCE_ASP:`
(if it's not the mother, go get the mother)

2021-11-11 13:20 UTC, vgrange approved these changes
LGTM

2021-11-11 13:21 UTC, vgrange commented on itou/employee_record/models.py
> +        Fetch SIRET number or ASP source structure ("mother" SIAE)
typo @ikarius  `s/or/of/`

2021-11-11 13:52 UTC, merged