Permettre de lever une suspension au moment de l'embauche
betagouv/itou pull request #973
Opened 2021-11-15 09:05 UTC by madjid-asa

### Quoi ?
Permettre la levée anticipée d'une suspension dès lors qu'un employeur valide une embauche

UNIQUEMENT POUR LES SUSPENSIONS POUR MOTIF "contrat de travail terminé ou contrat de travail rompu"

Date de fin de suspension = J-1

### Pourquoi ?
Actuellement seul l'auteur de la suspension peut la lever/modifier
C'est bloquant pour une nouvelle embauche

### Comment ?
    # Personne A : salarié chez ETTI_A
    # Personne A termine son contrat chez ETTI_A
    # ETTI_A enregistre une suspension -> Personne A
    # 1 mois plus tard ...
    # ETTI_B -> Décide de recruter personne A
    # Pas de diag, car existance de PASS
    # L'employeur valide la candidature 
    # => Suspension est levée: date de fin est égale à j-1 de la date de début de contrat
    # =============> Quid du cas de l'annulation de l'embauche et qu'il a une suspension ? 
    # ===============> Changement de la date de fin du PASS IAE, à la durée réel de suspension (début +)
    # ===============> Quid de la date de fin de suspension ? -> On revient sur la dernière date de fin connu
    # 1 an plus tard ...
    # L'employeur B suspend Personne A
    # => Création d'une nouvel suspension

### Autre (optionnel)

- Ajout de champs pour stocker la dernière date de fin connu

2021-11-17 10:47 UTC, celine-m-s requested changes
Il manque des tests unitaires. Les tests fonctionnels sont longs et fragiles, on les évite autant que possible. :)
Je rappelle également les remarques sur la forme de la PR communiquées dans Slack.
J'ai une question de nommage. À voir ce que tu en penses et ce qu'en dit Marc.

2021-11-17 10:47 UTC, celine-m-s commented on itou/approvals/models.py
> +    def can_update_suspension(self):
Voir mon autre commentaire.

2021-11-17 10:47 UTC, celine-m-s commented on itou/www/apply/views/submit_views.py
> +        if not approvals_wrapper.latest_approval.can_update_suspension:
En lisant cette ligne, je me demande si `Approval.can_update_suspension` est le bon nom. En effet, je me demande pourquoi mettre à jour une suspension alors qu'on en train de candidater.
C'est logique de vérifier que le PASS est actif mais ça l'est moins de vérifier si la mise à jour des suspensions est possible.
Que pensez-vous de `Approval.is_open_to_application_process` ? Une autre idée ?

2021-11-17 10:47 UTC, celine-m-s commented on itou/www/apply/tests/tests_process.py
> +    def test_accept_with_active_suspension(self):
Ici, tu ne testes qu'un cas particulier : une candidature peut être acceptée si le candidat a un PASS suspendu pour la raison `BROKEN_CONTRACT`. Cela devrait apparaître dans la docstring.
Je me demande également si tu as vraiment besoin de toutes ces données. Chaque utilisation d'une `factory` coûte beaucoup en mémoire.
Plus globalement, je pense que des tests unitaires seraient plus pertinents. Ils couvriraient plus de cas d'usage. Je comprends l'intérêt de ce test mais il n'est pas suffisant selon moi.

2021-11-17 10:48 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lever une suspension au moment de l'embauche](https://trello.com/c/g46PX9gV/2360-lever-une-suspension-au-moment-de-lembauche)

2021-11-17 10:54 UTC, celine-m-s commented on itou/www/apply/tests/tests_process.py
> +        # Now, other Siae want to hired the job seeker
```suggestion
        # Now, another Siae wants to hire the job seeker
```

2021-11-17 10:55 UTC, celine-m-s commented on itou/www/apply/tests/tests_process.py
> +        # for know, we dont manage the cancel case
```suggestion
        # for now, we don't manage the cancel case
```

2021-11-17 13:24 UTC, kemar requested changes
Il y a des modifications de code à faire. Lis bien les retours pour les traiter un par un. On peut en discuter au besoin.

2021-11-17 13:24 UTC, kemar commented on itou/approvals/models.py
> +    def can_update_suspension(self):
Ici, il faut tester les méthodes ou _properties_ ajoutées aux _models_, ça permet :

- de vérifier le résultat attendu via des tests relativement courts
- de pouvoir bâtir sereinement sur ce socle dans le reste du code (dans les vues, les commandes etc.)

C.f. https://github.com/betagouv/itou/blob/master/itou/approvals/tests.py

2021-11-17 13:24 UTC, kemar commented on itou/job_applications/models.py
> +                active_suspension = self.approval.suspension_set.in_progress().last()
Je suis d'accord :

1. tu peux factoriser avec `last_in_progress_suspension`, tester, puis ré-utiliser partout
2. ce code devrait se trouver dans `approvals/models.py` plutôt que dans `job_applications/models.py`

2021-11-17 13:24 UTC, kemar commented on itou/www/apply/views/submit_views.py
> +        if not approvals_wrapper.latest_approval.can_update_suspension:
Moi non plus, je ne comprends pas le code ici.

Dans quel cas aurait-on encore besoin d'afficher un message indiquant à l'utilisateur qu'il ne peut pas aller plus loin si le PASS du candidat est suspendu ?

Je croyais qu'on ne bloquait plus le tunnel de candidature même en cas de PASS suspendu, non ?

2021-11-18 13:10 UTC, madjid-asa commented on itou/www/apply/views/submit_views.py
> +        if not approvals_wrapper.latest_approval.can_update_suspension:
Il y a deux cas où on peut continuer dans le tunnel :) 
La nouvelle version devrait être plus clair !

2021-11-18 13:11 UTC, madjid-asa commented on itou/www/apply/tests/tests_process.py
> +    def test_accept_with_active_suspension(self):
J'ai rajouté les tests unitaires :)

2021-11-23 09:07 UTC, kemar requested changes
Je suggère quelques améliorations de perf et des changements dans les noms. Si OK pour toi, je relirais une dernière fois les tests après ces changements.

2021-11-23 09:07 UTC, kemar commented on itou/approvals/models.py
> +    def update_last_suspension(self, hiring_start_at):
```suggestion
    def unsuspend(self, hiring_start_at):
```

2021-11-23 09:07 UTC, kemar commented on itou/approvals/models.py
> +    def is_open_to_application_process(self):
```suggestion
    def can_be_unsuspended(self):
```

2021-11-23 09:07 UTC, kemar commented on itou/approvals/models.py
> +        if self.is_open_to_application_process and active_suspension:
```suggestion
        if active_suspension and self.is_open_to_application_process:
```

Ici tu peux inverser les clauses de la condition de façon à ne pas déclencher la vériication de la seconde si la première est fausse de façon à économiser des requêtes.

2021-11-23 16:51 UTC, celine-m-s commented
Je te laisse traiter les retours de Marc et je ferai une repasse après. :)

2021-11-25 14:57 UTC, madjid-asa commented on itou/www/apply/views/submit_views.py
> +        if not approvals_wrapper.latest_approval.is_open_to_application_process:
Yes t'as raison c'est plus parlant

2021-11-25 15:01 UTC, madjid-asa commented on itou/approvals/models.py
> +            return self.suspensions_by_start_date_asc.last()
Comme `is_suspended` et `suspensions_by_start_date_asc` étaient en cache je pensais que c'était mieux de faire comme ça mais du coup je prend ta reco

2021-11-25 15:06 UTC, madjid-asa commented on itou/approvals/models.py
> +        if self.is_open_to_application_process and active_suspension:
bien vu :)

2021-11-25 15:57 UTC, kemar approved these changes
LGTM Attention à merger uniquement après la suppression de la possibilité d'annuler une candidature acceptée.

2021-11-25 15:57 UTC, kemar commented on itou/approvals/tests.py
> +    def test_can_be_unsuspended_without_suspension(self):
Ouais j'ai vu ça dans la méthode `can_be_unsuspended` qui retourne `True` quand il n'y a pas de suspension.

D'un point de vue logique, c'est un peu bizarre de pouvoir arrêter la suspension d'un PASS IAE qui n'est pas suspendu.

Mais je n'ai pas plus élégant à proposer là maintenant…

2021-11-25 15:57 UTC, kemar commented on itou/www/apply/tests/tests_process.py
> +        # for now, we don't manage the cancel case
Je ne comprends pas bien ce commentaire ?

2021-11-25 17:27 UTC, madjid-asa commented
![](https://github.trello.services/images/mini-trello-icon.png) [✅ Lever le blocage de prescription même si le PASS IAE est suspendu (carte post atelier)](https://trello.com/c/LfStUCSR/2199-%E2%9C%85-lever-le-blocage-de-prescription-m%C3%AAme-si-le-pass-iae-est-suspendu-carte-post-atelier)

2021-11-25 21:40 UTC, celine-m-s commented on itou/www/apply/tests/tests_process.py
> +        # for now, we don't manage the cancel case
Je pense qu'on peut le supprimer. Il doit faire référence au fait qu'on ne gère pas l'annulation d'une candidature.

2021-11-25 22:01 UTC, celine-m-s requested changes
Bravo pour toutes ces modifications ! Le code est beaucoup plus clair. Il reste encore quelques points à clarifier et on sera bons.
💪

2021-11-26 15:33 UTC, madjid-asa commented on itou/approvals/models.py
> +        return True
yes t'as raison

2021-11-26 16:06 UTC, madjid-asa commented on itou/www/apply/tests/tests_process.py
> +        # for now, we don't manage the cancel case
oui c'était bien pour parler de l'annulation des candidatures.

2021-11-26 16:11 UTC, madjid-asa commented on itou/approvals/tests.py
> +    def test_can_be_unsuspended_without_suspension(self):
Si c'est plus logique du coup de renvoyer `False` effectivement, et du coup de changer la condition dans `submit_views.py`

2021-11-26 16:17 UTC, madjid-asa commented on itou/approvals/tests.py
> +        reasons_to_open_process = [Suspension.Reason.BROKEN_CONTRACT.value, Suspension.Reason.FINISHED_CONTRACT.value]
T'as totalement raison, d'autant plus que d'après ce que j'ai compris, les conditions devraient prochainement changer. 

Au final c'est un peu similaire au [cas de la variable de rétroactivité](https://github.com/betagouv/itou/pull/980#discussion_r757131006) ^^

2021-11-29 13:30 UTC, celine-m-s approved these changes
LGTM!
:champagne: !

2021-12-02 13:41 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Bye bye 96h](https://trello.com/c/T2pMDp5L/2278-c1-bye-bye-96h)

2021-12-07 19:25 UTC, merged