Limite de la rétroactivité des suspensions à 30 jours avant la date du jour
betagouv/itou pull request #980
Opened 2021-11-16 18:19 UTC by madjid-asa

### Quoi ?

Permettre aux utilisateurs "SIAE" + " Prescripteurs habilités" de déclarer une suspension jusqu'à 30 jours avant la date du jour

### Pourquoi ?

Demande de la DGFEP.

### Comment ?

Ouvrir le droit à la rétroactivité à 30j (pour les PASS et les agréments PE importés)
SI le PASS a moins de 30 jours ce sera au plus tot la date de démarrage du PASS

2021-11-17 10:52 UTC, madjid-asa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rétroactivité de la suspension](https://trello.com/c/VPDSCHDA/2359-r%C3%A9troactivit%C3%A9-de-la-suspension)

2021-11-25 21:37 UTC, celine-m-s requested changes
Cette PR est une très bonne entrée en matière dans l'univers des tests unitaires ! C'est top !
Il y a toutefois plusieurs points à améliorer. N'hésite pas si tu veux qu'on en discute ensemble lundi pour que je te les explique de vive voix.

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/models.py
> +        # by default the next min start is the date of last hiring start of user
```suggestion
        # Default starting date.
```
Cela étant, je pense pas que ces commentaires soient toujours pertinents maintenant que le code est plus clair.

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/models.py
> +        min_suspension_start_at = approval.user.last_accepted_job_application.hiring_start_at
```suggestion
        start_at = approval.user.last_accepted_job_application.hiring_start_at
```

`min_suspension_start_at` est bien long et donc plus compliqué à comprendre.
Etant donné qu'on ne manipule pas d'autre objet et qu'il n'y a pas de maximum, je propose d'en raccourcir le nom.

Par ailleurs, regrouper les variables en haut de méthode serait intéressant. Cela permettrait de se concentrer sur les conditions après sans pollution.

Quelque chose comme ça : 

```
# Variables and default behavior.
today = datetime.date.today()
start_at = approval.user.last_accepted_job_application.hiring_start_at
start_at_threshold = today - relativedelta(days=Suspension.MAX_RETROACTIVITY_DURATION_DAYS)

# Start at overrides to handle edge cases.
if approval.last_old_suspension:
    start_at = ...
    # ...

# Final return: start_at or start_at_threshold.
if start_at < start_at_threshold:
    return start_at_threshold
return start_at
```

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/models.py
> +        # We set the next min to the date of last old suspension if suspension exist
```suggestion
```
Ce commentaire me paraît redondant car il suffit de lire le code qui est en-dessous.

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/models.py
> +                            f"Date de début minimum: {next_min_start_at.strftime('%d/%m/%Y')}."
```suggestion
                            f"Date de début minimum : {next_min_start_at.strftime('%d/%m/%Y')}."
```

Petite subtilité de la langue française : [il y a une espace avant et après les deux points](https://www.btb.termiumplus.gc.ca/redac-chap?lang=fra&lettr=chapsect6&info0=6.13) (à l'inverse de l'anglais où il n'y a pas d'espace avant).

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/tests.py
> +        # test the when suspension is out of boundaries
```suggestion
        # Suspension.start_date is too old.
```

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/tests.py
> +        suspension.start_at = start_at - relativedelta(months=1)
Ce test est fragile. Pourquoi ? Car le jour où `MAX_RETROACTIVITY_DURATION_DAYS` ne vaudra plus 30 jours mais 40, ton test sera rouge au lieu d'être vert.
Je suggère de rendre la période dynamique.

```suggestion
        suspension.start_at = start_at - relativedelta(days=Suspension.MAX_RETROACTIVITY_DURATION_DAYS + 1)
```

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/tests.py
> +        # the case when end_at < start_at
```suggestion
        # Suspension.end_at < Suspension.start_at
```

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/tests.py
> +        # declare suspension in the future
```suggestion
        # Suspension.start_at is in the future.
```

2021-11-25 21:37 UTC, celine-m-s commented on itou/approvals/tests.py
> +        suspension = SuspensionFactory(approval=approval)
À vérifier, mais je pense que tu n'as pas besoin de créer de `Suspension` en base. Tu pourrais seulement instancier la classe avec `SuspensionFactory.build(approval=approval)`.

Par ailleurs, je comprends que tu te sers de cet objet pour tous tes tests suivants. Or cela peut porter à confusion car on peut assez rapidement travailler avec des attributs qu'on a oubliés car il ont été surchargés dans un test intermédiaire. Par exemple, ton test 2 vient écraser les attributs du test 1 mais le test 3 se base encore sur ceux du test 2. Sauf si tu n'as pas surchargé les attributs du test 2, auquel cas la valeur est celle du test 1. Bref, c'est le bordel ! 😄 
Une bonne pratique, pour éviter que deux tests se télescopent sans le vouloir, est de repartir d'un objet différent à chaque test.

Par exemple :

```
# Suspension.start_date is too old.
suspension = SuspensionFactory.build(approval=approval)
suspension.start_at = start_at - relativedelta(months=1)
suspension.end_at = start_at + relativedelta(months=2)
with self.assertRaises(ValidationError):
    suspension.clean()

# Next test
suspension = SuspensionFactory.build(approval=approval)
# ...
```

2021-11-26 15:14 UTC, madjid-asa commented on itou/approvals/models.py
> +        min_suspension_start_at = approval.user.last_accepted_job_application.hiring_start_at
yes t'as raison :)

2021-11-26 15:15 UTC, madjid-asa commented on itou/approvals/tests.py
> +        suspension.start_at = start_at - relativedelta(months=1)
t'as totalement raison 🙏

2021-11-26 15:16 UTC, madjid-asa commented on itou/approvals/tests.py
> +        suspension = SuspensionFactory(approval=approval)
Bien vu, je n'avais jamais vu l'utilisation de `.build` mais je comprends très bien ton retour, j'ai update tu me dit si c'est good :)

2021-11-29 13:27 UTC, celine-m-s approved these changes
LGTM
Merci d'avoir pris en compte tous mes retours ! :clap:

2021-12-02 14:23 UTC, merged