Suppression du délai de rétraction / annulation de 96h
betagouv/itou pull request #983
Opened 2021-11-18 09:49 UTC by ikarius

### Quoi ?

Résumé des changements apportés.

### Pourquoi ?

Indiquer le problème que nous sommes en train de résoudre et les objectifs métiers ou techniques qui sont visés par ces changements.

### Comment ?

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran (optionnel)

Utile pour les changements liés à l'UI.

### Autre (optionnel)

- si des tests manquent, indiquer la raison, la probabilité, et les risques associés à ce manque
- être explicite sur le délai attendu pour une revue de code
- être explicite sur la qualité attendue pour la revue de code
- etc.

2021-11-30 13:33 UTC, kemar requested changes
Quelques suggestions d'améliorations et une question.

2021-11-30 13:33 UTC, kemar commented on itou/job_applications/models.py
> +            return not has_blocking_employee_record_status and today <= self.hiring_start_at
La logique métier qui concerne les fiches salarié devrait se trouver dans le modèle approprié et y être testée plutôt que de figurer à l'intérieur d'une méthode d'un autre modèle.

Par exemple ça devrait être quelque chose comme :

```python
return today <= self.hiring_start_at and not self.employee_record.has_blocking_status
```

2021-11-30 13:33 UTC, kemar commented on itou/job_applications/models.py
> +        return self.hiring_start_at
En lisant ça je ne suis pas vraiment convaincu par le fait de conserver une `property` "proxy" dont le seul rôle est de surcharger une propriété déjà existante…

Je suis d'avis de la supprimer.

2021-11-30 13:33 UTC, kemar commented on itou/job_applications/tests.py
> +        job_application_future_ok = JobApplicationWithApprovalFactory(hiring_start_at=today)
Du coup le nom de la variable peut induire en erreur car la candidature n'est plus dans le futur, n'est-ce pas ?

2021-11-30 13:33 UTC, kemar commented on itou/templates/employee_record/list.html
> -                        <li>Les candidatures acceptées ne seront visibles <b>qu'après échéance du délai d'annulation de 96H</b>.</li>
Bien joué d'avoir trouvé cette ligne 👍

2021-11-30 13:33 UTC, kemar commented on itou/job_applications/models.py
> +            return not has_blocking_employee_record_status and today <= self.hiring_start_at
Autre remarque : du coup si je comprends bien on peut toujours annuler une candidature tant que la date d'embauche est dans le futur. Mais comment pourrait-on déjà avoir une fiche salarié `SENT` ou `PROCESSED` dans ce cas ?

2021-11-30 14:15 UTC, ikarius commented on itou/job_applications/models.py
> +        return self.hiring_start_at
euh, complètement d'accord. J'ai été flemmard sur le coup

2021-12-02 10:58 UTC, ikarius commented on itou/job_applications/models.py
> +            return not has_blocking_employee_record_status and today <= self.hiring_start_at
Excellente remarque. 
Qui m'a amené à demander plus de précision au métier.
Pour résumer, on peut annuler une embauche à tout moment, excepté lorsqu'il existe une fiche salarié associée, dans l'état `PROCESSED` ou `SENT`.
Ce qui explique de nouvelles modifications dans le code et dans les tests.

2021-12-02 13:42 UTC, celine-m-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [[C1] Bye bye 96h](https://trello.com/c/T2pMDp5L/2278-c1-bye-bye-96h)

2021-12-07 13:24 UTC, kemar requested changes
Un petit bug HTML à corriger. Le reste est laissé à ton appréciation.

2021-12-07 13:24 UTC, kemar commented on itou/job_applications/models.py
> +            # there is no employee record linked with a status :
```suggestion
            # there is no employee record linked with a status:
```

Pas d'espace avant les `:` en anglais ;)

2021-12-07 13:24 UTC, kemar commented on itou/templates/apply/includes/state_transition_siae.html
> +                </p>Si une fiche salarié a été saisie pour cette embauche, elle sera annulée.</p>
```suggestion
                <p>Si une fiche salarié a été saisie pour cette embauche, elle sera annulée.</p>
```

Enlève tes moufles ;) Faut faire gaffe quand même car une mauvaise hiérarchie de balises HTML peut casser une mise en page.

2021-12-07 13:24 UTC, kemar commented on itou/www/apply/tests/tests_process.py
> +            hiring_start_at=(timezone.localdate()) + relativedelta(days=1),
```suggestion
            hiring_start_at=timezone.localdate() + relativedelta(days=1),
```

Ouais… si tu fais ça je ne suis plus vraiment convaincu de l'intérêt de conserver ces parenthèses ?

2021-12-07 13:24 UTC, kemar commented on itou/www/apply/tests/tests_process.py
> +        EmployeeRecordFactory(job_application=job_application, status=EmployeeRecord.Status.PROCESSED)
Peut-être qu'une _factory_ liée à `JobApplication` devrait encapsuler la création d'un objet `EmployeeRecord` plutôt que de devoir utiliser deux _factories_ à plusieurs endroits ?

2021-12-07 13:31 UTC, ikarius commented on itou/www/apply/tests/tests_process.py
> +            hiring_start_at=(timezone.localdate()) + relativedelta(days=1),
Black et formattage plus automatique à cause d'un bug de Neovim. Du coup, je risque d'en avoir d'autres. Merci

2021-12-07 16:13 UTC, merged